### ISSUE TITLE
`node -p 123` runs and prints expression; ts-node requires `-p -e 123`

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1002]
### Expected Behavior

`ts-node -p 'someExpression()'` behaves the same as `node -p 'someExpression()`: run and print the expression.

### Actual Behavior

You have to do `ts-node -p -e 'someExpression()'`

Not a big deal, but ideally we can match the same shorthand as node.  Should be an easy tweak to our option parsing.

### Steps to reproduce the problem

```
ts-node -p '1+1' # fails
node -p '1+1' # logs the expression value (123) to the console
```

### Specifications

* ts-node version: v8.8.1
* TypeScript version: v3.7.2
* tsconfig.json, if you're using one: N/A
* node version: v13.8.0
* Operating system and version: Ubuntu
* If Windows, are you using WSL or WSL2?:

**Comment by blakeembrey** [comment]
It's not possible with our option parsing IIRC. It used to work with minimist, but not with with `arg`.

**Comment by cspotcode** [comment]
Ah bummer.  Looks like you're right; there's no way to tell it that `-p` either has a string value or is a boolean flag.  Oh well, not a big deal.

Out of curiosity, was `args` chosen for particular reasons?  To be fast and small, perhaps?

**Comment by blakeembrey** [comment]
Basically, yeah - simple and type-safe. Using minimist and other argument parsing libraries carried some type unsafety and foot guns you always needed to verify. E.g. with `minimist` the values could always be either singular or an array (depending on the number of arguments passed).
