### ISSUE TITLE
How to use ts-node with ndb?

### ISSUE THREAD

**Issue by Aaron-Bird** [TypeStrong/ts-node#1005]
It works fine when I try to use '--inspect'.

```
nodemon --watch index.ts --exec node --inspect -r ts-node/register index.ts
```

But when I use ndb like this, it cannot display the source-map correctly.

```
ndb node -r ts-node/register index.ts
```

When I set a breakpoint in ndb, it does not stop.
If I write "debugger" in the code, ndb will pop up a blank page and stop.

I found a similar [issue](https://github.com/GoogleChromeLabs/ndb/issues/34), but the problem seems to have been fixed?
Did I make a mistake in use?

**Comment by blakeembrey** [comment]
@Aaron-Bird Did you figure something out? It helps to post your solution or reason for closing in case someone else stumbles upon this.

**Comment by Aaron-Bird** [comment]
@Aaron-Bird
I think this is a ndb bug and has nothing to do with ts-node.
It seems that ndb does not fix the bug of inline source map.
