### ISSUE TITLE
How does ts-node locate and load tsconfig.json in vs code??

### ISSUE THREAD

**Issue by gwd0715** [TypeStrong/ts-node#1006]
- VS Code Version: 1.44.0
- OS Version: macOS 10.15.4
- Code Runner Version: 0.9.17
- ts-node Version: 8.8.2
- ts-node is installed globally by npm

**Describe the bug**
I encountered this problem in my typescript project.
In order to clearly illustrate this bug, I made a similar file structure in an empty folder.
Normally, the directory of tsconfig.json is the root directory of a typescript Project. 
This is my config file:
```json
{
	"compilerOptions": {
		"module": "CommonJS",
		"noImplicitReturns": true,
		"noUnusedLocals": true,
		"outDir": "lib",
		"sourceMap": true,
		"strict": true,
		"target": "ES2018"
	},
	"compileOnSave": true
}
```
1.However, if code-runner.cwd is not set and code-runner.fileDirectoryAsCwd is false, it will use the path of root folder that is open in VS Code. And in this case, if tsconfig.json is in a subfolder,  ts-node cannot load this configuration file automatically. (Notice, I have already set the target to ES2018)
<img width="724" alt="Screen Shot 2020-04-10 at 11 17 17 PM" src="https://user-images.githubusercontent.com/17922721/79001669-7b6d9c00-7b81-11ea-9c5a-da22e87d3b58.png">
<img width="891" alt="Screen Shot 2020-04-10 at 9 23 26 PM" src="https://user-images.githubusercontent.com/17922721/78993946-87e9f880-7b71-11ea-852c-253db1721c45.png">
And I figured out this is maybe ts-node only load tsconfig.json from Cwd. But see the second case.

2.If code-runner.cwd is not set and code-runner.fileDirectoryAsCwd is true, and move tsconfig.json to the root directory instead of a subfolder, ts-node can still load the tsconfig.json even it is in the parent directory of Cwd when you run the .ts file in the subfolder. 
![image](https://user-images.githubusercontent.com/17922721/79001820-cab3cc80-7b81-11ea-96bf-17421a475110.png)
<img width="836" alt="Screen Shot 2020-04-10 at 9 35 30 PM" src="https://user-images.githubusercontent.com/17922721/78994661-35a9d700-7b73-11ea-850d-11a78825f798.png">
So maybe when .fileDirectoryAsCwd is true, ts-node can automatically search tsconfig.json in the parent directory??  However, things aren't this easy.

3.If code-runner.cwd is not set and code-runner.fileDirectoryAsCwd is false, and tsconfig.json is in the root directory, now open the subfolder in the vscode and run the code, ts-node can still load tsconfig.json even Cwd is the directory of this subfolder and this config file is out of sight.
<img width="724" alt="Screen Shot 2020-04-10 at 11 17 17 PM" src="https://user-images.githubusercontent.com/17922721/79001669-7b6d9c00-7b81-11ea-9c5a-da22e87d3b58.png">
<img width="780" alt="Screen Shot 2020-04-10 at 10 54 52 PM" src="https://user-images.githubusercontent.com/17922721/78999959-4d3a8d00-7b7e-11ea-8e31-5bc52ea567b0.png">
<img width="833" alt="Screen Shot 2020-04-10 at 10 55 32 PM" src="https://user-images.githubusercontent.com/17922721/79000000-65aaa780-7b7e-11ea-9167-dc36046092fe.png">

So please tell me,  what is going on?

**Comment by blakeembrey** [comment]
This seems like more of a VS Code question than anything. TS Node resolves by CWD by default, that’s all. It’ll traverse up the directory structure the same as TSC.

**Comment by cspotcode** [comment]
Closing as no further action is required on our end.
