### ISSUE TITLE
Feature: Add cli option to load different tsconfig.json

### ISSUE THREAD

**Issue by unional** [TypeStrong/ts-node#101]
One particular use case I need is for running tests against global version of typings.

When I create typings, currently I need to create two versions: one for module (top-level module declaration), and one for global (a script file version of the prior).

I write tests for them but currently only run against the module version.
If I can specify a different `tsconfig.json`, I can load the global version and run the same tests against it.

**Comment by unional** [comment]
Does `--project` accepts, folder or can specify the file path directly? I can test it out.

**Comment by unional** [comment]
Confirmed that it does not handle file path.

**Comment by blakeembrey** [comment]
The `--project` option should accept the path, but it's broken in TypeScript stable because of a bug in TypeScript. You can drop back to an older `ts-node` version that handles it. For the file use-case, I'd like to mirror TypeScript behaviour so they'll need to expose it (if they haven't already).

**Comment by blakeembrey** [comment]
This should be working today. The `--project` option in `0.8.0` accepts a file path.
