### ISSUE TITLE
Tell users to add "node" to types in "tsconfig.json" if they're missing something obvious (fs, path, process, __dirname, etc)

### ISSUE THREAD

**Issue by SephReed** [TypeStrong/ts-node#1012]
### Desired Behavior
Failing to create a tsconfig file with `"types": ["node"]` is really easy, even if you remember to install `@types/node`.  If this is missing from tsconfig and you try to use something like `fs, process, __dirname, path` or many other very obvious node items you get this error.

>Cannot find name '__dirname'.

It would be really helpful to check if the module is item is in an array of node stuff, and check if tsconfig is set up for node.  If not, be helpful.

> Cannot find name '__dirname'.  This is a typical node environment variable, but you do not have tscnofig types set up for node.  Check this link.

### Is this request related to a problem?

At least 5 times in my life I've ran into this issue then spent 5-10 minutes getting it solved.  It's a hassle.

**Comment by blakeembrey** [comment]
It might also be worth flagging this with the TypeScript team so that it benefits users in code editors, not just in `ts-node`.

**Comment by SephReed** [comment]
Hmmm.. I think you're right, though I have very little faith in it happening.

**Comment by cspotcode** [comment]
Sounds like something that should be handled by TypeScript, the same way they are emit messages like the following:

![image](https://user-images.githubusercontent.com/376504/80012811-e1202900-849b-11ea-9b1c-b01d49c8e9e3.png)

**Comment by cspotcode** [comment]
@SephReed check this in TypeScript's source code.
https://raw.githubusercontent.com/microsoft/TypeScript/master/src/compiler/checker.ts
```
                case "process":
                case "require":
                case "Buffer":
                case "module":
                    return compilerOptions.types
                        ? Diagnostics.Cannot_find_name_0_Do_you_need_to_install_type_definitions_for_node_Try_npm_i_types_Slashnode_and_then_add_node_to_the_types_field_in_your_tsconfig
                        : Diagnostics.Cannot_find_name_0_Do_you_need_to_install_type_definitions_for_node_Try_npm_i_types_Slashnode;
```

Based on the above, looks like TypeScript already implements this feature but does not exhaustively check for all node globals.  This should be a good starting point to figure out why they chose not to  match on `__filename` and `__dirname`.

**Comment by SephReed** [comment]
I swear I've had this happen on process too... 

Great find!  If I can link this file directly in the issue, then it might actually work out.

**Comment by Almenon** [comment]
@SephReed can you post your tsconfig please? I tried the below but I still got a cannot find name error:

```json
{
 "compilerOptions": {
    "types" : ["node",]                                                                                              }                                                                                                                 
  }
} 
```

I have @types/node installed globally. Maybe it needs to be installed locally 🤔

**Comment by cspotcode** [comment]
Closed because it's something that's handled by typescript itself, so any changes to this behavior would happen within typescript.
