### ISSUE TITLE
[META] Where to announce big changes and solicit feedback from the userbase?

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1024]
@blakeembrey 

I'd like to merge and publish experimental ESM support today.  I think this is a good way to get feedback.  While it's experimental, it doesn't need to be 100% bug-free, and it can be iterated as patch or minor releases.  (like semver before 1.0)

In general, are there places where releases are announced if they have big new features?  I know about:

* TypeScript community Discord
* TypeScript subreddit

Anywhere else?  I don't use Twitter so I don't know if that's worth looking at.

**Comment by blakeembrey** [comment]
I can announce it on Twitter, probably worth announcing since there's some TypeScript accounts that could retweet. Other than that, I'm not really familiar - never done many announcements personally.

**Comment by cspotcode** [comment]
Ok, that sounds good.

On second thought, maybe it's not best to do a wide announcement for the first experimental release.  We have enough people in the issue tracker who are curious, I can ping them on the relevant tickets to solicit feedback.  Hopefully we'll be able to knock out the initial bugs together.

But for future releases, I'll share on the subreddit and Discord.
