### ISSUE TITLE
ts-node running tsx syntax is always Unexpected token '<'

### ISSUE THREAD

**Issue by Song-Qian** [TypeStrong/ts-node#1046]
I have a question. I am pre-researching a Vue server rendering project. In the project, I use TSX syntax. When I use VS Code to configure the TS-Node environment to run the project, I always report Unexpected token '<' Wrong, this problem has troubled me for a long time, I don't know which part of the problem happened, I hope to get an answer.

The following is an example of the content of the code that I think should be provided

![image](https://user-images.githubusercontent.com/33682535/82148526-2a8b4a80-9887-11ea-9e5b-b8462558ddcb.png)

![image](https://user-images.githubusercontent.com/33682535/82148545-44c52880-9887-11ea-9299-5f7ac199ef08.png)

![image](https://user-images.githubusercontent.com/33682535/82149089-ccf7fd80-9888-11ea-9967-acce52a97709.png)

![image](https://user-images.githubusercontent.com/33682535/82149022-696dd000-9888-11ea-982c-9ad365f1bf8c.png)

When I start with VS Code

![image](https://user-images.githubusercontent.com/33682535/82149128-0b8db800-9889-11ea-8e7f-2c37b32c620f.png)

**Comment by cspotcode** [comment]
"jsx": "preserve" is the culprit.  This is unrelated to ts-node, since it
is a TypeScript compiler behavior.

**Comment by Song-Qian** [comment]
Thanks for your answer, if I must use "jsx": "preserve", should I use the corresponding implementation of jsxFactory?

**Comment by cspotcode** [comment]
If you use jsx: preserve, then the compiler will emit JSX syntax.  Node
cannot run jsx syntax.

**Comment by Song-Qian** [comment]
Thanks again.
