### ISSUE TITLE
Can't run ts-node inside Angular Package Format library

### ISSUE THREAD

**Issue by fireflysemantics** [TypeStrong/ts-node#1049]
Cross referencing the issue, as not sure exactly whether it is ng-packagr or `ts-node`s domain.

https://github.com/ng-packagr/ng-packagr/issues/1648

**Comment by cspotcode** [comment]
Looks like the tsconfig sets `"module": "esnext"` so the TS compiler will emit ES import/export syntax, which node cannot handle in a CommonJS module context.
