### ISSUE TITLE
masked / confusing error messages

### ISSUE THREAD

**Issue by linusnorton** [TypeStrong/ts-node#105]
Running my TS app with a syntax error through ts-node produces the rather cryptic error

```
$ ./node_modules/.bin/ts-node src/app.ts 
SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.loader (/opt/putfood/node_modules/ts-node/src/ts-node.ts:225:14)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (app.ts:4:1)
    at Module._compile (module.js:413:34)
    at Object.loader (/opt/putfood/node_modules/ts-node/src/ts-node.ts:225:14)
```

If I run it through plan node (after compiling the JS I get the much better:

```
$ nodejs src/app.js 
/opt/putfood/src/model/dependency/DependencyContainer.js:35
                const [db, repo, emailer] = yield Promise.all([this.get("database"), this.get("user.repository"), this.get("email.service")]);
                      ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    ...
```

Obviously the root cause is my syntax error but it would be nice if ts-node would output something similar to node. Critically the file and line with the actual error are missing from the output.

**Comment by blakeembrey** [comment]
Honestly, not sure myself how to achieve this properly. That error is thrown by node, I don't think it's wise to start intercepting thrown errors and trying to format them - but I can't think of any other way to improve this.

**Comment by linusnorton** [comment]
If it would return the same error as node I think it would be perfect but somewhere the critical information is getting lost. 

The error from node:

```
$ nodejs src/app.js 
/opt/putfood/src/model/dependency/DependencyContainer.js:35
                const [db, repo, emailer] = yield Promise.all([this.get("database"), this.get("user.repository"), this.get("email.service")]);
                      ^

SyntaxError: Unexpected token [
```

The error from ts-node

```
$ ./node_modules/.bin/ts-node src/app.ts 
SyntaxError: Unexpected token [
```

I'm not sure where those first two lines go, but they are the useful part.

**Comment by blakeembrey** [comment]
@linusnorton I'd love if it were that simple. They are already the exact same error, `ts-node` is not changing it. The `node` executable itself is doing additional processing here, which it's not doing with TypeScript files.

**Comment by linusnorton** [comment]
Wow, that's a bit odd to say the least. Thanks anyway

**Comment by blakeembrey** [comment]
Feel free to keep it open, I'd love to investigate when I have a chance because I know it sucks.

**Comment by blakeembrey** [comment]
I believe this may also be related to handling in https://github.com/evanw/node-source-map-support.
