### ISSUE TITLE
Circular type error thrown in CI (TSC builds fine/local tests run fine in ts-node)

### ISSUE THREAD

**Issue by bdistin** [TypeStrong/ts-node#1050]
### Expected Behavior
ts-node should behave as typescript, and not throw an error for the type.

### Actual Behavior
In CI ts-node throws an error and stops all unit tests from running. <https://github.com/dirigeants/Project-Blue/runs/697053999?check_suite_focus=true#step:7:7>

### Steps to reproduce the problem
This is related to another dep of the project `@klasa/bitfield` specifically a BitFieldResolvable type. While it is circular in 2 steps sortof, it's completely fine for typescript, and even works locally with ts-node running tests in ts for ava.

It's also completely fine in some of the repos it's in. While the [bitfield repo](https://github.com/dirigeants/bitfield/blob/master/src/index.ts#L5) itself doesn't have a problem running tests; our [WebSocket repo](https://github.com/dirigeants/ws/blob/master/src/util/Intents.ts#L3) had the issue from ts-node versions >8.6.2 to 8.10.1, and Project Blue only started having an issue recently (version 8.10.1) with [this](https://github.com/dirigeants/Project-Blue/blob/feat/magic-rgb-mushrooms/src/lib/util/bitfields/Permissions.ts#L3) which hasn't changed in the last 3 months (there are others that haven't ever had a problem in that same folder) and dependabot has been continuously testing/updating ts-node.

So while I know this isn't really "steps to reproduce" that's difficult because it's triggering in different repos, on different versions. Also only in CI. I have been able to run unit tests locally with ts-node on many of those versions with no issue, including the most recent version.

### Minimal reproduction
Reproduction doesn't seem to be consistent based on versions or existence of a type or type like one causing the error. Just tried dropping ts-node to version 8.0.0, and not even it will work on that line, even though the line hasn't changed in some time.

I really wish I could be more help, but none of my debugging results make any sense. I am hoping something I have said may give you guys some idea.

### Specifications

* ts-node version: 8.0.0, >8.6.2 to 8.10.1
* node version: 12.x, 14.x
* TypeScript version: ^4.0.0-dev.20200521, ^3.8.3
* tsconfig.json, if you're using one:
<https://github.com/dirigeants/ws/blob/master/tsconfig.json>
<https://github.com/dirigeants/Project-Blue/blob/master/tsconfig.json>
* Operating system and version: GitHub Actions (ubuntu-latest, windows-latest, macOS-latest)
* If Windows, are you using WSL or WSL2?: Not locally, unsure if GitHub Actions does

**Comment by cspotcode** [comment]
We really appreciate the effort to come up with a reliable reproduction, even if it was not 100% possible in this case.

A few things you can try:

Running with the `--files` flag: This may have to do with the order of loading files.  
When you run tsc, your entire project is loaded and typechecked all at once.  ts-node does the same thing with `--files`.  But without `--files` we don't eagerly add all `"files"` and `"includes"` from your tsconfig.  We add them as needed by `require()` calls and as triggered by `import`s and `/// <reference`s in the code.

Disabling any CI caching.

Prove without a doubt that ts-node is *always* using the version of TypeScript you expect.  Some circular references are supported in the current TypeScript but not older versions.  `process[Symbol.for('ts-node.register.instance')].ts.version`

**Comment by bdistin** [comment]
Unfortunately I could not find a way to pass that option into Ava, and discovered they have a new way of supporting typescript via tsc. That way seems to work, so I will close this now. Sorry, we couldn't pin down the underlying issue.
