### ISSUE TITLE
Transformers with transpileOnly

### ISSUE THREAD

**Issue by thetutlage** [TypeStrong/ts-node#1051]
I have read the readme file and it does mention that the transformers are not supported with the `transpileOnly` mode.

I do see that the source code is using [ts.transpileModule](https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L491) which does support custom transformers. So my question is mainly to understand the reasoning behind not allowing transformers, when the underlying API of typescript allows it?

**Comment by cspotcode** [comment]
Git blame offers some context.

https://github.com/TypeStrong/ts-node/blame/master/src/index.ts#L789
https://github.com/TypeStrong/ts-node/pull/879

Transformers get access to the typechecker, which isn't available in transpileOnly mode.

If you want to use transformers in transpileOnly mode, I recommend using `ttypescript` via our `compiler` option.  This will let you configure transformers via your tsconfig file.

`ttypescript` is a drop-in replacement for `typescript` with comprehensive transformer support.  `ts-node` supports using alternative compilers.

https://github.com/cevek/ttypescript/tree/master/packages/ttypescript

**Comment by thetutlage** [comment]
> Transformers get access to the typechecker
Yup, but there are other transformers as well. For example: A transformer to process path aliases and can be done in transpile only mode as well.

> If you want to use transformers in transpileOnly mode, I recommend using ttypescript via our compiler option. This will let you configure transformers via your tsconfig file.

Yes, but don't want to use that.

The main question was, if `transpileModule` from compiler API accept the transfomers (with whatever limited capability), then why we cannot pass those transformers to typescript vs deciding to remove them all together

**Comment by cspotcode** [comment]
Looking at our source code again, it looks like transformers actually are supported in `transpileOnly` mode.  The README's not super-clear, but it says that you cannot pass a factory function to our `transformers` option, but you can pass an object.

**Comment by thetutlage** [comment]
The code right now only accepts the `compilerOptions` and not the transformers.  This line https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L491

Whereas the options Typescript accepts are following.

```ts
interface TranspileOptions {
  compilerOptions?: CompilerOptions;
  fileName?: string;
  reportDiagnostics?: boolean;
  moduleName?: string;
  renamedDependencies?: MapLike<string>;
  transformers?: CustomTransformers;
}
```

**Comment by cspotcode** [comment]
This is what I'm looking at:

![image](https://user-images.githubusercontent.com/376504/82724903-450a5d00-9ca7-11ea-8f3e-4bc2608b3d4d.png)

Which matches the type signature in our README.

**Comment by thetutlage** [comment]
If types are working doesn't mean the runtime code is also working. The source code reference I shared with you clearly shows that `transformers` are not passed to the `transpileModule` method.

Check this out 

![CleanShot 2020-05-23 at 13 20 24](https://user-images.githubusercontent.com/1706381/82725097-3f893300-9cf8-11ea-887e-4ca7dc11e38b.gif)

**Comment by cspotcode** [comment]
In that case, marked as "bug" and "help wanted."  We'll accept a pull request that fixes it.

**Comment by thetutlage** [comment]
Sure, I will do a PR. Just wanted to understand, if we both expect it to work. Thanks 😄

**Comment by zyf0330** [comment]
Hello, `ts-node -C ttypescript` still fails, why?
