### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by bennyn** [TypeStrong/ts-node#1052]
### Expected Behavior

I expected "ts-node" to run my Jasmine test suite without complaining about "window" not being defined in my dependencies.

### Actual Behavior

Getting error:

> node_modules\amplify\lib\amplify.js:427
> }( this.amplify = this.amplify || {} ) );
> ^
> ReferenceError: window is not defined

### Steps to reproduce the problem

I ran:

>  nyc --nycrc-path=nyc.config.json jasmine --config=jasmine.json

Problem shows up when including my "globals.ts" file.

### Minimal reproduction

**globals.ts**

```ts
import {amplify} from 'amplify';

declare global {
  interface Window {
    amplify: amplify.Static;
  }
}

window.amplify = amplify;
```

**SomeModule.test.ts**

```
describe('SomeModule', () => {
  describe('test', () => {
    it('works', () => {
      expect('a').toBe('a');
    });
});
```

**jasmine.json**

```json
{
  "random": true,
  "spec_dir": "src",
  "spec_files": ["globals.ts", "SomeModule.test.ts"],
  "stopSpecOnExpectationFailure": true
}
```

**nyc.config.json**

```json
{
  "all": false,
  "check-coverage": false,
  "exclude": ["**/*.d.ts", "**/*.test*.ts"],
  "extension": [".ts"],
  "include": ["src/**/*.ts"],
  "per-file": false,
  "reporter": ["text-summary"],
  "require": ["tsconfig-paths/register", "ts-node/register/transpile-only"]
}
```

### Specifications

* ts-node version: 8.10.1
* node version: 13.10.1
* TypeScript version: 3.9.2
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "alwaysStrict": true,
    "baseUrl": ".",
    "declaration": false,
    "downlevelIteration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": ["dom", "esnext"],
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "src/script/auth",
    "paths": {
      "Util/*": ["./src/script/util/*"]
    },
    "resolveJsonModule": true,
    "rootDirs": ["src/script"],
    "sourceMap": true,
    "target": "es6"
  },
  "exclude": ["node_modules", "server"]
}
```
* Operating system and version:
* If Windows, are you using WSL or WSL2?: Windows 10

**Comment by cspotcode** [comment]
"Reference error" comes from node, not ts-node.  Looks like this is not a
ts-node issue.

**Comment by cspotcode** [comment]
Gonna go ahead and close this since I'm pretty sure it's not a `ts-node` issue.  If I'm wrong about that, we can definitely re-open.
