### ISSUE TITLE
Line numbers in stack trace wrong (on Windows)

### ISSUE THREAD

**Issue by jugglingthebits** [TypeStrong/ts-node#1058]
### Expected Behavior
I use ts-node to run an express app. An error handler catches exceptions. I expect line numbers to match the actual ones.

### Actual Behavior
The line numbers don't match.

### Steps to reproduce the problem
1. Run our (non-open-source) express app using ts-node
2. Trigger some exception
3. See stack trace with wrong line numbers

### Minimal reproduction

When I run https://github.com/TypeStrong/ts-node-repros/pull/4 locally on my Windows machine, I get different results compared to the Github Action result.

Github Action (correct):
![grafik](https://user-images.githubusercontent.com/3235163/83160256-42749100-a107-11ea-9a0a-ee913f20ad40.png)

Local machine (wrong):
![grafik](https://user-images.githubusercontent.com/3235163/83159552-64214880-a106-11ea-8cb9-7222a97aa01c.png)

On my machine, it reports line 4 to throw, as opposed to line 6 in the Github Action.

When I set `hookRequire = true` in the sourceMap setup, it starts reporting correct line numbers on my machine, too.

![grafik](https://user-images.githubusercontent.com/3235163/83159922-d7c35580-a106-11ea-87a0-eea75675ffa0.png)

![grafik](https://user-images.githubusercontent.com/3235163/83159988-ec075280-a106-11ea-9d50-9dd61ba832d4.png)

### Specifications

ts-node v8.10.1
node v12.17.0
compiler v3.9.3

* Operating system and version: Windows 10

* If Windows, are you using WSL or WSL2?: No

**Comment by cspotcode** [comment]
Might this be a duplicate of #1055 & #1037?

**Comment by jugglingthebits** [comment]
@cspotcode absolutely! will close this.

Duplicate of #1055

**Comment by jugglingthebits** [comment]
I can confirm that this works when using master.

**Comment by cspotcode** [comment]
@jugglingthebits Thanks, I'm working on preparing a release to fix this.  Unfortunately, I am swamped at work this week, so I think I'm going to publish as a different npm dist-tag so that people can install and test.  Then when I get confirmation that it works, I'll promote the dist-tag to `latest` so it's installed from npm by default.

**Comment by jugglingthebits** [comment]
@cspotcode thanks you! I can test the update here if it helps.

**Comment by cspotcode** [comment]
@jugglingthebits I just published 8.10.2 to npm as the `next` dist-tag.  If you're able to do a quick test, I'll be very grateful.
![image](https://user-images.githubusercontent.com/376504/83163623-3eca1580-a0d9-11ea-8475-abd448d46f18.png)

**Comment by jugglingthebits** [comment]
I can confirm that it works for me (on Windows)

**Comment by jugglingthebits** [comment]
@cspotcode thank you for your efforts!
