### ISSUE TITLE
ts-node with mocha v7 can't run tests

### ISSUE THREAD

**Issue by MoamenMohamedd** [TypeStrong/ts-node#1061]
### Expected Behavior
when adding this test script 
`mocha --require ts-node/register --extensions ts,tsx --watch --watch-files src 'src/**/*.spec.{ts,tsx}'` 

or

`mocha --require ts-node/register src/**/*.spec.ts`

 in package.json it should execute tests using mocha when running npm test.

### Actual Behavior
This error keeps showing 

> project@1.0.0 test /home/moamen/foo/baz
> mocha --require ts-node/register src/**/*.spec.ts
(node:48106) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.help (/home/moamen/foo/baz/node_modules/yargs/lib/usage.js:240:22)
    at Object.self.showHelp (/home/moamen/foo/baz/node_modules/yargs/lib/usage.js:432:15)
    at Array.<anonymous> (/home/moamen/foo/baz/node_modules/mocha/lib/cli/cli.js:53:13)
    at Object.fail (/home/moamen/foo/baz/node_modules/yargs/lib/usage.js:41:17)
    at /home/moamen/foo/baz/node_modules/yargs/lib/command.js:246:36
(Use node --trace-warnings ... to show where the warning was created)
(node:48106) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:48106) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

However ts-node by itself is working and it compiles code correctly.

### Steps to reproduce the problem
I followed basic instructions 
1) install ts-node globally
2) add this test script in package.json `mocha --require ts-node/register --extensions ts,tsx --watch --watch-files src 'src/**/*.spec.{ts,tsx}' ` 
3) npm test

### Specifications

* ts-node version: v8.10.2
* node version: v8.10.2
* TypeScript version: v3.9.3
* tsconfig.json, if you're using one:
```
{
"compilerOptions": {
        "target": "es6" ,
        "module": "commonjs",
        "sourceMap": true ,
        "outDir": "dist" ,
        "strict": true ,
        "moduleResolution": "node" ,
        "esModuleInterop": true 
        },
    "lib": ["es2015"]
}
```
* Operating system and version: manjaro relase: 20.0.1 code name: Lysia, kernel version: 5.6.12-1

**Comment by cspotcode** [comment]
Thanks for the detailed report.  At first glance, this looks like a mocha bug.  Mocha is throwing the error, and I'm not seeing where `ts-node` is failing.  According to that stack trace, mocha is calling yargs' `showHelp` function.

Have you tried using `mocha --require` without `ts-node`?  Do a very similar mocha invocation, but one that doesn't require TS and doesn't load `ts-node`?

**Comment by MoamenMohamedd** [comment]
yes you are right I tried with another package and same error occurred  
`mocha --require faker/register src/**/*.spec.ts`
