### ISSUE TITLE
Options.ignore changed type from 8.0.1 to 8.0.2

### ISSUE THREAD

**Issue by simhnna** [TypeStrong/ts-node#1063]
Previously (ts-node 7.x.x) options.ignore used to be a `string | string[]` and it continued to be supported in 8.0.0.

However in 8.0.2 it was changed to only accept `string`

The breaking change is this commit https://github.com/TypeStrong/ts-node/commit/0db041f4ca0e7f125bc1febc037ece742503f340

The current types only allow an array, but the docs say that the default is a string

https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L171

Can we bring back `string | string[]`?

**Comment by cspotcode** [comment]
What's your use-case?  Is this causing you trouble on a project?

**Comment by blakeembrey** [comment]
The commit you pointed out doesn’t change the input type of the option. Also, as far as I can see in both that commit and master, it accepts only an array of strings.

**Comment by blakeembrey** [comment]
To clarify, the contract this module follows is what is documented (usually in the type system). In this case the breaking change was an undocumented use case that wouldn’t compile in typescript. Happy to update the README to match correctly.

**Comment by cspotcode** [comment]
Closing because relevant docs improvements are covered by #1089.
