### ISSUE TITLE
Cannot find name xxx, while defined in @types/xxx.d.ts

### ISSUE THREAD

**Issue by adaamz** [TypeStrong/ts-node#1066]
### Expected Behavior
No import error

### Actual Behavior
```
vehicle.ts:1:41 - error TS2304: Cannot find name 'Vehicle'.
```
while webpack compiles with no problems (via ts-loader)

### Steps to reproduce the problem
1. create @types/vehicle.d.ts with defined type `Vehicle`
2. create vehicle.ts with used type `Vehicle` from `vehicle.d.ts`
3. run ts-node vehicle.ts

### Minimal reproduction repository (with github actions integrated)
https://github.com/adaamz/ts-node-jasmine-bug

### Specifications
* ts-node version: 8.10.2
* node version: 10, 12, 14
* TypeScript version: 3.9.5
* tsconfig.json:
```json
{
  "compilerOptions": {
    "allowJs": false,
    "allowSyntheticDefaultImports": false,
    "alwaysStrict": true,
    "esModuleInterop": false,
    "module": "commonjs",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "target": "es5"
  }
}
```
* Operating system and version:
Windows 10, also github actions (ubuntu latest)

**Comment by cspotcode** [comment]
Try running ts-node with the `--files` flag.  Tsc loads all matched "files"
and "includes" when it typechecks; ts-node does not for performance
reasons.  `--files` makes it load them like tsc.

**Comment by cspotcode** [comment]
I should say "eagerly loads.". Ts-node always loads files when they're ///
<referenced, imported, or require()d.  But in your example, you're relying
on tsc's eager loading of all matched "includes" and "files"

**Comment by adaamz** [comment]
thx for reply!
So how should I change my code that i don't need this "hack"/change of default behavior?
I don't understand what is non-standard in my codebase.

**Comment by cspotcode** [comment]
Add a /// <reference to the file that you need the type-checker to look at.

**Comment by adaamz** [comment]
So the @types directory is problem?

I have there currently only 1 file in my project, so I can move it somewhere else. My use case for this is I want to hide/separate definitions from real app code, because it is really long :-/

**Comment by cspotcode** [comment]
To make TSC behave like `ts-node`, make the `files` and `include` arrays in your tsconfig empty except for the entry-point file.

```
"files": ["vehicle.ts"],
"include": [],
```

That's what ts-node is doing.  Empty arrays, except when a file is require()d, it gets added to the `files` array.

Then you can experiment to make your setup work the way you want.

Since this is not a ts-node bug, this is all the assistance I have time to provide.  ts-node's README, StackOverflow, reddit, and the TypeScript Discord may be able to offer more assistance.

Good luck!

**Comment by adaamz** [comment]
Thanks for tips.

I get to working solution with these changes
- tsconfig.json moved to project root
- added typeRoots to tsconfig.json
- moved vehicle types to `@types/Vehicle/index.d.ts`
https://github.com/adaamz/ts-node-jasmine-bug/pull/1

Do you have any idea why this works and why is necessery to have tsconfig in project root and manually set these typeRoot directories and have types in this vehicle/index.d.ts (even have types in vehicle.d.ts and import in index.d.ts doesnt work)?

**Comment by Bijiabo** [comment]
Still not work for me, why it's so different as tsc....
