### ISSUE TITLE
what are the breaking changes in v7 and v8?

### ISSUE THREAD

**Issue by oprogramador** [TypeStrong/ts-node#1068]
Hi,

could you specify the breaking changes in https://github.com/TypeStrong/ts-node/releases?after=v8.2.0 for v7 and v8?

**Comment by cspotcode** [comment]
For upgrading from v7 -> v8:
https://github.com/TypeStrong/ts-node/releases/tag/v8.0.0

For upgrading from v6 -> v7:
https://github.com/TypeStrong/ts-node/releases/tag/v7.0.0

You'll have to decide if those changes will break your project.  For many projects and usages, these changes do not break anything.

**Comment by oprogramador** [comment]
thanks
