### ISSUE TITLE
ESM support: can't recognize '--experimental-specifier-resolution' flag passed via NODE_OPTIONS

### ISSUE THREAD

**Issue by VladimirGrenaderov** [TypeStrong/ts-node#1072]
Code at https://github.com/TypeStrong/ts-node/blob/44c61af923baaa9f3aa4b84a93fe903cf44f10fb/dist-raw/node-esm-resolve-implementation.js#L73 uses process.execArgv to get options and doesn't analyze NODE_OPTIONS anyhow.

**Comment by cspotcode** [comment]
I'm marking this as "help wanted" to indicate that we'll wait for a pull request.  This seems like a straightforward contribution.

`node-esm-resolve-implementation.js` is largely copied from node's own source code.
https://github.com/TypeStrong/ts-node/blob/44c61af923baaa9f3aa4b84a93fe903cf44f10fb/dist-raw/node-esm-resolve-implementation.js#L1-L4

To write an ESM loader, we need to mimic many built-in behaviors of node.  Unfortunately node does not expose this functionality via an API.  So our best option for maintainability is to copy-paste node's own implementation where appropriate, tweaking as needed.

See also: discussion in #1010, where @evg656e helped me implement our `execArgv` parsing.

**Comment by evg656e** [comment]
Yep, I missed the need to parse the `NODE_OPTIONS` environment variable in the initial implementation.

Unfortunately, the `arg` parser does not allow getting options of the environment variables (like 'yargs` [.env](https://yargs.js.org/docs/#api-reference-envprefix) function does).

The workaround to use [ParseNodeOptionsEnvVar](https://github.com/nodejs/node/blob/67ba825037b4082d5d16f922fb9ce54516b4a869/src/node_options.cc#L1024) from node source.

I rewrote [getOptionValue](https://github.com/evg656e/ts-node/blob/0276a9255552495d2384de222c00bfd0d68b1a81/dist-raw/node-esm-resolve-implementation.js#L53) code in my branch.

As you can see, the code becomes quite messy, so it may be worth putting it into a separate file to keep main module clean.
