### ISSUE TITLE
fall use enum with Logical nullish assignment (??=)

### ISSUE THREAD

**Issue by bluelovers** [TypeStrong/ts-node#1079]
```ts
POSTAG_KEYS.forEach(function (key)
{
	let lc = key.toLowerCase();

	// @ts-ignore
	POSTAG[lc] ??= POSTAG[key];
	// @ts-ignore
	CHSNAME[lc] ??= CHSNAME[key];
	// @ts-ignore
	ZHNAME[lc] ??= ZHNAME[key];
	// @ts-ignore
	ENNAME[lc] ??= ENNAME[key];
});
```

if use `=` will not have error

`POSTAG_KEYS` is enum keys

POSTAG, CHSNAME, ZHNAME, ENNAME is enum

use `@ts-ignore` but still get error

typescript didn't have error for this code

### Expected Behavior

no error

### Actual Behavior

```
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts(13,15): error TS1109: Expression expected.
index.ts(15,16): error TS1109: Expression expected.
index.ts(17,15): error TS1109: Expression expected.
index.ts(19,15): error TS1109: Expression expected.
```

### Specifications

* ts-node version:
* node version:
* TypeScript version:
* tsconfig.json, if you're using one:
```
{}
```
* Operating system and version:
* If Windows, are you using WSL or WSL2?:

**Comment by cspotcode** [comment]
TSError indicates a TypeScript error.  Is this error happening with TSC?

**Comment by bluelovers** [comment]
my ide didn't show error, only happen when run with ts-node

**Comment by cspotcode** [comment]
What about if you compile with TSC?

**Comment by bluelovers** [comment]
looks like is my bad, repo exists 2 version of typescript
