### ISSUE TITLE
Translate import.meta.url into __filename

### ISSUE THREAD

**Issue by Jack-Works** [TypeStrong/ts-node#1080]
[See the solution here](#issuecomment-661604358)

### Desired Behavior

```ts
console.log(import.meta.url) // equal to __filename
import.meta.url = ''
console.log(import.meta.url) // equal to ''
console.log(import.meta)
```

Generally, add a custom transformer, and transform the code above into:

```ts
// this identifier should be created by ts.createFileLevelUniqueName()
const _meta = { url: __filename }
console.log(_meta.url) // equal to __filename
_meta.url = ''
console.log(_meta.url) // equal to ''
console.log(_meta)
```

### Is this request related to a problem?

I need to render my ES module based application on the server-side (SSR).

My code involves usage of `import.meta.url`. TypeScript (and ts-node) reports

> error TS1343: The 'import.meta' meta-property is only allowed when the '--module' option is 'esnext' or 'system'.

But it _can_ be resolved in the node. There is a way to support it.

### Alternatives you've considered

Let me able to use other typescript packages like `ttypescript` so I can specify my own `import.meta` transformer in `tsconfig` and get used by ts-node.

```jsonc
// tsconfig.json
{
  "ts-node": {
    "transpileOnly": true,
    "typescript": "ttypescript",
    "plugins": ["import.meta.transformer"]
  },
  "compilerOptions": {}
}
```

**Comment by cspotcode** [comment]
You mention that you want to use `ttypescript` with custom plugins.  This should work, but you've specified "plugins" in the wrong place.  The schema helpfully points this out:
![image](https://user-images.githubusercontent.com/376504/87954082-df093e80-ca79-11ea-8a52-e27b59134f67.png)
![image](https://user-images.githubusercontent.com/376504/87954121-ec262d80-ca79-11ea-846b-4b8cd5e23118.png)

I would try moving "plugins" to the right place and see if that does the trick.  Note that we *do* support a nested `compilerOptions` within the `ts-node` config object, which can contain ts-node-specific overrides, but I'm not sure if ttypescript will recognize it.  If you find out, I'm curious to know the answer.

**Comment by Jack-Works** [comment]
Umm how can I let ts-node call ttypescript instead of typescript in tsconfig file? I'll try it.

(It would be better if I can specify transpileOnly mode in tsconfig cause the caller of ts-node is which I can't controll)

**Comment by cspotcode** [comment]
Our readme explains how to specify ts-node options in your tsconfig file.  The schema should help you too.  (see the screenshots of tooltips above)  If you're not using an editor with that sort of tooling, then you can read the schema manually on SchemaStore: https://www.schemastore.org/json/

**Comment by Jack-Works** [comment]
Cool! I'll investigate it later today

**Comment by Jack-Works** [comment]
Done, anyone wants to use `import.meta` in `ts-node` please go to https://github.com/Jack-Works/commonjs-import.meta

```jsonc
{
    "ts-node": {
        "$schema": "https://unpkg.com/browse/ts-node@8.8.2/tsconfig.schema.json",
        "compilerOptions": {
            "module": "CommonJS",
            "plugins": [{ "transform": "@magic-works/commonjs-import.meta" }]
        },
        "compiler": "ttypescript",
        // One of:
        "ignoreDiagnostics": [1343],
        // Or:
        "transpileOnly": true
    }
}
```

**Comment by cspotcode** [comment]
@Jack-Works Nice, looks great, and thanks for sharing here.

Small correction on the schem:, it's meant to describe the entire tsconfig file, not the ts-node sub-object.  And we've merged it into the official schema which editors pull by default, so specifying it should not be necessary at all.  But if you do want to specify explicitly, then `"$schema"` should be a property of the root object.

For example:
```
{
  "$schema": "node_modules/ts-node/tsconfig.schema.json", // Can use a URL or local path.  This is optional, b/c editors pull the official schema by default (AFAIK)
  "ts-node": {...},
  "include": ["src"],
  "compilerOptions": {...}
}
```

Here is the official schema which already includes `ts-node`'s options.
https://json.schemastore.org/tsconfig

---

What is `ignoreDiagnostics: [1343]` for?  Is there a way to use type assertions to avoid introducing that diagnostic?

**Comment by Jack-Works** [comment]
> The 'import.meta' meta-property is only allowed when the '--module' option is 'esnext' or 'system'.ts(1343)

**Comment by Jack-Works** [comment]
> And we've merged it into the official schema which editors pull by default

Cool!
