### ISSUE TITLE
npm WARN ts-node@8.10.2 requires a peer of typescript@>=2.7 but none is installed. You must install peer dependencies yourself

### ISSUE THREAD

**Issue by zaima-zaima** [TypeStrong/ts-node#1094]
I have installed the typescript@3.9.7,but I can't install yet

**Comment by cspotcode** [comment]
Per npm's instructions, you must install peer dependencies yourself.  Fortunately this is a characteristic of the node ecosystem, not of ts-node specifically, so there is no need for us to provide guidance in this situation.  You should be able to find all the information you need in npm's documentation, on various forums, etc.  ts-node is not doing anything atypical or non-standard.
