### ISSUE TITLE
Flag to override a default of `transpileOnly`

### ISSUE THREAD

**Issue by ArkadyDR** [TypeStrong/ts-node#1119]
### Desired Behavior

If I configure `transpileOnly: true` in my `tsconfig.json`, I would like to provide a flag to `ts-node` that is the opposite of `-T`/`--transpile-only`, i.e. forces type checking.

### Is this request related to a problem?

In our project, developers typically run compile/lint/test under a single npm script (eg `npm run check`), which does a `tsc` and then runs tests and various other scripts under `ts-node`. In this case any type checking when running tests/scripts is redundant as we've already passed `tsc` over the whole codebase and bailed if it didn't compile. Rather than specify for every step in that chained command that it should be run in `transpileOnly` mode, it is far easier/briefer to configure in `tsconfig.json` that by default `ts-node` should run in transpileOnly mode.

However, if a developer wants to run a particular step/script with type checking on during development, there isn't a flag to force this behavior back on again.

### Alternatives you've considered

- Have a separate tsconfig file that doesn't force `transpileOnly`, and have developers use `--project <my other file>` to indicate they want checking. Requires maintaining two tsconfig files, as the `ts-node` compiler options don't appear to follow through 'extends'? Also is less obvious than `--transpile-only=false` or `-t` or similar.
- Have a custom script pulled in via `require` that looks for a CLI argument to turn on type checking, and adjust ts-node's setting on the fly. In testing this looks like it is too late to change the behavior - I can toggle the `ts-node.register.instance.options.transpileOnly` value without effect.
- Make the `-T` flag toggle between type checking and transpileOnly, so that you can set it to be transpile by default and then `-T` has the effect of turning it back on. I think this would be confusing as it relies on you knowing what the evaluated setting is (it has a default, then can be overridden in config, and then overridden via an environment variable)

### Additional context

As is typical in development, hardest bit would be figuring out what to call the flag. :smile:

**Comment by cspotcode** [comment]
We use this for parsing flags under the hood: https://www.npmjs.com/package/arg

Does it offer any mechanism to pass `false` for a boolean flag?

**Comment by cspotcode** [comment]
If not, I've seen that a -`-no-` prefix is used to flip the meaning of a flag in some CLI tools.  Yargs does this automatically for example.

**Comment by cspotcode** [comment]
@ArkadyDR I've labelled this as "help wanted" to indicate we'll probably accept a PR implementing the `--no-` prefix on all our Boolean flags.  For example, `--no-transpile-only` can set `transpileOnly` to false even if it is true in a tsconfig file.

I say "probably" because there's a slim chance it would be rejected in code review if others thought it complicated our CLI interface or some of the `--no-` variants looked confusing.  I don't think we would show them in our `--help` output, and we would only make a small mention of it in the README: something like "flags can be negated with a `--no-` prefix, for example `--no-files`.

Having said that, you have a real, practical use-case, so this seems like a feature worth having.

PR checklist:
* Update the README as described above
* Add the necessary declarations and logic to `bin.ts`: https://github.com/TypeStrong/ts-node/blob/master/src/bin.ts#L35-L112
* make sure `false` correctly overrides `true` as it passes through our `create()` codepaths (if we are lazy and check for "falsiness" instead of `undefined` then we might need to tweak some stuff)

**Comment by blakeembrey** [comment]
This may be confusing (and the `--no-` a better long term option), but we do have a legacy `--type-check` flag that's actually used for exactly this. There was a version a few years back that was `--transpile-only` by default and the flag is still in our `bin.ts` file. I'm not 100% confident that both these flags are currently working properly with all the different places they can be specified, but assuming they are the only place you need to update is https://github.com/TypeStrong/ts-node/blob/8dfb75cfe811b8741218c19f56bd9ff5d1425daa/src/index.ts#L438.

**Comment by blakeembrey** [comment]
Changing that do `options.transpileOnly === true && options.typeCheck !== true` should do the trick, although ideally I think we'd want to kill this flag and have only one so they're being merged correctly throughout each step (e.g. `transpileOnly: true` in the CLI should correctly override `typeCheck: true` in our config.

**Comment by ArkadyDR** [comment]
Thanks for the quick feedback @blakeembrey and @cspotcode .

> Does it offer any mechanism to pass false for a boolean flag?

Had a look, doesn't appear to offer anything specifically around this. I don't think it even supports `--transpile-only=no` (where the `=no` bit is optional).

With respect to a general `--no-` prefix, I think with most of the CLI options it would make them confusing and not indicate what it's trying to do. For example:

- `--no-compiler` is misleading - it means "use the default compiler"?
- `--no-project` is confusing with `--skip-project`

Then it's also unclear whether some of them should have the semantics of adding to existing lists or replacing them. For example if I wanted to stop a particular configured `require` from being brought in, do I go `--no-require --require <everything else>`, or does `--require <everything else>` overwrite? (This isn't how @cspotcode implemented the merging of the `require` option, rightly so I think).

I think rather than `--no-transpile-only`, it personally would make more sense to me to be `--type-check` and `--no-type-check`, what was the reason you switched from one to the other?

**Comment by ArkadyDR** [comment]
> Changing that do options.transpileOnly === true && options.typeCheck !== true should do the trick, although ideally I think we'd want to kill this flag and have only one so they're being merged correctly throughout the codebase (e.g. transpileOnly: true in the CLI should correctly override typeCheck: true in our config.

Sounds straightforward, I'll have a play when I next get some free time.

**Comment by blakeembrey** [comment]
Realized I didn't answer this question:

> what was the reason you switched from one to the other?

It was mostly to align with https://github.com/TypeStrong/ts-loader#transpileonly, and also because `--type-check` days was when transpile only was the default behavior but that ended up confusing more people than it's worth.

**Comment by ArkadyDR** [comment]
Thanks @cspotcode, you got some free time before me I see :)
