### ISSUE TITLE
return new TSError(diagnosticText, diagnosticCodes)

### ISSUE THREAD

**Issue by SeanDez** [TypeStrong/ts-node#1125]
### Expected Behavior

VsCode runs debugger normally

### Actual Behavior

Upon starting the debugger;

```
/home/owner/cp/asanaTaskRepeaterBackend/node_modules/ts-node/src/index.ts:500
    return new TSError(diagnosticText, diagnosticCodes)
           ^
node_modules/source-map-support/source-map-support.js:475
Process exited with code 1
TSError: ⨯ Unable to compile TypeScript:
src/authenticate/router.ts(45,1): error TS1128: Declaration or statement expected.

    at createTSError (/home/owner/cp/asanaTaskRepeaterBackend/node_modules/ts-node/src/index.ts:500:12)
    at reportTSError (/home/owner/cp/asanaTaskRepeaterBackend/node_modules/ts-node/src/index.ts:504:19)
    at getOutput (/home/owner/cp/asanaTaskRepeaterBackend/node_modules/ts-node/src/index.ts:739:36)
    at Object.compile (/home/owner/cp/asanaTaskRepeaterBackend/node_modules/ts-node/src/index.ts:955:32)
    at Module.m._compile (/home/owner/cp/asanaTaskRepeaterBackend/node_modules/ts-node/src/index.ts:1043:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/owner/cp/asanaTaskRepeaterBackend/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### Steps to reproduce the problem

1. Install ts-node 9.0.0 via npm
2. Run a VsCode launch config with these exact settings:

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-node",
      "request": "launch",
      "name": "Launch Program",
      "skipFiles": [
        "<node_internals>/**",
        "node_modules"
      ],    
      "runtimeArgs": [
        "-r",
        "ts-node/register",
        // "--no-cache"
      ],
      "args": [
          "${workspaceFolder}/src/server.ts"
      ]
    }
  ]
}
```

### Minimal reproduction

See above.

### Specifications

* ts-node version: 9.0.0
* node version: 12.18.4
* TypeScript version: "^3.9.7"
* tsconfig.json, if you're using one: 
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "CommonJS",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "outDir": "compiled"
  },
  "include": [
    "src"
  ],
  "exclude": ["node_modules", "**/*.test.ts"]
}
```
* Operating system and version: Lubuntu 18.04
* If Windows, are you using WSL or WSL2?:

**Comment by cspotcode** [comment]
```
TSError: ⨯ Unable to compile TypeScript:
src/authenticate/router.ts(45,1): error TS1128: Declaration or statement expected.
```

This is a normal TypeScript error.  ts-node uses the TypeScript compiler to check for syntactic and semantic errors.  When the compiler returns errors, we throw them.  This is intended behavior.

**Comment by ivanjeremic** [comment]
In my case, the normal compilation has no errors but running with ts-node it throws errors.

**Comment by JontyyYang** [comment]
> ```
> TSError: ⨯ Unable to compile TypeScript:
> src/authenticate/router.ts(45,1): error TS1128: Declaration or statement expected.
> ```
> 
> This is a normal TypeScript error. ts-node uses the TypeScript compiler to check for syntactic and semantic errors. When the compiler returns errors, we throw them. This is intended behavior.

I also encountered this problem, what I want to ask is, can ts-node execute ts file, can it only prompt for type errors without blocking

**Comment by blakeembrey** [comment]
From the [docs](https://github.com/TypeStrong/ts-node#diagnostics), you can use `--log-error`.

**Comment by AceCoderYoda** [comment]
Expected behaviour?
So why doesn't it throw this error from one folder, but does when run from another.
Using the exact same command the only difference being the folder from which it is run, I either get an error or it runs perfectly. So from one folder it compiles, from the other it doesn't

**Comment by cspotcode** [comment]
Directory-sensitive behavior would be due to cwd-mode which is no longer the default as of v10.

https://github.com/TypeStrong/ts-node/releases/tag/v10.0.0
