### ISSUE TITLE
TypeError: Cannot destructure property 'graphqlHTTP' of 'express_graphql_1.default' as it is undefined

### ISSUE THREAD

**Issue by dschinkel** [TypeStrong/ts-node#1127]
I'm pretty stuck here so posting this here since I think it's a ts-node issue or issue that can be resolved by ts-node somehow but I don't know what.  I've posted this other places but so far, no luck on help with it.

mocha is using ts-node here.  It's not a mocha issue.

**When I run this test:**
```js
import { expect } from '../test.imports';
import App from '../../../server-new/api';

const request = require('supertest');

describe.skip('Company - Integration Tests', () => {
  let req;

  before(() => {
    const service = App.listen(4000);
    req = request.agent(service);
  });
```

**I get:**

```js
const { graphqlHTTP } = expressGraphQL;
        ^
TypeError: Cannot destructure property 'graphqlHTTP' of 'express_graphql_1.default' as it is undefined.
The test imports a file api.ts (import App from '../../../server-new/api';) which in turn imports GraphQL:
```

**api.ts**(I had to import graphQL this way because those two modules did not have default exports so node won't let me)

```js
import it any other way:

import expressGraphQL from 'express-graphql';
import graphQL from 'graphql';

const { graphqlHTTP } = expressGraphQL;
const { buildSchema } = graphQL;
```

**mocharc.json** in my actual test folder is:

```js
{
  "extension": ["ts"],
  "spec": ["src/test/server-new/**/*.spec.ts"],
  "require": ["./src/test/server-new/compiler.ts"]
}
```

**compiler.ts**
```js
require('ts-node').register({
	project: './src/test/server-new/tsconfig.json',
});
```

I also have a **tsconfig.json** in my **test** folder:
```js
{
  "compilerOptions": {
    lib": ["es2020"],
    "module": "commonjs",
    "target": "es2020",
    "sourceMap": false,
    "inlineSources": false,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "noImplicitThis": false
  "include": ["src/test/server-new/**/*.ts"]
}
```

Note that the f**older api.js is in** has a **package.json** with `"type":"module"` so it's treating that as an ESM module.

Now, outside of the tests, when I run that service, it runs fine with this script after TS compiles it to my dist folder. I'm not running tests on my dist but this is just to say that the api.ts runs fine in production: `node --optimize_for_size --trace-warnings --es-module-specifier-resolution=node --no-warnings dist/server-new/server.js`

**Comment by cspotcode** [comment]
I recommend asking about this on the TypeScript Discord server.  Could be an `esModuleInterop` issue, could be an issue with doing native ESM incorrectly.

Right now, the evidence points towards this being either an honest mistake on your part or a limitation in the combination of TypeScript & node.  I'm not seeing clear evidence that it's a `ts-node` problem specifically.  Unfortunately this issue tracker isn't intended for general TypeScript support, whereas the TypeScript Discord is set up to answer support questions.

If this can be narrowed down to a simpler, reproducible example, that demonstrates a bug in `ts-node` (as opposed to TypeScript, mocha, and/or node) then we'll fix it.
