### ISSUE TITLE
ESM fix for node 14.13.1 breaking change

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1130]
Pretty sure it's cuz the URL protocol for native modules changed from `nodejs:` to `node:` and has to do with our necessary forking of node's resolver.

Fix must:
- be backwards compatible (at least in the short-term).  Before 14.13.1 needs to use `nodejs:`; after needs to use `node:`
- test suite updated to run 14.13.0 and 14.13.1 (or at least one 14.x version before and one after)
- specs should attempt to load native modules *without* import elision

Relevant conversation starts here: https://github.com/TypeStrong/ts-node/issues/1007#issuecomment-706684853

**Comment by cspotcode** [comment]
Maybe `node:` vs `nodejs:` can be feature-detected the first time our `resolve` implementation is called. `defaultResolve('node:fs')` and look at what it gives us.

**Comment by concision** [comment]
If anyone needs a quick fix, experimentally this solution seems to work by early deferring Node.js builtin modules (i.e. `null` specifier). Might not work in 100% of scenarios - your mileage may vary.

Create a new file `ts-node-esm-fix.mjs` and set the ESM loader to it (e.g. `--loader=./ts-node-fix.mjs`):
```js
import url from "url";

// initialize ts-node ESM loader; promise to early initialize
const esmLoader = new Promise(async (resolve, reject) => {
    try {
        resolve(await import("ts-node/esm.mjs"));
    } catch (error) {
        reject(error);
    }
});

// delegate to ts-node ESM loader
export async function resolve(specifier, context, defaultResolve) {
    // resolves change from 'nodejs:' to 'node:'
    if (url.parse(specifier).protocol === null) return defaultResolve(...arguments);
    return (await esmLoader).resolve(...arguments);
}
export async function getFormat() {
    return (await esmLoader).getFormat(...arguments);
}
export async function transformSource() {
    return (await esmLoader).transformSource(...arguments);
}
```

**Comment by cspotcode** [comment]
Over the weekend I merged a fix to master, so this should already be fixed
on master.

**Comment by cspotcode** [comment]
Npm can install ts-node directly from github instead of npmjs.com, allowing you to use the latest code from master.

**Comment by concision** [comment]
Ah, I did not realize that npm/yarn will build a module directly from GitHub! Thanks for letting me know! And thank you for your work on ts-node! :)
