### ISSUE TITLE
does not return exitCode to stderr in windows

### ISSUE THREAD

**Issue by dphochman** [TypeStrong/ts-node#1133]
### Expected Behavior

A command-line with `ts-node` followed by `&&` should not continue executing commands if the ts-node process returns a non-zero exit code.  This is true for `node`, `deno`, and other command-line tools.  This is true on Linux, MacOS, and Windows.

### Actual Behavior

In a Windows Command Prompt (cmd), a command-line continues even if the ts-node process returns with a non-zero exit code.  It works as expected in Mac and Linux.  It works as expected for node and deno.

### Steps to reproduce the problem

1. Make a script or executable typescript expression that returns a non-zero exit code, e.g. `process.exit(1)`, `process.exitCode=1`. 
1. Run the script or expression via `ts-node`, and use the exit code in a command pipeline with the `&&` operator.
1. If an expression returns a non-zero exit code, the commands following the `&&` operator should not be executed.

### Minimal reproduction

The first command fails in Windows, and succeeds in Linux & MacOS:
* `ts-node -e "process.exit(1)" && echo FAIL`
* `ts-node -e "process.exit(0)" && echo SUCCESS`

It works as expected for node, in Windows, Linux, & MacOS:
* `node -e "process.exit(1)" && echo FAIL`
* `node -e "process.exit(0)" && echo SUCCESS`

### Specifications

* ts-node v9.0.0
* node v12.16.1
* compiler v3.9.7
* Operating system and version: Microsoft Windows [Version 10.0.18363.1139]
* If Windows, are you using WSL or WSL2?: no

**Comment by cspotcode** [comment]
Do you know if this is caused by npm's shim scripts?  Does it happen for
other CLI tools installed via npm, which have the same shim script?

**Comment by dphochman** [comment]
@cspotcode good question! i think you are on the right track.  
expanding the command outside of the script does not fail:

`node "%USERPROFILE%\AppData\Roaming\npm\node_modules\ts-node\dist\bin.js" -e "process.exit(1)" && echo FAIL`

that's a bit more verbose than `ts-node -e "process.exit(1)" && echo FAIL`
but it proves your point.

**Comment by cspotcode** [comment]
Unfortunately if this is caused by npm's cmd shims, there's not anything we
can do.  We get a bunch of bug reports about the cmd shims on Windows.  It
all works fine on Posix.  If you're curious for more details you can search
for the other issues.
