### ISSUE TITLE
throw error: Unable to compile TypeScript - when check data type by function

### ISSUE THREAD

**Issue by ngvcanh** [TypeStrong/ts-node#1135]
### Expected Behavior

Detect the previously returned `undefined` instance and the other is `string`

### Actual Behavior

Can't understand checked data case it is `undefined` previously and throw error

### Steps to reproduce the problem

Throw error at line 89 in index.ts file.

### Minimal reproduction

```
git clone https://github.com/ngvcanh/node-ts-error.git
cd node-ts-error
npm i
npm start
```

### Specifications

* ts-node version: `9.0.0`
* node version: `12.16.1`
* TypeScript version: `4.0.3`
 tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "outDir": "dist",
    "sourceMap": true,
    "baseUrl": "src"
  }
}
```
* Operating system and version: Windows 10 x64 - 19041.572
* If Windows, are you using WSL or WSL2?:

**Comment by cspotcode** [comment]
What error(s) do you get when you compile your code with `tsc`?

**Comment by ngvcanh** [comment]
> What error(s) do you get when you compile your code with `tsc`?

I compiled with `tsc` and no error in there

**Comment by cspotcode** [comment]
What do you think is the difference between the two?  Something to do with not using `--files`?  Given that we use typescript to do the typechecking, what would have changed?  Where does a bugfix need to happen?

**Comment by ngvcanh** [comment]
@cspotcode 

I would like to describe a bit of what I have tried.

That's when I was using the `map()` method to traverse an array of data and that required returning a value.

Inside the callback function passed to the `map()` method, I call a defined function that returns a `string` or `undefined`.

I have tried the following 3 methods of checking data:

```
let value = format(...);

// Option 1
if (value === undefined){
    return undefined;
}
else{
    return value + "any";
}

// Option 2
if (value === undefined){
    return undefined;
}
return value + "any";

// Option 3
if (isUndefined(value)) return undefined;
return value + "any";
```

So, when I run the code without compile, Option 3 has an error while options 1 and 2 have no errors. The `isUndefined()` function simply returns the result of the condition like options 1 and 2.

```
function isUndefined(obj: any): boolean {
  return obj === undefined;
}
```

I think TypeScript does not understand that `undefined` type is checked inside the function.

I'm new to TypeScript and I really do not understand the difference between the two.

**Comment by cspotcode** [comment]
@ngvcanh 
I'm getting the same error from `tsc`, according to this reproduction: https://github.com/TypeStrong/ts-node-repros/runs/1306068270#step:5:38

You can see what I'm doing in `run.sh`.  I clone your reproduction, then run `tsc`.

**Comment by ngvcanh** [comment]
@cspotcode 
That error is what I mean. I think TypeScript ignores conditions that are listed inside a conditional function.

I'm new to TypeScript so I got a bit confused with them. I don't know what I should do to overcome that error.

And you've tagged `need more info` but I don't really know what to add as well. Can you tell me what more information I should provide?

Thank you and regards for your support.

**Comment by cspotcode** [comment]
"needs more info" was a signal to myself that I was waiting for your response.

This is the `ts-node` issue tracker, which is intended for reporting bugs or enhancement requests for `ts-node`.

In this case, this is a TypeScript diagnostic, and `ts-node` is correctly reporting the diagnostic to the user.  So this is not a `ts-node` bug.

To ask questions about TypeScript, I recommend the TypeScript Discord server, which is one of our suggested links when you open an issue.

**Comment by ngvcanh** [comment]
I just want to comment on this as a solution for someone to come later and need it. I have no intention of reopening this issue.

The function declaration is as follows so that TypeScript understands the function used to check the data type:

```js
function isUndefined (obj: any): obj is undefined {
    return obj === undefined;
}
```

The way of declaring functions to check other data types is similar to the above declaration
