### ISSUE TITLE
Tons of errors randomly

### ISSUE THREAD

**Issue by sandorvasas** [TypeStrong/ts-node#1143]
Version 7

I'm not sure if this is a ts-node error or a typescript compiler one, but I have no clue how to trace this back: Sometimes when our project is started up, typescript type errors pop up in the console one by one. Only one pops up, and when fixed, another pops up. These errors are related to code snippets sometimes more than years old, meaning they compiled fine for years, and now the compiler just seemingly randomly found a type error in them. Our project being pretty large, this is kind of nightmarish when it does this during making urgent hotfixes that need to be pushed fast. What could possibly be the reasons behind such behavior?

### Expected Behavior
Compiles fine as before.

### Steps to reproduce the problem
I have no idea.

**Comment by cspotcode** [comment]
I'm gonna close this because it doesn't seem to be a bug report, and this issue tracker isn't used for support requests.  We have links [here](https://github.com/TypeStrong/ts-node/issues/new/choose) to a few community resources you can use to get support.
