### ISSUE TITLE
Parsing of CLI args differs between ts-node and node -r ts-node/register

### ISSUE THREAD

**Issue by ArkadyDR** [TypeStrong/ts-node#1162]
On windows, ts-node is splitting quoted CLI args (eg paths) on spaces, different from what node.exe is doing. This impacts CLI tools that are run under `npx ts-node`.

### Sample code

index.ts:
```js
console.log(process.argv.slice(2));
```

### Expected Behavior

```sh
λ node -r ts-node/register index.ts "C:\Program Files"
[ 'C:\\Program Files' ]

λ npx ts-node index.ts "C:\Program Files"
[ 'C:\\Program Files' ]
```

### Actual Behavior

```sh
λ node -r ts-node/register index.ts "C:\Program Files"
[ 'C:\\Program Files' ]

λ npx ts-node index.ts "C:\Program Files"
[ 'C:\\Program', 'Files' ]
```

(note ts-node split the string into two args)

### Steps to reproduce the problem

See above.

### Minimal reproduction

See above.

### Specifications

* ts-node version: 9.0.0
* node version: 14.15.0
* TypeScript version: 4.1.2
* tsconfig.json, if you're using one: Not using one

Operating system and version (If Windows, are you using WSL or WSL2?):

* Windows 10.0.17763 native , in cmd.exe.

**Comment by ArkadyDR** [comment]
Actually sorry this is a fault with `npx`:

```sh
λ .\node_modules\.bin\ts-node index.ts "C:\Program Files"
[ 'C:\\Program Files' ]
```

**Comment by cspotcode** [comment]
Ts-node doesn't do this.  We get process.argv just like any other CLI
module installed via npm.

The problem lies with the .cmd shim emitted by npm, and with Windows' shell.
