### ISSUE TITLE
"process" should be an easy import.  error TS2307: Cannot find module 'process' or its corresponding type declarations.

### ISSUE THREAD

**Issue by SephReed** [TypeStrong/ts-node#1163]
### Expected Behavior
Using `process` shouldn't be hard.  If it's missing for some reason, very clear error messaging should explain why.  I'm sure it takes barely anything to get it working once that's been explained.

### Actual Behavior
This error is thrown:
> error TS2307: Cannot find module 'process' or its corresponding type declarations.

It gives no direction, even though "process" is rather high on the list of things you'd expect ts-node to make easy.

### Steps to reproduce the problem
```
//test.ts
import { argv } from 'process';

console.log(argv);
```

> $ ts-node test.ts

### Extras

I asked a question here.  https://stackoverflow.com/questions/64996921/ts-node-error-cannot-find-module-process-or-its-corresponding-type-declaratio

I'm really just plastering this question everywhere because google didn't yield any results, and it probably should.

**Comment by cspotcode** [comment]
You probably want #862

Let me know if you think that's what you're looking for.  If so, I'll mark this as a duplicate to point people towards the ideal solution.

**Comment by cspotcode** [comment]
Related: #1012
