### ISSUE TITLE
SyntaxError with tsx file ending.

### ISSUE THREAD

**Issue by NaridaL** [TypeStrong/ts-node#1178]
### Expected Behavior

According to the readme, ts-node registers itself for file endings `.tsx?`, i.e. `.ts` and `.tsx`. Therefore the behavior should be the same for both file endings.

### Actual Behavior

`SyntaxError: Cannot use import statement outside a module` with.tsx file

### Steps to reproduce the problem

```sh
# create a test.ts file
$ echo "import * as path from 'path'" >> test.ts
$ echo "console.log(Object.keys(path))" >> test.ts

# works as expected
$ ts-node test.ts
[
  'resolve',    'normalize',
  'isAbsolute', 'join',
  'relative',   'toNamespacedPath',
  'dirname',    'basename',
  'extname',    'format',
  'parse',      'sep',
  'delimiter',  'win32',
  'posix',      '_makeLong'
]

# copy to test.tsx
$ cp test.ts test.tsx

# try running it with ts-node
$ ts-node test.tsx
(node:19628) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\aval\tsdev\chroma.ts\ts-node-error\test.tsx:1
import * as path from 'path'
^^^^^^

SyntaxError: Cannot use import statement outside a module
...

# -O does nothing
$ ts-node -O "{\"module\":\"commonjs\"}" test.tsx
(node:1784) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
C:\Users\aval\tsdev\chroma.ts\ts-node-error\test.tsx:1
import * as path from 'path'
^^^^^^

SyntaxError: Cannot use import statement outside a module
...


```

### Minimal reproduction

see above

### Specifications

* ts-node v9.1.1
* node v14.15.2
* compiler v4.1.3

* tsconfig.json, if you're using one: none, see above
* Operating system and version:
* 
![image](https://user-images.githubusercontent.com/10828874/102395668-c034b700-3fdb-11eb-89b5-10b33a7631b4.png)

* If Windows, are you using WSL or WSL2?: no

**Comment by cspotcode** [comment]
It'll only register if you have "jsx" enabled in your tsconfig.json.

**Comment by cspotcode** [comment]
Here's our registration implementation:
https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L393-L403

**Comment by NaridaL** [comment]
@cspotcode Figured it out too after I posted 😄. Having this work out of the box probably doesn't make sense, as TS itself requires the jsx optionto be set.

I've improved the docs #1179
