### ISSUE TITLE
Documentation unclear for "Help! My Types Are Missing!"

### ISSUE THREAD

**Issue by phao5814** [TypeStrong/ts-node#1183]
I'm currently going through the documentation and I'm getting a little confused by the "[Help! My Types Are Missing!](https://github.com/TypeStrong/ts-node#help-my-types-are-missing)" section as a Typescript newbie.

Everything makes perfect sense until I hit the following section.

> For module definitions, you can use paths:
> 
> ```
> {
>   "compilerOptions": {
>     "baseUrl": ".",
>     "paths": {
>       "custom-module-type": ["types/custom-module-type"]
>     }
>   }
> }
> ```

What should be the path's name if my module's name is "special-module"? From the above section, I'm lead to believe that the path name should be "special-module-type" but that doesn't seem right... Also, shouldn't the path value begin with `"typings/...."` given our example project structure (shown below)?

> ```
> Example project structure:
> 
> <project_root>/
> -- tsconfig.json
> -- typings/
>   -- <module_name>/
>     -- index.d.ts
> ```

Some clarification and explanation around this would be appreciated.

**Comment by cspotcode** [comment]
This looks more like a candidate for the discussion forum.  I explain the difference here: https://github.com/TypeStrong/ts-node/discussions/1174

This is a recent change, so no big deal.  But I'm going to close this issue; you can copy-paste the description into a new discussion thread.
