### ISSUE TITLE
Cannot start in docker: Killed | error Command failed with exit code 137.

### ISSUE THREAD

**Issue by murbanowicz** [TypeStrong/ts-node#1184]
The code compiles without an issue without the Docker. (it fails due to missing configuration, but it logs config errors).
In Docker it has all the config but fails without any other logs than: `Killed | error Command failed with exit code 137.`

Any idea what can be the reason? It makes development hard when I have to rebuild my container each and every time.

Tried with Node 12,14 / standard,alpine.

I am on WSL2 Ubuntu 20.04
Same happens on MacOS with Docker

Dockerfile is dead simple:
```
FROM node:12.18

WORKDIR /srv
CMD npm run start:develop
```

where start develop is just: `ts-node ./src` and whole root folder is bound to `/srv`

**Comment by cspotcode** [comment]
This looks more like a candidate for the discussion forum.  I explain the difference here: https://github.com/TypeStrong/ts-node/discussions/1174

This is a recent change, so no big deal.  But I'm going to close this issue; you can copy-paste the description into a discussion.
