### ISSUE TITLE
ts-node not reflecting code changes in intermediate file.  Seems like chache not updated.  Where is the cache?

### ISSUE THREAD

**Issue by craigphicks** [TypeStrong/ts-node#1188]
### Expected Behavior
`ts-node` runs the current code - not an older version in a cache.  

### Actual Behavior
Change in code not reflected.  This is not a file explicitly passed to `ts-node`, but a file upon which it depends.

### Steps to reproduce the problem
Because the cache is opaque, it can't be reproduced

### Minimal reproduction
Because the cache is opaque, it can't be reproduced

### Specifications

ts-node v9.1.1
node v14.15.1
compiler v4.1.3
@tsconfig/node14
```
{}
```
* Operating system and version: 

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

* I couldn't see anything on the npm page about the location of a cache.  If I could find find it I would try deleting it.

**Comment by cspotcode** [comment]
`ts-node` does not write any cache to disk.  It *might* if you pass `--compiler-host --emit`, but since you're not doing that, no cache is written to disk.

**Comment by cspotcode** [comment]
I say "it might" meaning I haven't looked at that bit of the code in a while, and since you're not using those flags, it wouldn't be affecting you.

**Comment by craigphicks** [comment]
ok - I'll intestigate more and close until then
