### ISSUE TITLE
Support all node CLI flags

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/ts-node#12]
Should be able to enable things like `--harmony` from `ts-node --harmony script.ts`. Good place to start: https://github.com/babel/babel/blob/master/packages/babel-cli/src/babel-node.js

**Comment by mgechev** [comment]
May be tsc flags such as `--experimentalDecorators` as well?

**Comment by blakeembrey** [comment]
That's probably doable, but it is already possible using `tsconfig.json`.

**Comment by neomantra** [comment]
I'm personally interested in passing the `--debug` flag to node.  Would you accept a PR for that or are you more interested in a general solution?

On the general side, rather than fancy auto-detect that Babel did there, how about something blindly forwards user specified options on the generated node command, e.g. `--forwardOption --debug`.

**Comment by blakeembrey** [comment]
@neomantra yes, I'm perfectly happy with that - that would be my preferred solution.

**Comment by danielnaab** [comment]
@blakeembrey Thanks, I was just looking for this feature today, and see it was just pushed yesterday with 0.9.2. But it's not clear to us it - is it documented somewhere?

**Comment by blakeembrey** [comment]
@danielnaab `ts-node --debug script.ts`

**Comment by danielnaab** [comment]
@blakeembrey Hmm, I had tried `ts-node --harmony_default_parameters script.ts`. Should that work? With that form I get the REPL instead of the script executed.

**Comment by blakeembrey** [comment]
You're right, sorry. Looks like the functionality is a little broken because of https://github.com/TypeStrong/ts-node/blob/master/src/_bin.ts#L72. We might need to invert that check and consider every argument that's a string as a string and treat the rest as boolean.

**Comment by blakeembrey** [comment]
Either that, or have the first bin script (https://github.com/TypeStrong/ts-node/blob/master/src/bin.ts) strip out the node arguments it finds first before passing them along.

**Comment by blakeembrey** [comment]
@danielnaab Fixed it with https://github.com/TypeStrong/ts-node/commit/e9c70124113b2e8958f23b388ddd51578ac8e967. Update to `0.9.3` and try again.

**Comment by danielnaab** [comment]
@blakeembrey Excellent, thank you very much!
