### ISSUE TITLE
ts-node throws that it cannot find module lined via npm

### ISSUE THREAD

**Issue by Fuzzyma** [TypeStrong/ts-node#1200]
### Expected Behavior

It should load my project and resolve all modules correctly

### Actual Behavior

It throws an error that it cant find a module

```sh
PS F:\projects\myproject> npm run server2

> canvas@0.0.0 server2
> node --experimental-specifier-resolution=node --loader ts-node/esm server/index.ts

(node:48528) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

F:\projects\myproject\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:765
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
        ^
Error: ERR_MODULE_NOT_FOUND vue F:\projects\vue-model\src\Model.ts
    at packageResolve (F:\projects\myproject\node_modules\ts-node\dist-raw\node-esm-resolve-implementation.js:765:9)
lve-implementation.js:920:11)
    at F:\projects\myproject\node_modules\ts-node\src\esm.ts:55:38
    at Generator.next (<anonymous>)
    at F:\projects\myproject\node_modules\ts-node\dist\esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (F:\projects\myproject\node_modules\ts-node\dist\esm.js:4:12)
    at resolve (F:\projects\myproject\node_modules\ts-node\dist\esm.js:31:16)
    at Loader.resolve (node:internal/modules/esm/loader:86:40)
npm ERR! code 1
npm ERR! path F:\projects\myproject
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node --experimental-specifier-resolution=node --loader ts-node/esm server/index.ts

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2021-01-23T16_41_48_615Z-debug.log
```

### Steps to reproduce the problem

This is an error happening on a colleagues machine. It works as it should on mine.
He runs win 10, I run win 7.

### Minimal reproduction

Since this is working perfectly find for me and errors only for him I cant really create a minimal reproduction. I am really sorry.
I will however try to debug it once I can do a live share session with him.

**Note:** The module which creates the error is only linked like this:

```
dependencies: {
  "vue-model": "file:../vue-model"
}
```

Maybe win10 symlinks are different from win7?

I will try to remove the symlink and see if that works

### Specifications

* ts-node version: 9.1.1
* node version: v15.5.1
* TypeScript version: v4.1.3
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "lib": ["esnext", "dom"],
    "plugins": [{ "name": "@vuedx/typescript-plugin-vue" }],
    "allowSyntheticDefaultImports": true
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"],
  "ts-node": {
    "transpileOnly": true
  }
}
```
* Operating system and version: win10
* If Windows, are you using WSL or WSL2?: No

**Comment by Fuzzyma** [comment]
I was able to figure out the issue.

As I said, I import a package which was linked via npm.
This package has a peer dependency that I have installed in my project. However, it seems like ts-node tries to load the dependency from the node-modules of the package I imported. Since it cant find the dependency, it fails with the error above.

Installing the peer dependency in the linked project resolves the error.

**Comment by cspotcode** [comment]
This is normal node behavior, right?  As in, node will do the same thing even if you are not using ts-node?

**Comment by Fuzzyma** [comment]
As far as I know, peer dependencies are never installed as dependency. They are installed as dependency of the main project. Therefore, when hitting a peer dependency, node/ts-node should look in the main projects node modules folder and not the ones of the dependency.

**Comment by cspotcode** [comment]
node does not understand dependencies or peerDependencies (it does not look
at those fields of package.json) so it will not change it's behavior for a
peerDep.

I still believe this is normal node behavior and that ts-node is not
deviating in any way.  We'll need a reproduction proving otherwise if we
are to change anything.

**Comment by Fuzzyma** [comment]
I will create a case once I have the time. I would be confused if node would handle it that way.

Linking dependencies is a valid way of adding a dependency to your project. And dependencies of dependencies are usually installed in your dependencies and not in the dependencies of your dependencies.
What ts-node is doing: It looks into the node_modules folder of the dependency and searches for a package. If it is not found, it goes one level up and looks in that node_modules if it can find the package and so on. This will work for every dependency which was installed without linking. However, since a linked dependency is not in the subtree of the project itself, it will never hit the projects node_modules folder and thus not find the dependency.
A way to solve this would be to *not** resolve the link to the actual path but use the virtual path instead

**Comment by cspotcode** [comment]
Resolving symlinks is a node behavior governed by this flag:
nodejs.org/api/cli.html#cli_preserve_symlinks

**Comment by cspotcode** [comment]
I'm going to close this as likely a normal limitation of node's resolution behavior.  We can always re-open if you're able to narrow it down to a bug that is specifically in `ts-node`.
