### ISSUE TITLE
async functions constructor name are being interpreted as 'Function'

### ISSUE THREAD

**Issue by lucasgmagalhaes** [TypeStrong/ts-node#1209]
I don't know if this is a ts-node problem or I should create this issue in typescript repo, but there it is:
The error happened when I was testing a function in Jest, but creating a simple function in a .ts file also makes the error happen.

### Expected Behavior

![image](https://user-images.githubusercontent.com/19666463/107132467-14fafc80-68be-11eb-949d-3fd9a3b65781.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/19666463/107132437-e2e99a80-68bd-11eb-9b40-aa1f072ed157.png)

### Steps to reproduce the problem

Create a simple file with an async function.
prints on console his constructor name.

### Specifications

ts-node v8.8.2
node v14.7.0   
compiler v4.1.3

tsconfig.json
```javascript
{
  "compilerOptions": {
    "outDir": "lib",
    "rootDir": ".",
    "resolveJsonModule": true,
    "allowJs": true,
    "checkJs": true,
    "pretty": true,
    "skipLibCheck": true,
    "declaration": true,
    "module": "CommonJS",
    "target": "es6",
    "moduleResolution": "node",
    "newLine": "LF",
    "noImplicitAny": true,
    "removeComments": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "allowUnusedLabels": false,
    "allowUnreachableCode": false,
    "esModuleInterop": true
  },
  "include": ["src/**/*", "index.ts"],
  "exclude": ["node_modules", "lib", "tests", "e2e"]
}
```

jest.config.ts

```javascript
// Set TEST environment to avoid process to exit with code 1 inside aplicaton
process.env.ENV = "TEST";

module.exports = {
  rootDir: ".",
  verbose: false,
  preset: "ts-jest",
  testEnvironment: "node",
  collectCoverageFrom: ["./src/**/*.ts"],
  testMatch: ["**/tests/**/*.test.ts"],
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  modulePathIgnorePatterns: ["./tests/mocks", "./tests/manual_test", "./tests/dirTestFiles"],
  projects: ["<rootDir>/tests"],
  restoreMocks: true,
  forceExit: true,
  transform: {
    "^.+\\.js?$": "babel-jest",
  },
};

```

* Operating system and version: Microsoft Windows [versão 10.0.19042.746]
* If Windows, are you using WSL or WSL2?: no

**Comment by cspotcode** [comment]
To figure out if a problem is related to a particular tool, you need to try
it without that tool.  Have you tried this without ts-node?

**Comment by lucasgmagalhaes** [comment]
I executed that code inside typescript playground also, and there the output was the expected.

**Comment by cspotcode** [comment]
The problem with using the playground, is there are *many* differences from when you see the error.  You've removed node, ts-jest, your tsconfig file, and ts-node.  So any of them could be the culprit.  You'll have to narrow it down further.  I suspect this is an issue with your "target" config.

**Comment by cspotcode** [comment]
I'm going to close this as likely being a `"target"` issue.  If you're able to narrow it down to a `ts-node` bug, feel free to reply and we'll re-open this issue.

**Comment by stuikomma** [comment]
Commenting to explain how to set the correct target version.

I am using ts-node v10.9.1 which supports these targets: 'es3', 'es5', 'es6', 'es2015', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', 'es2022', 'esnext'

Here is the result of running `async function foo() {}; foo.constructor.name` with each target version.

| target        | result           |
| ------------- |:-------------:|
| ES3 |  Function |
| ES5 |  Function |
| ES6 |  Function |
| ES2015 |  Function |
| ES2016 |  Function |
| ES2017 |  AsyncFunction |
| ES2018 |  AsyncFunction |
| ES2019 |  AsyncFunction |
| ES2020 |  AsyncFunction |
| ES2021 |  AsyncFunction |
| ES2022 |  AsyncFunction |
| ESNext |  AsyncFunction |

Choose a version that fits your needs and set this in your target config:
```json
// tsconfig.json
{
    "compilerOptions": {
        "target": "ES2022" // Set it to ES2017 or higher
    }
}
```
