### ISSUE TITLE
Allow stack-trace-limit

### ISSUE THREAD

**Issue by mmahalwy** [TypeStrong/ts-node#1215]
### Desired Behavior
Ability to specify `stack-trace-limit` as a flag. 

### Is this request related to a problem?
No

### Alternatives you've considered
`ts-node-dev` seems to work with `stack-trace-limit`.

**Comment by cspotcode** [comment]
If you are referring to a node CLI flag, we have an explainer for this: #1182

You can also set it programmatically: `Error.stackTraceLimit = 5;`
