### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by jingwenw** [TypeStrong/ts-node#1218]
### Expected Behavior
ts-node index.ts should able to start

### Actual Behavior
ts-node index.ts  shows the following error:

        const auth = await env.mongo.auth.get(req.session?.authId || '');
                                                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)

### Steps to reproduce the problem
in the source code: 

  app.get('/', async (req, res) => {
    const auth = await env.mongo.auth.get(req.session?.authId || '');
    if (!auth) return res.send(htmlPage(`<a href="/auth">Login with Lichess to continue</a>`));
    return res.send(htmlPage(`
    <main></main>
    <script src="/dist/app.dev.js"></script>
    <script>App.start(${JSON.stringify({
      username: auth.username,
      token: auth.access_token
    })})</script>
`));
  });

### Specifications

* ts-node version: 9.1.1
* node version: v12.20.1
* TypeScript version:4.1.5
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "rootDir": "./",
    "outDir": "./build",
    "esModuleInterop": true,
    "strict": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "noUnusedLocals": false,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedParameters": false
  }
}
```
* Operating system and version: ubuntu 20.04
* If Windows, are you using WSL or WSL2?:

**Comment by cspotcode** [comment]
Does your node version support the ?. operator?

**Comment by jingwenw** [comment]
Can you please advise which version support ?. operator? The nodejs is 12.20.1.
Thanks,
James

**Comment by blakeembrey** [comment]
@jingwenw It does not: https://node.green/#ES2020-features-optional-chaining-operator-----. You need to set `target` to an ES version that your node.js supports, probably `ES2019`.

**Comment by jingwenw** [comment]
Thanks - it really helps - the issue is gone after I upgrade nodejs to 14.*.

So this case can be closed. And again, thank everyone for the professional support!
