### ISSUE TITLE
Follow-up on question to @ava/typescript maintainers

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1234]
Reminder to myself to follow-up on https://github.com/avajs/typescript/issues/29

**Comment by wycats** [comment]
I've been trying to use ava with ts-node. I managed to figure out that I needed `tsnode/esm`, but when I write `.ts` tests that use imports, I seem to unavoidably get:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/wycats/Code/wyst/node_modules/.pnpm/ts-node@9.1.1_typescript@4.3.0-dev.20210223/node_modules/ts-node/esm.mjs
```

**Comment by cspotcode** [comment]
I'll need a more complete reproduction to point you in the right direction.

**Comment by cspotcode** [comment]
@wycats looks like you're hitting an ava limitation.  Tools like mocha detect if node should treat a file as CommonJS or as ESM.  ava needs this to be explicitly configured.

Here is an example of ava and ts-node using `import` syntax compiled to and executed as CommonJS:
https://github.com/TypeStrong/ts-node-repros/runs/1964972170

Here is an example of ava and ts-node using `import` syntax compiled to and executed as ESM:
https://github.com/TypeStrong/ts-node-repros/runs/1964966424

**Comment by mesqueeb** [comment]
@cspotcode I have an issue with `ts-node` executing Ava tests, as soon as I added `"type": "module"` to the package json, `ts-node` complains that `Ava` doesn't have a default export.

Here is my thread on Ava, they think it's related to `ts-node`: https://github.com/avajs/ava/discussions/2698#discussioncomment-408273

Should I open a new issue for this?

**Comment by cspotcode** [comment]
@mesqueeb I've created an ava discussion thread.  Please post your question over there. #1247

I've explained the difference between discussion threads and issues here: #1174

In short, *proven* * bugs and feature requests can be posted as issues, but questions should be posted in Discussions.  If you're unsure if it's a bug or not, it's probably not a bug, so starting the conversation in Discussions is appropriate.

*We get a lot of issues which are posed as bugs, but are actually not.  Best to start in Discussions and, where appropriate, create an issue requesting improved documentation once we you have a solution.
