### ISSUE TITLE
Not possible to specify project location when running mocha test on individual files

### ISSUE THREAD

**Issue by jusefb** [TypeStrong/ts-node#124]
Hi,

I am having an issue when running mocha tests on individual files. I have two tsconfig.json files in my project one for client side typescript and one for serverside typescript. The specific tsconfig.json files are located in directories /client and /server respectively. When I run Mocha tests on the /server/test entire directory recursively via this command all works fine. 

**mocha --require ts-node/register server/test --recursive**

However if I run the tests in a specific file in that directory I get Typescript compilation errors

**mocha --require ts-node/register --project server server/test/api/routes/users/get-users.spec.ts**

All works fine if I place a tsconfig.json file in the route directory of the project. Basically It seems like ts-node/register does not pickup the tsconfig.json in a subdirectory when specifying a file to run.

**Comment by blakeembrey** [comment]
See https://github.com/Microsoft/TypeScript/issues/2965.

**Comment by blakeembrey** [comment]
I've just released a new version that uses `tsconfig` module instead of `typescript` - you're welcome to give that a go instead: https://github.com/TypeStrong/ts-node/releases/tag/v0.8.0.
