### ISSUE TITLE
Unable to find module with tsconfig-paths

### ISSUE THREAD

**Issue by edaqa-uncountable** [TypeStrong/ts-node#1269]
ts-node is unable to find a module and I don't know how to further debug the issue.

I use a command-line like this:
```
node_modules/.bin/ts-node --project ./tsconfig.json -r tsconfig-paths/register test/js/sample.ts
```

Where there is a `paths` section in the tsconfig.ts file
```
  "compilerOptions": {
    "baseUrl": "js",
    "paths": {
      "some_base/*": ["base/*"],
    }
```

And then I try to import via it:

```
// this fails
import { checkConstraints } from 'some_base/comp'

// this works (not using path aliases)
import { checkConstraints } from 'base/comp'
```

I was unable to find an option in ts-node or tsconfig-paths that would let me diagnose the issue further.

**Comment by cspotcode** [comment]
Check this out:
https://github.com/TypeStrong/ts-node/discussions/1263
