### ISSUE TITLE
Breaking changes v9.0.0 -> v9.1.0?

### ISSUE THREAD

**Issue by jsjoeio** [TypeStrong/ts-node#1283]
### Expected Behavior
`ts-node` executes start script and app starts on on port `8080` like it used to.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3806031/112401307-78eb5000-8cc7-11eb-920e-b4d60d8f108b.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3806031/112401327-81dc2180-8cc7-11eb-9d16-da1b7c5f1100.png">

### Actual Behavior
Strange behavior affecting between the child process and the parent process in our app. The child sends a message, the parent gets the process and sends a message back but the child never gets it.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/3806031/112401022-dd59df80-8cc6-11eb-83e3-3cd26e5841b9.png">

### Steps to reproduce the problem
1. `git clone https://github.com/cdr/code-server.git && git checkout jsjoeio/ts-node-repro`
2. `yarn && yarn add -D ts-node@9.1.0`
3. `yarn watch`
4. See output in console (app never starts as it should on port `8080`)

### Minimal reproduction

^See reproduction steps above. If that doesn't suffice or overcomplicates things, feel free to close this issue.

### Specifications

* ts-node v9.1.0
* node v12.16.1
* compiler v4.2.3
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "strict": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "forceConsistentCasingInFileNames": true,
    "outDir": "./out",
    "declaration": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "tsBuildInfoFile": "./.cache/tsbuildinfo",
    "incremental": true,
    "typeRoots": ["./node_modules/@types", "./typings", "./test/node_modules/@types"],
    "downlevelIteration": true
  },
  "include": ["./src/**/*.ts"],
  "exclude": ["/test", "/lib", "/ci", "/doc"]
}
```
* Operating system and version: macOS Big Sur 11.2.2 (20D80)
* If Windows, are you using WSL or WSL2?: N/A

### Additional Context

The `ts-node` upgrade came through dependabot in https://github.com/cdr/code-server/pull/2919. Our tests were passing so we thought it was fine to merge. (And now we have a note to write a test for testing our dev workflow, including use of `ts-node` to prevent this in the future).

After hours of debugging yesterday, my co-maintainer and I realized something in `9.1.0` (tested both `9.1.0` and `9.1.1`) started  causing issues. We looked at the release notes but didn't see anything unusual.

I figured it could be helpful to report this just in case.

**Comment by cspotcode** [comment]
Is there a list of binaries which must be globally installed to reproduce this?  I'm seeing errors about `jq`, `gulp`, and `npm-run-all`.

**Comment by cspotcode** [comment]
These are the errors preventing the reproduction from working as expected. (I assume)
https://github.com/TypeStrong/ts-node-repros/runs/2197059246

Is the reproduction incomplete?  Are there additional steps which need to be run?

**Comment by jsjoeio** [comment]
> I'm seeing errors about jq, gulp, and npm-run-all

Apologies! Those are probably required for VS Code.

I spoke to @code-asher and he was able to provide a minimal reproduction setup. Here's the repo:
https://github.com/code-asher/ts-node-repro

**Comment by jsjoeio** [comment]
Okay so we couldn't reproduce in the [minimal reproduction](https://github.com/TypeStrong/ts-node-repros/runs/2197351471?check_suite_focus=true#logs).

One observation: we're both testing using Node v12, but the repro GH action suite uses LTS.

And in 9.1.0, the tests for 12.16 were removed: https://github.com/TypeStrong/ts-node/pull/1148

So I guess that means this is a bug in Node and not `ts-node`?

**Comment by code-asher** [comment]
fwiw, I reproduced in GH actions with v12: https://github.com/TypeStrong/ts-node-repros/pull/8

**Comment by cspotcode** [comment]
Thanks, I'm seeing the same.  I see it on node 12.21.0 but not node 15.12.0.  I suspect this has something to do with the way node's `child_process` module sets up the IPC channel.

**Comment by cspotcode** [comment]
I found something interesting.  Switching the `stdio` configuration for the child_process fixes the problem.

```
    stdio: ['inherit', 'pipe', 'pipe', "ipc"], // <-- this works on node 12
    // stdio: ["ipc"], <--- this exhibits the failure we are seeing on node 12
```

Do you know, are we allowed to use file descriptor 0 for an IPC channel?  If so, how does the child process learn that file descriptor 0 is an IPC channel?

I am also double-checking to be sure that `ts-node` is properly setting up `process.execPath`, `process.execArgv`, `process.argv0`, and `process.argv`.

**Comment by jsjoeio** [comment]
That is a fantastic question...This is waay out of my wheelhouse. I have no idea.

**Comment by code-asher** [comment]
Nice find! I'm not entirely sure why we're using fd 0 for IPC. :thinking: It was probably due to some kind of misunderstanding.

We'll switch to doing it the correct way. I have no idea if IPC is "supposed" to work on fd 0 so I don't know if this is still technically a bug, but this resolves our issue at the very least! Thank you for figuring this out!

**Comment by jsjoeio** [comment]
Feel free to close this if you'd like! You ended up helping us find the underlying bug in our own codebase and we really appreciate that!

**Comment by cspotcode** [comment]
Excellent, glad to hear that.  I'm going to keep this open a bit longer
because it might still be a bug on our end, or at least something we can
avoid, if I can figure out what to tweak.

**Comment by cspotcode** [comment]
I came back to this and found the culprit.

Doing `const _thisIsNeverUsed = process.stdin;` triggers this bug in vanilla `node` without `ts-node`.  `ts-node >= 9.1.0` eagerly saves a reference to `process.stdin`, which is why we were seeing the bug triggered by `ts-node`.

I guess that node 12.16.1 had some initialize-on-demand behavior that was triggered by a getter on `process.stdin`.  Seems rare enough not to warrant a workaround.

However, if we *did* need to implement a workaround, the solution is to avoid calling `createRepl` in `bin.ts` unless the REPL will be used.  `createRepl()` internally saves a reference to `process.stdin`.  Avoiding that call avoids triggering this bug.

It is worth repeating for anyone reading this in the future: this bug does *not* happen on never versions of node.
