### ISSUE TITLE
Unhandled synchronous exceptions are handled by default

### ISSUE THREAD

**Issue by not-rusty** [TypeStrong/ts-node#1284]
### Expected Behavior

The same as node, after this code:

```typescript
throw new Error('an error')
```

It should log the error *with the stacktrace*

### Actual Behavior

It just logs the error message at `stderr`, without any stacktrace. I must note that it was extremely confusing when debugging some backend typescript code.

### Steps to reproduce the problem

Just try to reproduce a normal unhandled exception.

### Specifications

ts-node v9.1.1
node v14.16.0
compiler v4.2.3
* tsconfig.json, if you're using one:
```
{
    "compilerOptions": {
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "alwaysStrict": true,
        "baseUrl": "./src",
        "checkJs": false,
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "lib": ["es2019", "es2020.promise", "es2020.bigint", "es2020.string"],
        "module": "commonjs",
        "moduleResolution": "node",
        "noEmit": true,
        "noImplicitAny": true,
        "noImplicitThis": true,
        "skipLibCheck": true,
        "strict": true,
        "strictFunctionTypes": true,
        "strictNullChecks": true,
        "target": "es2019",
        "paths": {
            "src/*": ["./src/*"]
        }
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}

```
* Operating system and version: Ubuntu 20.04

Why does this happen? Is it intended? Am I missing something?

**Comment by cspotcode** [comment]
I've attempted to reproduce what you're seeing here:
https://github.com/TypeStrong/ts-node-repros/tree/unhandled-exception-output
The logs are here:
https://github.com/TypeStrong/ts-node-repros/runs/2196857780

I am seeing it logging a 10-line stack trace.  It appears to be working correctly.

Are there an additional requirements to reproduce the missing stack trace?  Is it possible that you have additional moving parts which are to blame?

**Comment by not-rusty** [comment]
I installed ts-node globally and it correctly logged the error with the stack trace. However, if I run it with npx it just logs the error message. Both done in an empy folder, with a minimal package.json.

I used: 

`$ ts-node --transpile-only -e "throw new Error('test')"` <- correctly outputs stack trace
`$ npx ts-node --transpile-only -e "throw new Error('test')"` <- only message given, at stderr

I have no idea why this happens. I've tested it in both node 12.16 and 14.16. I made sure no other dependencies where installed

Also tested in our linux EC2 on development, and it also happens. And with a fresh node v14 install.

I'd love to provide more details, but that's all I know :(

**Comment by blakeembrey** [comment]
IIRC this is a `npx` behavior that you should see if any package, not just `ts-node`. Reference issue: https://github.com/npm/npx/issues/36. I couldn't find a related issue in the npm CLI repo though, but I suspect it still exists then.

**Comment by blakeembrey** [comment]
Actually, turns out I had debugged and filed an issue about this three years ago. https://github.com/zkat/npx/issues/188 and duplicate issue in `ts-node`: https://github.com/TypeStrong/ts-node/issues/592.

**Comment by not-rusty** [comment]
Thank you very much, I'm happy to know it's not something about ts-node! I'll close this as it is already mentioned in your linked issue.

Duplicate of #592
