### ISSUE TITLE
toString 'async function', the value should be '[object AsyncFunction]'

### ISSUE THREAD

**Issue by howel52** [TypeStrong/ts-node#1306]
### Expected Behavior
The String value in `async function` is 'AsyncFunction', so in this snippet `Object.prototype.toString.call(async function bar(){})`, the value should be `[object AsyncFunction]`

see: [ecma262](https://tc39.es/ecma262/#sec-async-function-objects)

### Actual Behavior
[object Function]

### Steps to reproduce the problem
1. open terminal
2. run `ts-node -e "console.log(Object.prototype.toString.call(async function bar(){}))"`

### Minimal reproduction
`ts-node -e "console.log(Object.prototype.toString.call(async function bar(){}))"`

### Specifications

* ts-node version: v8.10.2
* node version: v12.22.1
* TypeScript version: v3.9.6

* Operating system and version: macOS 11

**Comment by cspotcode** [comment]
I'm pretty sure this has been asked before; there should be another ticket
explaining it.

**Comment by cspotcode** [comment]
Here's the ticket I was thinking of: #1209

This is probably something that will happen with `tsc` `node` as well, indicating it's a characteristic of `tsc`.  I would check that next.

**Comment by cspotcode** [comment]
I'm going to close this because I'm pretty sure this would happen with `tsc`, too, so it's not a `ts-node` bug.  Feel free to reply if I'm wrong about that and I'll reopen it.
