### ISSUE TITLE
Document reason for TS 2.7 support, possibly increase minimum supported version

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1316]
When I started working on ts-node, the readme said we supported TS 2.7 and the tests ran against TS 2.7, so I've maintained that support.  But I don't actually know why we support that version.  Enough time has passed, it may make sense to increase the minimum supported version.

@blakeembrey do you remember if there were any specific reasons for supporting 2.7?  Was a high-profile project stuck on 2.7 at some point in the past?

A quick search turned up #527 but I don't know if it's related.

Some data points:

* ts playground supports as far back as 3.3.3 https://www.typescriptlang.org/play
* DefinitelyTyped tests TS versions less than 2 years old. Currently 3.5 and above https://github.com/DefinitelyTyped/DefinitelyTyped#older-versions-of-typescript-34-and-earlier
* typescript 2.7 does not support the `lib` options in @tsconfig/node12 from @tsconfig/bases

**Comment by cspotcode** [comment]
Or maybe ts-node added a feature that was broken on versions *older* than 2.7, and so it was documented that 2.7 was the minimum?

**Comment by blakeembrey** [comment]
Yeah, if you need to upgrade in a major version don't restrict yourself! I don't really remember now, but going a git blame on that specific line in the README is pretty helpful for the history of the changes. Looks like I last bumped it from 2.0 -> 2.7 in https://github.com/TypeStrong/ts-node/pull/895 which was a minimum feature requirement.

**Comment by cspotcode** [comment]
Ok, thanks.  Turns out it won't be necessary for v10, because I ended up re-adding `@tsconfig/node10`  to keep things simple.  But this is good to know for v11.

**Comment by cspotcode** [comment]
Closing as answered.

**Comment by jhmaster2000** [comment]
To future readers, as the milestone links above aren't very helpful to connect these together, the v11 plan relating to this issue is here: #1505
