### ISSUE TITLE
npm package includes .js.map files, but not the .ts files

### ISSUE THREAD

**Issue by BurtHarris** [TypeStrong/ts-node#132]
It seems pointless to include the map files if the original source files are not installed.

**Comment by blakeembrey** [comment]
You don't need the typescript files to run the package.

**Comment by blakeembrey** [comment]
Perhaps it should be compiled with "include sources", is that what you mean?

**Comment by BurtHarris** [comment]
Yes, well, that's something you would be better able to decide; but if you include the maps, it seems logical to include the sources they refer to.

**Comment by blakeembrey** [comment]
Thanks for bringing it to my attention.

**Comment by BurtHarris** [comment]
***Thank you*** Blake.   Its taken a while to understand the Typings tool, but as I do, I appreciate it more and more.
