### ISSUE TITLE
A basic but full example of using profiling is missing

### ISSUE THREAD

**Issue by dsaf** [TypeStrong/ts-node#1325]
### Expected Behavior

Readme having a short section saying "follow these steps to carry out basic performance profiling..." etc.

### Actual Behavior

Documentation has no explanation on how to carry out performance profiling. Saying "You can always use node -r ts-node/register and do anything you want in node.js" #795 is not useful at all, unfortunately. All this does is it enters some weird Node REPL or something. I am very new to Node, but have prior profiling experience using other languages/tools.

### Steps to reproduce the problem

Try finding at least some basic information on how to do performance profiling with ts-node while being a noob with Node/TypeScript.

### Minimal reproduction

Try finding at least some basic information on how to do performance profiling with ts-node while being a noob with Node/TypeScript.

### Specifications

Any version, any platform.

**Comment by blakeembrey** [comment]
You should read the existing node.js documentation for things that aren’t related to `ts-node`. I found this article which should help you: https://nodejs.org/en/docs/guides/simple-profiling/. Aside from that I’m not any help on this. You can run any of this stuff using node and just add `-r ts-node` as documented in the README.
