### ISSUE TITLE
ts-node field declared in extended tsconfig.json

### ISSUE THREAD

**Issue by jjangga0214** [TypeStrong/ts-node#1328]
### Desired Behavior

When `"ts-node"` field is configured in extended tsconfig, it should also work.

For example, let's say there are `tsconfig.root.json` and `tsconfig.json`.
`"ts-node"` is declared in `tsconfig.root.json` and `tsconfig.json` extends it.

`tsconfig.root.json`
```jsonc
{
  "compilerOptions": {
    // ... some configuration
  },
  "ts-node": {
    "transpileOnly": true,
    "transpiler": "ts-node/transpilers/swc-experimental"
  }
}
```

`tsconfig.json`
```json
{
  "extends": "tsconfig.root.json"
}
```

If we use `tsconfig.json` with `ts-node`, currently it does not read `"ts-node"` field from `tsconfig.root.json` though extended.

**Comment by blakeembrey** [comment]
IIRC it’s unfortunately due to the TypeScript API here - I don’t think we can get access to the extended definitions to be able to merge it. We should be able to file an issue in TypeScript to request support in the most recent version.

**Comment by cspotcode** [comment]
See also: #1292
The comments talk about implementation.

If you'd like, feel free to pick up that PR where it was left off.  I can help explain anything that's confusing.
