### ISSUE TITLE
Unable to transpile in fast mode when lib flag used

### ISSUE THREAD

**Issue by asvetliakov** [TypeStrong/ts-node#134]
```
$ mocha -r ./testIndex.js src/app/containers/Application_Spec.tsx
TSError: ⨯ Unable to compile TypeScript
Option 'lib' cannot be specified with option 'noLib'. (5053)
    at getOutput (C:\Users\asvet\work\applications\frontend\node_modules\ts-node\src\index.ts:207:13)
    at compile (C:\Users\asvet\work\applications\frontend\node_modules\ts-node\src\index.ts:214:12)
    at loader (C:\Users\asvet\work\applications\frontend\node_modules\ts-node\src\index.ts:304:23)
    at Object.require.extensions.(anonymous function) [as .tsx] (C:\Users\asvet\work\applications\frontend\node_modules\ts-node\src\index.ts:321:14)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```
Test file doesn't matter.

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["es2015", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "jsx": "react",
    "sourceMap": true,
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules",
    "public",
    "compiled"
  ]
}
```

testIndex.js
```js
require("ts-node").register({
    fast: true
});
```

Without fast option it compiles fine, but isn't being run in suitable time (15 seconds for single test file, 29 seconds for whole test suite)

Uh, forgot,  TS version 1.9.0-dev.20160612,

**Comment by asvetliakov** [comment]
Workaround: use ```noProject``` and ```compilerOptions```, but i think the ts-node should automatically unset lib option when fast mode is used.

**Comment by blakeembrey** [comment]
@asvetliakov That's odd, any idea where TypeScript is getting `noLib` from. Seems like TypeScript should work without me hacking any more options here - but I've implemented enough of them, if they decline to fix this on their end, I'm happy to patch it.

**Comment by asvetliakov** [comment]
I fast checked and TS compiler forces noLib option along with few others (isolatedModules, noExternalResolve) in transpileModule() itself, so this may be TS error. You can close the issue then if you want.

Anyway it's working fine with workaround, now the speed is comparable with when using separate watcher and running tests from transpiled files directly :100:

**Comment by blakeembrey** [comment]
We can keep it open for a while, it should definitely be fixed - whether with a hack or not. I'd say since your particular feature is a nightly that it's not urgent to patch, but let's open an issue with TypeScript still. Have you seen an issue open or do you want to open one and link it here?

**Comment by asvetliakov** [comment]
Not sure what's going on:

```js
const typescript = require("typescript");

const input = `export class Test { }`;

const output = typescript.transpileModule(input, {
        compilerOptions: {
            target: "es5",
            lib: ["es2015", "dom"],
            module: "commonjs"
        }
    }
);

console.log(output.outputText);

```
this works

```
require("ts-node").register({
    fast: true,
    noProject: true,
    compilerOptions: {
        target: "es5",
        lib: ["es2015", "dom"],
        module: "commonjs"
    }
});

require("./test.ts"); // export class Test {}
```
this doesn't

**Comment by blakeembrey** [comment]
Interesting, thanks. Is it the same error? I can definitely investigate myself at a later time too, but thanks for your help, it's really useful! 

The only other options being populated are these: https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L95-L102. I'm not sure it'd be one of those though.

**Comment by asvetliakov** [comment]
Yes, for second example it gives the same error:
```
TSError: ⨯ Unable to compile TypeScript
Option 'lib' cannot be specified with option 'noLib'. (5053)
    at getOutput (C:\Users\asvet\work\applications\frontend\node_modules\ts-node\src\index.ts:207:13)
...
```

Just tried to put missed options (sourcemaps...) into compilerOptions to first example - original transpileModule() still works without errors.

Thanks. Low priority may be

**Comment by asvetliakov** [comment]
Update: ```reportDiagnostics: true``` option in transpileModule(input, { ... }) gave me same error message with original transpileModule() call , so it's definitely TS bug

**Comment by asvetliakov** [comment]
TS issue created:
https://github.com/Microsoft/TypeScript/issues/9173

Sorry for inconvience :smile:

**Comment by blakeembrey** [comment]
Not inconvenient at all 😄 Thanks for debugging it!
