### ISSUE TITLE
Fallback to `ts.transpileModule` whenever we get "Emit skipped"

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1345]
Should we fallback to `ts.transpileModule` whenever we get "Emit skipped"?

Seems like a bit of a hack, but it means certain situations "just work."  If the file is statically imported, then it's already being typechecked.  The only limitation is that `transpileOnly` needs `isolatedModules`, so if projects rely on rare things like inlined const enumeration values, that'll fail.  But otherwise seems like a win.

Would fix #693

**Comment by iamarpitpatidar** [comment]
#1593 https://github.com/TypeStrong/ts-node/issues/1593
