### ISSUE TITLE
tsconfig.json/paths not working with ts-node

### ISSUE THREAD

**Issue by unional** [TypeStrong/ts-node#138]
One neat trick to use `tsconfig.json/paths` is to pointing the module name to your source file:

```ts
// tsconfig.json of blue-tape-fixture
{
  ...
  "paths": {
    "blue-tape-fixture": [ "src/" ]
  }
}
```
This way, your test files can reference the source as if it is a proper module:
![image](https://cloud.githubusercontent.com/assets/3254987/16176202/fcb426da-35bc-11e6-98c6-c7c61b8a0bd7.png)
You can see it is working in vscode. But it does not when I run test with ts-node:
```js
// package.json
{
  "scripts": {
    "test": "ts-node -P tsconfig.build.json node_modules/blue-tape/bin/blue-tape \"test/**/*.ts\" | tap-spec"
  }
}
```

The error is:
```sh
Error: Cannot find module 'blue-tape-fixture'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
```

You can see it here: https://github.com/unional/blue-tape-fixture/tree/ts-node
```sh
# clone
npm install
npm test
```

**Comment by blakeembrey** [comment]
@unional That's the node.js error - TypeScript is working fine, but node will never be able to resolve an alias like that unless TypeScript emits code that rewrites paths. What do you think is the solution here?

**Comment by unional** [comment]
I see. In order for it to work, a module-path-rewriter need to be written and loaded by `ts-node` for it to work.
Alternatively is to load the transpiled code `dist/*`, which kind of defeat the purpose of `ts-node` (I said kind of because the test file, in this use case, can remain as ts files).

**Comment by blakeembrey** [comment]
This module uses the emitted code though - it's TypeScript itself that doesn't do any rewriting right?

**Comment by unional** [comment]
Just check. Nope it does not do any rewriting. Seems like the `baseUrl` and `paths` is only used during compilation. By design or bug on TS side?

**Comment by unional** [comment]
Update https://github.com/unional/blue-tape-fixture/tree/ts-node to demo the issue.
run `npm run build-test` and see under `dist/test/index.ts` it is will requiring `blue-tape-fixture`

**Comment by unional** [comment]
Confirm above statement: https://github.com/Microsoft/TypeScript/issues/5039#issuecomment-206451221

**Comment by blakeembrey** [comment]
@unional Yeah, it's tricky. I can understand TypeScript's stance, if they don't have a solution for it built-in I think we can investigate adding a plugin once they implement the pluggable transforms in TypeScript 2.0. This is definitely more of a user-land feature.

**Comment by sanex3339** [comment]
any news? i want to use 'paths' option in my tests

**Comment by blakeembrey** [comment]
No, it does not work and is not expected to work.

**Comment by jonaskello** [comment]
Maybe this could be solved by augmenting node's loading rather than having typescript re-write the paths. There are some alternatives mentioned [here](https://gist.github.com/branneman/8048520). In particular I' thinking that [wrapping the global require](https://gist.github.com/branneman/8048520#7-the-wrapper) and just changing the path according to tsconfig would be the simplest solution.

**Comment by jonaskello** [comment]
When I looked closer I realised that wrapping global require is not possible in a way that replaces it (the example above installs a separate require function). However it is possible to patch `Module._load` like is done in [mock-require](https://github.com/boblauer/mock-require). I did some experiments with this and it seems doable. I'll try to put together a PR to demonstrate.

**Comment by jonaskello** [comment]
For those interested I did a PR to enable execution of projects with tsconfig paths in #254.

**Comment by jonaskello** [comment]
Instead of the PR, I have now created the [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) package that makes it possible to automatically resolve paths during execution with ts-node, node, or mocha. Just follow the instructions in the readme.

**Comment by shirakaba** [comment]
Note to all using @jonaskello 's tsconfig-paths:

The errror "`Missing paths in compilerOptions. tsconfig-paths will be skipped`" means that you don't have any `paths` property specified in your *tsconfig.json*. I had been able to use imports relative to my `src` directory just by specifying `"baseUrl": "."`, but to get ts-node/node/mocha to understand the same imports, I **also** needed to specify a `paths` property in my *tsconfig.json*, eg:

    "paths": {
      "src/*" : ["./src/*"]
    }

Hope this helps another overwhelmed soul.

**Comment by michaeljota** [comment]
@shirakaba Just a note, you can set your `"baseUrl"` to `"./src/"` and `"paths"` like this
```json
"paths": {
  "*" : ["./*"]
}
```
I will be the same, but you are able to add more paths with the same root more easily.

**Comment by ashok-sc** [comment]
I've tried nearly all the above solutions and I'm still getting `Module not found: Error: Can't resolve ...`. 

What's the solution here? I have updated my `tsconfig.json` `webpack.config.js` and even tried tsconfig-paths. None of these work.


```
//tsconfig.json
{
  ...
  "baseUrl": "./src",
    "paths": {
      "@src/*": [
        "*"
      ]
    }
}
```

**Comment by jonaskello** [comment]
@ashok-sc ts-node has no support for paths in tsconfig.json, and [no plans](https://github.com/TypeStrong/ts-node/pull/254#issuecomment-269404787) to add it. I think your best bet to get it working is using [tsconfig-paths](https://github.com/dividab/tsconfig-paths). If you have trouble using it feel free to file an issue at that repo.

If you are using webpack the scenario is quite different. If you are using ts-loader you might want to try [tsconfig-paths-webpack-plugin](https://github.com/dividab/tsconfig-paths-webpack-plugin) altough it is still early in development. If you are using awsome typescript loader then it has this type of plug-in built-in.

**Comment by michaeljota** [comment]
@ashok-sc As @jonaskello said, there is no plan to support path, as you need to replace the path call with the proper full path in order to be understandable for Webpack. You could use [Awesome Typescript Loader](https://github.com/s-panferov/awesome-typescript-loader) that have a plugin out-the-box for that, but still, it needs to be a plugin.

**Comment by ashok-sc** [comment]
Hey @jonaskello and @michaeljota thanks for the help! I am in fact using awesome-typescript-loader with webpack. However, the instructions are quite poor. I understand that you may not have the answers here, but I thought I'd give it a shot anyway. 

The [instructions](https://github.com/s-panferov/awesome-typescript-loader#advanced-path-resolution-in-typescript-20) state to add the TsConfigPathsPlugin, but it's not clear as to what it needs in the constructor. Here's what I tried:

```
new TsConfigPathsPlugin({
    configFileName: path.join(__dirname, './tsconfig.json'),
    compiler: 'typescript'
  })
```

This doesn't seem to work though and I still get module not found. 

Anyway, if you don't have the answer of the top of your head feel free to ignore.

**Comment by jonaskello** [comment]
Here's a gist of what a webpack config should look like with awesome-typescript-loader's tsconfig paths plugin. I don't pass anything in the constructor in my config, but maybe you need it if your tsconfig.json is in a non-standard location.

```
var TsConfigPathsPlugin = require('awesome-typescript-loader').TsConfigPathsPlugin;

module.exports = {
	entry: ...,
	output: ...,
	resolve: {
		extensions: ['...'],
		plugins: [
			new TsConfigPathsPlugin()
		]
	}
}
```

**Comment by jonaskello** [comment]
@ashok-sc If it does not work, you can try version 0.2.0 of [tsconfig-paths-webpack-plugin](https://www.npmjs.com/package/tsconfig-paths-webpack-plugin). I have added code that prints the path that it tries to load the tsconfig.json from.

Note, `tsconfig-paths-webpack-plugin` is used instead of the one in awesome-typscript-loader. You can also use it with ts-loader.

**Comment by michaeljota** [comment]
@ashok-sc I use ATL as @jonaskello describe and I have not faced any problems.

**Comment by ashok-sc** [comment]
Hey so I've actually got the plugin to work!

Unfortunately now I still have an issue where `index.ts` files don't work.

For example an import like this:
`import config from '@src/server/config';`

where the module is `./src/server/config/index.ts` is not working. I'm getting the following error:
```
Error: Cannot find module '@src/server/config'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
```

**Comment by ashok-sc** [comment]
I've also tried `import config from '@src/server/config/index'` and nothing. Is this expected to be broken. Support for path resolution on all fronts feels quite broken.

**Comment by jonaskello** [comment]
Try it with `tsc`. If the project compiles with `tsc` then it should also work with the plugins. If you get errors with `tsc` you can try `tsc --traceResolution`. See more [here](https://www.typescriptlang.org/docs/handbook/module-resolution.html) under heading "Tracing module resolution".

**Comment by michaeljota** [comment]
@ashok-sc can you post the content of your tsconfig?

**Comment by ashok-sc** [comment]
Here's my tsconfig.json:

```
{
  "compilerOptions": {
    "outDir": "./compiled/",
    "sourceMap": true,
    "noImplicitAny": false,
    "module": "commonjs",
    "lib": ["es6", "dom", "esnext"],
    "target": "es6",
    "jsx": "react",
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "baseUrl": "src",
    "paths": {
      "@src/*": [
        "*"
      ]
    }
  },
  "include": [
    "./src/core/*",
    "./src/client/*",
    "./src/server/*"
  ]
}
```

**Comment by ashok-sc** [comment]
@jonaskello will try this with tsc in a bit.

**Comment by michaeljota** [comment]
Had you try to add a slash to the end of the `baseUrl`? Or maybe do otherwise, set `baseUrl` to `./` and set `@src/*` to `src`?

**Comment by xvilo** [comment]
with baseUrl enabled it seems @jonaskello's plugin will also use this for npm_modules that otherwise would load normally. When removing baseUrl and paths all together and using relative paths the project compiles again. 

```
$ npm run test

> xxxxxx@1.0.0 test /Users/xvilo/projects/xxxxxx
> mocha -r ts-node/register -r tsconfig-paths/register --require tests/testHelper.js tests/js/**/*.spec.ts

Error: Cannot find module '/Users/xvilo/projects/xxxxxx/src/js/util'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/Users/xvilo/projects/xxxxxx/node_modules/tsconfig-paths/lib/register.js:29:44)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xvilo/projects/xxxxxx/node_modules/tough-cookie/lib/memstore.js:35:12)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xvilo/projects/xxxxxx/node_modules/tough-cookie/lib/cookie.js:36:25)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xvilo/projects/xxxxxx/node_modules/jsdom/lib/api.js:5:21)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xvilo/projects/xxxxxx/tests/testHelper.js:1:13)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at requires.forEach.mod (/Users/xvilo/projects/xxxxxx/node_modules/mocha/bin/_mocha:511:3)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/xvilo/projects/xxxxxx/node_modules/mocha/bin/_mocha:510:10)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxxxxx@1.0.0 test: `mocha -r ts-node/register -r tsconfig-paths/register --require tests/testHelper.js tests/js/**/*.spec.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xxxxxx@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xvilo/.npm/_logs/2018-06-21T15_25_59_483Z-debug.log
```

and with baseUrl and paths disabled:

```
$ npm run test

> xxxxxx@1.0.0 test /Users/xvilo/projects/xxxxxx
> mocha -r ts-node/register -r tsconfig-paths/register --require tests/testHelper.js tests/js/**/*.spec.ts

Missing baseUrl in compilerOptions. tsconfig-paths will be skipped


  Dom.createNodeFromString
    ✓ Div with class
    ✓ span with class
    ✓ img
    ✓ table with 1 tr and 1 td with content
    ✓ ul
    ✓ li
    ✓ ul with li


  7 passing (22ms)
```

part of my package.json

```json
"scripts": {
    "test": "mocha -r ts-node/register -r tsconfig-paths/register --require tests/testHelper.js tests/js/**/*.spec.ts"
  },
```

**Comment by alexeychikk** [comment]
tsconfig.json/paths not working if you set `outDir`

**Comment by joseluisq** [comment]
For production apps after a `tsc` build. 
I have created a [TS Paths replacer in Go](https://github.com/joseluisq/go-tspath) which is pretty fast and that addresses [the custom paths issue](https://github.com/Microsoft/TypeScript/issues/10866).
After it's applied you only need to run your app `node main.js`.

**Comment by alexeychikk** [comment]
@joseluisq That doesn't address the issue in any possible way. People here want to run typescript code directly with a support of `paths` aliases from tsconfig.json for the dev purposes and not only. 
Specifically I am facing the issue of wrong paths resolution when `outDir` is specified in tsconfig.json.

_By the way, there is already a proven solution to the problem you referenced_ https://github.com/ilearnio/module-alias

**Comment by joseluisq** [comment]
@alexeychikk [this thread](https://github.com/TypeStrong/ts-node/pull/254#issuecomment-269404787) confirms that the maintainer is not interested in any implementation of TS paths support, but he suggests external implementations as you have enumerated instead.

Sure, if the people wants to run TS code directly via ts-node is [dividab/tsconfig-paths](https://github.com/dividab/tsconfig-paths) an alternative. I use it for development.

My solution is pretty simple: replace TS path aliases usig

**Comment by SephReed** [comment]
Oh boy.  This looks like it's going to be fun to figure out.

**Comment by viT-1** [comment]
@alexeychikk 
1) module-alias not the best way if you use es6
https://github.com/ilearnio/module-alias/issues/59
2) If project doesn't use webpack "even webpack" is not usecase.
3) May be you can help me to configure tsconfig-paths to use it as npm script with ts-node (extended tsconfig with outDir)?

**Comment by SephReed** [comment]
@jonaskello You saved my ass here!

Is there any reason why this shouldn't become a default built in part of ts-node?  It seems like it would make more sense to include this by default, than to not.

**Comment by bennyn** [comment]
Thanks @jonaskello! 

It also seems to work when using `ts-node` through `nyc`:

**nyc.config.js**

```js
module.exports = {
  all: false,
  exclude: ['**/*.d.ts', '**/*.test*.ts', '**/index.ts'],
  extension: ['.ts'],
  include: ['src/**/*.ts'],
  reporter: ['text-summary'],
  require: ['tsconfig-paths/register', 'ts-node/register'],
};
```

**Comment by talwrii** [comment]
Thank you to janaskello for `tsconfig-paths` a slight annoyance I have is that it seems like `tsconfig-paths` needs to be installed in projects themselves for `ts-node -r tsconfig-paths/register` to work - which is a bit of a pain for third party libraries (my use case of understanding someone else code is perhaps unusual).

I'd also like to say that on newer versions of node you get a `MODULE_NOT_FOUND` error (other page about this suggest deleting and reinstalling things for this). It's odd how `ts-node` in one says can "find" the library (because if a file does not exist you get a different error) but then fails to import.

I would vote for ts-node refusing to run if paths is set given that this error is a little cryptic (I didn't find this page until I guessed that the problem might be because ts-node is ignoring paths and googled this - working in someone elses repo).

**Comment by blephy** [comment]
I was running on the same issue when running webpack with ts-node (i'm using Typescript language webpack configuration) but already followed the webpack documentation and installed `tsconfig-paths`.

Just putting `"moduleResolution": "node"` into my tsconfig.webpack.json resolved the issue.

Hope this help

**Comment by SephReed** [comment]
> @jonaskello You saved my ass here!
> 
> Is there any reason why this shouldn't become a default built in part of ts-node? It seems like it would make more sense to include this by default, than to not.

Apparently I've been through this before...  lol.

This really probably should become default behavior.

**Comment by rachaeldawn** [comment]
Okay, so I found a solution that works reasonably well for my use-case. I needed this just for Knex's `knexfile.ts` and couldn't find a solution

# Constraints:
- Every "path" in paths I have has only 1 item in the array
- I am able to use `module-alias` as a dev dependency
- I have only 1 file that _requires_ this fix, however putting this in a `fix-paths.ts` file works if it is is imported **first**
- I am able to use `"resolveJsonModule": true`

# Code
```typescript
import moduleAlias from 'module-alias';
import * as path from 'path';
import { compilerOptions } from './tsconfig.json';

const root = path.join(__dirname, compilerOptions.baseUrl || '');

for (const [key, paths] of Object.entries(compilerOptions.paths)) {
  const target = path.join(root, paths[0]);
  moduleAlias.addAlias(key, target);
}

```

**Comment by SephReed** [comment]
Clearly I'm a weirdo.  This is my fourth time finding this thread, but it doesn't appear to get much activity.  It's probably because I use mono-repos.

**Comment by fatihaziz** [comment]
maybe my work arounds will help:
1. install required plugins:
`npm i -D ttypescript typescript-transform-paths ts-node tsconfig-paths`. 
these are packages that will help us to transform the paths.
2. then, on tsconfig.json, i put:

       {
        "ts-node": {
          "transpileOnly": true,
          "require": [  // set this so you dont need to use ts-node -r 
        	"typescript-transform-paths/register",
        	"tsconfig-paths/register"
           ]
        },         
	    "compilerOptions": {
		   "composite": true,
		   "rootDir": ".", // must define
		   "baseUrl": "src", // must define, the paths will relative to this
		   "outDir": "../lib", 
		   "skipLibCheck": false,
		   "paths": {
			"@app/*": ["./*"],
			"@controllers/*": ["./controllers/*"],
           },
		    "plugins": [
			  { "transform": "typescript-transform-paths" }
		    ]
        }
       }

3. then on your codes you can use:
          
       import myControllers from "@controllers/main.ts"

4. now you can compile, `npx ttsc -p tsconfig.json`
5. and to run on ts-node use `npx ts-node -p tsconfig.json src/app.ts`

my conclusion: 
to work around with ts-node paths, we need tsconfig-paths required on ts-node runtime.
but on production we just need to compile them into absolute path, so we use ttypescript and typescript-transform-paths to compile then transform the relative path to absolute path.
with this solution the code will running with only `node lib/index.js` without registering any paths plugin.

**Comment by puchm** [comment]
Does anyone have an idea on how to work around this issue when using ESM? I am normally using `node --loader ts-node/esm <path>` to start scripts but I could not get it to work using any of the solutions proposed here.

**Comment by danielo515** [comment]
@fatihaziz you answer saved my life, thanks!

**Comment by droplessdeclan** [comment]
@puchm Did you ever manage to find a solution to this? I'm having the same issue

**Comment by cspotcode** [comment]
For a solution you can use today, see #1450

Path mapping is being added as a built-in feature of ts-node in an upcoming release.  To follow progress, see #1585
