### ISSUE TITLE
use ts-node field from extended tsconfig

### ISSUE THREAD

**Issue by stefanprobst** [TypeStrong/ts-node#1382]
### Desired Behavior

currently it is possible to define a `ts-node` field in `tsconfig.json` for configuration, but when extending from a tsconfig package, which has a `ts-node` field, that config is not used.

For example, in my project i have:
```json
{
  "extends": "@stefanprobst/tsconfig"
}
```

and that npm package provides a `tsconfig.json` which has:

```json
{
  "ts-node": {
    "compilerOptions": {
      "module": "commonjs"
    }
  }
}
```

### Is this request related to a problem?

it would allow me to define a `"ts-node"` config field once in a tsconfig npm package, and extend it in my projects

### Alternatives you've considered

put `ts-node` config field directly in project's `tsconfig.json`.

**Comment by cspotcode** [comment]
This is a dupe and has already been implemented.

**Comment by stefanprobst** [comment]
thanks!

for reference: https://github.com/TypeStrong/ts-node/pull/1356 (not released yet)
