### ISSUE TITLE
TS's new node ESM support

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1414]
Will need work on our side to integrate.

https://github.com/microsoft/TypeScript/pull/44501
https://github.com/weswigham/TypeScript/pull/67

## Roughly

adds new `module: node12` and `module: nodeNext` configs
In them:
- existing extensions obey package.json "type" field
- new extensions `.mts`, `.mjs`, `.cts`, `.cjs` force one or the other; ignore package.json "type" field

## Questions I still have

Are any of the above assumed to be modules without needing to add `export {};`?

**Comment by alvis** [comment]
With 4.5 beta announced 2 weeks ago, and the final on the horizon, time for us to do something.

**Comment by PodaruDragos** [comment]
Will this mean that we can now potentially have `import { foo } from './foo'`, basically omitting the extensions just like in `commonJS` ?

**Comment by cspotcode** [comment]
@PodaruDragos you're probably looking for node's `--experimental-specifier-resolution=node` which we already support.  Just as node requires you to pass that flag, we *also* require you to pass that flag, often via the `NODE_OPTIONS` environment variable.

https://nodejs.org/dist/latest-v17.x/docs/api/esm.html#customizing-esm-specifier-resolution-algorithm
