### ISSUE TITLE
pretty option is ignored in terminal

### ISSUE THREAD

**Issue by elevatebart** [TypeStrong/ts-node#1418]
### Expected Behavior

When I specify `pretty: false` I expect the errors to respect that.
This is particularly useful if I am developing a tool that uses ts-node and I need to handle 3rd party potentially faulty code.

### Actual Behavior

Because of this line, when I use a terminal as the main output for my tool, `pretty` is ignored: 
https://github.com/TypeStrong/ts-node/blob/e8a4d76ad6e9772296e31b871560ae6bd78a1165/src/index.ts#L628-L630

### Steps to reproduce the problem

Run ts-node on a faulty codebase with `--pretty false` option.
Errors are still styled with terminal only decoration.

### Minimal reproduction

https://github.com/TypeStrong/ts-node-repros/pull/16

### Specifications

ts-node v8.3.0
node v14.17.0
compiler v4.3.5

tsconfig.json
```
{
  "compilerOptions":{
    "pretty": false
  }
}
```
* Operating system and version: MacOS - Big Sur

**Comment by cspotcode** [comment]
Sounds like we want 3x states for the pretty flag: true forces it enabled, false forces it disabled, and undefined (not specified anywhere) allows the default to be determined based on `isTTY`.  Does that make sense?

Are you able to send a pull request for this?

**Comment by cspotcode** [comment]
The docs will need to be updated to match, as well.
https://typestrong.org/ts-node/docs/options/#diagnostics

**Comment by elevatebart** [comment]
I'll whip up a PR right now.
I don't see where this is tested though. 
Do you know if it is tested at all?

**Comment by cspotcode** [comment]
I replied to the PR before seeing this comment.

It might be untested.  Most of the tests invoke the CLI, which isn't the fastest but is simple to think about.  Feel free to write a couple tests that do that.
