### ISSUE TITLE
forceConsistentCasingInFileNames breaks with VS Code 1.3.1 Open New Command Prompt command

### ISSUE THREAD

**Issue by rob3c** [TypeStrong/ts-node#144]
Hi, I just posted bug https://github.com/Microsoft/vscode/issues/9448 in the vscode repo that affects `ts-node`. I'm not sure if this can be addressed in `ts-node` or where the actual problem is, but the bug shows `tsc` compiling successfully where `ts-node` fails under certain circumstances on windows due to a breaking change in VS Code.

Here's my overview of the issue from the vscode tracker:

"Starting with the 2016-07-14 release of Visual Studio Code Insiders edition (and now released in regular VS Code 1.3.1), the behavior of the _Open New Command Prompt_ command (`ctrl+shift+C`) changed on Windows. Now, it lower-cases the drive letter in the new console's prompt, and that seems to affect the ability of at least `ts-node` (and possibly other tools) to build typescript code when the `forceConsistentCasingInFileNames` compiler option is set in _tsconfig.json_."

**Comment by rob3c** [comment]
Just a quick update: it looks like the related vscode issue with their terminals on Windows at https://github.com/Microsoft/vscode/issues/9448 just got closed.

Considering Windows has a case-insensitive file system, it's still pretty odd that there's a case-sensitivity issue in the typescript ecosystem somewhere like this, possibly in TS itself (someone in the vscode thread linked to a possible cause at https://github.com/Microsoft/TypeScript/issues/10095). That said, it's still amazes me that things work cross-platform as well as they do, given the differences that libraries deal with internally to make things just work for the most part.

Anyway, it looks like the immediate issue of vscode compatibility has been addressed on their end, so we can go ahead and close this if you think it's just adding noise at this point even though the underlying issue - whatever it may be - is still at large :-)

**Comment by blakeembrey** [comment]
Let me know if you think this should stay open 😄
