### ISSUE TITLE
Error-stacktrace are wrong when using ts-node + source-map-support

### ISSUE THREAD

**Issue by stavalfi** [TypeStrong/ts-node#1440]
When I downgrade to ts-node `9.1.1` all works great (or run my code without ts-node I get the correct javascript stacktraces).

### Expected Behavior

correct error-stacktraces

### Minimal reproduction

I can't share my code because it's private.
I couldn't reproduce this bug easily in a minimal example.

### Specifications

```
ts-node v10.2.1
node v14.15.4
compiler v4.1.3
```

* ts-node version:
* node version:
* TypeScript version:
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declaration": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "strict": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "ES2019",
    "lib": ["esnext", "DOM", "DOM.Iterable"],
    "preserveSymlinks": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "composite": true,
    "baseUrl": "packages",
    "paths": {
      "@singer/common": ["common/src/index.ts"],
      "@singer/test-infra": ["tests-infra/src/index.ts"]
    },
    "resolveJsonModule": true,
    "jsx": "react"
  }
}
```
* Operating system and version: macos big sur 11.5.2

**Comment by cspotcode** [comment]
Probably a duplicate of #1438

**Comment by stavalfi** [comment]
I will update if it helped. Thanks.

**Comment by stavalfi** [comment]
Update:

after upgrading to:
```
"@cspotcode/source-map-support": "0.6.1",
"ts-node":"10.2.1"
```

all works great.

Thanks!

**Comment by cspotcode** [comment]
You may able to remove the @cspotcode/source-map-support dependency entirely, since ts-node already registers it.

**Comment by stavalfi** [comment]
> You may able to remove the @cspotcode/source-map-support dependency entirely, since ts-node already registers it.

In production I run js files directly with node so i must register it manually.
as it's best practice to declare the deps im using directly and yarn2/pnpm wont let me use it without declaring it, then I must :P
