### ISSUE TITLE
Proxy not available in ts-node

### ISSUE THREAD

**Issue by viocost** [TypeStrong/ts-node#1443]
### Search Terms

Proxy

### Expected Behavior
Run ts-node repl
Expecting Proxy to be defined

### Actual Behavior
Proxy is undefined

### Steps to reproduce the problem
Start ts-node repl
observe Proxy is undefined

Do the same thing in nodejs - Proxy is a Function

### Specifications
ts-node v10.2.1
node v16.8.0
compiler v4.4.2

* ts-node version:
* node version:
* TypeScript version:
* tsconfig.json, if you're using one:
```
{}
```
* Operating system and version: Linux Ubuntu 21
* If Windows, are you using WSL or WSL2?:

**Comment by viocost** [comment]
something weird on my end

**Comment by Zeatynis** [comment]
Hello, I have an issue with proxy too. Is there any workaround? I tried to set proxy by npm set but it doesn't work either.
