### ISSUE TITLE
Listeners for `uncaughtException` cannot be used in the REPL

### ISSUE THREAD

**Issue by pravic** [TypeStrong/ts-node#1451]
When using [`unload.add()`](https://www.npmjs.com/package/unload/v/2.1.0) `ts-node` fails with 

> TypeError [ERR_INVALID_REPL_INPUT]: Listeners for `uncaughtException` cannot be used in the REPL

<details>
  <summary>detailed stack trace</summary>

```
repl.js:265
        throw new ERR_INVALID_REPL_INPUT(
        ^

Uncaught:
TypeError [ERR_INVALID_REPL_INPUT]: Listeners for `uncaughtException` cannot be used in the REPL
    at process.<anonymous> (repl.js:265:15)
    at process.emit (events.js:326:22)
    at process.EventEmitter.emit (domain.js:483:12)
    at process.emit (...\node_modules\@cspotcode\source-map-support\source-map-support.js:527:35)
    at _addListener (events.js:357:14)
    at process.addListener (events.js:405:10)
    at Object.add (...\node_modules\unload\dist\lib\node.js:36:11)
    at startListening (...\node_modules\unload\dist\lib\index.js:29:14)
    at Object.add (...\node_modules\unload\dist\lib\index.js:33:3)
    at initialize_addon (...\lib\index.ts:58:10) {
  code: 'ERR_INVALID_REPL_INPUT'
```
</details>

### Search Terms

uncaughtException, ERR_INVALID_REPL_INPUT

### Expected Behavior

Continue to work? By either ignoring `uncaughtException` or by properly supporting it.

### Actual Behavior

> TypeError [ERR_INVALID_REPL_INPUT]: Listeners for `uncaughtException` cannot be used in the REPL

### Steps to reproduce the problem

* `npx ts-node`
* enter the following two lines
* boom, the mentioned exception

### Minimal reproduction

```typescript

import * as unload from 'unload'
unload.add(function() {})

```

### Specifications

* ts-node version: 10.2.1
* node version: 12.22.4
* TypeScript version: 4.3.5
* tsconfig.json, if you're using one:
<details>
  <summary>tsconfig.json</summary>

```
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "./dist",
    "declaration": true,
    "strict": true,
    "noUnusedLocals": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "inlineSources": true,
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "newLine": "lf",
    "noEmitOnError": true,
    "lib": ["es2018", "dom"],

    // The dependency `unload` has bad typings. This setting causes TS to check only typings
    // actually referenced/used by our code.
    "skipLibCheck": true
  },

  "include": ["index.ts", "proxy/**/*", "lib/**/*"],

  // Most ts-node options can be specified here using their programmatic names.
  "ts-node": {
    "transpileOnly": false,
    "compilerOptions": {
      // compilerOptions specified here will override those declared above,
      // but *only* in ts-node.

      // counterproductive for test scripts
      "noUnusedLocals": false
    }
  }
}

```
</details>

* Operating system and version: Win10 21H1 19043
* If Windows, are you using WSL or WSL2?: nope

**Comment by cspotcode** [comment]
Is this a vanilla node limitation?  We mimic -- and inherit limitations
from -- vanilla nodejs.

**Comment by cspotcode** [comment]
> TypeError [ERR_INVALID_REPL_INPUT]: Listeners for uncaughtException cannot be used in the REPL

This error comes from node's REPL, so it is correct for ts-node to do the same, since we use node's REPL to implement our own and we want to match behavior.

**Comment by pravic** [comment]
> Is this a vanilla node limitation? We mimic -- and inherit limitations from -- vanilla nodejs.

Looks like it is: https://nodejs.org/api/repl.html#repl_global_uncaught_exceptions
