### ISSUE TITLE
Update #1007 with exact node version that broke ESM

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1453]
I mention that node 16.10.0 will break the ESM API, but it could be 16.9.x instead.  When this happens, update the post accordingly.

https://github.com/nodejs/node/pull/37468

**Comment by connorjclark** [comment]
Is this related to the error `ReferenceError: exports is not defined in ES module scope` received when trying to import a node builtin (like `fs`) when using `ts-node/esm`?

**Comment by cspotcode** [comment]
The breaking changes to ESM did *not* release in node v16.10.0.

**Comment by stanf0rd** [comment]
I could just confirm
`ReferenceError: exports is not defined in ES module scope`
when import `fs/promises` using both node 16.9.0 and 16.11.1

Is that issue related to this thread?

**Comment by cspotcode** [comment]
No that's a user error, unrelated.
