### ISSUE TITLE
Don't use `cwd` at `register` time

### ISSUE THREAD

**Issue by weswigham** [TypeStrong/ts-node#146]
`gulp` respects a `cwd` command - however this argument only sets the process's `cwd` _after_ the register hook has been run (but before the `gulpfile` is required). This causes dissonance where `ts-node` can only correctly transpile files when the cwd does not change between the register invocation and a require call. See [this issue](https://github.com/gulpjs/gulp-cli/issues/89) for discussion.

**Comment by blakeembrey** [comment]
What do you suggest as an alternative? It's used to load `tsconfig.json`.

**Comment by weswigham** [comment]
Can we delay loading of the `tsconfig.json` until at least the first call to `require`?

**Comment by blakeembrey** [comment]
That might be possible - so it'd only initialize TypeScript after we require our first TypeScript file?

**Comment by weswigham** [comment]
Yep. That seems like it should work.

**Comment by blakeembrey** [comment]
@weswigham Actually, I just realised this doesn't exactly work unless we add a new flag. The current behaviour of `ts-node` also supports `allowJs`, but that can't be known unless we load `tsconfig.json`. I suppose it could be changed to a `ts-node` flag instead, but what are your thoughts?

**Comment by blakeembrey** [comment]
It could also be a major change to _always_ requiring the `--project` option to be set and make it be "no project" by default. This would avoid the `cwd` from being used at all until TypeScript is created. Should the TypeScript option (assuming this is for `getCurrentDirectory`) always use `process.cwd()` too?

**Comment by weswigham** [comment]
So the exact issue we were having is that, without our Gulpfile.ts, if used from a subdirectory like `cd src && gulp local --cwd ../`, `ts-node` compiles the `Gulpfile` with the `cwd` still being within the `src` directory (resulting in many type-not-found errors, ofc). We're not even in a scenario where passing `--project` is an option (so the only method to configure the hook is via the config file) - the require hook is non-configurably loaded by `gulp` via `liftoff` via `rechoir`. On the other hand, `rechoir` via `interpret` only loads `ts-node` for either `.ts` or `.tsx` files, so the js-mode will never come up via gulp. _On the other hand_ we definitely still want the ability to include js files in our Gulpfile.ts compilations (usually when a lib has no types and it's effort to write some), so keeping the ability to have `allowJs` on would be good. We just don't _need_ a `js` entrypoint.

**Comment by blakeembrey** [comment]
Right, but that won't help here - I can't break people who are expect `allowJs` to work and may be using `.js` as an entry point. There's a wide range of clients, and, unfortunately, configuration is near impossible on all of them because they need `tsconfig.json` and may not have another way of setting it. I feel loading `tsconfig.json` is still an iffy default, but I can leave it.

However, why would type errors be occurring because of the `cwd` in TypeScript? Shouldn't everything be relative? I mentioned it above, but could not caching the `cwd` and using `process.cwd` work better with TypeScript then?

**Comment by weswigham** [comment]
@blakeembrey  The `cwd` being in the inner directory causes you to load the wrong `tsconfig` from it.

**Comment by blakeembrey** [comment]
Ok, got it. It's tricky to workaround then. I think perhaps I need a new flag that'll set `lazy: true` on register then. On the CLI it can continue working the same.

**Comment by weswigham** [comment]
@blakeembrey That sounds workable.

**Comment by blakeembrey** [comment]
@weswigham Out of curiosity, would you want type errors or fast transpilation when working with Gulp?

**Comment by weswigham** [comment]
@blakeembrey I've personally appreciated the type errors. Gulp plugins have a bad habit of failing completely silently and being a pain to debug, and types help with that.

**Comment by blakeembrey** [comment]
@weswigham Would you like to test https://github.com/TypeStrong/ts-node/pull/147? There'll be a few other changes before the next major release, but that hopefully solves lazy loading.
