### ISSUE TITLE
Add a factice FileSystemError interface specific to errors triggered by the native "fs" module.

### ISSUE THREAD

**Issue by SmashingQuasar** [TypeStrong/ts-node#1476]
### Desired Behavior

Let's assume a code such as:

```ts
try
{
	const STAT: Stats = await fs.stat(file_path);

	return STAT.isFile();
}
catch (error: unknown)
{
	switch (error.code)
	{
		case "ENOENT":
			return false;

		case "EACCES":
			console.log(`Requested file ${file_path} cannot be loaded. File exists but reader got denied permissions. Error code: EACCES.`);

			return false;

		default:
			console.log(`Requested file ${file_path} could not be loaded due to an unhandled error. Error code: ${error.code}.`);

			return false;
	}
}
```

This code is considered invalid by TypeScript, because `code` does not exit on type `unknown` which makes perfect sense.
Now, if we were to check that `error` is an instance of `Error`, it would still reject this code, as the native class `Error` does not have a `code` property.
In reality, this code is valid. Errors thrown by the native "fs" module are hi-jacked to create a dynamic property `code` containing a string. This is a bad practice inside Node.JS itself that I have reported here: https://github.com/nodejs/node/issues/40232

The desired behavior would be that TypeScript recognizes that calls to "fs" will throw a special `Error` class (which I called `FileSystemError` for clarity in the title) that has a `code` property.

### Is this request related to a problem?

This request is directly tied to the improper property addition inside Node.JS reported here: https://github.com/nodejs/node/issues/40232

### Alternatives you've considered

Of course, we could use a `// @ts-ignore` comment, but the idea is to avoid those comments for obvious reasons. Also, we work in a very strict environment where our ESlint rejects `// @ts-ignore` comments to avoid code base instabilities.
This means to make this work, we have to work with the following code:

```ts
// FileSystemError.ts

declare interface FileSystemError extends Error
{
	code: string;
}

export type { FileSystemError };

// FileSystem.ts

/**
 * IsFileSystemError
 */
public static IsFileSystemError(error: unknown): error is FileSystemError
{
	/* eslint-disable-next-line */
	// @ts-ignore
	return (error instanceof Error) && (typeof error.code === "string");
}

/**
 * FileExists
 */
public static async FileExists(file_path: string): Promise<boolean>
{
	try
	{
		const STAT: Stats = await fs.stat(file_path);

		return STAT.isFile();
	}
	catch (error: unknown)
	{
		if (FileSystem.IsFileSystemError(error))
		{
			switch (error.code)
			{
				case "ENOENT":
					return false;

				case "EACCES":
					console.log(`Requested file ${file_path} cannot be loaded. File exists but reader got denied permissions. Error code: EACCES.`);

					return false;

				default:
					console.log(`Requested file ${file_path} could not be loaded due to an unhandled error. Error code: ${error.code}.`);

					return false;
			}
		}
	}

	return false;
}

```

This solution is the only one we could find that is the closest to the desired behavior but sadly requires disabling ESlint and using a `// @ts-ignore` comment.

### Additional context

This has been tested with TypeScript 4.4.3 and Node.JS 16.10.0.

I realize this may be difficult to implement in the current state of TypeScript but I believe it is worth considering to avoid `// @ts-ignore` comments.

**Comment by cspotcode** [comment]
At a glance, this looks like a feature request for typescript, not for ts-node.  Is that correct?

**Comment by SmashingQuasar** [comment]
> At a glance, this looks like a feature request for typescript, not for ts-node. Is that correct?

Actually, it's kind of a request specifically for Node.JS. I opened the issue I linked and I am willing to fix it through a PR but it seems this Error hi-jacking is pretty much everywhere in the source code so it's going to take a lot of time to fix it.
I am not sure this is even doable through `ts-node` but I had to try my luck here.

I opened a correlated issue (feature request) for TypeScript if you are interested: https://github.com/microsoft/TypeScript/issues/46114

This would at least help determining that the parameter of the `catch` clause is an instance of Error or it's children. Right now it's can of a mess to work around as you could see.

**Comment by cspotcode** [comment]
Unfortunately we don't implement workarounds for TypeScript or node bugs; those will need to be handled in the correct projects.  Our goal is to match node's behavior, warts and all.  Except, of course, for node's lack of built-in TypeScript support; that is what we try to change.  But anything else is out of scope.

**Comment by SmashingQuasar** [comment]
It's disappointing but understandable. I had little hope that this would even be possible solely through `ts-node`.
If you consider this to be an interesting problem, please feel free to support the issue opened on Node.JS's repository.
I'm closing this issue as it no longer is relevant to this repository.

**Comment by cspotcode** [comment]
For what it's worth, I don't actually think this is a bug in node, so I don't think it will be changed.  It's been this way for a long time, and what you're proposing appears to be a breaking change.  Plus we have nice ways to handle this in TypeScript already: custom type guards, type assertions, etc.  So you probably won't be able to convince the node team that this is worth a breaking change.

**Comment by Zamralik** [comment]
> For what it's worth, I don't actually think this is a bug in node, so I don't think it will be changed. It's been this way for a long time, and what you're proposing appears to be a breaking change. Plus we have nice ways to handle this in TypeScript already: custom type guards, type assertions, etc. So you probably won't be able to convince the node team that this is worth a breaking change.

It's not a bug per say as it's perfectly valid in JavaScript to extend an object with new properties without it being part of its class prototype.

The only fix is on NodeJS to create a new class ErrorWithCode.

The only workaround is to have a guard that violate some eslint strict rules.

```ts
interface ErrorWithCode extends Error
{
    code: number;
}

function hasProperty<KeyName extends string>(value: object, key_name: KeyName): value is { [key_name in KeyName]: unknown }
{
    return key_name in value;
}

function isErrorWithCode(value: unknown): value is ErrorWithCode
{
    return (
        value instanceof Error
        &&
        hasProperty(value, "code")
        &&
        typeof value.code === "number"
    );
}
```
