### ISSUE TITLE
configurable TMP_DIR

### ISSUE THREAD

**Issue by djeeg** [TypeStrong/ts-node#149]
Is it possible to override the tmp dir for cached files?

```
import { EOL, tmpdir } from 'os'
const TMP_DIR = join(tmpdir(), 'ts-node')
```

**Comment by blakeembrey** [comment]
Sure, it could be added. Care to share why so I understand better?

**Comment by djeeg** [comment]
I like to have a single directory for generated files, so they don't pollute the rest of my source tree, babel/ts-node/webpack caches etc

It also makes excluding these files from various globs easier too

I have updated to the latest version and it works like a charm.

Thanks @blakeembrey , awesome turn around time!

**Comment by blakeembrey** [comment]
@djeeg Wouldn't the tmp directory be outside of your source tree though? I didn't think anyone would actually see the files.

**Comment by djeeg** [comment]
I seem to get this because I mount my source directory into a docker container via a volume (then monitor via nodemon)
It looks like os.tmpdir() resolves to the volume mount point, which is the source root

This is my setup

```
-windows
  /project [shared \\computer\project]
   /node_modules
   /output
   /src
     /run.tsx
   
-boot2docker
  /mnt/computer_project as \\computer\project
  
-a docker container
  -volume [/mnt/computer_project:/serviceroot]
    /serviceroot
	  /src
		/run.tsx
			-nodemon
	  /ts-node - was getting created here
	  /output/ts-node - now I can create it here
```
