### ISSUE TITLE
Can't use dynamic imports with swc

### ISSUE THREAD

**Issue by petercoulton** [TypeStrong/ts-node#1508]
### Search Terms

- swc dynamic imports
- swc 'regenerator-runtime'

### Expected Behavior

Dynamic imports should continue to work after switching to the swc transpiler.

### Actual Behavior

Throws `Error: Cannot find module 'regenerator-runtime`

### Steps to reproduce the problem

```typescript
const example = async () => {
    const other = await import('./other')
    console.log(other)
}

example().then(() => console.log(`done`))
```

See https://github.com/TypeStrong/ts-node-repros/pull/20 for full example.

### Minimal reproduction

https://github.com/TypeStrong/ts-node-repros/pull/20

### Specifications

* ts-node version: v10.2.1
* node version: v16.8.0
* TypeScript version: 4.4.3
* tsconfig.json, if you're using one:
```
{
  "extends": "ts-node/node16/tsconfig.json",

  "ts-node": {
    "transpileOnly": true,
    "transpiler": "ts-node/transpilers/swc-experimental"
  },

  "include": ["**/*.ts"],
  "exclude": ["node_modules"]
}

```
* Operating system and version: macOS 11.6 Big Sur
* If Windows, are you using WSL or WSL2?: no

**Comment by cspotcode** [comment]
Thanks.  It also occurred to me, we can detect when an import fails and log a helpful warning.  For example, when a file compiled by ts-node attempts to `require('regenerator-runtime')` and fails, we can detect this and log a helpful warning suggesting that the user should install `regenerator-runtime`.  I've added a note about this to #1504
