### ISSUE TITLE
findConfigFile issue on Windows

### ISSUE THREAD

**Issue by cartant** [TypeStrong/ts-node#151]
@blakeembrey For your reference, I can confirm that `ts-node` is affected by [this issue](https://github.com/Microsoft/TypeScript/pull/9625) and that on Windows platforms, `tsconfig.json` files in parent directories will not be found.

**Comment by blakeembrey** [comment]
Thanks for the heads up. For a work-around, you should be able to point to the parent directory manually using `ts-node --project ..`. Let me know if that works for you.

**Comment by cartant** [comment]
Yeah, specifying a relative project directory using the `--project` switch definitely works.

The problem isn't a major inconvenience, for me. I created this issue so that's it's documented - should anyone else happen to search for it - and is linked to the TypeScript issue/PR.

I'd considered submitting a PR, but it was a little messy, as it seems that `normalizeSlashes` is public in a JavaScript sense, but not in a TypeScript sense - so my attempt at a code-based work around needed to mess up the [`TSCommon`](https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L20-L38) interface with an optional `normalizeSlashes` function. And I thought that was pretty ugly.

(By the way, although I don't use it, I did have a quick look at `ts-loader`. It's not affected by the TypeScript  issue, as it implements its own [`findConfigFile`](https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L20-L38) function.)

**Comment by blakeembrey** [comment]
@cartant Yes, I used to have my own implementation before 1.0 as well. It just made more sense to use the TypeScript implementation that already exists. For reference, I used to use https://github.com/TypeStrong/tsconfig.

**Comment by blakeembrey** [comment]
That said, `ts-loader` suffers from also being out of date with TypeScript now. I was really hoping TypeScript would update the method as more functionality got added, but I guess the external APIs are high on their priorities. For instance, `tsc` can take a project path to a directory or to a filename. I updated this in the `tsconfig` module, which I could re-use again here _and_ in other projects - but it would be nice for TypeScript to externalize it also. What do you think?

**Comment by blakeembrey** [comment]
@cartant Updated the `tsconfig` module and reverted back to using it (see https://github.com/TypeStrong/ts-node/releases/tag/v1.2.0 and https://github.com/TypeStrong/ts-node/commit/84fcf198a4779aecb6d8efbdd29eb3efa91115b0).

**Comment by cartant** [comment]
@blakeembrey I was wondering whether or not there is any documentation regarding APIs like `findConfigFile`? In the absence of any easily discoverable documentation, it is certainly a problem area.

As you point out, `tsc` can be passed a directory or a file. If a tool implements similar behaviour and always passes the received path to `findConfigFile` a subtle bug would be introduced, as the filename would be stripped and replaced with `tsconfig.json`. So if you happened to have multiple configuration files with different names (which I do: one to keep the Sublime Text TypeScript plugin happy; and another for `tsify`-based builds) it'd always pick the `tsconfig.json` file.

I think there is something to be said for using some common code to keep the `tsconfig.json` resolution DRY in a suite of tools - and to resolve the backslash issue (if it weren't so annoying, it'd be amusing that it's Microsoft's platform that has the issue).

Whether or not non-TypeScript code should used for the parsing of the `tsconfig.json` is another issue, but for `tsconfig.json` file resolution, yes, I think using `tsconfig` is the way to go.

**Comment by blakeembrey** [comment]
I think the only "official" documentation is their own definitions. That's at least how I started using it personally. I assumed anything in there is actually public, since TypeScript goes to an effort to mark `@internal` on other methods. There's sadly been multiple issues with that method (the slashes isn't the first so far, just the latest). It's not a great API, I think because there's a lot of optimisations they did internally (E.g. path representation is consistently slashes) which don't translate to a public API (paths are paths, usually use `path.join` and co to normalize across OSes).

> As you point out, tsc can be passed a directory or a file. If a tool implements similar behaviour and always passes the received path to findConfigFile a subtle bug would be introduced, as the filename would be stripped and replaced with tsconfig.json.

Not sure I got the gist of this, but the idea would be that you wouldn't pass a specified file to `findConfigFile` - it's only used when nothing is specified (like `tsc`). I had that functionality in here before (use `--project` or fallback to finding it using TypeScript). That said, it's not a big deal - I spent an hour or so refactoring `tsconfig` to mirror `tsc` today, so it should be resolved for good now.

It'd be good to port the functionality back into TypeScript when possible, but until then I'll just use `tsconfig` consistently as a polyfill that fixes the buggy functionality.

**Comment by cartant** [comment]
> Not sure I got the gist of this ...

It's just that `findConfigFile` isn't documented and would work in most cases if passed a path to a `tsconfig.json` file. Given that, I think it'd be easy for someone to mistake it for a function that behaves similarly to `tsc`'s command-line option. That is, just pass it a path to whatever and it'll find the `tsconfig.json` file.

**Comment by blakeembrey** [comment]
@cartant Fair enough. I actually have to read the source code with TypeScript to make sure it's the method I want. In this case, it is - it's not meant to be passed a `tsconfig.json` file though, it's meant to be passed a starting directory (E.g. `cwd`). Passing it a full path to `tsconfig.json` would still fail on the slashes issue. 

In the past, it even failed to resolve from the directory you gave it (patched that last year I think) and only ever worked on the actual `cwd`. I don't have an answer on how to make it better sadly. Like I mentioned, these external APIs feel lower priority (for instance, fixing it took a year - https://github.com/Microsoft/TypeScript/issues/2965 - there weren't an pointers on everywhere it needed fixing, so I didn't actually fix it for the longest time).

Anyway, if you read through the command line parser, it does use this function internally - it's just the functionality of setting a path/directory was always custom inlined. It's little API features like that which should probably be documented for people trying to use the TypeScript API somewhere. The primary consumer is just going to use existing tools, but the rest of people that run into this and workaround it and then it breaks again later, etc. is in for some pain. I know I have, and I've seen other people unfamiliar with how to actually start using the compiler directly.

Now I've just thrown a bunch of words here and don't want to delete that work. Take it all with a grain of salt 😄 If anything, people can now use `tsconfig` for the functionality. The only other tricky thing is using the parsing functions to transform the JSON in the following step (have to remember old versions had a different method with a different API).

**Comment by cartant** [comment]
> [Microsoft/TypeScript#2965](https://github.com/Microsoft/TypeScript/issues/2965)

I'm certainly glad I didn't make the switch to TypeScript last year.

**Comment by blakeembrey** [comment]
Haha, things are definitely getting better 😄 To be honest, after using 2.0 for a while on private projects, it hurts to use 1.8 still on public projects. Funny that.

**Comment by cartant** [comment]
Unfortunately, until [this](https://github.com/Microsoft/TypeScript/issues/9768) is fixed, TypeScript 2.0 is not an option, for me.

I guess what I was trying to say, in my earlier ramblings, was that I am all for using `tsconfig` in `ts-node` and in other TypeScript tools, as the TypeScript API doesn't have a single function that applies the `tsconfig.json` resolution mechanism used in `tsc` and that there are things to look out for with `findConfigFile`, etc. Although, from what you've been saying, it seems much better than it once was.

**Comment by blakeembrey** [comment]
That's a bummer. Thanks for all your help though 😄 I think it's still similar, but the language itself is definitely improving greatly - native `@types`, node resolution, null checking, ES6-support. It's been improving quickly 😄
