### ISSUE TITLE
CI uses cache option from setup-node GitHub Action

### ISSUE THREAD

**Issue by oscard0m** [TypeStrong/ts-node#1512]
### Desired Behavior
Not a problem but workflows of this project could get benefit from using `cache` from `setup-node` GitHub Action

### Is this request related to a problem?
No

### Alternatives you've considered
-

### Additional context
https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies

**Comment by cspotcode** [comment]
It looks like we already do caching:

https://github.com/TypeStrong/ts-node/blob/89bde5169aefcf1012ae19a5d5f8710bf1916828/.github/workflows/continuous-integration.yml#L27-L34

I'm going to close this to tidy up our PR queue.  Hypothetically, if someone feels we will benefit from replacing our current caching with `setup-node`'s caching implementation, we can consider re-opening.
