### ISSUE TITLE
typeRoots not supported

### ISSUE THREAD

**Issue by filipesilva** [TypeStrong/ts-node#153]
Heya, I'm using `ts-node` with `protractor` to run some TS tests and wanted to try out the new `@types/*` repos for typings.

My `tsconfig.json` has `"typeRoots": [ "../node_modules/@types" ]` and that seems to work with the local project `tsc`, but not with `ts-node`.

Does `ts-node` at the moment support `typeRoots`?

**Comment by blakeembrey** [comment]
TypeScript 2.0 is still in beta, so it's hard to know. I believe support was probably added with https://github.com/TypeStrong/ts-node/commit/240d4b9b751a5c551730a9856502f561844ae3b6 but if you can confirm that would help.

**Comment by filipesilva** [comment]
@blakeembrey just tested and it does work, cheers!

**Comment by cristianmtr** [comment]
This doesn't work for me.

- Windows 7, x64

```
ts-node --version
ts-node v2.0.0
node v6.2.0
```

- tsconfig:
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": false,
        "types": [
            // add node as an option
            "node"
        ],
        // typeroots option has been previously configured
        "typeroots": [
            // add path to @types
            "../node_modules/@types"
        ]
    }
}
```

**Comment by blakeembrey** [comment]
Try with a capital R. When in doubt, please try `tsc` directly to confirm if it should work.
