### ISSUE TITLE
swc transpiler does not set `strictMode` to match tsconfig

### ISSUE THREAD

**Issue by Janpot** [TypeStrong/ts-node#1531]
### Search Terms

swc

### Expected Behavior

Running
```ts
function defaultHello () {
  return ''
}

class X {
  constructor(x) {
    this.hello = () => (x.hello || defaultHello)()
  }
}

console.log(new X({
  hello () {
    return this.y || 'this works'
  }
}).hello())
```

using

```json
  "ts-node": {
    "transpileOnly": true,
    "transpiler": "ts-node/transpilers/swc-experimental"
  },
```

will print

```
this works
```

(this is what is printed without using `swc`)

### Actual Behavior

an error is printed:

```
/swctest/index.ts:13
    return this.y || 'this works'
                ^
TypeError: Cannot read property 'y' of undefined
    at hello (/swctest/index.ts:13:17)
    at X.hello (/swctest/index.ts:7:50)
    at Object.<anonymous> (/swctest/index.ts:15:4)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/swctest/node_modules/ts-node/src/index.ts:1371:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/swctest/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```

### Specifications

```
ts-node v10.4.0
node v14.16.0
compiler v4.4.4
@swc/core 1.2.103 
```
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "target": "es5",                 
    "module": "commonjs",
    "esModuleInterop": true, 
    "forceConsistentCasingInFileNames": true, 
    "strict": false,  
    "skipLibCheck": true },

  "ts-node": {
    "transpileOnly": true,
    "transpiler": "ts-node/transpilers/swc-experimental"
  },
}
```
* Operating system and version: MacOS 11.6

**Comment by cspotcode** [comment]
@Janpot What is your tsconfig?  There are various options which affect "use strict" and I want to make sure I understand your project configuration 100%.  Thank you in advance.

---

I did a bit of research here.  `tsc`, by default, will add `"use strict"` whenever you use any sort of import or export.

Your script above is a special case.  I expect that *most* node scripts, even standalone ones, will have at least one import, for example `import {} from 'fs';`  TS is bending over backwards to allow scripts with _zero_ imports or exports run in non-strict mode.  I suspect this behavior only exists for backwards compatibility, and you generally always want "use strict" enabled.

swc is not as nuanced as TS.  We can either tell it to always emit use strict, or never emit.

Given this limitation of swc, I'm going to pragmatically assume that all node scripts have an import or export, and set swc's options accordingly.

If a user *really really* needs to avoid strict mode, they will likely have `alwaysStrict: false, noImplicitUseStrict: true`.  We can detect this and tell swc not to emit `"use strict"`

**Comment by cspotcode** [comment]
Nevermind... of course you included your tsconfig at the top, doh!

**Comment by Janpot** [comment]
This was originally discovered in a repo that was transitioning from js to ts. all the imports were `require` calls. not all files had a `'use strict'` pragma. the original js files were not compiled before and after running them through ts-node, this issue came up.

**Comment by cspotcode** [comment]
Thanks, good to understand the context.  I think the implementation we settled on is the best we can do, given that swc's configuration is a bit more limited than tsc's.
