### ISSUE TITLE
move .ts_node_repl_history with TS_NODE_REPL_HISTORY 

### ISSUE THREAD

**Issue by mirsella** [TypeStrong/ts-node#1546]
node support NODE_REPL_HISTORY environment variable to change the node_repl_history file.
for example `export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history` to move it to a different place than the default which cluster the home dir.

so maybe for ts-node we can use  TS_NODE_REPL_HISTORY.

thanks

**Comment by cspotcode** [comment]
We already have this in our documentation, don't we?

**Comment by mirsella** [comment]
my bad, sorry didn't find TS_NODE_HISTORY before
