### ISSUE TITLE
Wrong error when using no type while declaring constant in repl

### ISSUE THREAD

**Issue by Dragonizedpizza** [TypeStrong/ts-node#1563]
### Expected Behavior

undefined/nothing.

### Actual Behavior

```
/home/arch/Desktop/Hurricano/<repl>.ts:3
export {};
^^^^^^

Uncaught SyntaxError: Unexpected token 'export'
```
### Steps to reproduce the problem

1. Make a ts-node repl.
2. Type in `const h = {};`

### Minimal reproduction

![image](https://user-images.githubusercontent.com/70718540/145353218-307cbee3-c105-466d-8ebd-14a5987f1a4f.png)

### Specifications

* ts-node v10.4.0
* node v16.13.0
* compiler v4.5.2
tsconfig.json, if you're using one: 

https://srcb.in/ldUTwVZaod
* Operating system and version:
* Garuda Linux Soaring.

**Comment by cspotcode** [comment]
Looks like tsconfig "module: esnext" is the culprit.

**Comment by Dragonizedpizza** [comment]
Ok

**Comment by cspotcode** [comment]
I assume this has been resolved.  If not, feel free to reply and we can re-open.

**Comment by Jamesernator** [comment]
> Looks like tsconfig "module: esnext" is the culprit.

> I assume this has been resolved. If not, feel free to reply and we can re-open.

So this happens with `"module": "NodeNext"` as well, although I don't understand why this happens with either option.

Like shouldn't the repl mode always compile the code given as CommonJS/script regardless of the `"module"` field?

**Comment by Jamesernator** [comment]
> Yeah, I think the bug here is that we don't force the repl to be CJS even in ESM projects. I thought I already had a ticket for this; can you check for one and, if not found, file a new bug report?

I think this is #1752

**Comment by cspotcode** [comment]
Thanks, I added a comment on that issue about a couple possible ways to fix it.
