### ISSUE TITLE
unknown file extension ".ts"

### ISSUE THREAD

**Issue by yangdan8** [TypeStrong/ts-node#1569]
Change chalk from 4.1 2 upgrade to 5.0 After 0, execute gulp to call node code, and the error "unknown file extension '.ts'" will be reported

**Comment by cspotcode** [comment]
This issue is too vague and does not include the information we request in our issue template.  I've labelled it accordingly, and we will close it in a few days if we don't receive an update.

**Comment by laurentpayot** [comment]
@yangdan8  I had the same issue. In my `package.json` I had this line : `"type": "module",` (to use ES modules). 
Removing this line fixed the ts-node error, but disabled my ES modules, obviously.

**Comment by laurentpayot** [comment]
I’m using tsconfig-path, and finally could use ES modules thanks to  https://github.com/TypeStrong/ts-node/discussions/1450#discussioncomment-1806115.
