### ISSUE TITLE
「captureRejections」 property not works in ts-node

### ISSUE THREAD

**Issue by Scared-Heart** [TypeStrong/ts-node#1587]
### Search Terms
I wanna create a eventEmitter with 「captureRejections」
it works in with node.js
but not works with ts-node

### Expected Behavior

create a eventEmitter instance with able to capture promise rejections with ts-node

### Actual Behavior
「captureRejections」property not work with ts-node
but works with node

### Steps to reproduce the problem
create a file testEvent.js

```
const { EventEmitter } = require('events');
const ee = new EventEmitter({ captureRejections: true });
console.log(ee)
```

run 
```
ts-node testEvent.js
```

check console output
```
EventEmitter {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  [Symbol(kCapture)]: false
}
```
[Symbol(kCapture)]: false  means 「captureRejections」property is not setted

however, when i use node 

run

```
node testEvent.js
```

console output 
```
EventEmitter {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  [Symbol(kCapture)]: true
}
```
[Symbol(kCapture)]: false means 「captureRejections」works

this is so confusing

### Specifications

* ts-node version: v10.4.0
* node version: v14.15.0
* TypeScript version: 4.4.4
* tsconfig.json, if you're using one: not use

* Operating system and version: macos 10.15.5 (19F101)

**Comment by Scared-Heart** [comment]
captureRejections doc
https://nodejs.org/docs/latest-v14.x/api/events.html#events_events_capturerejections

**Comment by cspotcode** [comment]
I'm unable to reproduce this.  Usually when that happens, it means the reporter was making an honest mistake.

I've labelled this issue "needs more information" and I'll close in a few days if I don't hear back.

**Comment by Scared-Heart** [comment]
> I'm unable to reproduce this. Usually when that happens, it means the reporter was making an honest mistake.
> 
> I've labelled this issue "needs more information" and I'll close in a few days if I don't hear back.

```
const emitter = require('events')
const em1 = new emitter({ captureRejections: true })
console.log(em1)
```
I tried the code above on online runtime node.js again and it reproduced(node -v 14.x), 「captureRejections」property is setted with value true, the same result with my local test.
however, then i use local node.js REPL, it's different, 「captureRejections」property is false.
run with ts-node, 「captureRejections」is always setted with false.

So, first question is should ts-node works the same with node in 「experimental features」? 
if that's true, i guess this is a problem need 2 be fixed cause it's a trap for dev.
second question is why node REPL works different with node $fileName.js ?
maybe i should create a issue for node?

**Comment by cspotcode** [comment]
Sounds like you've narrowed this down to a bug in the behavior of whatever version of `node` you have installed locally, is that right?

**Comment by Scared-Heart** [comment]
> Sounds like you've narrowed this down to a bug in the behavior of whatever version of `node` you have installed locally, is that right?

emm, it's just a clue when i saw your reply and tried again. Cause i guess, if you reproduced this code with node REPL then it's not right.

I tried with node version 12-17, it works fine with ```captureRejections``` property, but node REPL is wrong.

what i expected is that then i run this code with ```ts-node```, it works the same as ```node```, ```captureRejections``` can be applied to eventEmitter.

**Comment by cspotcode** [comment]
I see, you are saying that the node REPL exhibits this bug?  Then it is a node bug?

I modified your `testEvent.js`
```
// For some reason, the following import of `Recoverable` triggers this bug
// If this import is removed, the bug goes away.
const { Recoverable } = require('repl');

const { EventEmitter } = require('events');
const ee = new EventEmitter({ captureRejections: true });
console.log('Event emitter created with captureRejections: true, so `Symbol(kCapture) should be true');
console.log(ee);
```

And the bug reproduces on the latest node v17.3.0:
```
❯ node -v
v17.3.0

❯ node ./testEvent.js
Event emitter created with captureRejections: true, so `Symbol(kCapture) should be true
EventEmitter {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  [Symbol(kCapture)]: false
}

```

**Comment by Scared-Heart** [comment]
exactly! I agree that it's a node bug. And i don't know how ```ts-node``` works different too, maybe caused by node.js 'repl' module.

**Comment by CMCDragonkai** [comment]
I can confirm this is a node bug as well. Has anybody created an issue upstream?

**Comment by CMCDragonkai** [comment]
Oh I found it https://github.com/nodejs/node/issues/41391
