### ISSUE TITLE
How to invalidate require.cache?

### ISSUE THREAD

**Issue by mohsen1** [TypeStrong/ts-node#159]
I'm using ts-node to invoke my TypeScript file. Following recommendation by [Webpack hot example](https://github.com/glenjamin/ultimate-hot-reloading-example/blob/master/server.js#L36-L45) I want to invalidate `require.cache` on file changes. 

Is it possible to do this when I started my program with `ts-node`?

**Comment by blakeembrey** [comment]
Yes? It's exactly the same as the link you posted.

**Comment by mohsen1** [comment]
Yup, that works. Thanks!

For the recored, the references to required modules won't change, and they need to get re-required.

Here is what I had:

##### `index.ts`
```ts
declare const require: any;

const chokidar = require('chokidar');
const dynamicModule = require('./dynamic.ts')

setInterval(()=> {
  console.log(`content of dynamic module is: ${dynamicModule}`);
}, 500);

const watcher = chokidar.watch('./dynamic.ts');

watcher.on('ready', () => {
    watcher.on('all', () => {
        Object.keys(require.cache).forEach((id) => {
            console.log('??????', id);
            if (/dynamic\.ts$/.test(id)) {
                console.log('deleting cache for module:', id);
                delete require.cache[id];
            }
        });
    });
});
```

##### `dynamic.ts`
```ts
declare const module: any;

module.exports = 'B';
```

##### `tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "noResolve": true,
    "sourceMap": true,
    "noImplicitAny": true,
    "removeComments": true,
    "experimentalDecorators": true,
    "jsx": "react"
  },
  "exclude": [
    "node_modules"
  ]
}
```

##### `package.json`
```json
{
  "name": "test-ts-node-watch",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "chokidar": "^1.6.0"
  }
}
```

Changing `dynamic.ts` file export string does not change the output in the console. 

But changing the `index.ts` to require the module on each interval call works:

```ts
setInterval(()=> {
  console.log(`content of dynamic module is: ${ require('./dynamic.ts') }`);
}, 500);
```

**Comment by blakeembrey** [comment]
Awesome! Yep, any previous requires won't magically be updated - the dependents would have to be re-parsed to be evaluated with the new content.
