### ISSUE TITLE
receive ERR_UNKNOWN_FILE_EXTENSION in any TS file

### ISSUE THREAD

**Issue by lyrieek** [TypeStrong/ts-node#1592]
### Search Terms
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for ..
I've already seen #1062 

### Expected Behavior

run typescript files

### Actual Behavior

throw ERR_UNKNOWN_FILE_EXTENSION error message

### Steps to reproduce the problem

Run any *.ts file

### Minimal reproduction

``` tsconfig.json
//tsconfig.json
{
	"compilerOptions": {
		"module": "CommonJS"
	}
}
```
``` package.json
//package.json
{
	"name": "test",
	"type": "module"
}
```
``` test.ts
//test.ts
console.log(1)
```
ts-node test.ts
``` output
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for ..\test.ts
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:101:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:31)
    at async Loader.import (internal/modules/esm/loader.js:164:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
```

### Specifications

ts-node -vv
``` output
ts-node v10.4.0
node v14.15.1
compiler v4.5.4
```
I installed it globally

Windows 10, in git-bash

**Comment by cspotcode** [comment]
https://github.com/TypeStrong/ts-node/issues/1062#issuecomment-1000945733

**Comment by lyrieek** [comment]
but I don't want the ESM loader, I just need CommonJS

**Comment by cspotcode** [comment]
The problem is the `package.json` `"type": "module"` says that you want ESM.

**Comment by benjaminParisel** [comment]
I have same problem (with same version of ts-node, node and comiler). I think it's because a dependency used in my project contains the famous line `"type":"module"` in its package.json.
Do you have some tips to avoid this error ?

**Comment by cspotcode** [comment]
https://typestrong.org/ts-node/docs/module-type-overrides

**Comment by benjaminParisel** [comment]
Ty for the link, i resolve my problem. I do a mistake in mocha configuration file.

**Comment by berekmerilorand** [comment]
Receiving unknown file extension ".ts" error after upgrading wdio to 8 and Appium >16.

Detailed description https://github.com/TypeStrong/ts-node/issues/1584#issuecomment-1380397569.
