### ISSUE TITLE
TSError in Linux (but not mac) for things there don't seem right

### ISSUE THREAD

**Issue by iangregsondev** [TypeStrong/ts-node#1594]
### Expected Behavior

A TS file that compiles on a mac should compile on linux too, but ts-node throws errors. I was able to ignore those errors and it works by passing -T parameter but I am confused why I need to do that and is it the correct way or a workaround.

### Actual Behavior

This is what I get on linux, but this should not happen as there is nothing wrong. I have eslint installed and an IDE - the code seems perfect and simple. Mac throws no errors and runs successfully.

```
/home/runner/work/test-nx-deploy/test-nx-deploy/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
Error: tools/docker/deploy.ts(12,24): error TS2339: Property 'repo' does not exist on type '{ [x: string]: unknown; repo: string; tag: any[]; appName: string; file: string; tagWithLatest: boolean; tagWithSemver: boolean; tagWithGitSha: boolean; readme: string; _: (string | number)[]; $0: string; } | Promise<...>'.
  Property 'repo' does not exist on type 'Promise<{ [x: string]: unknown; repo: string; tag: any[]; appName: string; file: string; tagWithLatest: boolean; tagWithSemver: boolean; tagWithGitSha: boolean; readme: string; _: (string | number)[]; $0: string; }>'.
Error: tools/docker/deploy.ts(13,18): error TS2339: Property 'tag' does not exist on type '{ [x: string]: unknown; repo: string; tag: any[]; appName: string; file: string; tagWithLatest: boolean; tagWithSemver: boolean; tagWithGitSha: boolean; readme: string; _: (string | number)[]; $0: string; } | Promise<...>'.
  Property 'tag' does not exist on type 'Promise<{ [x: string]: unknown; repo: string; tag: any[]; appName: string; file: string; tagWithLatest: boolean; tagWithSemver: boolean; tagWithGitSha: boolean; readme: string; _: (string | number)[]; $0: string; }>'.
```

My execution is

```
ts-node --files -P ./tools/docker/tsconfig.json ./tools/docker/deploy.ts
```

tsconfig are correct but I will paste it here

./tools/docker/tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "CommonJS",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node"
  },
  "exclude": ["**/*.spec.ts", "**/*.test.ts"],
  "include": ["**/*.ts"]
}

```

![image](https://user-images.githubusercontent.com/2370364/148969018-77ba70b5-9107-433a-a476-2da4da7ef22c.png)

### Specifications

Here is the mac where there is no error

ts-node v9.1.1
node v16.13.1
compiler v4.4.4

and linux one where the errors happen

ts-node v9.1.1
node v16.13.1
compiler v4.4.4

* ts-node version:
* node version: 16
* TypeScript version:
* tsconfig.json, if you're using one:
```
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "CommonJS",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node"
  },
  "exclude": ["**/*.spec.ts", "**/*.test.ts"],
  "include": ["**/*.ts"]
}
```
* Operating system and version: mac works, linux does not.. Mac is 12.1 and linux is ubuntu latest

**Comment by cspotcode** [comment]
How should someone reproduce this?

I also see that it's running on an old version of ts-node.

**Comment by iangregsondev** [comment]
Hi, can put together a small repo if you like - or thought it might be something obvious or a known issue..

ts-node was installed by a 3rd part app I am using (nrwl nx) - I will install the latest and come back later..

Thank you

**Comment by iangregsondev** [comment]
I updated to the latest version and still the same. Its ironic because thinking about it, i want to run it without transcompiling, which already works.

I am going to close this as it appears to only be a ME problem :-) And considering I am not transcompiling anymore - this is no longer a problem, only when I transcompile. 

I do all my syntax checking in my IDE anywhere and on the mac while testing it works perfect.

Thanks for coming back to me anyway.
