### ISSUE TITLE
tsconfig.paths not working with ES modules

### ISSUE THREAD

**Issue by eng-dibo** [TypeStrong/ts-node#1596]
I switched my project to enable ES modules

- added `type: module` in package.json
- use `node --loader ts-node/esm` instead of `ts-node`
- changed `module: commonjs` to `esnext`

it works fine, except when starting using paths aliases.

so, ` import test from './file';` works, but  `import test from '@app/file';` doesn't

[minimal reproduction](https://stackblitz.com/edit/node-wlm8vs?file=index.ts)

**Comment by cspotcode** [comment]
Related:
[#1452](https://github.com/TypeStrong/ts-node/issues/1452#issuecomment-917572328)
#1375
#1585 

Closing as answered and tracked by other issues

**Comment by eng-dibo** [comment]
related: https://github.com/dividab/tsconfig-paths/issues/122
