### ISSUE TITLE
Add common ESM errors to Troubleshooting page

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1607]
There are a few errors thrown by node -- and by our copy-pasted node code -- that confuse users.  Add these to the troubleshooting page.

For example, when you try to `require()` a TS file and it's supposed to be executed as native ESM, the user gets a cryptic `ERR_REQUIRE_ESM`.  When they try to do the same via `import()` instead of `require()` -- or `node ./index.ts` inside a `type: module` directory -- they get `ERR_UNKNOWN_FILE_EXTENSION`

**Comment by simonbuchan** [comment]
Note the `ERR_UNKNOWN_FILE_EXTENSION` also happens with extensionless files, like `require.resolve("mocha/bin/mocha")` (which breaks `ts-mocha` at the moment).

**Comment by cspotcode** [comment]
Linking to https://github.com/nodejs/node/discussions/41711 where the solution is being discussed.  Once a solution is settled upon, ts-node can implement a workaround to mimic the fixed behavior on old node versions.
