### ISSUE TITLE
Compile error when using `should` in `mocha`

### ISSUE THREAD

**Issue by janslow** [TypeStrong/ts-node#161]
Often, when I run `mocha` using `ts-node` (using `mocha --compilers 'ts:ts-node/register' -r should ./src/tests/filings/filing-summary.ui.ts`), I get the following compile error:

```
/usr/local/lib/node_modules/ts-node/src/index.ts:258
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
src/tests/filings/filing-summary.ui.ts (16,15): Property 'should' does not exist on type 'Filing[]'. (2339)
```

This error is not raised when I run the TS compiler directly via the CLI or from within Sublime Text.

The line causing the error is:

``` ts
      const filings: Filing[] = await createFilingApi(driver).getFilings({ pageSize: 1 });
      filings.should.have.length(1);
```

I do have the correct definition for `should` installed (`registry:dt/should#8.1.1+20160608082854` via `typings`).

Once it occurs, the only way I can fix the error is by running the following command (note the lack of `-r should`), at which point compilation works but the tests fail (as `Object.should` isn't loaded), but I can then run the original command again and everything works fine.

I've tried disabling the ts-node cache by setting `TS_NODE_CACHE=false` and also explicitly calling `require('ts-node').register({ cache: false })` instead of using `ts-node/register`, but it doesn't solve the problem. Neither does explicitly importing `should` using `import 'should'` or `import * as should from 'should'`

```
// Version details
node@6.2.2
ts-node@1.2.1
mocha@2.5.3
typescript@1.8.10
should@10.0.0
```

**Comment by blakeembrey** [comment]
Can you please create a production that someone can debug? I'm not sure how a runtime feature flag (`-r`) could affect compile-time, perhaps there's a different issue?

**Comment by janslow** [comment]
I'll try, but I've had trouble reproducing it on demand in my current setup, so I haven't been able to create a minimal example.

The main reason I filed this issue is in the hope that someone else has had a similar problem, as I've had this problem for several weeks and the only thing that I know confidently is that the issue only occurs when using `ts-node`.

**Comment by seansfkelley** [comment]
I'm seeing this exact issue. Clone [this project at branch `ts-node`](https://github.com/palantir/react-layered-chart/tree/ts-node) and run `npm install && ./node_modules/.bin/tsd install && npm test`:

```
> npm test

> react-layered-chart@1.6.0 test /Volumes/git/react-layered-chart
> mocha 'test/**/*.ts'


/Volumes/git/react-layered-chart/node_modules/ts-node/dist/index.js:159
                    throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset));
                    ^
TSError: ⨯ Unable to compile TypeScript
test/CanvasContextSpy-test.ts (20,20): Property 'should' does not exist on type 'PropertySet[]'. (2339)
test/CanvasContextSpy-test.ts (28,15): Property 'should' does not exist on type 'MethodCall[]'. (2339)
test/CanvasContextSpy-test.ts (36,20): Property 'should' does not exist on type '(PropertySet | MethodCall)[]'. (2339)
test/CanvasContextSpy-test.ts (47,20): Property 'should' does not exist on type 'PropertySet[]'. (2339)
test/CanvasContextSpy-test.ts (56,15): Property 'should' does not exist on type 'MethodCall[]'. (2339)
test/CanvasContextSpy-test.ts (65,28): Property 'should' does not exist on type 'MethodCall[]'. (2339)
test/CanvasContextSpy-test.ts (73,28): Property 'should' does not exist on type 'MethodCall[]'. (2339)
npm ERR! Test failed.  See above for more details.
```

I see the exact same symptoms described above, including that it _does_ work through `tsc` and none of my IDEs complain about the same problems.

**Comment by janslow** [comment]
I stopped getting this problem (without being able to reproduce it) a while ago, but I've no idea why, so I'm afraid I can't really help.

**Comment by seansfkelley** [comment]
It appears to be specifically related to `should`. I [switched to using `chai`](https://github.com/palantir/react-layered-chart/tree/ts-node-chai) to work around this issue, and it works great.

**Comment by janslow** [comment]
I am now using `typescript@2.0.3` and `@types` instead of `typings`, which may have made a difference

**Comment by blakeembrey** [comment]
Closing this now as it seems like to be some sort of type loading issue.
