### ISSUE TITLE
works extremely slow when adding/removing files on windows 

### ISSUE THREAD

**Issue by pleerock** [TypeStrong/ts-node#163]
We have a 100k lines project and more then 1000 ts files. Once everything compiled it runs in 6-8 seconds on windows machines and 3-4 seconds on mac. Both with ssd and i7 processors with 8gb RAM. On first compile it runs ~10 minutes on windows, and pretty quick on mac (10 seconds). After any file being added or removed it runs again quickly on mac, and on windows it take ~7-8 minutes

**Comment by blakeembrey** [comment]
You should probably log the issue on TypeScript. I think someone has brought this up before (see https://github.com/TypeStrong/ts-node/issues/137#issuecomment-231557287).

**Comment by blakeembrey** [comment]
Actually, it might be different. Can you please provide more information? What do you mean when you say "everything compiled"? What version is Windows running vs Mac? What flags are you using? What does it mean when you say "any file added or removed"?

**Comment by pleerock** [comment]
mac os x el capitan
windows 10

* "everything compiled" I mean when you install ts-node and do `ts-node app.js` for the first time.
* once app is run, if you stop it and run once again - it runs fast - only in 10 seconds. 
* if you stop app again, change any file and run again - it runs ~12 seconds
* if you add a new file, or remove any file - it runs slow again - few minutes

I don't use any flags. However if I use `-F` flag, it works fast. But site is not working (I guess it cuts out some reflected type information? - not sure). I tried all other flags - neither help

**Comment by blakeembrey** [comment]
Thanks. Unless you're willing to debug, I'd suggest opening an issue on TypeScript. There's no way, that I can understand, that this would be a bug in `ts-node`. The TypeScript team would probably be able to provide more help also, since I do not work on a Windows machine myself.

**Comment by blakeembrey** [comment]
I'd also link any issue you create back to this issue. As for why the `--fast` flag causes issues for you, I couldn't say - it seems odd since it should be the same emitted code. Perhaps that's another issue to bring up with TypeScript if you manage to reproduce it minimally.

**Comment by pleerock** [comment]
but how it can be a typescript issue if when I use tsc I dont have such problems. It compiles fast and without problems. Same, for example, if I use gulp-typescript - I don't have any problems

**Comment by blakeembrey** [comment]
Are you using the same version of TypeScript? The module is quite small, you are welcome to try and debug the cause in `ts-node`, but I don't see anywhere it can be caused. You said you tried "all the flags", so I can only assume it's an issue with TypeScript. Did you try disabling the cache? You are also the first person to report any issue here, and there's no way for me to reproduce it provided. You are welcome to share a reproductive use-case.

**Comment by pleerock** [comment]
> Are you using the same version of TypeScript?

yes

> You said you tried "all the flags"

all yours flags, like -F, ---cache-dir, etc.

> Did you try disabling the cache?

do you mean with -F option? If yes, then yes I tried it and as I said it works fast, but with runtime errors, which are not reproduced when using tsc (without ts-node)

Did you check this tool on a big projects on windows? sometimes windows file system is problematic for some specific use cases, maybe any of them used and this is causing an issue?

btw if you have a time and interest in this issue I can make a call and show you a behaviour on my machine

**Comment by blakeembrey** [comment]
It's `--no-cache` and `--cache-directory`, you can see it in https://github.com/TypeStrong/ts-node#configuration-options. No, as I mentioned I do not use Windows, and it's probable none of my projects are even the size of yours. I won't have any immediate time, I'll leave this open in case someone else can debug.

**Comment by pleerock** [comment]
> It's --no-cache and --cache-directory, you can see it in https://github.com/TypeStrong/ts-node#configuration-options.

yeah, sure, I used them just as in docs, I simply wrote you without looking docs, sorry about that.

okay, I'll try to debug in a free time and if I get something new, I'll let you know

**Comment by blakeembrey** [comment]
Thank you 😄

**Comment by pleerock** [comment]
after investigating it a bit more, I found a pace where everything goes slow. [Here is](https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L245):

```typescript
const output = service.getEmitOutput(fileName)
```

When I go deeper into typescript compiler the problem is in this line:

```typescript
synchronizeHostData();
```

In a `synchronizeHostData` method of the typescript compiler the problem is in this line:

```typescript
newProgram = ts.createProgram(hostCache.getRootFileNames(), newSettings, compilerHost, program);
```
btw `hostCache.getRootFileNames()` returns array of ts files of the project, 500 ts files

In a `createProgram` function problem is in `processRootFile` function call:

```typescript
if (!tryReuseStructureFromOldProgram()) {
            ts.forEach(rootNames, function (name) { return processRootFile(name, /*isDefaultLib*/ false); });
```
btw `rootNames` is the same array of ts files of the project, 500 ts files

`processRootFile` function processes each file. it takes a few milliseconds to proceed each file, but since there are lot of files (500) items it takes him a few seconds to complete.

And since `getEmitOutput` is called for each file (500 files), processRootFile is called 500 times, and there it proceeds 500 files. so we have 500 * 500 = 250000 times processRootFile is being called.


Since I don't have any problems with tsc compiler, I guess it still ts-node issue. I can only guess maybe ts-node uses typescript compiler apis inefficiently and this is lead to this slownest?

**Comment by blakeembrey** [comment]
That's the standard way to use the TypeScript compiler. You can read about it in https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API, I've been using it since I started working with TypeScript. Have you checked out `tryReuseStructureFromOldProgram`? Perhaps there's something going wrong in there when using Windows that's not occurring on other platforms?

I'm guessing the reason you aren't seeing this with the `tsc` compiler is because you only ever emit things once. If you're only emitting it once, there's not a case where you need to re-use the old program. Since `ts-node` can receive any out-of-band require and cache reloads, it's not feasible to only compile everything just once.

I'm going to ping some people from the TypeScript team who will likely be able to provide a lot more help than I can.

/cc @weswigham @mhegazy

**Comment by mhegazy** [comment]
the multiple calls to createProgram indicates that the API believes something has changed between the calls to `getEmitOuptut`,  and thus needs to recreate a new program, and walk the references each time. 
I could be caused by version mismatch or file path mismatch between the API and ts-node host. i can look more if you can provide a repro i can debug and understand the reason of this behaviour.
