### ISSUE TITLE
`moduleType` is not actually a valid config field (unlike `moduleTypes`)

### ISSUE THREAD

**Issue by dPowNextdoor** [TypeStrong/ts-node#1630]
## Summary

In the website, ReadMe, and other docs, it says [`moduleType`: Override the module type of certain files, ignoring the package.json "type" field. See "Module type overrides" for details.](https://github.com/TypeStrong/ts-node/blob/db6f850eff15e30b985767c60f786f3da6b22af5/website/docs/options.md?plain=1#L57). However `moduleType` is an [internal](https://github.com/TypeStrong/ts-node/pull/1371/files#diff-6149369fc9ec5883f1bce9df118fe4f956d36f894b4e12dedac18fa59d36e53cR23-R24)-[only](https://github.com/TypeStrong/ts-node/pull/1371/files#diff-12fd75b6663a778841dbf7601ba19de808d7c703757d7ccf039d5afd3770fb54R11-R22) field, not to be used by the tsconfig.json's `ts-node` field.

### Expected Behavior

Any field listed in the website, ReadMe, etc. to be usable.

### Actual Behavior

This field (to my knowledge, please correct me if I'm wrong) doesn't do anything. `moduleTypes` (emphasis on the trailing `s`) does.

### Steps to reproduce the problem

Look through the source code linked above.

Alternatively, don't set `type: module` in package.json, import some CJS file into your TS file, and then change the tsconfig.json given below from

```javascript
// no errors
"moduleType": "esm",
"moduleTypes": {
    "**/*.mjs": "esm",
    "**/*.cjs": "cjs"
}
```

to

```javascript
// lots of errors
"moduleTypes": {
    "**/*.js": "esm",
    "**/*.mjs": "esm",
    "**/*.cjs": "cjs"
}
```

and watch `ts-node` collapse.

### Specifications

* ts-node version: v10.4.0 (latest)
* node version: v16.13.2
* TypeScript version: v4.6.0-dev.20220204 (though tested on 4.5.4 and 4.5.5 as well)
* tsconfig.json, if you're using one:
```json
{
    "compilerOptions": {
        "target": "ESNext",
        "lib": [
            "ESNext",
            "DOM",
            "DOM.Iterable"
        ],
        "module": "ESNext",
        "moduleResolution": "node",
        "strict": true,
        "jsx": "react-jsx",
        "allowJs": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "resolveJsonModule": true,
        "forceConsistentCasingInFileNames": true,
        "newLine": "lf",
        "preserveSymlinks": false,
        "incremental": true,
        "isolatedModules": true,
        "outDir": "dist",
        "declaration": true,
        "declarationDir": "dist/types",
        "baseUrl": ".",
        "paths": {
            "@/*": [ "src/*" ],
            "/*": [ "*" ]
        }
    },
    "include": [
        "./src/**/*"
    ],
    "exclude": [
        "./node_modules",
        "dist"
    ],



    "ts-node": {
        "require": [
            "tsconfig-paths/register"
        ],
        "preferTsExts": true,
        "experimentalReplAwait": true,
        "transpileOnly": true,
        "moduleType": "esm", // Field in question
        "moduleTypes": {
            "**/*.mjs": "esm",
            "**/*.cjs": "cjs"
        },
        "compilerOptions": {
            "module": "nodenext",
            "isolatedModules": false
        },
        "include": [
            "./**/*"
        ]
    }
}
```
* Operating system and version: Mac (Big Sur 11.6.1), Linux (Mint Uma)

## Related

Maybe this is part of the [experimental phase of `ts-node`](https://github.com/TypeStrong/ts-node/issues/1007), but I had assumed `moduleType: "esm"` would feign setting `type: module` in package.json, but clearly it does not. In fact, it doesn't appear to do anything.

## Suggested Fix

Either fix (what I assume to be) the typo in the docs, or (preferably) make `moduleType` do as it currently says it does and override `type` in package.json.

**Comment by cspotcode** [comment]
Is this a typo, a missing "s"?

**Comment by cspotcode** [comment]
Fixed by #1633 

The docs on this page are correct: https://typestrong.org/ts-node/docs/module-type-overrides

See also: #1007 which explains the best way to take advantage of our native ESM support.

**Comment by dPowNextdoor** [comment]
Thanks @cspotcode! I know this was very minor, but I went down a rabbit hole, confused why `moduleType` wasn't working. I appreciate the fix (and how quickly it was made)!

**Comment by cspotcode** [comment]
The valid options are also described in the official schema.  Some editors can pick this up and assist you.

https://www.schemastore.org/json/

![image](https://user-images.githubusercontent.com/376504/152859660-6ac3a798-8aeb-40de-b730-6fa48fda419a.png)
