### ISSUE TITLE
node with--loader ts-node/esm does not respect 'main' in 'package.json' and 'path' in 'tsconfig.json'

### ISSUE THREAD

**Issue by phatNfqAsia** [TypeStrong/ts-node#1653]
### Search Terms
yarn workspace
cross-package import
module resolve bug

### Expected Behavior
node should resolve packages successfully, like VSC does
e.g: path "packages/api-derive/src/packageInfo.ts"
![vsc know](https://user-images.githubusercontent.com/39822773/154929262-f3f70760-2483-41fd-b31f-e471386e07a0.jpg)

### Actual Behavior
Node find package in path "node_modules/@polkadot/api-derive/packageInfo" and throw error
![image](https://user-images.githubusercontent.com/39822773/154929585-25d08032-0756-4532-9fb8-291bfa5a82b4.png)

```
CustomError: Cannot find module '.../api/node_modules/@polkadot/api-derive/packageInfo' imported from '.../api/packages/api/src/detectOther.ts'
```

### Steps to reproduce the problem
Long story short: I set up the main in package.json 
```diff
{
+ main: "src/index.ts"
}
```
and path in tsconfig.json 
```
"paths": {
      "@polkadot/api": ["api/src"],
      "@polkadot/api/*": ["api/src/*"],
...
    },
```
properly so that VSC can resolve my package reference. But when I run command 
```shell
cd packages/troubleshoot
# node --loader ts-node/esm --experimental-specifier-resolution=node src/index.ts
yarn dev-2 src/index.ts 
```
It can not resolve the package which I have specified with all the flag needed 

### Minimal reproduction
follow my above steps with this:
https://github.com/coolcorexix/api/tree/investigate-4559 

### Specifications
* ts-node version: 10.5.0
* node version: v14.17.4
* TypeScript version: 4.5.5
* tsconfig.json, if you're using one: Please check out in the code provided 

* Operating system and version: Ubuntu 20.4

**Comment by cspotcode** [comment]
Are you hitting this?  https://typestrong.org/ts-node/docs/paths

**Comment by phatNfqAsia** [comment]
> 

Yes I already done this, but the nothing change

**Comment by cspotcode** [comment]
`tsconfig-paths` has not implemented support for the ESM loader, so if you're trying to use tsconfig-paths with `--loader ts-node/esm`, it will not work.  See https://github.com/TypeStrong/ts-node/discussions/1450
