### ISSUE TITLE
Use pirates to manage hook registration

### ISSUE THREAD

**Issue by graingert** [TypeStrong/ts-node#166]

**Comment by graingert** [comment]
https://www.npmjs.com/package/pirates it makes things easy and handles some conflicts and edge cases for you

**Comment by blakeembrey** [comment]
Any idea why this would help `ts-node`? Pirates seems to override `_compile`, but I don't need that at all.

**Comment by blakeembrey** [comment]
Closing as unanswered.

**Comment by graingert** [comment]
This would be used in
```js
require('ts-node').register({ /* options */ })

// Or using the shortcut file.
require('ts-node/register')
```

**Comment by graingert** [comment]
This code could be simplified https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L297

This would also allow Typescript to emit ES6, and have babel/babel-plugin-modern-node take it the rest of the way

**Comment by blakeembrey** [comment]
Can you give an example of how it can help? I've looked through the pirates project multiple times and couldn't see how it would help me.

**Comment by graingert** [comment]
@blakeembrey https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L290 you do use "._compile"

**Comment by graingert** [comment]
just replace all of:

https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L289-L309

with
```js 
// Now you can just do this!: 
var revert = pirates.addHook(function hook(code, filename) {
  return service().compile(fileName);
}, { exts: ['.ts', '.tsx'] });
```

**Comment by blakeembrey** [comment]
What about https://github.com/babel/babel/pull/3609#issuecomment-236307505?

**Comment by blakeembrey** [comment]
What about the custom ignore logic also?

**Comment by graingert** [comment]
your custom ignore logic, just ignores node_modules.

**Comment by blakeembrey** [comment]
Currently, yes. But you can see there's existing open issues to change that.

**Comment by graingert** [comment]
you can rename shouldIgnore to matcher

**Comment by blakeembrey** [comment]
Hmm, ok. And I'm guessing the filesystem reading is now going to be handled by node somewhere? I can't really see in the codebase where the file is read from the filesystem to be able to compile it. If that's true, I can try and refactor this project because otherwise reading from the filesystem multiple times is largely inefficient (which is what your would do, it'd be reading twice right?)

**Comment by graingert** [comment]
ah yes, you're correct you can't read from the filesystem otherwise you'll get stale code from your parent hook.

**Comment by blakeembrey** [comment]
Do you have any comment on it being deprecated though? I'm going to re-open to revisit the loading logic, no guarantee I'd use `pirates` though (it's low usage and deprecation is a little concerning).

**Comment by graingert** [comment]
@ariporad @blakeembrey It's not deprecated yet...
