### ISSUE TITLE
[Node 17.5.0] JSON support in ESM no longer requires --experimental-json-modules

### ISSUE THREAD

**Issue by Jamesernator** [TypeStrong/ts-node#1661]
### Search Terms

json, json modules, esm, experimental-json-modules

### Expected Behavior

To be able to import json modules without the `--experimental-json-modules` flag in `ts-node/esm`.

As of Node 17.5.0 the flag is no longer required, it just prints a usual experimental warning.

### Actual Behavior

Currently `ts-node/esm` loader only allows JSON modules if `--experimental-json-modules` is passed to the Node executable. If this option is not passed it fails with an error despite Node no longer requiring the flag.

### Steps to reproduce the problem

Import a json module and use `node --loader ts-node/esm ./jsWithJsonImport.js`.

The exact line that checks the condition is [here](https://github.com/TypeStrong/ts-node/blob/main/dist-raw/node-esm-default-get-format.js#L57). Simply removing the conditional would make the behaviour be consistent with node.

### Specifications

```txt
ts-node v10.5.0
node v17.5.0
compiler v4.5.5
```

```json
{
  "include": [
    "**/*.ts",
    "**/*.json"
  ],
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "sourceMap": true,
    "downlevelIteration": true,
    "composite": true,

    "strict": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noEmit": true,

    "allowSyntheticDefaultImports": true,
    "useDefineForClassFields": true,
    "importsNotUsedAsValues": "error",
    "noUncheckedIndexedAccess": true
  },
  "ts-node": {
    "transpileOnly": true
  }
}
```

**Comment by cspotcode** [comment]
Sounds like a straightforward change, can you send us pull request?  The next version is going to be published soon, we can include it.

Might be best to keep the conditional check on versions of node earlier than 17.5.0, so that we're consistent with whatever node version you're running.

**Comment by cspotcode** [comment]
I've scheduled the 10.6.0 release for next Wednesday.  If you're able to prepare a PR by then, we can include it in the release.

**Comment by cspotcode** [comment]
@Jamesernator is this something you can send a PR for?  We can include it in 10.6.0 which I'd like to release tomorrow.  My time is occupied by other tickets.

**Comment by Jamesernator** [comment]
> @Jamesernator is this something you can send a PR for? We can include it in 10.6.0 which I'd like to release tomorrow. My time is occupied by other tickets.

I've made the change on a fork, I just need to add a couple tests which I'll do sometime today.
