### ISSUE TITLE
Error with global variable that be declared

### ISSUE THREAD

**Issue by suzuki11109** [TypeStrong/ts-node#167]
In my code I use Twilio client library which provides a global variable named Twilio.
I've declare type at the top of the file like this.
```
declare var Twilio: any;
```
I got error ```Twilio is not defined``` when running mocha with ts-node.
It's like it did not see the declaration.
But this's not happened with typescript loader compiling. The code and the application is working perfectly fine.

Thanks 😃

**Comment by blakeembrey** [comment]
You mean "ReferenceError: Twilio is not defined"? That's a JavaScript error, you actually need to put Twilio in your code for it to work. Just because you told the compiler it's there, doesn't mean it exists at runtime.

**Comment by suzuki11109** [comment]
Yes, I mean "ReferenceError: Twilio is not defined".
Yes, I was thinking about that too. 
It's fixed now. 
Thanks.
So I'll close this issue.
