### ISSUE TITLE
ESM support fails with symlinks

### ISSUE THREAD

**Issue by tkrotoff** [TypeStrong/ts-node#1671]
ESM support enabled does not work with symlinks.

### Reproduction

The directory contains a symlink + source code imports it:

```
common/getErrorMessage.ts

back/common => symlink to parent common/ directory
back/server.ts (contains import ... from './common/getErrorMessage')
back/package.json
back/...

front/package.json
front/...
```

It works with `ts-node`, not with `ts-node/esm`:

```
% cd back
% node --loader=ts-node/esm --experimental-specifier-resolution=node server.ts
...

import { getErrorMessage } from './common/getErrorMessage';
         ^^^^^^^^^^^^^^^
SyntaxError: Named export 'getErrorMessage' not found. The requested module './common/getErrorMessage' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from './common/getErrorMessage';
const { getErrorMessage } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:179:5)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)
```

(Of course the suggestion does not work because common/getErrorMessage has no default export)

If instead of using a symlink I copy-paste common directory, everything works fine with `ts-node/esm`.

### Specifications

- ts-node v10.6.0
- node v16.10.0, v16.14.0, v17.6.0
- TypeScript v4.5.2
- macOS 11.6

- tsconfig.json:
```
{
  "compilerOptions": {
    "noEmit": true,
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "isolatedModules": true,

    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

**Comment by cspotcode** [comment]
You might be hitting an issue with node' static analysis of CommonJS files.

```
The requested module '...' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

https://nodejs.org/dist/latest-v17.x/docs/api/esm.html#import-statements

> When importing [CommonJS modules](https://nodejs.org/dist/latest-v17.x/docs/api/esm.html#commonjs-namespaces), the module.exports object is provided as the default export. Named exports may be available, provided by static analysis as a convenience for better ecosystem compatibility.

I would test against the latest node version to see if behavior is different.

**Comment by tkrotoff** [comment]
I've tried with the latest LTS (16.14.0), same problem as with 16.10.0 :-/

**Comment by cspotcode** [comment]
Next thing to check is your package.json files.  As you probably know, in node, the `type` field affects how files are treated by node.

**Comment by tkrotoff** [comment]
Obviously package.json contains `"type": "module"` otherwise 

> If instead of using a symlink I copy-paste common directory, everything works fine with `ts-node/esm`

wouldn't work

**Comment by tkrotoff** [comment]
Great!
I've created a PR that "fixes" your branch and reproduces the error: https://github.com/TypeStrong/ts-node-repros/pull/24/commits

**Comment by cspotcode** [comment]
That's what I suspected: you didn't tell us where your package.json is located.  Remember that we follow node's rules for package.json "type", and we also follow node's rules for following symlinks.  This will affect how your files are executed.  .ts files follow the same rules as .js as it pertains to package.json "type"
