### ISSUE TITLE
Compilation error with mocha and TypeScript 2.0 on Windows 10

### ISSUE THREAD

**Issue by ospatil** [TypeStrong/ts-node#168]
I'm trying to run mocha tests using `--compilers ts:ts-node/register` with **TypeScript 2.0** but get the following error only on Windows (10) while it works flawlessly on a Mac - 

``` sh
C:\temp\nodets\node_modules\ts-node\src\index.ts:259
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
test\greeter-spec.ts (6,1): Cannot find name 'describe'. (2304)
test\greeter-spec.ts (7,3): Cannot find name 'it'. (2304)
    at getOutput (C:\temp\nodets\node_modules\ts-node\src\index.ts:259:17)
    at C:\temp\nodets\node_modules\ts-node\src\index.ts:268:16
    at Object.compile (C:\temp\nodets\node_modules\ts-node\src\index.ts:404:17)
    at loader (C:\temp\nodets\node_modules\ts-node\src\index.ts:290:33)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\temp\nodets\node_modules\ts-node\src\index.ts:307:14)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at C:\temp\nodets\node_modules\mocha\lib\mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\temp\nodets\node_modules\mocha\lib\mocha.js:217:14)
    at Mocha.run (C:\temp\nodets\node_modules\mocha\lib\mocha.js:485:10)
    at Object.<anonymous> (C:\temp\nodets\node_modules\mocha\bin\_mocha:405:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
npm ERR! Test failed.  See above for more details.
```

You can replicate the issue using the following steps -

``` sh
git clone https://github.com/ospatil/tsnode-issue.git
cd tsnode-issue
npm install
npm test
```

I managed to get it working on Windows by adding a triple slash reference to mocha type definition `/// <reference path="../node_modules/@types/mocha/index.d.ts" />` to `test/greeter-spec.ts` but it seems redundant since it works flawlessly without it on Mac.

**Comment by andregs** [comment]
Same issue here, and the triple slash workaround also worked for me.

**Comment by ecozoic** [comment]
Same issue here (although it's occurring w/ @types/protractor and not mocha), on Windows with ts-node@1.4.3. The triple-slash fix worked for me.

**Comment by Jontem** [comment]
You can also add the compilerOptions property `"types": ["mocha"]`.

**Comment by erik-sn** [comment]
Same issue on Ubuntu - triple slash also fixed it for me.

**Comment by budiadiono** [comment]
Giving `"types": [ "node", "mocha", "chai" ]` under `compilerOptions` on `tsconfig.json` solve the issue.

**Comment by jamelt** [comment]
@budiadiono Can you elaborate? I added that to my `tsconfig.json` to no avail.

Also is there anyway this can be addressed without having to main a separate list of typings? This is a rather broken approach, in my opinion.

**Comment by budiadiono** [comment]
@jamelt, maybe you forgot to install `@types/[module]` for requested types? Thus you have to do `"include": [ "**/*.ts" ]` that makes `typescript` look for the scripts in entire location.

**Comment by mortterna** [comment]
I had similar issue of ts-node on windows not finding protractor types under node_modules/@types without explicit "include": [ "**/*.ts" ] configuration while in osx everything seemed to work without it.

**Comment by hans-permana** [comment]
> Giving "types": [ "node", "mocha", "chai" ] under compilerOptions on tsconfig.json solve the issue.

this works for me.

**Comment by jjcamp** [comment]
`import "mocha";` works for me.

This doesn't work so well for node library types though (would have to add each individually), and adding node to types in compilerOptions causes conflicts in ts-node if another module also uses node typings.

`/// <reference>` seems to be the best option in that case, but this seems to be indicative of a larger problem which only happens in ts-node and not the typescript compiler.

**Comment by blakeembrey** [comment]
Closing in favour of https://github.com/TypeStrong/ts-node/issues/216. It looks like all the issues stem from Windows and I'd guess it's a path issue with TypeScript (they do some odd escaping and expect inputs escaped in certain ways - possibly it's a related issue to this).

If you're working around it, use `tsconfig.json` _or_ `<reference types>`. **Do not** use an `import` as it will emit a runtime require statement, which is why you can't use it for global declarations.

**Comment by wrumsby** [comment]
I was running into a very similar problem, ensuring `typeRoots` was defined and correct in my `tsconfig.json` solved the issue for me, e.g.

```bash
yarn add -D @types/mocha
```

```json
{
   "types": [
     "mocha"
  ],
  "typeRoots": [
    "./node_modules/@types"
  ]
}
```

**Comment by forman** [comment]
@wrumsby, thanks, that worked for me as well!

**Comment by bertolo1988** [comment]
The only thing that worked for me in Ubuntun 17.04 was:

`npm install --save-dev @types/mocha`

and adding this to tsconfig.json

```
{
   "types": [
     "mocha"
  ],
  "typeRoots": [
    "./node_modules/@types"
  ]
}
```
