### ISSUE TITLE
Restrict peer-dependency version of TypeScript

### ISSUE THREAD

**Issue by hediet** [TypeStrong/ts-node#1684]
To reduce chances of unrelated [breaking changes in TypeScript](https://github.com/microsoft/monaco-editor/pull/3001#issuecomment-1057179258), I suggest that ts-node has a more restrictive peer-dependency constraint on TypeScript.

Currently, it is just `>= 2.7`:
https://github.com/TypeStrong/ts-node/blob/f5b6e2d141f9871a276039e8dc19ee96982d814a/package.json#L150

However, I think it is better to explicitly list all major versions:
`"typescript": "^2.7 || ^3.0 || ^4.0"`

@andrewbranch

Again, thanks for creating & maintaining this tool! It allowed us to migrate some ugly untyped JS build scripts to nicely typed TypeScript build scripts :)

**Comment by andrewbranch** [comment]
Since TypeScript doesn’t follow SemVer, I don’t think such a scheme buys ts-node users anything.

**Comment by andrewbranch** [comment]
I believe the breaking API change in TS did not ship in 4.6, so currently only nightly users have been affected, but that change will ship in 4.7 in a few months.
