### ISSUE TITLE
Esm loader public API not working

### ISSUE THREAD

**Issue by philkunz** [TypeStrong/ts-node#1688]
### Search Terms
createEsmHooks()

### Expected Behavior

I have the following code in a project with type=module

```typescript
import * as tsNode from 'ts-node';
import { CompilerOptions } from 'typescript';

const defaultTsNodeOptions: tsNode.CreateOptions = {
  compilerOptions: {
    lib: ['dom'],
    target: <any>'es2020',
    experimentalDecorators: true,
    esModuleInterop: true,
    strictNullChecks: false,
    moduleResolution: <any>'node12',
    module: <any>'ESNext',
    importsNotUsedAsValues: <any>'preserve',
  } as CompilerOptions,
  skipIgnore: true
};

const esmHooks = tsNode.createEsmHooks(tsNode.register(defaultTsNodeOptions));
```

My understanding is that this should cause subsequent import() calls like ('myfile.ts', or 'myfile.js') to work.

### Actual Behavior
.ts is not recognised and .js is not found when only .ts file is present

**Comment by philkunz** [comment]
ah ok, I understand that this creates a loader api for nodejs. How do I register it, without using the --loader option of the node cli?

**Comment by cspotcode** [comment]
See node's documentation for the requirements around loaders.  You'll be surprised to find that node is limited in this way; it forces the use of `--loader`.
