### ISSUE TITLE
--transpileOnly wrong behavior(?) when importing enum

### ISSUE THREAD

**Issue by micalevisk** [TypeStrong/ts-node#1689]
### Search Terms

transpileOnly 

### Expected Behavior

When you run with [`--transpileOnly`](https://typestrong.org/ts-node/docs/options/#transpileonly), the  
`import { X } from 'x'`  
must behave the same as  
`import * as X from 'x'`  
when running without the `-T` flag -- and using the `allowSyntheticDefaultImports`

### Actual Behavior

Using [this package](https://github.com/sambrmg/mysql-error-codes) which exports an enum like:

```ts
import { MysqlErrorCodes } from 'mysql-error-codes'
console.log(MysqlErrorCodes.ER_DUP_ENTRY) // this is undefined only with -T flag
```

I'm getting `undefined` when the transpile only flag is turned on

### Minimal reproduction

See https://github.com/TypeStrong/ts-node-repros/runs/5519081953?check_suite_focus=true

### Specifications

* ts-node version: v10.7.0
* node version: v16.13.0
* TypeScript version: 4.6.2
* Operating system and version: Ubuntu

**Comment by cspotcode** [comment]
Could be a preserveConstEnums issue?  isolatedModules will allow tsc to
flag that kind of problem.

**Comment by micalevisk** [comment]
I guess? the package I've tested has used that `preserveConstEnums` flag when compiling their code

What I didn't understand here is why I'm getting this behavior only when the 'transpile only' feature is enabled. Do you think this is expected?

---

Running without `-T` but with `isolatedModules` enable I got this TS error:

```
TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.
```

**Comment by cspotcode** [comment]
It's expected, yes.  The Typescript website has documentation for the
--isolatedModules flag which should explain this.
