### ISSUE TITLE
Replace language services with program usage

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/ts-node#17]
The REPL would still need to use the language services API (to use `.type`, for example), but the execution environment can avoid it. It should be possible to create a program with the compiler options and write all the files into a tmp directory (or into memory?). When reading again (from node, this time) we check the modtime in the tmp directory vs the current file and either read from cache or re-compile using TypeScript and output diagnostics.

What's the downsides of either approach?

From #16.

**Comment by atrauzzi** [comment]
Where did this idea ever end up going?

**Comment by blakeembrey** [comment]
Not sure, I don't think I ever fully investigated because there wasn't really any defined benefit and others brought to my attention that it would be unnecessary. If you'd like to see it, I'd love to know why!

**Comment by atrauzzi** [comment]
✏️️ Sure! I've been looking into comparisons of runtime interpreted languages with bytecode caches to compiled and JIT'ed languages.  Best example there would be PHP vs C#.  I landed here because I wanted to see if there's any way to have TypeScript adopt the convenient _"reload on change"_ aspect of PHP, but without the overhead of having to rebuild everything, only the parts that changed.

If that were to become something it could do, TypeScript would have a really neat edge by combining the fast dev/preview cycles of PHP with the strong typing of C#.

**Comment by blakeembrey** [comment]
That should already be possible today. It would keep the compilation in memory and use the TypeScript service to refresh only the files changed. There's also a `ts-node` cache that would be re-used if the compilation input hasn't changed. There's likely some minor improvements that _could_ be made, but at that point if what you really want is performance you'd be better off using the `-F` flag for transpiling only and using your editor for the compilation errors (personally that's how I tend to work - `tsc -w` with something like `onchange` reloading the server each edit).

**Comment by atrauzzi** [comment]
I'm thinking it would be nice to have both.  So I'd like to be able to compile for production scenarios, but during development, have it all running hot as I'm editing.

Some of this is dependent on the process model in effect for the project.  So for this next question, let's assume an always-running web application.  Like express, hapi, etc...

Does ts-node require any supporting file watchers and restarts, or can it actually detect file changes while running, rebuild only what's needed and just keep working seamlessly?

**Comment by blakeembrey** [comment]
> Does ts-node require any supporting file watchers and restarts, or can it actually detect file changes while running, rebuild only what's needed and just keep working seamlessly?

`ts-node` does none of that. I think that would be too much for this library to do. There's a lot of good existing tools for that, which I mentioned some above. You could use `onchange` or `nodemon` to watch for changes and use the "fast" transpilation mode (it only transpiles and doesn't give any type errors -making it a lot faster). There's a cache for both modes too, which should improve it a little bit, but once a change occurs in non-fast mode it would need to gather all the files for type information.

Does that help?

**Comment by atrauzzi** [comment]
Hmm, possibly!  Using something like `nodemon` and then fast mode plus a cache sounds like the "reinterpret only what's changed, opcache PHP" behaviour I'm after.  The question will be whether it bears out in practice as the same near-instant code-reload-refresh experience that PHP offers.

I'm hoping to start the web component of a project I'm working on in the next bit, so once I've managed to settle on all the 3rd party code & frameworks, I'll see about setting things up as you describe.

Thanks for the tips!
