### ISSUE TITLE
Custom options get over written at runtime

### ISSUE THREAD

**Issue by danew** [TypeStrong/ts-node#1702]
### Search Terms

Cannot enable swc, transpileOnly, 10.7.0

### Expected Behavior

When enabling `swc` it should run correctly.
```json
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "ts-node": {
    "swc": true,
    "transpileOnly": true,
    "logError": true,
  }
}

```

### Actual Behavior

Reports the following error:
```
"Cannot enable 'swc' option with 'transpileOnly: false'.  'swc' implies 'transpileOnly'."
```

### Steps to reproduce the problem

1. Enable swc
2. Run `ts-node server.ts`

### Minimal reproduction

I'll create a minimal repo in the morning.

I believe the `assign` function within the function `findAndReadConfig` has an incorrect order of the objects.

Within `create` in `index.ts`, it's running `findAndReadConfig(rawOptions)` which extracts the different parts of the configuration within the system but then writes over the changes by assigning `rawOptions`s values within the `assign` function call.

[configuration.ts#L86](https://github.com/TypeStrong/ts-node/blob/main/src/configuration.ts#L86)
```ts
const options = assign<RegisterOptions>(
  {},
  DEFAULTS,
  tsNodeOptionsFromTsconfig || {},
  { optionBasePaths },
  rawOptions
);
```
After applying the following patch to the order of the assign, I get what I would expect:
Patch:
```diff
const options = assign<RegisterOptions>(
  {},
+ rawOptions
  DEFAULTS,
  tsNodeOptionsFromTsconfig || {},
  { optionBasePaths },
- rawOptions
);
```

Output:
```diff
{
  scope: false,
  emit: false,
  files: false,
  pretty: false,
+ transpileOnly: true,
- transpileOnly: false,
  preferTsExts: false,
+ logError: true,
- logError: true,
  project: './tsconfig.json',
  skipProject: false,
  skipIgnore: false,
  compilerHost: false,
  tsTrace: [Function: bound log],
  swc: true,
  optionBasePaths: {
    swc: '<project-directory>'
  }
}
```

Patched version:
https://github.com/danew/ts-node/commit/e3e8bfde356626cb902ff78b59ed139b7a4400a3

### Specifications

* ts-node version: 10.7.0
* node version: 16.13.2
* TypeScript version: 4.6.3
* tsconfig.json, if you're using one:
```json
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "compilerOptions": {
    "allowJs": true,
    "outDir": "build",
    "moduleResolution": "node",
    "baseUrl": ".",
    "isolatedModules": true,
    "resolveJsonModule": true,
    "incremental": true,
  },
  "exclude": ["node_modules", "build"],
  "include": ["back_end", "src"],
  "ts-node": {
    "swc": true,
    "transpileOnly": true,
    "logError": true,
  }
}

```
* Operating system and version: macOS Monterey 12.0.1

**Comment by cspotcode** [comment]
We'll definitely need that reproduction, because when I try to reproduce, it works correctly for me.

Using your tsconfig.json:

```
❯ ts-node --showConfig
{
  "ts-node": {
    "logError": true,
    "transpileOnly": true,
    "swc": true,
    "cwd": "/d/Personal-dev/@TypeStrong/ts-node-repros/issue-1702",
    "projectSearchDir": "/d/Personal-dev/@TypeStrong/ts-node-repros/issue-1702",
    "project": "/d/Personal-dev/@TypeStrong/ts-node-repros/issue-1702/tsconfig.json"
  },
  "compilerOptions": {
    "lib": [
      "es2021"
    ],
    "module": "commonjs",
    "target": "es2021",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "sourceMap": true,
    "inlineSourceMap": false,
    "inlineSources": true,
    "declaration": false,
    "noEmit": false,
    "outDir": "./.ts-node"
  }
}
```

**Comment by danew** [comment]
Turns out I cannot reproduce this outside of my project. I'll investigate further in the coming weeks, but will use `patch-package` to resolve the fix for now.

Thanks for helping!

**Comment by cspotcode** [comment]
If you cannot reproduce outside your project, I'm guessing there is another
tsconfig in there somewhere, a different version of ts-node is being used,
or something like that.  --showConfig can help because it shows the full
path to the config file.  These issues are typically user error.

**Comment by hiukky** [comment]
same problem here when extending a custom configuration!, the ts-node key is not inherited.

**Comment by cspotcode** [comment]
The `"ts-node"` key is, in fact, inherited from one tsconfig to another.  Assuming we're talking about the same thing.

If you're able to create a minimal reproduction proving me wrong, however, we can certainly prioritize a bugfix.

**Comment by alex12058** [comment]
I recently encountered this while running a command using [pnpm](https://github.com/pnpm/pnpm) to execute a command. I found pnpm was incorrectly setting `transpileOnly` to `false`. No default was provided while parsing arguments with [minimist](https://github.com/substack/minimist) so it was initialised with the value `false`.

Discussed here: https://github.com/wclr/ts-node-dev/issues/297#issuecomment-1182043492
