### ISSUE TITLE
Specifying project when using with Mocha

### ISSUE THREAD

**Issue by OliverJAsh** [TypeStrong/ts-node#172]
The docs suggest usage with Mocha is done like so:

```
mocha --compilers ts:ts-node/register
```

What if I want to specify a TypeScript project for the files? I've tried the following to no avail:

```
mocha --compilers ts:ts-node/register --project server/tsconfig.json
```

**Comment by blakeembrey** [comment]
Unfortunately these programs don't enable a way to pass sub-arguments along to `ts-node`. I would recommend using the environment variables mentioned in the README.

**Comment by OliverJAsh** [comment]
I don't see any documentation on the environment variables in the README?

**Comment by blakeembrey** [comment]
https://github.com/TypeStrong/ts-node#configuration-options - it's mentioned for each of the options.
