### ISSUE TITLE
Unexpected reserved word when compiling with Mocha

### ISSUE THREAD

**Issue by kylelamse** [TypeStrong/ts-node#173]
When I try to run `mocha --compilers ts:ts-node/register`
and when importing anything using the ES6 `import` syntax I get this error:

```
(function (exports, require, module, __filename, __dirname) { import { expect } from 'chai';
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

Here is my .tsconfig.json:
```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs"
    },
    "exclude": [
        "node_modules"
    ],
    "compileOnSave": true,
    "buildOnSave": false,
    "atom": {
        "rewriteTsconfig": false
    }
}
```

Here is the the test for Mocha:
```javascript
import { expect } from 'chai';
import { test } from '../test.ts';

describe('test', () => {
  it('should work', () => {
    expect(test).to.equal('hello world!');
  });
});
```

Here is the TypeScript module referenced:
```typescript
export const test: string = 'hello world!';
```

My package.json just in case it's relevant:
```json
{
  "name": "typescript-mocha-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "mocha --compilers ts:ts-node/register"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "chai": "^3.5.0",
    "mocha": "^3.0.2",
    "ts-node": "^1.2.2",
    "typescript": "^1.8.10"
  }
}
```

Really simple stuff.  I just want to import a TypeScript module with the ES6 syntax and run it in Mocha.  What's strange is that I can use the ES6 `import` syntax perfectly fine when just using `ts-node` to run a TypeScript file, but for some reason, using `mocha --compilers ts:ts-node`, Mocha freaks out on the `import`.

**Comment by blakeembrey** [comment]
I can see from your error this is an error in a `.js` file. This isn't a bug in `ts-node`, change the extension to `.ts` if you want it to compile as TypeScript.

**Comment by kylelamse** [comment]
You are correct.  Changed the test to the name `test.spec.ts` and it worked perfectly.  Thanks!
