### ISSUE TITLE
Lose sourcemap related too `.ts` file while use vscode debug

### ISSUE THREAD

**Issue by tianyingchun** [TypeStrong/ts-node#1735]
### Search Terms

 incorrect debug *.ts file using vscode

### Expected Behavior

Should correct located breakpoint on sourcemap file.

### Actual Behavior
while debug `a.ts` using vscode, it will generated new `a.ts` file mirror, it is transpiled file content, 
it should step point `source a.ts` .

### Steps to reproduce the problem
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/2833251/165880404-b6c11e5c-12f5-4ad5-9f65-8224d37fb091.png">

```ts
{
  "name": "ts-node",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "tsconfig": "ts-node --showConfig",
    "serve": "ts-node ./src/index.ts"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@tsconfig/node16": "^1.0.2",
    "ts-node": "^10.7.0",
    "typescript": "^4.6.4"
  }
}
```

.vscode
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "runtimeArgs": ["-r", "ts-node/register"],
      "args": ["${workspaceFolder}/src/index.ts"],
      "env": {
        "TS_NODE_PROJECT": ".vscode/tsconfig.json"
      }
    }
  ]
}

```

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/2833251/165880448-a7cdff76-9dad-4956-a85d-b5003e95acbf.png">

vscode debug  will regenerated new transpiled file 

it should be source file is fine.

### Specifications

* ts-node version: "^10.7.0",
* node version:v17.6.0
* TypeScript version:"^4.6.4"
* tsconfig.json, if you're using one:
```
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "ts-node": {
    // It is faster to skip typechecking.
    // Remove if you want ts-node to do typechecking.
    "transpileOnly": true,
    "files": true,
    "compilerOptions": {
      // compilerOptions specified here will override those declared below,
      // but *only* in ts-node.  Useful if you want ts-node and tsc to use
      // different options with a single tsconfig.json.
      "outDir": "./dist",
      "sourceMap": true
    }
  },
  "compilerOptions": {
    // typescript options here
    // "jsx": "react-jsx"
    "sourceMap": true
  }
}

```
* Operating system and version:
* If Windows, are you using WSL or WSL2?:

**Comment by cspotcode** [comment]
What operating system and version?  Can we get a copy of that error as text instead of screenshot?

**Comment by tianyingchun** [comment]
are you on dicord? i can share you some detail information?

**Comment by tianyingchun** [comment]
my os is mac os (12.3.1) M1 ,  and vscode is 
Version: 1.67.0-insider (Universal)

**Comment by tianyingchun** [comment]
debug lunch configuration is below
```
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "runtimeArgs": ["-r", "ts-node/register"],
      "args": ["${workspaceFolder}/src/index.ts"]
    }
```
the debug console output is 
```text
/usr/local/bin/node -r ts-node/register /Users/tianyingchun/Documents/flatjs/ts-node/src/index.ts
Could not read source map for file:///Users/tianyingchun/Documents/flatjs/ts-node/src/index.ts: ENOENT: no such file or directory, open '/Users/tianyingchun/Documents/flatjs/ts-node/pplication/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiL1VzZXJzL3RpYW55aW5nY2h1bi9Eb2N1bWVudHMvZmxhdGpzL3RzLW5vZGUvc3JjL2luZGV4LnRzIiwic291cmNlcyI6WyIvVXNlcnMvdGlhbnlpbmdjaHVuL0RvY3VtZW50cy9mbGF0anMvdHMtbm9kZS9zcmMvaW5kZXgudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBLE1BQU0sSUFBSSxHQUFHLE1BQU0sQ0FBQztBQUNwQixNQUFNLElBQUksR0FBRyxHQUFHLEVBQUU7SUFDaEIsT0FBTyxJQUFJLE9BQU8sQ0FBQyxDQUFDLE9BQU8sRUFBRSxNQUFNLEVBQUUsRUFBRTtRQUNyQyxPQUFPLENBQUMsR0FBRyxDQUFDLFNBQVMsQ0FBQyxDQUFDO1FBQ3ZCLE9BQU8sQ0FBQyxDQUFDLENBQUMsQ0FBQztJQUNiLENBQUMsQ0FBQyxDQUFDO0FBQ0wsQ0FBQyxDQUFDO0FBRUYsQ0FBQyxLQUFLO0lBQ0osTUFBTSxJQUFJLEVBQUUsQ0FBQztBQUNmLENBQUMsQ0FBQyxFQUFFLENBQUMiLCJzb3VyY2VzQ29udGVudCI6WyJjb25zdCBuYW1lID0gXCJ0aWFuXCI7XG5jb25zdCBmdW5jID0gKCkgPT4ge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnNvbGUubG9nKDExMTEyMjIxMSk7XG4gICAgcmVzb2x2ZSgxKTtcbiAgfSk7XG59O1xuXG4oYXN5bmMgZnVuY3Rpb24gKCkge1xuICBhd2FpdCBmdW5jKCk7XG59KSgpO1xuIl19'
```

**Comment by tianyingchun** [comment]
you are right, i changed vscode to another version issue is gone.

**Comment by cspotcode** [comment]
Which version were you using before, and which did you switch to?  If someone else has the same problem, they will probably find this issue and want to know the answer.  It would be nice for us to help them.

**Comment by tianyingchun** [comment]
now switch to `
Version: 1.66.2 (Universal)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:20.994Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0`

before is 

`
Version: 1.67.0-insider (Universal)
Commit: 8632e9c4096eab5773958b9fb3f45f92efba74a8
Date: 2022-04-29T05:14:56.276Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0
`

**Comment by cspotcode** [comment]
Thanks!
