### ISSUE TITLE
10.8.0: TypeError: getSetExternalModuleIndicator is not a function

### ISSUE THREAD

**Issue by philkunz** [TypeStrong/ts-node#1773]
The latest version (10.8.0) gives me a

```
TypeError: getSetExternalModuleIndicator is not a function
    at transpileModule ([...]/node_modules/ts-node/src/ts-transpile-module.ts:137:35)
```

**Comment by philkunz** [comment]
issue is obsolete, the TypeScript version that caused this was a 4.7.0 nightly build

**Comment by cspotcode** [comment]
Thanks, just to confirm, are you now using the 4.7.0 stable release?  Or did you have to downgrade to 4.6.0 or earlier?
