### ISSUE TITLE
Support consuming Angular Package Format in favour of ESM import resolution 

### ISSUE THREAD

**Issue by magyargergo** [TypeStrong/ts-node#1809]
### Search Terms
afp support in esm resultion

### Expected Behavior
It would be nice to specify other `package.json` attributes in `tsconfig` than just relying on the `main` attribute.

### Actual Behavior
The following commit shows what changes are necessary to be done to reproduce this issue.
- https://github.com/magyargergo/test-apf-with-ts-node/commit/25d122aed1548ed289f62667028b842d727fad4c

The problem happened after `ts-node` tried to resolve `@ionic/storage` package and instead of consuming the `index.js` from the `esm2015` folder it fell back to `CommonJs` and resolved the `bundles/ionic-storage.umd.js` file from `main` attribute in the `package.json`.

### Steps to reproduce the problem
Run `yarn prepare:app` once you clone my repo below.

### Minimal reproduction
https://github.com/magyargergo/test-apf-with-ts-node

### Specifications

| Package name        | Version |
| ------------------- | ------- |
| ts-node                    | 10.7.0    |
| node                         | 16.14.0 |
| TypeScript               | 4.6.2     |
| angular                     | 13.3.0   |

**Comment by cspotcode** [comment]
This sounds like a feature request, is that correct?  It is likely out of scope as well.  ts-node's goal is to run TS natively on node using TypeScript's and node's conventions, but it sounds like this feature request is requesting support for a non-standard package format, one that neither node nor typescript natively recognize.

Happy to discuss further, but this is likely going to be out of scope for ts-node.  It would be best to implement it as a third-party component which can be combined with ts-node.

**Comment by cspotcode** [comment]
Gonna go ahead and close this, but it's not locked and can always be reopened.
