### ISSUE TITLE
ts-node treats "files" in tsconfig.json differently than tsc

### ISSUE THREAD

**Issue by blai** [TypeStrong/ts-node#185]
With Typescript@2, the following will work with `tsc`, but `ts-node` will complain

`tsconfig.json`
```
{
  "compilerOptions": {
    ...
  },
  "files": [
    "node_modules/@types/winston/index.d.ts"
  ]
}
```

`some.ts`
```ts
export class SomeService {
  logger: LoggerInstance; // LoggerInstance is defined in @types/winston/index.d.ts
  constructor(logger: LoggerInstance) {
    this.logger = logger;
  }
}
```

`ts-node` error will be something like `Cannot find name 'LoggerInstance'. (2304)`

**Comment by blakeembrey** [comment]
I would expect that use-case to fail in both `tsc` and `ts-node`, since `winston/index.d.ts` would be in external module format (`files` does nothing here). In this case, what would be resolving is `typescript@2.0`'s change to typings resolution (which looks in `node_modules/@types`) but this configuration should also be set up in `ts-node`. What version of `ts-node` are you using? Can you make sure you're using at least `1.2.0`?

**Comment by blai** [comment]
I am using `ts-node: ^1.2.2`

**Comment by blakeembrey** [comment]
@blai Can you confirm you're actually compiling the file. I just tested with `tsc` and it's definitely failing. Make sure you add your file to the project compilation context otherwise it won't be compiled. With the snippet you gave above, the only files it would be compiling are those in `files`.

![image](https://cloud.githubusercontent.com/assets/1088987/17952525/a15d39a8-6aae-11e6-98da-62f507e3e60c.png)

**Comment by blakeembrey** [comment]
All the interfaces in `@types/winston` would be external, so you'd need to import them anyway to fix this. So:

1. Don't use `files` to specify `@types` - it doesn't do anything (and is probably causing your confusion here, `files` is literally saying use these entry points)
2. Use `import` for these modules (`import { LoggerInstance } from 'winston'`)

**Comment by blai** [comment]
I agree I was hacking this on a potentially unintended behavior.

Since in the [tsconfig doc](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html) it didn't clearly spell out what happen when you have both `files` and `compilerOptions .project`, and there's the `exclude`, it leads one to believe that `files` is sort of the opposite of `exclude`, which means it should be a set of files that are always included (loaded) as part of transpilation (or it could be, like you said, the entry points when `compilerOptions.project` is missing.

But then is there really is no easy way of enabling global type definitions without having to import them in each and every files that uses the types? My motive is that since things like log happens in nearly every file, it would be cool to attach the usage to a common type interface instead of importing the actual module that provides such functionality (that way we can easily replace the function provider, in this case, winston, with something else in the future that also provide a similar type interface). The triple-slash directives does not seem to cut this clean either.

**Comment by blai** [comment]
IMHO, I think that there should be a `@types/logger` definition, and `winston` should use that type definition, and consumers of winston should be using the general `logger` type interface, instead of one that is specific to `winston`, so I can one day exchange `winston` with a more modern implementation.

**Comment by blakeembrey** [comment]
You're welcome to suggest that change, but unfortunately that's also not possible with the `@types` infrastructure. I wanted to achieve that sort of things with Typings, and did to some extent, but if you really want a global definition just write it yourself and include it. TypeScript is structural, if the types are assignable you won't have any problems and you also won't be locked into iterating changes with `winston`. That said, I don't recommend globals and I personally usually creates an `interfaces` folder for this sort of thing that I import from.

**Comment by blakeembrey** [comment]
Also, to confirm, `files` and `exclude` are mutually exclusive.

**Comment by blakeembrey** [comment]
You may want to look up the different between global and external types too. The module you are using is external, which means you'd be importing from it. If you create a file with _no_ imports or exports, it's considered global and would pollute the projects global scope.
