### ISSUE TITLE
SWC and multiline comments breaks debug sourcemaps

### ISSUE THREAD

**Issue by Kaizer69** [TypeStrong/ts-node#1869]
### Expected Behavior

Debug Typescript with SWC

### Actual Behavior

Debugging with Webstorm and default flags and multiline comments (/** */) put the debugger at wrong breakpoints lines.
Debugging instead with ts-node works correctly.

### Steps to reproduce the problem

preserveAllComments: false in .swcrc

If you don't want to read .swcrc (see other issues regard this), you should put a flag in tsnode for setting *preserveAllComments* flag

It's a fault of SWC, but because we cannot set any of options of swcrc, the problem is also in ts-node

**Comment by cspotcode** [comment]
Is there an swc bug report for this that I can follow?

**Comment by Kaizer69** [comment]
I should search on their repo. Maybe I try to patch tsnode with preserveAllComments: false using SWC and tell you if it's working.

**Comment by cspotcode** [comment]
@Kaizer69 any luck?

**Comment by Kaizer69** [comment]
Nope, I open an issue on SWC because also setting preserveAllComments flag, the breakpoints are wrong.
[SWC issue #5628](https://github.com/swc-project/swc/issues/5628)
I should try with VSCode instead of Webstorm. Maybe and IDE problem?

**Comment by cspotcode** [comment]
I'll go ahead and close this.  This issue doesn't have a minimal reproducible example, so if your conversation with SWC uncovers some new information to suggest that ts-node needs to make changes, then please add one to this issue and we can re-open.

**Comment by Birch-san** [comment]
thanks very much @Kaizer69 for reporting this -- same thing happened to me. my source maps were busted. but then I deleted all my multi-line comments and source mapping worked again.
