### ISSUE TITLE
ts-loader does not resolve .cjs imports in a "type": "module" project

### ISSUE THREAD

**Issue by phil-lgr** [TypeStrong/ts-node#1871]
### Search Terms

type module, esm, cjs

### Expected Behavior

ts-loader loads .cts file as CommonJS and then compile the subsequent imports as CommonJS as well.

This is taken from the docs: https://github.com/TypeStrong/ts-node#err_unknown_file_extension

e.g. `ts-node node_modules/webpack/bin/webpack --config webpack.config.cts` where webpack.config.cts is:

```ts
import * as webpack from 'webpack';
import { commonOutput } from './webpack.common.config.cjs';

const config: webpack.Configuration = {
  mode: 'production',
  entry: './foo.js',
  output: {
    // commenting this line (not importing from './webpack.common.config.cjs')
    // will remove the error
    ...commonOutput,
  },
};

export default config;
```

Webpack's configuration doc page: https://webpack.js.org/configuration/

### Actual Behavior

ts-node loads the first entry file (.cts), but throw an error when importing other .cjs files:

```
$ ts-node node_modules/webpack/bin/webpack --config webpack.config.cts
[webpack-cli] Failed to load '/Users/phil/Code/ts-node-webpack/webpack.config.cts' config
[webpack-cli] Error: Cannot find module './webpack.common.config.cjs'
Require stack:
- /Users/phil/Code/ts-node-webpack/webpack.config.cts
- /Users/phil/Code/ts-node-webpack/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/phil/Code/ts-node-webpack/node_modules/webpack-cli/lib/bootstrap.js
- /Users/phil/Code/ts-node-webpack/node_modules/webpack-cli/bin/cli.js
- /Users/phil/Code/ts-node-webpack/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/phil/Code/ts-node-webpack/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/phil/Code/ts-node-webpack/webpack.config.cts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/Users/phil/Code/ts-node-webpack/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .js] (/Users/phil/Code/ts-node-webpack/node_modules/ts-node/src/index.ts:1621:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/phil/Code/ts-node-webpack/webpack.config.cts',
    '/Users/phil/Code/ts-node-webpack/node_modules/webpack-cli/lib/webpack-cli.js',
    '/Users/phil/Code/ts-node-webpack/node_modules/webpack-cli/lib/bootstrap.js',
    '/Users/phil/Code/ts-node-webpack/node_modules/webpack-cli/bin/cli.js'
```

### Steps to reproduce the problem

Reproduction repo here: https://github.com/phil-lgr/ts-node-webpack-5-repro

But basically, in a .cts file, if I import another .cts, it errors, but if I don't use commonOuput, it is fine (    // ...commonOutput,):

```ts
import * as webpack from 'webpack';
import { commonOutput } from './webpack.common.config.cjs';

const config: webpack.Configuration = {
  mode: 'production',
  entry: './foo.js',
  output: {
    // commenting this line (not importing from './webpack.common.config.cjs')
    // will remove the error
    // ...commonOutput,
  },
};

export default config;
```

### Minimal reproduction

https://github.com/phil-lgr/ts-node-webpack-5-repro

### Specifications

```
ts-node v10.9.1
node v16.15.1
compiler v4.8.2
```
* package.json:
```
{
  "name": "ts-node-webpack",
  "version": "1.0.0",
  "description": "",
  "license": "MIT",
  "scripts": {
    "build": "ts-node node_modules/webpack/bin/webpack --config webpack.config.cts"
  },
  "type": "module",
  "dependencies": {
    "@types/node": "^16",
    "ts-node": "^10.9.1",
    "typescript": "^4.8.2",
    "webpack": "^5.74.0",
    "webpack-cli": "^4.10.0"
  }
}
```
MacOS 12.4

**Comment by phil-lgr** [comment]
My current workaround is to not use ts-node and use .mjs files instead

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/9644867/186951813-a0554c78-354b-43bd-876e-35ea7542e81f.png">

**Comment by cspotcode** [comment]
I wonder if you need to enable `esm` and/or `experimentalResolver` so that node understands the `.cts` file extension.  `experimentalResolver` is not documented as well as it should be.

Your tsconfig would look like this:

```jsonc
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "moduleResolution": "NodeNext", // <- switching to NodeNext so that TypeScript matches the behavior of nodejs for file extensions and package.json "type"
    "module": "NodeNext"
  },
  "ts-node": {
    "esm": true,
    "experimentalResolver": true
  }
}
```

**Comment by phil-lgr** [comment]
Hi @cspotcode, thanks for the quick reply

I just tried the options you suggested and 

```
"experimentalResolver": true
```
did the trick

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "ts-node": {
    "experimentalResolver": true
  }
}
```

What is going on there? I did not know about `experimentalResolver` before

**Comment by cspotcode** [comment]
That's great!

The problem is that we need to teach node three things:
a) how to resolve import specifiers to files.  An import specifier is the string that you pass into `import` or `require()`
b) how to execute those files: as ESM or CJS
c) transform TS source code into JS so that node can execute JS instead of failing to understand TS syntax

Historically, we had never hooked into node's CommonJS *resolver*. (a)  But with CTS, MTS, etc. we had to start hooking into node's CommonJS resolver to teach it to handle certain situations for (a) and a bit of (b).  This was a big change, so I wanted it behind a flag at least initially to avoid breaking everyone.  I think it should be on by default, but I wanted to get some real-world feedback first.

**Comment by phil-lgr** [comment]
Thanks again for your reply, this is extremely useful. Feel free to close this one.
