### ISSUE TITLE
[Bug] ts-node fails on node v16.17.0 in npm run

### ISSUE THREAD

**Issue by c-vetter** [TypeStrong/ts-node#1889]
After updating to node v16.17.0, `ts-node` fails when running inside `npm run`.
Works fine with node v16.15.0, which I've reverted back to.

May be specific to Windows.

### Search Terms
+ windows
+ argument not recognized
+ npm npx

### Expected Behavior
```ps
$ npx ts-node test.ts
works
$ npm test

> test
> ts-node test.ts

works
```

### Actual Behavior
```ps
$ npx ts-node test.ts
works
$ npm test

> test
> ts-node test.ts

The argument '/C/Users/rp/AppData/Local/Temp/test-a99da100.sh' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Usage: pwsh[.exe] [-Login] [[-File] <filePath> [args]]
                  [-Command { - | <script-block> [-args <arg-array>]
                                | <string> [<CommandParameters>] } ]
                  [-ConfigurationName <string>] [-CustomPipeName <string>]
                  [-EncodedCommand <Base64EncodedCommand>]
                  [-ExecutionPolicy <ExecutionPolicy>] [-InputFormat {Text | XML}]
                  [-Interactive] [-MTA] [-NoExit] [-NoLogo] [-NonInteractive] [-NoProfile]
                  [-OutputFormat {Text | XML}] [-SettingsFile <filePath>] [-SSHServerMode] [-STA]
                  [-Version] [-WindowStyle <style>] [-WorkingDirectory <directoryPath>]

       pwsh[.exe] -h | -Help | -? | /?

PowerShell Online Help https://aka.ms/powershell-docs

All parameters are case-insensitive.
```

### Steps to reproduce the problem
Run these in [the repro](https://github.com/c-vetter/repro_ts-node_lts-npm-fail):
+ `npx ts-node test.ts`
+ `npm test`

### Minimal reproduction
https://github.com/c-vetter/repro_ts-node_lts-npm-fail

### Specifications

* ts-node version: 10.9.1
* node version: 16.17.0
* TypeScript version: 4.8.3
* tsconfig.json, if you're using one: `null`
* package.json:
```json
{
	"scripts": {
		"test": "ts-node test.ts"
	},
	"dependencies": {
		"ts-node": "10.9.1",
		"typescript": "4.8.3"
	}
}
```
* Operating system and version: Windows 10 Pro (Microsoft Windows NT 10.0.19044.0 x64)
* If Windows, are you using WSL or WSL2?: Nope, native Powershell Core

**Comment by cspotcode** [comment]
Closing as an npm / npx / node bug.  We get a ton of these.  Best of luck!
