### ISSUE TITLE
Compatibility with Typescript 2 beta

### ISSUE THREAD

**Issue by kataik** [TypeStrong/ts-node#191]
**Version:** 1.3.0

After installing Typescript 2 beta, ts-node does not work any more. Please note that tsc and ts still works.

Error message:

> c:\Work\Dev\T_CoreWebRc2\src\T_CoreWebRc2\node_modules\typescript-node\dist\typescript-

> node.js:31
>     return ts.parseConfigFile(config, ts.sys, fileName);
>               ^

> TypeError: ts.parseConfigFile is not a function
>     at readConfig (c:\Work\Dev\T_CoreWebRc2\src\T_CoreWebRc2\node_modules\typescript-node\dist\typescript-node.js:31:15)
>     at Object.register (c:\Work\Dev\T_CoreWebRc2\src\T_CoreWebRc2\node_modules\typescript-node\dist\typescript-node.js:43:18)
>     at Object.<anonymous> (c:\Work\Dev\T_CoreWebRc2\src\T_CoreWebRc2\node_modules\typescript-node\dist\bin\ts-node.js:34:33)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (c:\Work\Dev\T_CoreWebRc2\src\T_CoreWebRc2\node_modules\typescript-node\bin.js:3:1)

**Comment by blakeembrey** [comment]
Works fine. Install `ts-node`.

**Comment by blakeembrey** [comment]
I did respond to literally the same report in https://github.com/Microsoft/TypeScript/issues/10639#issuecomment-243937296 with the explanation. Please read the comment there.

**Comment by kataik** [comment]
Thanks and sorry for the duplicate!
