### ISSUE TITLE
Do you know how to pipe this to another compiler?

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/ts-node#194]
Hi

In wallaby and karma there are preprocessors which mocha does not have.
My goal is to transpile es6 import/exports to commonjs via import-to-commonjs library.
This needs to be done after the TS compilation.

The reason for this is that I am targetting es6/es6 environment as I am targetting Node 6 environment  with ES 6 support and I really do not like the `import * as A' types of imports.

**Comment by blakeembrey** [comment]
@tomitrescak TypeScript can emit CommonJS, why not just use that? Aside from that, you can use any other node.js `require` loader, as long as it also plays nicely with `require.extensions`.

**Comment by tomitrescak** [comment]
Emission of commonjs is problematic. Often, when packages default export is cosnstructor, you have to import like "import A = require('module').

Also, typescript forces you to use 'import * as A' notation.
I know these are small things, but they make code nicer.

**Comment by blakeembrey** [comment]
@tomitrescak That's what you should be doing. A CommonJS export should _always_ be imported using `import x = require('x')`. Also, it doesn't force you to use `import * as A` notation. It's probable there's some missing knowledge here, but I'm still not sure what you're trying to do. Can you give me an example at all? Maybe a link to the project you want to use?

**Comment by tomitrescak** [comment]
Well, as Ryan Cavanaugh mentioned "You're probably sad about this. Grief is a normal part of programming. Please jump to stage five in the Kübler-Ross model: Acceptance." ;) I'll just use the other then.

Weird thing for me is that allowdefaultsyntheticimports does not change a thing for me.

**Comment by blakeembrey** [comment]
@tomitrescak You should check the documentation for `tsconfig.json`, but `allowSyntheticDefaultImports` does not change any emit. I'm still confused about what you were trying to achieve - can you give a link?

**Comment by tomitrescak** [comment]
Do not worry about it. Blake, it is a long story and a bit complex one.

If you have time:
I have an application that shares code between client (React) and server (Express).
In my workflow I compile to JS and let webpack load JS code not TS code as it is faster and less problematic.

As a result, I was compiling everything to ES2015 modules, in order not to have nasty namespaced React elements (e.g. namespace1.Element). For this purpose I have build "import-to-commonjs" loader, that allows to load ES6 code with import statements without sourcemapped transpilation. With this I could use the same approach to imports as with JS and webpack (i.e. no 'import * as ...' notation).

I had everything working nicely and efficiently with unit tests running un Wallaby.JS. The problem appeared, when I started to fit everything within CI and I needed it to run in pure Mocha.

This is where TS loader comes out and play and where my problems started as I was using those "non-standard" import statements (import a from 'a' instead of import * as a from 'a') and everything broke. 

As a result, all I needed was to pipe the typescript compilation from ts-node to my import-to-commonjs tool to be able to run all tests. 

But, for now I decided to re-write all my import statements to Typescript notation.

**Comment by blakeembrey** [comment]
Haha, I think I understand now. The Webpack and node loader patterns are definitely a lot different, but possibly you could have written a version for `require.extensions` and `ts-node` would have "wrapped" any existing `.ts` loader. The other solution might have been to bundle Webpack into a package you can run in node - at least a lot of people, from what I've seen, use custom imports and loaders which make it hard to run under native node anyway.
