### ISSUE TITLE
--transpile-only execute the code instead of showing transpilation result

### ISSUE THREAD

**Issue by hadrien-toma** [TypeStrong/ts-node#1964]
### Search Terms

- transpile-only

### Expected Behavior

Beeing able to get the transpiled JS.

### Actual Behavior

Executing the transpiled JS without seeing it before that.

### Steps to reproduce the problem

```bash
docker run --rm --interactive --tty node /bin/bash -c "
    uname --all &&
    npm install --global npm && 
    echo \"npm -v -> \$(npm -v)\" && 
    echo \"node -v -> \$(node -v)\" && 
    echo \"npx --yes ts-node -v -> \$(npx --yes ts-node -v)\" && 
    echo 'const counter: number = 0; console.log({ counter });' > index.ts && 
    npx ts-node --transpile-only index.ts"
```

Which gives:

```bash
Linux a81d6aefd151 5.19.0-32-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2 x86_64 GNU/Linux

changed 21 packages in 19s

16 packages are looking for funding
  run `npm fund` for details
npm -v -> 9.6.0
node -v -> v19.7.0
npx --yes ts-node -v -> v10.9.1
{ counter: 0 }
```

### Specifications

* Operating system and version:

```bash
> cat /etc/lsb-release

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

> uname --all

Linux farfetchd 5.19.0-32-generic #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Gerrit0** [comment]
That option means to skip type checking, not skip running. It's working as expected.

**Comment by hadrien-toma** [comment]
Hum, okay, thanks for your answer.
Maybe you know how can I see the transpiled result then? 🥺

**Comment by Gerrit0** [comment]
For that you should compile with tsc itself and look at the output file, no need for ts-node

**Comment by hadrien-toma** [comment]
It is more that I need ts-node, but I also would like to see what it is effectively executing.
So it seems to not be possible without installing tsc so I will close the issue.

**Comment by Gerrit0** [comment]
You could give ts-node `--emit --compilerHost` and look at the files in `.ts-node`, doesn't print the code, but...
