### ISSUE TITLE
Compile error when using ES6 standard object

### ISSUE THREAD

**Issue by nicolasxu** [TypeStrong/ts-node#197]
`let pets = new Set(["Cat", "Dog", "Hamster"]);
`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

error message:

04.iterate_Set.ts (7,16): Cannot find name 'Set'. (2304)

**Comment by blakeembrey** [comment]
You need to change your compiler options to support ES6 if you want to use ES6 features. I'd recommend reading about using `tsconfig.json` for this.

**Comment by nicolasxu** [comment]
Thanks!

**Comment by blakeembrey** [comment]
No worries. Sorry, sometimes I don't put the extra leg work in to find helpful links and things. But you can see the `tsconfig.json` for this project as an example - https://github.com/TypeStrong/ts-node/blob/master/tsconfig.json#L3. You'd just change that to `es6` in your case.
