### ISSUE TITLE
Custom Compiler is not working about transform

### ISSUE THREAD

**Issue by sunrabbit123** [TypeStrong/ts-node#1975]
### Search Terms

Hello, I am a developer who is trying to run a custom compiler using ts-node. Your ts-node is very impressive, and I wanted to use it, but it doesn't seem to work for me.

I ran the following command: [This](https://github.com/sunrabbit123/ttypescript/actions/runs/4496735647/jobs/7911670710)
```sh
node /home/sunrabbit/Desktop/ttypescript/node_modules/ts-node/dist/bin.js -C /home/sunrabbit/Desktop/ttypescript/packages/ttypescript/lib/typescript.js tsnode.ts
```
And the compiler options were successfully entered.

However, the transform did not work, and the following code was executed:
```ts
else {
    Module.runMain();
}
```

### Expected Behavior
cool run 

### Actual Behavior
It is not work

### Steps to reproduce the problem
clone my repository, install package and `npm run test tsnode.spec.ts`

### Specifications

* ts-node version: >=8.0.2
* node version: >= 16
* TypeScript version: 5.0

**Comment by cspotcode** [comment]
Does ttypescript support typescript v5?

**Comment by sunrabbit123** [comment]
As ttypescript supports ts-node, ts-node is involved in the process of supporting v5, and we are currently working on it.

**Comment by sunrabbit123** [comment]
https://github.com/sunrabbit123/ttypescript
support version

**Comment by cspotcode** [comment]
Which version of ts-node are you using?

**Comment by sunrabbit123** [comment]
I am using 10.9.1. Since I always install >=8.0.2, I can only get the latest version. My local environment is not important. Test failures occur in the virtual environment, which comes from package.json. The node version comes from Github Actions.

**Comment by sunrabbit123** [comment]
In phase 3, compiler options are processed, but the processed result is not used in phase 4. Am I misunderstanding something?

**Comment by sunrabbit123** [comment]
Then change the story
Which function in typescript are you calling to compile?

@cspotcode

**Comment by sunrabbit123** [comment]
The cause was createLanguageService.
Thanks.
