### ISSUE TITLE
Switch to package.json `prepack` script so that yarn can install from git

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#1979]
Related: https://github.com/TypeStrong/ts-node/pull/1958#issuecomment-1488910558

When installing directly from git, we have our `package.json` configured to run the build.  We are currently using `prepare` for this, but yarn does not support that and recommends `prepack` instead.

npm docs seems to agree https://docs.npmjs.com/cli/v9/using-npm/scripts

> Runs BEFORE a tarball is packed (on "npm pack", "npm publish", and when installing a git dependency).

**Comment by 4lph4-Ph4un** [comment]
You sure this install path from git works okay with Yarn >2?

This is from their documentation:
> Note: For this workflow to work, make sure that each individual workspaces can be built just by running yarn install && yarn pack into each individual workspace. In particular, avoid third-party release scripts unless they use yarn pack under the hood.

Link to the referenced part:
https://yarnpkg.com/features/protocols#frequently-asked-questions

Here's my issue related to this #2002
