### ISSUE TITLE
Code coverage with Istanbul

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/ts-node#2]
I spent a long time trying to resolve this already, but can't find a decent solution. I started based on https://github.com/babel/babel/blob/master/packages/babel/src/api/register/node.js with `process.env.running_under_istanbul` and got it executing but got stuck with no coverage information coming out.

**Comment by blakeembrey** [comment]
Istanbul 1.0 alpha.

**Comment by silviogutierrez** [comment]
So I'm trying the alpha as you suggested, but I still get no info coming out. Here's the command:

`./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- --compilers ts:ts-node/register client/test.ts`

Test passes fine, but it prints:

`No coverage information was collected, exit without writing coverage information` at the bottom.

Am I missing something? I'm on istanbul 1.0 alpha 2.

Thanks,

Silvio

**Comment by silviogutierrez** [comment]
Think I solved it! For the curious, you need an `.istanbul.yml` file. Mine is currently:

```
instrumentation:
  extensions:
    - .tsx
    - .ts
```

And it seemed to work.

**Comment by sinedied** [comment]
I still can't make it work with `istanbul@1.1.0-alpha.1` and jasmine: sourcemaps are broken for the jasmine reporters and something crash after the test executions :(

Without istanbul the tests run fin with jasmine.

**Comment by jonaskello** [comment]
I found [this comment](https://github.com/Izhaki/Typescript-Mocha-Istanbul-Boilerplate/issues/2#issuecomment-249435253) very helpful. Basically use `nyc` command to run instanbul instead of the `istanbul` command and it works.

**Comment by sinedied** [comment]
@jonaskello that's what I end up using, `nyc` works fine with `ts-node` without any pain.

**Comment by bennyn** [comment]
@sinedied Do you have a minimal working example? I would also like to setup `ts-node` with `nyc`. 😃
