### ISSUE TITLE
error TS2304: Cannot find name 'fetch'.

### ISSUE THREAD

**Issue by beppler** [TypeStrong/ts-node#2027]
### Search Terms

Node 18, fetch

### Expected Behavior
When using ts-node with Node 18, the fetch API should be supported as it is supported by Node itself.

### Actual Behavior
ts-node is reporting that fetch can not be found.

```ts
await (await fetch('https://www.google.com')).text();
```

Is returning the following error:

```
<repl>.ts:4:14 - error TS2304: Cannot find name 'fetch'.

4 await (await fetch('https://www.google.com')).text();
               ~~~~~
```

### Steps to reproduce the problem
Run the command above using `npx ts-node` against Node 18.

### Minimal reproduction

Run the following command:

```sh
npx ts-node -p -e "await (await fetch('https://www.google.com')).text();"
```
### Specifications

* ts-node version: v10.9.1
* node version: v18.16.0
* TypeScript version: v5.0.4
* tsconfig.json:
```
{
    "$schema": "https://json.schemastore.org/tsconfig",
    "compilerOptions": {
        "lib": ["es2023"],
        "module": "Node16",
        "target": "es2022",
        "strict": true,
        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "moduleResolution": "node"
    }
}
```
* package.json:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.ts",
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "ts-node": "^10.9.1",
    "typescript": "^5.0.4"
  }
}
```
* Operating system and version: Ubuntu 22.04.2

**Comment by cspotcode** [comment]
That'll be an issue with @types/node.
