### ISSUE TITLE
ts-node loses the class name from the stack trace when the error is thrown in a static method.

### ISSUE THREAD

**Issue by KostyaTretyak** [TypeStrong/ts-node#2046]
### Search Terms

- stack trace class name

### Expected Behavior

The class name must be present.

### Actual Behavior

The word "Function" is inserted instead of the class name.

### Steps to reproduce the problem

Call this code with `ts-node`:

```ts
class MyClass {
  static staticMethod() {
    throw new Error('Error in static method');
  }
}

MyClass.staticMethod();
```

And see the stack trace:

```text
Error: Error in static method
    at Function.staticMethod
```

If you run the same code from `node`, the stack trace will be correct:

```text
Error: Error in static method
    at MyClass.staticMethod
```

### Specifications

ts-node v10.9.1
node v18.17.1
compiler v5.1.6
Ubuntu 22.04

**Comment by cspotcode** [comment]
ts-node is compiling the code via tsc before executing it.  What happens when you compile via tsc and then run in node?  Same stack trace, or different?

**Comment by KostyaTretyak** [comment]
@cspotcode, just checked. If the compiled code reads node.js, then the class name is correct:

```text
Error: Error in static method
    at MyClass.staticMethod
```

**Comment by cspotcode** [comment]
Ok thanks, can you share that reproduction somewhere?  Can be a new git repo, then commit the package.json, tsconfig, .ts source, and compiled .js output.  It'll help reproducing locally.

Also, one more thing to try: make sure tsc emits a sourcemap, then run node with `--enable-source-maps`

ts-node enables sourcemaps and its own mapping of stack traces, so if we can compare ts-node's mapping against what vanilla node is doing, we can see how they both handle sourcemapping.

**Comment by KostyaTretyak** [comment]
@cspotcode, I've provided the code above that needs to be tested to see the problem.

**Comment by cspotcode** [comment]
Hmm here's what I see:

```
Error
    at Function.Foo.bar 
```

**Comment by KostyaTretyak** [comment]
I think I found the culprit. When `node` is run with the `--enable-source-maps` option, the class name is also lost.
