### ISSUE TITLE
--project setting ignored when running with mocha

### ISSUE THREAD

**Issue by tomitrescak** [TypeStrong/ts-node#205]
Hi, no matter how I specify the --project option it is ignored when running with mocha and it tries to load tsconfig from the root directory.

```
mocha --require ./test_setup.js --report lcovonly src/server/**/tests/*.ts --compilers ts:ts-node/register --project ./src
```

I have my tsconfig.json in src directory, but I need to run mocha from root. I tried changing setting of --project but to no avail.

**Comment by arusakov** [comment]
@tomitrescak 
I faced this problem before #200 
You can use ENV variable for project setting like this:
`TS_NODE_PROJECT=./src mocha --bla-bla-bla`

**Comment by blakeembrey** [comment]
Yes, that's just how Mocha, Gulp, Tape, TAP and every other CLI works. You can't pass sub-arguments. If you want to use options, you'd need to start mocha with `ts-node` instead or use environment variables.

**Comment by tomitrescak** [comment]
Thanks guys! Works.
