### ISSUE TITLE
Tracking: swc erroneously converts import assertions `assert` keyword to `with`

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#2051]
Tracking: https://github.com/swc-project/swc/issues/7908

Once swc fixes this, we may need to require the newer version or pass a flag.

Converting to `with` might be correct in some situations, I'm not an expert on the spec changes.  But I know that for our purposes on node, we need to keep the `assert`.

**Comment by MadCcc** [comment]
Is there anyway to override swc configuration in ts-node?
It is broken after swc released 1.3.83
![image](https://github.com/TypeStrong/ts-node/assets/27722486/5cfed301-44cd-4b80-8274-18a52c4120bb)

**Comment by cspotcode** [comment]
Linking:
https://github.com/swc-project/swc/issues/7928
https://github.com/TypeStrong/ts-node/issues/2056
