### ISSUE TITLE
register() no longer works in node20 with modules

### ISSUE THREAD

**Issue by imownbey** [TypeStrong/ts-node#2054]
### Search Terms
.register()
.register() node20

### Expected Behavior
The docs still imply that running
```
require("ts-node").register()
const target = await import("tsfile.ts")
```
should work

### Actual Behavior
It now errors with "unknown extension mts" or "unknown extension ts".

### Steps to reproduce the problem
file.mts
```
console.log("Hello")
```

entry.js
```
require("ts-node").register()
const target = await import("./file.mts")
```

### Specifications

* ts-node version:
* node version:
* TypeScript version:
* tsconfig.json, if you're using one:
```
{}
```
* package.json:
```
{
  "dependencies": {
      "ts-node": "^10.9.1",
  }
}
```
* Operating system and version: Mac
* If Windows, are you using WSL or WSL2?:

**Comment by intellix** [comment]
you've marked it as completed, but how did you fix it?
