### ISSUE TITLE
SWC: Reflect renamed keepImportAssertions configuration option

### ISSUE THREAD

**Issue by felixh10r** [TypeStrong/ts-node#2056]
### Desired Behavior

With version 1.3.83, swc renames the experimental configuration option `jsc.experimental.keepImportAssertions` to `jsc.experimental.keepImportAttributes` as per https://github.com/swc-project/swc/pull/7914 . 

### Is this request related to a problem?

All setups with swc > 1.3.82 will fail. This creates a dependency version limitation which should probably be reflected in `peerDependencies` or simply updated in a new `ts-node` release.

### Additional context

If the solution is to _simply_ change the name of the property, I'm happy to open a PR.

**Comment by felixh10r** [comment]
since the swc config option is experimental, it was changed in a _patch_ update to `@swc/core`, which may be updated by developers without knowing about the breaking behavior.

**Comment by meabed** [comment]
I tried commenting in SWC :) but no luck 😢

**Comment by isaacs** [comment]
Actually, we should just remove that option from ts-node, I think.  swc only emits `import .. from .. with {}`, not `import .. from .. assert {}`, and no version of node supports that syntax.

1.3.83 adds `emitAssertForImportAttributes`, but [it doesn't do that](https://github.com/swc-project/swc/issues/7928), so typescript currently actually relying on `import/assert` is (a) currently broken when using swc with ts-node, and (b) not likely to work any time soon.

Better to just have it strip the attributes, imo.

**Comment by isaacs** [comment]
`emitAssertForImportAttributes` would be nice, but I'd still recommend waiting until it's promoted out of experimental status.

**Comment by RobinTail** [comment]
Perhaps It would be convenient to have an ability to configure swc options in tsconfig besides just having
```
"swc": true
```

**Comment by meyfa** [comment]
I think a way of configuring SWC would definitely be nice long-term. For now, I would like to get SWC `>=1.3.83` to not fail our CI builds with ts-node. It seems like PR #2057 would achieve this. Is there any way to help moving this forward? @cspotcode

**Comment by MuTsunTsai** [comment]
Experiencing the same issue as well. Have to stay at SWC 1.3.82 for now.
