### ISSUE TITLE
Supporting native env file parsing (node 20 feature) in ts-node

### ISSUE THREAD

**Issue by shivarajnaidu** [TypeStrong/ts-node#2058]
### Desired Behavior
Able to pass env file to ts-node without dotenv as we do it in node 20 (native feature now).

### Is this request related to a problem?
Now we are able to pass env file path to node to load env variables but there is no straight forward way that we can use along with ts node

See this https://nodejs.org/en/blog/release/v20.6.0#built-in-env-file-support

**Comment by Doc999tor** [comment]
You can try this setting: 
```shell
node -r ts-node/register --env-file=dev.env app.ts
```
With `ts-node` installed locally as dev dependency works correctly

I tried many other configurations without success. For example, this variant is supposed to be correct 
```shell
npx cross-env NODE_OPTIONS='--env-file=dev.env' ts-node app.ts
```
but throws `node: --env-file is not allowed in NODE_OPTIONS`

**Comment by shivarajnaidu** [comment]
Thanks for the answer.

**Comment by Christiangsn** [comment]
> You can try this setting:
> 
> ```shell
> node -r ts-node/register --env-file=dev.env app.ts
> ```
> 
> With `ts-node` installed locally as dev dependency works correctly
> 
> I tried many other configurations without success. For example, this variant is supposed to be correct
> 
> ```shell
> npx cross-env NODE_OPTIONS='--env-file=dev.env' ts-node app.ts
> ```
> 
> but throws `node: --env-file is not allowed in NODE_OPTIONS`

Has anyone opened a ticket on the node requesting this? it would be very useful

**Comment by gregg-cbs** [comment]
Node has the --env-file flag, the issue is that ts-node does not have it
