### ISSUE TITLE
Running stale code

### ISSUE THREAD

**Issue by danvk** [TypeStrong/ts-node#206]
I'm running tests with:

    mocha --compilers ts:ts-node/register test/*_test.ts

This usually works fine but it occasionally executes a stale version of my TypeScript code. Running `tsc` and then the `mocha` command again fixes the issue.

Ideally ts-node would use the latest version of the code, or provide a way to disable the cache entirely.

```
$ ts-node --version
ts-node v1.3.0
node v5.5.0
```

**Comment by blakeembrey** [comment]
Maybe you're interested in https://github.com/TypeStrong/ts-node#configuration-options? Have you tried disabling the cache and see if it makes a difference?

**Comment by danvk** [comment]
Is there a way to disable the cache from the command line when you're using the mocha runner, rather than invoking `ts-node` directly? I'd try setting an environment variable, but #199.

**Comment by blakeembrey** [comment]
Nope, I'll have to fix that when I have time.

**Comment by danvk** [comment]
I've been noticing this more and more recently, both with mocha and when I run `ts-node` directly. I pretty much always run `tsc && ts-node ...` now, which largely defeats the purpose of ts-node.

```
$ ts-node --version
ts-node v1.6.0
node v5.5.0

$ tsc --version
Version 1.8.10
```

Here's my `tsconfig.json`:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": true,
        "suppressImplicitAnyIndexErrors": true,
        "sourceMap": true,
        "jsx": "react"
    },
    "exclude": [
        "node_modules",
        "typings/main",
        "typings/main.d.ts"
    ]
}
```

**Comment by blakeembrey** [comment]
Have you tried disabling the cache yet? Does that change anything? It seems unlikely there'd be hash collisions happening, but I'm not sure how else you could have stale code running. I'm also struggling to see how `tsc` would change what's happening if you're testing `.ts` files since there'd be no change before or after running it. Can you please share more information? What does it mean to you when you say "stale code"?

I'm going to go out on a limb and bet that actually, you're not using `ts-node` but just `node`. Are you generating the `.js` next to the `.ts` files? Because `node` will **always** take precedence on loading the `.js` file over the `.ts` file. If you had **no** `.js` files next to `.ts`, I think your code would actually work fine.

**Comment by danvk** [comment]
Thanks for the quick response @blakeembrey.

Let me see if I understand. Say I want to run `foo.ts` using ts-node. I do the following sequence:

1. Run `tsc` to generate `foo.js` and `foo.js.map`.
2. Modify `foo.ts`.
3. Run `ts-node foo.ts`.

Is the last command expected to run the latest version of `foo.ts` or will it run whatever's in `foo.js`?

**Comment by blakeembrey** [comment]
Not exactly. If you're generating your `.js` files next to `.ts` files, the `.js` file will always load first over the `.ts` file (this is just how `node` works). Instead, the _only_ step you should do using `ts-node` is 3. When you generate `.js` files from TypeScript, change the `outDir` to something like `dist/` instead (E.g. https://github.com/TypeStrong/ts-node/blob/master/tsconfig.json#L4). `ts-node` is incapable of loading `.ts` > `.js` files when they exist next to each other.

**Comment by danvk** [comment]
OK, I'll add `"noEmit": true` to my tsconfig to prevent .js file generation entirely. It sounds like that should fix this issue?

**Comment by blakeembrey** [comment]
Yes. But you still need to remove the existing `.js` files.

**Comment by danvk** [comment]
This seems to have fixed the issue. I'll re-open if I run into it again. Thanks for the help!

**Comment by blakeembrey** [comment]
No worries. Pasting the `tsconfig.json` really helped me realise the issue, but it was a bit of a mind bender thinking you were running into hash collisions 😄
