### ISSUE TITLE
ts-node is unable to resolve tsconfig files in Yarn workspace

### ISSUE THREAD

**Issue by unematiii** [TypeStrong/ts-node#2098]
### Search Terms

#2076, #2090, #2091

### Expected Behavior

Prior to Typescript 5.3 (ts-node 10.9.1) I was able to compile and run my code with tsconfig files that extend files exposed in one of the projects workspaces.

### Actual Behavior

```
[INFO] 15:08:30 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.1, typescript ver. 5.3.3)
/Users/mati/Projects/project/node_modules/ts-node-dev/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS6053: File '@organization/project-tsconfig/node.json' not found.
```

### Steps to reproduce the problem

Create workspace and `tsconfig.json` that extends another `tsconfig.json` in another workspace in the same project.

### Specifications

* ts-node version:  10.9.1
* node version:v20.9.0
* TypeScript version: 5.3.3
* Operating system and version: macOS Sonoma

**Comment by Guerteltier** [comment]
Why did you open an issue for a bug that was already reported twice and has already been fixed?

**Comment by unematiii** [comment]
Sorry, my bad. Apparently `ts-node-dev` has not been updated yet, so it was pulling in previous version of `ts-node`. Closing.
