### ISSUE TITLE
How funny a ts-node that does not read .ts file hahahha

### ISSUE THREAD

**Issue by allestaire** [TypeStrong/ts-node#2120]
### Search Terms

`yarn ts-node script.ts`

#### returns

`TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for`

And the configuration is too confusing when the content of the file is only `console.log` hahahahaha what kind of package is this. hahahaha

This package is much better [tsx](https://github.com/privatenumber/tsx)

### Specifications

* ts-node version:
* node version:
* TypeScript version:
* tsconfig.json, if you're using one:
```
{}
```
* package.json:
```
{}
```
* Operating system and version:
* If Windows, are you using WSL or WSL2?:

**Comment by jakesteele** [comment]
TS-Node doesn't work when your package type is "module" switch to commonJS and that error will go away :D

**Comment by allestaire** [comment]
> TS-Node doesn't work when your package type is "module" switch to commonJS and that error will go away :D

Already tried that. the thing is, TS-Node might be hard to configure, good thing I found the easier one

**Comment by dingshaohua-com** [comment]
```js
// test.ts
console.log('hello')
```

run script
```
npx ts-node ./test.ts 
```

Im get err like this:
```
TypeError: Unknown file extension ".ts" 
```
