### ISSUE TITLE
this Project  is  already  dead ,  please  friends use   tsx  or  swc-node to instead it  

### ISSUE THREAD

**Issue by Super1Windcloud** [TypeStrong/ts-node#2133]
this Project  is  already  dead ,  please  friends use   tsx  or  swc-node to instead it

**Comment by thetutlage** [comment]
If they both had similar behavior to Node.js module loader. TSX allows imports without `.js` extension and the same code will break if you compile it to JavaScript for distribution for production

**Comment by albertodiazdorado** [comment]
Yep, time to let `ts-node` go.

`ts-node` is dead, long live `tsx`!

**Comment by Super1Windcloud** [comment]
you're right

**Comment by josser** [comment]
Can't use tsx or swc-node because of decorators

**Comment by thetutlage** [comment]
@josser Checkout https://github.com/poppinss/ts-exec

**Comment by josser** [comment]
@thetutlage this is beautiful, it really should be in the README for everyone looking for alternatives.
Thank you!

**Comment by albertodiazdorado** [comment]
@thetutlage if ts-exec is built on top of SWC, why would one use that package instead of simply swc-node?

**Comment by thetutlage** [comment]
@albertodiazdorado Here's the reason. https://x.com/AmanVirk1/status/1997978405099475326

`ts-exec` doesn't allow directory imports via `index.ts` file and neither extension-less imports. Both are allowed by `swc-node`.

**Comment by albertodiazdorado** [comment]
Thanks!
