### ISSUE TITLE
Not using paths from tsconfig

### ISSUE THREAD

**Issue by Jontem** [TypeStrong/ts-node#219]
Typescript 2.0 has added support for having modules in other places than node_modules with the paths property. More info can be found in the [documentation](https://www.typescriptlang.org/docs/handbook/module-resolution.html). 

When running with ts-node this does not work. It just gives me the error that the module cannot be found.

test1.ts
```js
import * as foo from "foo";

console.log(foo.hello);
```

lib/foo/index.ts:
```js
export const hello = "hello";
```

Then running 
```
ts-node --compilerOptions '{"baseUrl": "./", "paths": {"foo": ["lib/foo"]}}' test1.ts
```

Same error with this tsconfig.json
```json
{
    "compilerOptions": {
        "baseUrl": "./",
        "paths": {
            "foo": ["lib/foo"]
        }
    }
}
```

Running `tsc` works

**Comment by blakeembrey** [comment]
This would be a runtime error. TypeScript does not rewrite the paths for you. Node does not know where to find your paths based on your configuration. Please search existing issues.

**Comment by Jontem** [comment]
#138

**Comment by MrCrimp** [comment]
For any search-engine travellers reading this,
This can to some extent be worked around by setting the NODE_PATH to your package.json dir, e.g

----
tsconfig.json
```

baseUrl: ".",

"paths": {
      "*": [
        "*"
      ]
    }
```

----
package.json
>"test": "export NODE_PATH=./ && mocha"

Then imports like these works for `ts-node/register` runs as well as tools providing resolve paths (babel, webpack)

`import * as log from 'src/utils/log'`

**Comment by mnasyrov** [comment]
Guys, this is a very useful workaround with NODE_PATH should be somewhere in README file. I stuck in two hours with baseUrl/paths problem while not found it in closed issues :)

**Comment by jonaskello** [comment]
For those interested I did a PR to enable execution of projects with tsconfig paths in #254.

**Comment by jonaskello** [comment]
@MrCrimp @mnasyrov I also used the NODE_PATH work-around, but this can now be solved easier with the [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) package. Just add it as a dev dependency and use the `-r tsconfig-paths/register` option of ts-node or mocha and all paths will work automatically without NODE_PATH :-).

**Comment by bennyn** [comment]
> @MrCrimp @mnasyrov I also used the NODE_PATH work-around, but this can now be solved easier with the [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) package. Just add it as a dev dependency and use the `-r tsconfig-paths/register` option of ts-node or mocha and all paths will work automatically without NODE_PATH :-).

Thanks for this hint! I guess to make it work through [nyc](https://github.com/istanbuljs/nyc) all it takes is:

**.nycrc.json**

```json
...
"require": [
  "ts-node/register",
  "tsconfig-paths/register"
],
...
```
