### ISSUE TITLE
How to debug Gulp tasks written in TypeScript via WebStorm

### ISSUE THREAD

**Issue by hivaga** [TypeStrong/ts-node#221]
First thank you for the plugin I am using it it works so all is great :). I have just one problem I am using WebStorm and kind of can't figure out how to be able to debug my Gulp *.ts files via it.

Currently it looks very easy to debug Gulp tasks in WebStorm when they are written in JavaScript. You just right click on the gulp task from the Gulp Tasks Window and select debug and voila :). 

Here is what happens if I try to debug a Gulp task written with TypeScript:

"C:\Program Files (x86)\JetBrains\WebStorm 2016.2.3\bin\runnerw.exe" "C:\Program Files (x86)\nodejs\node.exe" --debug-brk=64720 --expose_debug_as=v8debug E:\XXXXXXXX\node_modules\gulp\bin\gulp.js --color --gulpfile E:\XXXXXXXX\gulpfile.ts build.js.dev
Debugger listening on [::]:64720
[17:43:13] Requiring external module ts-node/register

Process finished with exit code -1073741510 (0xC000013A: interrupted by Ctrl+C)

I assume that you are compiling the gulp *.ts files then you provide them to Gulp as *.js but this is happening in hidden manner so to say (The gulp *.ts files are compiled in some X location then provided to Gulp as *.js and then deleted, but WebStrom does not know nothing about this and this is the problem.)

You can find a project which use TypeScript to write Gulp tasks here:https://github.com/mgechev/angular2-seed

**Comment by blakeembrey** [comment]
Can you please state the issue? I can't see what you're running into above.

**Comment by hivaga** [comment]
It is not a issue with the ts-node, since it is not a bug or missing functionality. 
The question is have you tried to debug this Gulp *.ts via WebStorm and do you know how this can be done. Since WebStorm is very popular IDE this kind of support or knowledge will be useful to many people who are using TypeScript, Gulp and ts-node.

**Comment by blakeembrey** [comment]
I don't use Webstorm myself, maybe you should ask somewhere like StackOverflow. If I had to hazard a guess, I'll say no. The node devtools don't support source maps properly - see https://github.com/TypeStrong/ts-node/issues/46.
