### ISSUE TITLE
Fast option enables strict mode?

### ISSUE THREAD

**Issue by OliverJAsh** [TypeStrong/ts-node#222]
I ran ts-node with the `--fast` option and noticed my programme failed because the code was not compliant with strict mode. If I emit the `--fast` option, my programme runs, so this seems to suggest `--fast` enables strict mode. Do you know why this is?

**Comment by blakeembrey** [comment]
No idea. It only uses the TypeScript transpiler. Even without `--fast`, it should be in strict mode. Are you using a flag to disable strict in `tsconfig.json`? Perhaps the transpile mode isn't re-using that? Could you share an example for me to look at?
