### ISSUE TITLE
Sharing `ts-node` Temp Directory

### ISSUE THREAD

**Issue by destroyerofbuilds** [TypeStrong/ts-node#225]
The current behavior of `ts-node` on a Linux system is to store transpiled files under a `/tmp/ts-node/` directory.

When the `ts-node` directory is first created the ownership of that directory is assigned to the user creating it. Furthermore, the permissions are 755 (or `rwxr-xr-x`). 

Meaning that on a multi-user system, only the original creator of the `ts-node` directory can use `ts-node` in its default configuration.

Others will get an error like `Error: EACCES: permission denied, mkdir '/tmp/ts-node/f84fcc3f56f0ac645f6723f0333120790d00c88f`.

I received that error while running `gulp` in a directory containing a `gulpfile.ts` file.

Instead, when a temp directory is created by `ts-node`, can that path be `ts-node-HASH` instead of a hashed directory under `ts-node`?

**Comment by blakeembrey** [comment]
Yes, absolutely. Sounds like a good idea.

**Comment by blakeembrey** [comment]
Actually, I'm an idiot. I can't create a random hash as that's the whole point of the shared temp directory, to speed up the startup when nothing has changed. Do you have any ideas? Perhaps we can have better directory default permissions?

**Comment by destroyerofbuilds** [comment]
@blakeembrey I see what you mean by needing to use the same temp directory across runs to gain the benefit of caching.

I'm not sure how we could adjust the directory permissions. Giving everyone read/write access to `ts-node` would be a security risk (I could inject code into the cache of other projects).

Also, the hash is based on the compiler options, so I believe it's possible for individual user's builds to get the same hash. 

Perhaps getting the username and including that in the path would be sufficient (so `/tmp/ts-node-USERNAME/`)?

**Comment by blakeembrey** [comment]
Sounds good. I'm happy to make any change so that it's still consistent for re-use. It may also be possible to use a hash of the current working directory if consistently getting the username across OS turns out to be tricky (haven't investigated). Feel free to make a PR with whichever option you feel is most suitable.

**Comment by egandro** [comment]
Hi,

I also noticed this issue. So here my 5 cents.

1) On Windows this is no problem.

%TMP% and %TEMP% is always set per user and even in Terminal Server enviorments where a user can have multiple logins this unique. Example:

TEMP=C:\Users\foo\AppData\Local\Temp
TMP=C:\Users\foo\AppData\Local\Temp

2) On Unix / OSX this is an isse.

$TEMP is pretty standard and a good choice. I suggest using $HOME/.ts-node-cache instead
(when the OS is Non-Windowish)

- we don't run in permission issues
- the user has his own protection on his/her $HOME drive

There is one (very rare situation) where $HOME is a probelm. For example the program runs under an apache process e.g. the httpd or the postgresd. $HOME is set to some esoteric space /var/lib/foo and the process can't write to that directory.

In this case the cache directory has to be set...

So... this would be my solution upto this point:

// pseudo code ahead
var defaultTmpDir = process.env.TMP;
if(process.platform != 'win32') {
        if(process.env.HOME != '') {
		defaultTmpDir = process.env.HOME + '.ts-node-cache';
	}
}

**Comment by destroyerofbuilds** [comment]
@egandro that's a good point about Windows. We don't technically need to solve the issue on Windows.

That leaves multi-user Unix systems.

I would suggestion against using `.ts-node-cache` directly under `$HOME`.

Instead, using the [XDG defined](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html#referencing) user-specific cache, `$HOME/.cache`, may be more appropriate. It's a well-defined location for temporary files, and avoids another top-level cache folder.

Though, what does the a user-local cache directory buy us that `$TEMP/ts-node-$USERNAME` does not?

**Comment by egandro** [comment]
I wouldn't go with $TEMP on Unix.

You also have to deal with the permissions in ts-node code - and this is NOT - the job of ts-node.

$HOME can be protected by the user (or not). 

$TEMP is always somehow public - only if you do special handling (which just leads to more work + errors in ts-node)

**Comment by shortenda** [comment]
I've forked the repo and I'm going to be implementing a patch to construct a hash of the process cwd to append to the current tmp path (so it'll be like tmpdir() + 'ts-node-' + hash(cwd)). I'm also hoping to write a couple of tests surrounding the cache directory. I'll reference this issue in the PR.

**Comment by inzerceubytovani** [comment]
Any progress here? I fix it by setting ts-node folder permission to group but now I need also make build with another user and I had to change rights also to files in ts-node folder.

**Comment by shortenda** [comment]
@inzerceubytovani I've opened a pull request for this.

**Comment by blakeembrey** [comment]
Merged in https://github.com/TypeStrong/ts-node/pull/267. Thanks @shortenda!
