### ISSUE TITLE
Issue with ts-node + Mocha: 'rootDir' is expected to contain all source files

### ISSUE THREAD

**Issue by bertolo1988** [TypeStrong/ts-node#233]
I am trying to run my tests with mocha and ts-node compiler.

I have a `src` folder with my code and `test` with a few tests.

This is my tsconfig.json:

```js
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "ES6",
        "outDir": "dist",
        "rootDir": "src",
        "sourceMap": true
    },
    "exclude": [
        "node_modules"
    ]
}
```

I am running the following command: `mocha --compilers ts:ts-node/register test/**.ts`
And when i do, i get this:

```bash
TSError: ⨯ Unable to compile TypeScript...
is not under 'rootDir'...
'rootDir' is expected to contain all source files. (6059)
```

Is there any easy way to circumvent this issue without having all the source code and the tests under the `src` folder?

**Comment by bertolo1988** [comment]
I solved this by changing `rootDir` to `rootDirs: ["src","test"],` and it worked.

**Comment by blakeembrey** [comment]
We could probably override `rootDirs`, but I'm not sure if that would introduce any odd side-effects in terms of TypeScript compilation. If someone knows, let me know. /cc @mhegazy

**Comment by bertolo1988** [comment]
Having rootDir and rootDirs is silly indeed.

**Comment by mhegazy** [comment]
why are you using `rootDirs`? I am not sure i see how this is relevant to the error you saw. here is more information about what `rootDirs` mean:http://www.typescriptlang.org/docs/handbook/module-resolution.html#virtual-directories-with-rootdirs

**Comment by dekryptic** [comment]
Any reason why switching from `"rootDir"` to `"rootDirs"` worked? I had the same issue with webpack.config.ts until I switched.
