### ISSUE TITLE
Configure ts-node options with mocha

### ISSUE THREAD

**Issue by jamelt** [TypeStrong/ts-node#234]
I'm looking at the documentation and it looks like you can configure ts-node to work with mocha by registering it as a compiler with the ``--compilers ts:ts-node/register`` option.  

My question is, how do I configure ts-node when using it this way? I see that there are command line options. But how do I pass these command line options like ``-P`` for instance into the mocha usage of ts-node?

The reason I'd like to do this is because I have a ``tsconfig.json`` file in the project root directory and a second one for tests in the ``<project-dir>/test`` folder &mdash; I'd like to use this instead for my ts-node compiler in mocha.

**Comment by blakeembrey** [comment]
The documentation is here: https://github.com/TypeStrong/ts-node#configuration-options. You need to use environment variables or watch for https://github.com/TypeStrong/ts-node/issues/4.

**Comment by blakeembrey** [comment]
Actually, #4 probably doesn't make much sense here - I'd stick with environment variables.

**Comment by RomainLanz** [comment]
Hey everyone!

I'm taking avantage of this issue to ask a question.

I'm starting a new package with TypeScript and I'm configuring everything to be able to test my code and get some code coverage.

The command line that I launch look like `mocha --compilers ts:ts-node/register test/**/*.ts -R spec`.
This allow me to run my test suite without any issues.

I'm struggling with how can I do the code coverage with `ts-node`, `mocha` and [remap-istanbul](https://github.com/SitePen/remap-istanbul) (that seems to be the correct tool).

It will be awesome if you have some idea/solution @blakeembrey.

**Comment by blakeembrey** [comment]
You really should make a new issue as it's unrelated, but you can't. If you look at `remap-istanbul` it works by loading source maps after the fact and re-mapping coverage. `ts-node` is all in-memory so that's not really useful. I recommend just using the `1.0.0` alpha of istanbul, you can read my answer here: https://stackoverflow.com/questions/34027197/how-do-you-use-istanbul-code-coverage-with-transpiled-typescript.

**Comment by jamelt** [comment]
@RomainLanz I had a lot of trouble doing it in memory (coincides with @blakeembrey just stated). I eventually had to produce js files and source maps onto the file system. I ended up using nyc (https://github.com/istanbuljs/nyc). I would recommend it to achieve your objective.

**Comment by jamelt** [comment]
@blakeembrey Thanks for the suggestion! It worked out perfectly.
