### ISSUE TITLE
Unexpected token import (only when used as part of a global node script)

### ISSUE THREAD

**Issue by notoriousb1t** [TypeStrong/ts-node#244]
I'm working on an experiment that transforms.ts files into a .css file.  It uses TypeStyle (FreeStyle) to configure the stylesheet and then dumps the contents of the css to a .css file of the same name.

Here is the code:  https://github.com/notoriousb1t/typestyle-cli

**When I run this directly, it works as intended.**
```bash
Christophers-MacBook-Pro:typestyle-cli cwallis$ node lib/index site.ts
starting...
reading from ../site.ts
writing to /Users/cwallis/sources/typestyle-cli/site.css
exiting: 0
Christophers-MacBook-Pro:typestyle-cli cwallis$ 
```

**When I run this install globally, it says it can't understand import (the bin command is typestyle)**
```bash
Christophers-MacBook-Pro:test-typestyle cwallis$ typestyle site.ts
starting...
/usr/local/lib/node_modules/typestyle-cli/lib/main.ts:1
(function (exports, require, module, __filename, __dirname) { import { TypeStyleWriter } from './TypeStyleWriter';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/typestyle-cli/node_modules/ts-node/src/index.ts:400:14)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/typestyle-cli/node_modules/ts-node/src/_bin.ts:182:12)
    at Module._compile (module.js:541:32)
exiting: 1
Christophers-MacBook-Pro:test-typestyle cwallis$ 
```

I don't know at this point with certainty that this is an issue with ts-node since I haven't worked with global npm scripts, but there are a lot of similar issues in this repo.  

Is there an option I can configure to allow imports?  I am not using this to distribute .ts files as part of an NPM repo.

**Comment by blakeembrey** [comment]
Publish your code as `.js` and not `.ts`. `ts-node` does not, by default, compile files in `node_modules`.

**Comment by blakeembrey** [comment]
Actually, I misunderstood - there's definitely zero chance of running code using ES6 modules in node. This is literally a runtime error telling you it's not possible. If you want ES6 modules in node, you should follow the node EPS (e.g. https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md). What would you expect to happen when you can't use `import` in JS?
