### ISSUE TITLE
Top-level await support in REPL

### ISSUE THREAD

**Issue by aseemk** [TypeStrong/ts-node#245]
Hey there,

Great work on ts-node! I just looked through the code a bit, and you all have clearly put a lot of thought and time into it. Thank you.

One request: I love using the REPL for quick exploration/experimentation/learning. And that often involves async steps, e.g. DB queries or API requests.

Before TypeScript, we used to use [Streamline.js](https://github.com/Sage/streamlinejs), and I loved that its REPL supported making async calls and awaiting their responses:

```
$ _node
_node> fs.stat('/dev/null', _)
{ dev: 1011986504, ... }
_node> r.get('https://httpbin.org/ip', _).body
'{\n  "origin": "1.2.3.4"\n}\n'
_node> ...
```

I understand that TypeScript and ES6/7 as languages don't allow top-level `await` in modules, but would you be open to supporting that in the REPL?

The way the Streamline REPL does it is simply by wrapping the code in an async IIFE, and only calling the REPL `eval` callback once the async IIFE finishes:

https://github.com/Sage/streamlinejs/blob/v2.0.13/lib/repl.js#L23-L42

Thank you in advance for the consideration! Cheers.

**Comment by blakeembrey** [comment]
Off then top of my head, I don't think it's possible to support without more hacking of the TypeScript compiler and/or into the future with ES6 modules. You need an async function for await for await to compile, but you can't import from inside a function (it must be at the top-level). Happy to keep the issue open though.

**Comment by aseemk** [comment]
Thanks for the quick reply!

Could ts-node wrap in async IIFE only if the input had no imports? (And anything else problematic?)

It could still be really valuable to support top-level `await` for simple cases, even if it wasn't supported for more complex ones.

**Comment by simonbuchan** [comment]
Maybe just `.then()` before printing?

```
> fetch('https://google.com').then(r => r.text())
... awaiting promise id: 2 (Ctrl-C to cancel)
'<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">\n<TITLE>302 Moved</TITLE></HEAD><BODY>\n<H1>302 Moved</H1>\nThe document has moved\n<A HREF="http://www.google.co.nz/?gfe_rd=cr&amp;ei=uK12WNbvMMTN8gfyir2ADw">here</A>.\n</BODY></HTML>'
```

Ideally do it more interactively, eg. show the prompt below the currently awaiting promises, print them as they arrive or something, but it's a start.

**Comment by unional** [comment]
Don't support it. 🌷 
https://gist.github.com/Rich-Harris/0b6f317657f5167663b493c722647221

**Comment by unional** [comment]
related topic:
https://gist.github.com/Rich-Harris/0b6f317657f5167663b493c722647221

**Comment by jessedvrs** [comment]
Temporary workaround which blocks the REPL while resolving:

```
const awaiter = promise => { const nothing = Symbol(); let ret = nothing; promise.then(response => { ret = response }); while(ret === nothing) { require('deasync').runLoopOnce(); } return ret; }

const value = awaiter(promise)
```

**Comment by webmaster128** [comment]
There is [top level await in the node 10+ repl](https://github.com/nodejs/node/issues/13209) and it could theoretically be utilized running `node --experimental-repl-await --eval 'require("./node_modules/ts-node/dist/bin.js")'`. However, this is stopped by the TypeScript compiler complaining

```
> const a: string = await Promise.resolve("a")
[eval].ts(1,19): error TS1308: 'await' expression is only allowed within an async function.
```

which is totally right, since top level await is not ([yet?](https://github.com/tc39/proposal-top-level-await)) valid JavaScript but a hack for repl convenience.

I don't see a way to get the `await` keyword untouched through the TypeScript compiler.

**Comment by webmaster128** [comment]
Updated version of @jessedvrs's workaround that works in a type safe fashion:

```
npm install deasync2 --save-dev
# or
yarn add deasync2 --dev
```

```ts
function wait<T>(promise: Promise<T>): T { return require('deasync2').await(promise); }

const value = wait(somePromise);
```

**Comment by blakeembrey** [comment]
@webmaster128 If I understand it, that flag would not do anything for `ts-node` since it would only apply to the default REPL instance. We'd have to go ahead and implement something like https://github.com/nodejs/node/commit/eeab7bc0688256247c47099a90c67741e6637e42 ourselves here. It should be a bit easier to do for us, but we'd need to make sure we're handling all the same things.

**Comment by webmaster128** [comment]
@blakeembrey if you run `node --experimental-repl-await --eval 'require("./node_modules/ts-node/dist/bin.js")'`, then you set `process.binding('config').experimentalREPLAwait = true` via the node command line. This runs our script, which then uses `lib/repl.js` I guess via `require("repl")`. Thus I expect it to work automatically. I think the only one that stops this from working is the TypeScript compiler, that says top level `await` is invalid.

**Comment by blakeembrey** [comment]
@webmaster128 I think there's a misunderstanding. All the code to handle top-level await is within `defaultEval`, which we don't use because we aren't evaling as JavaScript directly. Therefore we need to replicate all the logic to handle this into `ts-node` - the flag won't do anything since it only applies to the node.js REPL and you aren't opening the node.js REPL. The TypeScript compiler fix is the trivial part, we just ignore that diagnostic in the REPL.

**Comment by webmaster128** [comment]
> I think there's a misunderstanding. All the code to handle top-level await is within defaultEval, which we don't use because we aren't evaling as JavaScript directly.

You are probably right. I was a bit too optimistic here and did not follow the core carefully enough.

Would it be possible to implement the `await` keyword in the ts-node REPL using the `wait<T>(promise: Promise<T>): T` function from above?

**Comment by webmaster128** [comment]
> The TypeScript compiler fix is the trivial part, we just ignore that diagnostic in the REPL.

@blakeembrey could you elaborate on that part? I think I have a solution for running top level await in JavaScript utilizing the JavaScript AST (very similar to https://github.com/ef4/async-repl/blob/master/stubber.js and working in out setup). However, I don't know how to teach typescript to pass the `await` untouched from TS code to javascript.

**Comment by blakeembrey** [comment]
There’s a feature in the README that allows you to ignore TypeScript diagnostic codes, it’d just be reusing that from the REPL.

**Comment by webmaster128** [comment]
Thanks @blakeembrey! To make top level `await` available available in JavaScript, you need to do two things:

1. Ignore diagnostics

```ts
    myTypeScriptService = register({
      project: tsconfigPath,
      ignoreDiagnostics: [
        "1308", // TS1308: 'await' expression is only allowed within an async function.
      ],
    });
```

2. Set target to "es2017" or higher. Otherwise an awaiter is generated by TypeScript and `await` is rewritten to `yield`

This works for simple cases like for the cases `await 1` and `await 1 + await 2`.

In other scenarios, TypeScript treats `await` as a variable name, e.g. `await (1)`:

> TSError: ⨯ Unable to compile TypeScript:
> [eval].ts(1,1): error TS2552: Cannot find name 'await'. Did you mean 'waits'?

**Comment by blakeembrey** [comment]
I don’t think we can rely on the target though, can we instead parse and wrap the file before giving to to TypeScript instead? That way, even if it generates the awaiter, the code output will be functional?

**Comment by Pokute** [comment]
Top-level await seems to work at least to some extent with esm package after disabling both 1308 and 2304 diagnostics in source files. `TS_NODE_IGNORE_DIAGNOSTICS=1308,2304 TS_NODE_COMPILER_OPTIONS='{"target":"es6"}'`

Ignoring TS1308 is pretty simple and side-effect free since it seems to be related only to top-level await. Unfortunately TS2304 is required mainly due to `error TS2304: Cannot find name 'await'` and this suppresses all other 'cannot find name' errors.

It doesn't seem to work in command-line REPL though if started without a source file defined.

**Comment by webmaster128** [comment]
> I don’t think we can rely on the target though, can we instead parse and wrap the file before giving to to TypeScript instead?

That would require [this AST manipulation](https://github.com/ef4/async-repl/blob/master/rewrite.js) in TypeScript and not in JavaScript. I think the mayor challenge is how to expose local variables in TypeScript when rewriting:

```ts
let a = await 1;

a // 1
```

as 

```ts
(async () {
  let a = await 1;
})();

a // not available
```

what happens in the JavaScript version is that local declarations are converted to global properties (which only works in non-strict mode), e.g.

```js
let a = await 1;

a // 1
```

becomes

```ts
(async () {
  a = await 1;
})();

a // 1
```

**Comment by blakeembrey** [comment]
@webmaster128 That's a very good point, I didn't consider how the previous JS approach got around this issue either. Why couldn't you do AST manipulation with TypeScript though? I'm not sure myself how mature that API is, but `transforms` do exist as a feature.

Another question, but how would `const` variables be possible here? I guess we can rely on TypeScript type checking to workaround. It looks like in Chrome (and maybe node.js, haven't tested yet), it's rewritten `const` so it's no longer a `const` when using `await`.

**Comment by webmaster128** [comment]
> Why couldn't you do AST manipulation with TypeScript though?

Didn't try it.

>  It looks like in Chrome (and maybe node.js, haven't tested yet), it's rewritten const so it's no longer a const when using await.

Oh, interesting. I thought they had a more sophisticated approach allowing const. The method I use [does not support const either](https://github.com/ef4/async-repl#caveats) on the JS side. But TypeScript takes care of that. But I don't think that converting top level `let`/`const` to `var` semantics in a REPL is a big deal.

Do you have an idea for valid TypeScript that exposes variables declared in an async function body to the global scope?

**Comment by feliperyan** [comment]
Hello everyone, just stumbled on this one. Wondering if there are **simple** instructions on how to start a TS repl with `ts-node` and simply use `async 100` without being hit with:

```[eval].ts:1:1 - error TS1378: Top-level 'await' expressions are only allowed when the 'module' option is set to 'esnext' or 'system', and the 'target' option is set to 'es2017' or higher.```

**Comment by ilyakatz** [comment]
Would love to know if there has been any updates to this one. Is it possible to do?

**Comment by cspotcode** [comment]
@feliperyan have you tried setting options they way the error message tells you to?

**Comment by mmrko** [comment]
Getting along pretty well with wrapping the statement in an async IIFE as suggested above:

```js
  const wrapInAsync = (cmd) => {
    if (!cmd.trim()) return ""

    return `;(async () => {
      return (
        ${cmd}
      )
    })()`
  }

  const replInstance = repl.start()
  const defaultEval = replInstance.eval

  replInstance.eval = (cmd, context, filename, callback) => {
    defaultEval(wrapInAsync(cmd), context, filename, async (error, result) => {
      if (error) return callback(error)

      try {
        callback(null, await Promise.resolve(result))
      } catch (e) {
        callback(e)
      }
    })
  }
```

**Comment by guifel** [comment]
Solutions mentioned here (ignore TS error + `--experimental-repl-await`) work with scripts but not in REPL mode.

**Comment by cspotcode** [comment]
Does anyone know how `node`'s REPL handles top-level await?  Can we use their top-level await mechanism?  Is it exposed as an API?  Can we copy their source code?

Someone will need to propose how we can implement this.

**Comment by dansebcar** [comment]
In case it helps anyone else, I've had good results in REPL mode with `node --require ts-node/register/transpile-only --experimental-repl-await` (using node 14)

**Comment by vamsiampolu** [comment]
I was playing around with the repl today and managed to get it working. Looking at [the issue about native ESM support with ts-node](https://github.com/TypeStrong/ts-node/issues/1007) helped

**Environment**

Node.js Version: lts/fermium (v14.16.0)
Typescript Version: 4.2.2

**Configuration**

package.json (just the important bit to allow treating .js as ES6 modules):

```json
{
  "type": "module",
  "main": "./src/index.js"
}
```

Typescript config (just the important bit):

```json
{
  "compilerOptions": {
     "allowSyntheticDefaultImports": true,
      "target": "es2017",
      "module" "ESNext"
  },
  "include": ["src/**/*"]
}
```

**Usage**

If you are loading a typescript module that has a top level await:

```
node --experimental-top-level-await --loader ts-node/esm ./src/clients.ts
```

```
node --experimental-top-level-await --loader ts-node/esm
```

To import a module within the repl, use dynamic imports.

```js
> const clients = await import('./src/clients.ts')
```

**Comment by ejose19** [comment]
> In case it helps anyone else, I've had good results in REPL mode with `node --require ts-node/register/transpile-only --experimental-repl-await` (using node 14)

It's worth noting this only helps for importing typescript files from the REPL, but you can't use any TS syntax in node REPL, ie: 

```typescript
const foo: string = 'bar';
```

```
const foo: string = 'bar';
      ^^^

Uncaught SyntaxError: Missing initializer in const declaration
```

**Comment by ejose19** [comment]
> Does anyone know how `node`'s REPL handles top-level await? Can we use their top-level await mechanism? Is it exposed as an API? Can we copy their source code?
> 
> Someone will need to propose how we can implement this.

I've inspected the source and it seems it's handled here:

https://github.com/nodejs/node/blob/975bbbc443c47df777d460fadaada3c6d265b321/lib/repl.js#L424-L440

https://github.com/nodejs/node/blob/975bbbc443c47df777d460fadaada3c6d265b321/lib/internal/repl/await.js#L91-L176
