### ISSUE TITLE
@types issue question

### ISSUE THREAD

**Issue by paulsouche** [TypeStrong/ts-node#246]
Hi,

I had an issue compiling mocha unit test with ts-node as it could not find the mocha d.ts in @types. Do I really have to import mocha this way to have describe, it ... declared ?

```typescript
import * as mocha from 'mocha';
```

Normally it should load the d.ts automatically as not excluded in tsconfig. Or am I missing something ?

Error

``
node_modules\ts-node\dist\index.js:160
                    throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset));
                    ^
TSError: ⨯ Unable to compile TypeScript
test\test.ts (7,1): Cannot find name 'describe'. (2304)
test\test.ts (10,3): Cannot find name 'beforeEach'. (2304)
test\test.ts (12,3): Cannot find name 'it'. (2304)
npm ERR! Test failed.  See above for more details.
``

``
node 7.2.0
``

package.json

```json
{
  "scripts": {
    "test": "nyc mocha --recursive --compilers ts:ts-node/register"
  },
  "devDependencies": {
    "@types/chai": "^3.4.34",
    "@types/mocha": "^2.2.33",
    "chai": "^3.5.0",
    "mocha": "^3.2.0",
    "nyc": "^10.0.0",
    "ts-node": "^1.7.0",
    "typescript": "^2.0.10"
  },
  "nyc": {
    "include": [
      "src/**/*.ts"
    ],
    "exclude": [
      "node_modules",
      "build"
    ],
    "extension": [
      ".ts"
    ],
    "require": [
      "ts-node/register"
    ],
    "reporter": [
      "json",
      "html"
    ],
    "all": true,
    "sourceMap": true
  }
}
```

tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "noImplicitAny": true,
    "strictNullChecks": true,
    "outDir": "build",
    "sourceMap": true
  },
  "exclude": [
    "node_modules",
    "build"
  ]
}
```

Btw thanks a lot for the great work !

**Comment by blakeembrey** [comment]
Please see the existing issue, thanks. If you manage to find the issue, that would be useful, but so far it seems related to Windows and is probably a path issue with TypeScript.

**Comment by paulsouche** [comment]
Ok I found it ! I had to 

```typescript
/// <reference types="mocha" />
```

To declare mocha as ambient.

I do not understand of which existing issue you're talking about ? But mine can be closed now.

thanks anyway

**Comment by blakeembrey** [comment]
Try https://github.com/TypeStrong/ts-node/issues/168 or https://github.com/TypeStrong/ts-node/issues/216.
