### ISSUE TITLE
Prettier error messages

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/ts-node#25]
Let's see what can be done with https://github.com/Microsoft/TypeScript/pull/5140, otherwise let's think about it more.

Also relevant: http://flowtype.org/blog/2015/10/07/Version-0.17.0.html

Edit: https://github.com/Microsoft/TypeScript/blob/d5d7a2a2dc50e07d67547e81cde34c2e4d7c0bae/src/compiler/tsc.ts#L410

**Comment by atian25** [comment]
hey, @blakeembrey any plan on this ?

**Comment by whxaxes** [comment]
Is there any progress？
