### ISSUE TITLE
ts-node doesn't work when installed as -g in a package

### ISSUE THREAD

**Issue by egandro** [TypeStrong/ts-node#250]
Hi!

I am trying to create a small ts-node based CLI util. My intension is just to ship the ts files and avoid precompiling the application with js files.

This works fine when running in development in my $projectdir. However after installing the module via npm install -g the ts-node registration for .ts vanishes.

Voila:

file: launcher.js

#!/usr/bin/env node
require('ts-node/register');
require('./lib/cli.ts');

file: lib/cli.ts

import { TestClass } from './test';
TestClass.hello();

file: lib/test.ts

export class TestClass {
	public static hello() {
		console.log('Hello from TestClass');
	}
}

file: package.json

{
  "name": "tscli",
  "version": "1.0.0",
  "bin": {
    "tscli": "launcher.js"
  },
  "dependencies": {
    "@types/node": "^6.0.52",
    "ts-node": "1.7.2",
    "typescript": "^2.1.4",
    "typescript-require": "0.2.9-1"
  },
  "devDependencies": {}
}

$ node launcher.js
Hello from TestClass

$ sudo npm install tscli -g
$ tscli

/usr/local/lib/node_modules/tscli/lib/cli.ts:1
(function (exports, require, module, __filename, __dirname) { import { TestClass } from './test';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/tscli/node_modules/ts-node/dist/index.js:208:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/tscli/launcher.js:3:1)

**Comment by blakeembrey** [comment]
`ts-node` does not, by default, compile files in `node_modules`. The documentation for this can be seen in https://github.com/TypeStrong/ts-node#configuration-options under the ignore option. There's also existing issues on the topic, but promoting this practice is not something I wish to do - it's better to publish JavaScript.

**Comment by egandro** [comment]
Thank you.

That was of great help to me!
