### ISSUE TITLE
ts-node gets stuck 

### ISSUE THREAD

**Issue by testerez** [TypeStrong/ts-node#252]
I have a very strange issue. If I try to run anything with `ts-node`, It gets stuck and does not print anything. Even the simplest example fails: `ts-node -e 'console.log("Hello, world!")'`
I tried to update node, reinstall `ts-node` and `typescript`, same result.
I just realized that it does that only when a `tsconfig.json` is present in the current or parent directory.

```
> ts-node -v && tsc -v
ts-node v1.7.2
node v6.9.2
Version 2.1.4
```

**Comment by blakeembrey** [comment]
You will need to provide more detail for a reproduction, I can't really do anything with it at this point. Do you have an extremely large directory with no excludes in the config file? Maybe it's taking a while to parse the files you specified?

**Comment by testerez** [comment]
I can't reproduce it anymore...
