### ISSUE TITLE
Support tsconfig.json extending (via extends property)

### ISSUE THREAD

**Issue by arusakov** [TypeStrong/ts-node#255]
Also called "Configuration inheritance". It doesn't work now

**Comment by blakeembrey** [comment]
And it worked before?

**Comment by blakeembrey** [comment]
This is unlikely to be an issue with `ts-node` if it worked before. Please check your TypeScript version to make sure the version being used supports the feature.

**Comment by arusakov** [comment]
@blakeembrey 
It didn't work before, because it's new [feature](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#configuration-inheritance) of TS 2.1
I use `ts-node 1.7.3` and `typescript 2.1.4`.

**Comment by blakeembrey** [comment]
Really? It works fine for me without any changes.

**Comment by arusakov** [comment]
@blakeembrey 
I create a little [example](https://github.com/arusakov/upvista/tree/ts-node-repro/ts-node-repro).
In terminal it's without errors:
```
./node_modules/.bin/tsc -p ./src --noEmit
./node_modules/.bin/tsc -p ./test --noEmit
./node_modules/.bin/ts-node -P ./src ./src/1.ts
```
But:
```
./node_modules/.bin/ts-node -P ./test ./test/2.ts

TSError: ⨯ Unable to compile TypeScript
Cannot find global type 'Promise'. (2318)
src/1.ts (1,16): An async function or method must return a 'Promise'. Make sure you have a declaration for 'Promise' or include 'ES2015' in your `--lib
` option. (2697)
    at getOutput (/Users/arusakov/WebstormProjects/upvista/ts-node-repro/node_modules/ts-node/src/index.ts:312:17)
    at /Users/arusakov/WebstormProjects/upvista/ts-node-repro/node_modules/ts-node/src/index.ts:343:18
    at Object.compile (/Users/arusakov/WebstormProjects/upvista/ts-node-repro/node_modules/ts-node/src/index.ts:502:17)
    at Module.m._compile (/Users/arusakov/WebstormProjects/upvista/ts-node-repro/node_modules/ts-node/src/index.ts:406:44)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/arusakov/WebstormProjects/upvista/ts-node-repro/node_modules/ts-node/src/index.t
s:409:12)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```

I can provide any additional info or help with this.

**Comment by blakeembrey** [comment]
This isn't an issue with `extends`, it does work. But it appears that the default configuration we merge is prioritised over `extends`, which makes sense - https://github.com/TypeStrong/ts-node/blob/b2e6990783b6a3bb6fc52d101e625f0a6f6d8861/src/index.ts#L419-L434. I'm not sure on the correct solution as we need to merge those options as some point.

**Comment by arusakov** [comment]
@blakeembrey Thank you, it's clear. We can't reorder merge arguments, why?

**Comment by blakeembrey** [comment]
@Vishal-Isharani If you're after support, please create a separate issue or read the existing thread. Your comment is unrelated and doesn't add anything to the existing discussion.

@arusakov We can definitely move them so that we merge _after_ TypeScript parses them, but I'd need to find the correct TypeScript method for TypeScript to turn the passed in compiler options into their corresponding enum codes. If you know it, happy to make the change and will definitely accept a PR!

**Comment by blakeembrey** [comment]
So considering the fact that all the options minus those two pre-defined defaults need to be used anyway, I opted to just pull those two options out and set them after I parse the content. It should be patched with https://github.com/TypeStrong/ts-node/commit/ec00796677744f3ee60212e14abb0abb69a64218 now.
