### ISSUE TITLE
--require flag does not load from node_modules

### ISSUE THREAD

**Issue by jonaskello** [TypeStrong/ts-node#257]
As added in #181 ts-node accepts a --require flag. When trying to use this with the [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) package it fails to locate the package. Example:

```
$ ts-node -r tsconfig-paths main.ts 
Error: Cannot find module 'tsconfig-paths'
```

The reason seems to be [this line](https://github.com/TypeStrong/ts-node/blob/master/src/_bin.ts#L165) which does `Module._load(id)` in order to require the modules specified by `--require`. If it is changed to `require(id)`it will locate the package. It seems like `Module._load(id)` skips loading from `node_modules`. 

The `mocha` package also has a `-r` option and looking [here](https://github.com/mochajs/mocha/blob/master/bin/_mocha#L344) it seems they use `require` to load the modules rather than `Module._load`. So this example works:

```
$ mocha --compilers ts:ts-node/register -r node-tsconfig-paths mocha-example.ts
```

**Comment by blakeembrey** [comment]
We shouldn't technically be doing `require` as that could result in loading our own dependencies instead of the users, which would be a confusing situation. I believe this code was based on the `node` CLI itself here: https://github.com/nodejs/node/pull/881. I'm not sure about the current implementation in node anymore, I'll need to find out how to do a better implementation.

**Comment by blakeembrey** [comment]
Found it. Let's use `_preload_modules` found here: https://github.com/nodejs/node/blob/0fb21df6e692bef9f55b9bfa876f3c59dc590332/lib/internal/bootstrap_node.js#L391. We may need to fallback to `Module._load` on older node.js versions (I can't recall if this ever worked now, I'll check though).

**Comment by jonaskello** [comment]
Nice! I'm collaborating with @jontem on the `node-tsconfig-paths` package and he'll make a PR for this.

**Comment by blakeembrey** [comment]
Looks like this should have been resolved with https://github.com/TypeStrong/ts-node/pull/258 IIRC.
