### ISSUE TITLE
Command history support

### ISSUE THREAD

**Issue by jussiarpalahti** [TypeStrong/ts-node#259]
It seems that command history doesn't work, though it is a feature of regular node: https://nodejs.org/api/repl.html#repl_persistent_history

ts-node works great as a REPL for writing TypeScript and testing TS libraries, thank you. Access to command history is a big part of my regular REPL workflow so I'd be interested to having support for this.

I tested this on MacOS and Ubuntu, using node 6.5 and 7.3.

**Comment by blakeembrey** [comment]
Closed with https://github.com/TypeStrong/ts-node/commit/35d8a0c9357afe87955353c0d761554d6e5b9864. Supported on node.js 11+
