### ISSUE TITLE
Pass --max-old-space-size flag through to Node

### ISSUE THREAD

**Issue by danvk** [TypeStrong/ts-node#261]
This controls the amount of memory that the node process is able to use.

**Comment by danvk** [comment]
Huh, it's `--max-old-space-size` for the `node` command, but `--max_old_space_size` works with `ts-node`.

**Comment by juhoojala** [comment]
Is this information still accurate? Maybe this should be added to the documentation?

**Comment by blakeembrey** [comment]
See https://github.com/TypeStrong/ts-node#programmatic.

**Comment by zixia** [comment]
I'd like to put the answer right at here because this thread is on top of the google search ''ts-node max-old-space-size"

```sh
node -r ts-node/register --max-old-space-size
```

**Comment by aanno2** [comment]
> 
> 
> I'd like to put the answer right at here because this thread is on top of the google search ''ts-node max-old-space-size"
> 
> ```shell
> node -r ts-node/register --max-old-space-size
> ```

Ok, this makes it possibe to pass node options. However, with this solution I wonder how to pass ts-node options (like `--project`, `-P`).

**Comment by taehapark** [comment]
> > I'd like to put the answer right at here because this thread is on top of the google search ''ts-node max-old-space-size"
> > ```shell
> > node -r ts-node/register --max-old-space-size
> > ```
> 
> Ok, this makes it possibe to pass node options. However, with this solution I wonder how to pass ts-node options (like `--project`, `-P`).

You can set `TS_NODE_PROJECT` env for `--project`.

**Comment by mrbar42** [comment]
since there is no obvious answer in this thread, here's how i ended up adding the flag:
```sh
node --max-old-space-size=4096 -- node_modules/.bin/ts-node -P tsconfig.json index.ts
```

**Comment by jpike88** [comment]
why not just add a flag to ts-node and have it work as a passthrough?

**Comment by cspotcode** [comment]
ts-node does not actually invoke a node process.  By the time ts-node is executing, it is already within a node process, and we don't want to invoke another one.  So passing CLI flags to node is not something we can do.  If we were to conditionally spawn a node process based on certain flags, this would add a bunch of complexity.

The recommended solution, mentioned [here](https://github.com/TypeStrong/ts-node/issues/261#issuecomment-402093879), is also explained in our README.
https://github.com/TypeStrong/ts-node#programmatic

Use `node -r ts-node/register` which allows passing any `node` arguments and specifying any `ts-node` options via environment variables and/or a `"ts-node"` sub-object in tsconfig.json.

**Comment by blakeembrey** [comment]
Basically what @cspotcode said. We used to do this, then there were numerous requests for other flags to pass through. I believe it also created some obscure issues. Honestly just wasn't something we had bandwidth to maintain, and node's `--require` is already pretty great.

**Comment by KEMBL** [comment]
> ```shell
> node --max-old-space-size=4096 -- node_modules/.bin/ts-node -P tsconfig.json index.ts
> ```

guys, I had an error with that solution: 

`SyntaxError: missing ) after argument list`

for me it works fine with that fix:

`node --max-old-space-size=4096 -- node_modules/ts-node/dist/bin -P tsconfig.json index.ts`

ts-node: 8.10.1

**Comment by beenotung** [comment]
@KEMBL in your case, node_modules/.bin/ts-node maybe a shell script

**Comment by beenotung** [comment]
> ```shell
> node --max-old-space-size=4096 -- node_modules/ts-node/dist/bin.js -P tsconfig.json index.ts
> ```

It works for some case, but if you used advanced features, may get the error of `Error: Cannot find module 'tslib'`

**Comment by cspotcode** [comment]
Without seeing a reproduction, this sounds like a problem with your code,
not ts-node.

**Comment by sgentile** [comment]
> See https://github.com/TypeStrong/ts-node#programmatic.

I see you have posted this several times, however it's not clear where to put max_old_space_size

**Comment by sgentile** [comment]
> ts-node does not actually invoke a node process. By the time ts-node is executing, it is already within a node process, and we don't want to invoke another one. So passing CLI flags to node is not something we can do. If we were to conditionally spawn a node process based on certain flags, this would add a bunch of complexity.
> 
> The recommended solution, mentioned [here](https://github.com/TypeStrong/ts-node/issues/261#issuecomment-402093879), is also explained in our README.
> https://github.com/TypeStrong/ts-node#programmatic
> 
> Use `node -r ts-node/register` which allows passing any `node` arguments and specifying any `ts-node` options via environment variables and/or a `"ts-node"` sub-object in tsconfig.json.

do you have an example of this ?

I tried this but I get no output to confirm it when i run ts-node

```
{
    "ts-node": {
        "maxOldSpaceSize": 8196
    },
```

**Comment by FireworksX** [comment]
If you use ESM for ts-node
```
node --loader ts-node/esm -r ts-node/register --max-old-space-size=8192 ./server/boot.ts
```
