### ISSUE TITLE
Tests are only full bash compatable

### ISSUE THREAD

**Issue by Cyken-Zeraux** [TypeStrong/ts-node#262]
When running 'npm test' for this project under Windows 10, in cmd, the 'piping' tests fail:
https://gist.github.com/Cyken-Zeraux/1691d60ea9840637bc628e0279e849f4

This appears to be due to the '|' (pipe) operator, which is a bash utility. Cygwin with Git-Bash also did not work, resulting in the same errors. Native Windows-Ubuntu bash support worked perfectly, all passing.

Related version information in the output above is the same for windows cmd and git-bash cygwin.

**Comment by wedneyyuri** [comment]
What do you think about skipping this test while running on Windows? We can do assertions based on `process.platform`

**Comment by blakeembrey** [comment]
We can also Windows-ify it by using node streams instead (pipe into, pipe out of, etc).

**Comment by blakeembrey** [comment]
Should be resolved with https://github.com/TypeStrong/ts-node/commit/b251147375a242bacc6de146ea9fe6445fcd532a.
