### ISSUE TITLE
Not support refer class from other file

### ISSUE THREAD

**Issue by justforuse** [TypeStrong/ts-node#264]
I'm new, and when I create a Dog class which extends Animal lass that defined in other file, and I run `ts-node child.ts`.and then  `ReferenceError: Animal is not defined`.occured.
Here is my code:
child.ts:
```
///  <reference path="parent.ts" />

class Dog extends Animal{
    kind:string;
    constructor(name:string, kind:string){
        super(name);
        this.kind =kind;
    }
    getKind(){
        return this.kind;
    }
}

var dog = new Dog("myDog", "Hasuki")
console.log(dog.getName());
console.log(dog.getKind());
```

and parent.ts
```
class Animal{
    name:string;

    constructor(name:string){
        this.name = name;
    }
    getName(){
        return this.name;
    }
}
```

Wheret's wrong? or is ts-node not support?

**Comment by blakeembrey** [comment]
This will never be supported, you need to use CommonJS just like you do with node. Please search existing issues before filing a new one.
