### ISSUE TITLE
Incorrect order of extend()ing compilerOptions 

### ISSUE THREAD

**Issue by terasaka2k** [TypeStrong/ts-node#27]
In ts-node.ts around line 80,

```ts
  config.compilerOptions = extend({
    target: 'es5',
    module: 'commonjs'
  }, config.compilerOptions, {
    sourceMap: true,
    inlineSourceMap: false,
    inlineSources: false,
    declaration: false
  })
```

should be

```ts
  config.compilerOptions = extend({
    sourceMap: true,
    inlineSourceMap: false,
    inlineSources: false,
    declaration: false
  }, config.compilerOptions, {
    target: 'es5',
    module: 'commonjs'
  })
```

for `{ target: 'es5', module: 'commonjs' }` to take precedence over user's options, which potentially may be intended for latest browsers environments.

**Comment by blakeembrey** [comment]
@terasaka2k This is correct. The `sourceMap

**Comment by darthtrevino** [comment]
Consider this use case: I'm using webpack to chain the typescript-loader and the babel-loader together to take advantage of babel's hook runtime for things like HMR. I want my tsconfig.json to target ES6 and let the babel-loader transpile from ES6 to ES5 for browsers.

However, in my server code, I want to go straight from TS to ES5. I would like to be able to do this:

```
# index.js - server entry point
require('ts-node').register({
    compilerOptions: {
        target: 'es5'
    }
})
```
And then what I would expect to happen in ts-node would be something like:
`Object.assign({}, defaultConfig, tsConfigFromFile, tsConfigFromArgs)`

**Comment by blakeembrey** [comment]
@darthtrevino I'm not sure who you're responding to, but that's how it works already and the reason I closed the issue. However, there's no `compilerOptions` pass in to `ts-node`, it's all from `tsconfig.json`.

**Comment by blakeembrey** [comment]
It sounds like you're actually after a different feature? The ability to pass in compiler options that override `tsconfig.json`?

**Comment by darthtrevino** [comment]
Correct

**Comment by blakeembrey** [comment]
@darthtrevino https://github.com/TypeStrong/ts-node/issues/54

**Comment by darthtrevino** [comment]
Sweet! Thanks @blakeembrey !
