### ISSUE TITLE
requires typings for node

### ISSUE THREAD

**Issue by coopernyc** [TypeStrong/ts-node#272]
If I use a new way of loading tds via
npm i -D @types/node 

https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

ts-node failed with compilation exceptions, because it requires typings for node

I have to uninstall @types/node and reinstall typings then typings install env~node... in order for ts-node to work again

**Comment by blakeembrey** [comment]
Are you on Windows? You should search existing issues before logging a new one, see https://github.com/TypeStrong/ts-node/issues/216 and logged exactly one issue before this one is #271.
