### ISSUE TITLE
(feat request) TypeScript definitions

### ISSUE THREAD

**Issue by michaeljota** [TypeStrong/ts-node#273]
I know this only would use them to say 'register' and for the config object, but it still would be useful I think.

**Comment by blakeembrey** [comment]
They exist using Typings - see https://github.com/TypeStrong/ts-node/blob/master/typings.json. We can't use `@types` or provide one natively because I'm still waiting on https://github.com/Microsoft/types-publisher/issues/4.

**Comment by michaeljota** [comment]
I did not mean for development of the module, but for the use of the module. This module could have a index.d.ts and being declared in the `package` for IDE and editors with TSD awareness work with. 

I don't know if I explained it correctly.

**Comment by blakeembrey** [comment]
That's the same thing.
