### ISSUE TITLE
Error when usage with nodemon

### ISSUE THREAD

**Issue by perevezencev** [TypeStrong/ts-node#275]
Hi all, i try run ts-node with nodemon, like this:
`nodemon('. --exec ts-node')

and i get this error:

![image](https://cloud.githubusercontent.com/assets/5954104/23183522/6a9a2652-f88d-11e6-8b0e-292747e905cb.png)

my **tsconfig.json**
```
{
  "compilerOptions": {
    "noEmit": true,
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es5",
    "jsx": "react"
  },
  "awesomeTypescriptLoaderOptions": {
    "silent": true,
    "useBabel": true
  },
  "include": [
    "./src/**/*"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by blakeembrey** [comment]
Can you please give more information about how you're using `ts-node`? I don't see the command you're running in the screenshot and I'm also pretty sure it's impossible to get that error - there's code that's explicitly ignoring the error. What version of `ts-node` are you using?
