### ISSUE TITLE
Add support for pre-populating REPL context

### ISSUE THREAD

**Issue by ssalka** [TypeStrong/ts-node#276]
With node repl, I can do something like:

```
const repl = require('repl');
repl.context.something = 'I am defined';
repl.start();

...

> something
// 'I am defined'
```

I'm currently doing this in a JS repl to load frequently used libraries (lodash, moment, ...) and would like to do the same thing w/ TS-node, but it looks like the feature is not yet supported.

**Comment by blakeembrey** [comment]
I don't understand the feature/issue. You're writing JavaScript to populate the REPL context? Can you explain how that's related to `ts-node`?
