### ISSUE TITLE
'__extends' is not defined?

### ISSUE THREAD

**Issue by sdemurjian** [TypeStrong/ts-node#277]
I'm getting this in my project using a standard ts config, and compiling with ts-node.

Simple code throws this error:
```

    class Animal {
      private name: string;
      constructor(theName: string) { this.name = theName; }
    }

    class Rhino extends Animal {
      constructor() { super("Rhino"); }
    }
```

It doesn't throw an error in es6, only es5...but I'm compiling to es5 in other projects and have never had a problem.

This error does not occur when using `tsc`.

**Comment by blakeembrey** [comment]
Can you provide more information? Maybe a `tsconfig.json` file? That function is injected using `tsc` - did you try running the file `tsc` spat out? Can you check if the output from `tsc` has that function defined?

**Comment by sdemurjian** [comment]
hmm I was actually mistaken, it does not work with es5 with tsc as well. Here's my tsconfig.json, I think I just copied it from another project.

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "allowSyntheticDefaultImports": true,
        "sourceMap": true,
        "noEmit": true,
        "noEmitHelpers": true,
        "strictNullChecks": false,
        "lib": [
            "dom",
            "es6"
        ],
        "typeRoots": [
            "node_modules/@types"
        ],
        "types": [
            "body-parser",
            "compression",
            "cookie-parser",
            "express",
            "express-session",
            "helmet",
            "method-override",
            "morgan",
            "node",
            "passport",
            "sequelize",
            "winston"
        ]
    },
    "exclude": [
        "node_modules"
    ],
    "awesomeTypescriptLoaderOptions": {
        "forkChecker": true,
        "useWebpackText": true
    },
    "compileOnSave": false,
    "buildOnSave": false,
    "atom": {
        "rewriteTsconfig": false
    }
}
```

**Comment by blakeembrey** [comment]
It would be `noEmitHelpers`, I believe - that tells it to skip emitting all the helper functions like `__extends` and you are then responsible for adding the helpers yourself (e.g. https://github.com/Microsoft/tslib).

**Comment by sdemurjian** [comment]
thanks, appreciated
