### ISSUE TITLE
Don't support latest @types/xxx typings definition.

### ISSUE THREAD

**Issue by twoeo** [TypeStrong/ts-node#278]
**Reproduction**

```ts
//index.ts
const path = require('path');
```

```
npm install @types/node
ts-node index.ts
```

**Result**
Get Error: 
> TSError: ⨯ Unable to compile TypeScript
test.ts (1,14): Cannot find name 'require'. (2304)

This will works well.
```
tsc -p .
node index.js
```

**Comment by blakeembrey** [comment]
Are you on Windows? I believe there's half a dozen copies of this and anyone is free to submit a PR that fixes. See https://github.com/TypeStrong/ts-node/issues/216 for the open issue.
