### ISSUE TITLE
can't run in existing project with node_modules

### ISSUE THREAD

**Issue by snapwich** [TypeStrong/ts-node#28]
For some reason command line ts-node seems to search the local node_modules folder even when there are no references to it in the file you run.  Also, if I run ts-node to get a REPL and execute any command inside a project that has typescript in it, but also have typescript installed globally, I get thousands of duplicate identifier errors.

If I remove typescript from the local project, I get ````node_modules/autoprefixer-loader/node_modules/postcss/postcss.d.ts (2,22): Cannot find module 'd.ts/postcss'. (2307)
node_modules/autoprefixer-loader/node_modules/postcss/postcss.d.ts (3,2): Duplicate identifier 'default'. (2300)````

so it appears to search my node_modules folder for all kinds of definitions and then throw a bunch of errors before it evaluates the first line of typescript.  I get the same errors running an empty typescript file.  Is this expected behavior?

**Comment by blakeembrey** [comment]
`ts-node` requires the `typescript` module relative to the executable. If you're running `ts-node` locally, it'll require `typescript` locally. There's nothing happening globally, unless you have both `ts-node` and `typescript` globally. I don't believe there's ever a point where an overlap occurs.

If you have a case where this can be reproduced, I'd appreciate some more details. It sounds like you're running into a TypeScript issue though, and you're using modules that have duplicate type definition references.

**Comment by snapwich** [comment]
It seems to be related to my tsconfig.json.  

I was able to recreate it in a separate empty repository by having a local ts-node@0.5.0 and typescript@1.6.2 and a tsconfig.json with the following:
````
{
  "compilerOptions": {
    "module": "commonjs"
  }
}
````
this causes any form of ts-node that runs to error out with hundreds of duplicate identifier errors.  Is that compiler option incompatible with ts-node?

**Comment by blakeembrey** [comment]
Any `tsconfig.json` file without `files` specified will automatically glob all files in the directory. It's definitely not incompatible, are you sure this is a completely empty directory?

![image](https://cloud.githubusercontent.com/assets/1088987/11078198/404a4cd8-87b9-11e5-8dbd-0520144cc9bd.png)

**Comment by blakeembrey** [comment]
@snapwich Have you tried using it with `tsc`? What happens then?

**Comment by snapwich** [comment]
this is the contents of the new project

````
.
./node_modules
./node_modules/.bin
./node_modules/ts-node
./node_modules/typescript
./package.json
./test.ts
````

so is it globbing through my node_modules then?

**Comment by blakeembrey** [comment]
Yes, that's the default behavior of TypeScript too. This describes your issue: https://github.com/Microsoft/TypeScript/issues/3289.

**Comment by snapwich** [comment]
that looks like the problem.  thanks for your help

**Comment by snapwich** [comment]
@blakeembrey reading further into this, it looks like this still may be a ts-node problem as far as pulling in files.

on https://github.com/Microsoft/typescript/wiki/tsconfig.json it says "When input files are specified on the command line, tsconfig.json files are ignored." which does seem to be the case with tsc.  With the given tsconfig.json above: ```tsc test.ts``` compiles the file correctly without globbing through my node_modules but ```ts-node test.ts``` seems to ignore the test.ts specified if tsconfig.json is present and starts the globbing.

**Comment by blakeembrey** [comment]
That's documentation for `tsc`, `ts-node` uses the same behaviour as other loaders and tooling and will import files from `tsconfig.json`. This is required for `.d.ts` files to be properly loaded, otherwise you would need to manually recreate the files object in the CLI.

**Comment by blakeembrey** [comment]
I could add a `--noFiles` flag to ignore `tsconfig.json` files - but it's a pretty bad patch as I imagine you'll need it enabled again eventually for `.d.ts` files and we'll be back at square one.

**Comment by snapwich** [comment]
I use ````/// <reference path="./general.d.ts" />```` in my .ts files to include .d.ts definitions.  Is that not sufficient?

I'm not sure the standard convention for most typescript projects, but a root entry point with typescript references is what was recommended with the webpack typescript loader I am using, which is also why I have a tsconfig.json file in the root folder with no files currently.

**Comment by blakeembrey** [comment]
Yes, you can use that. I recommend against references in personal TypeScript projects and would advocate for using `files` in `tsconfig.json` instead. They can be used the same way here, except you don't need to duplicate that line into every single file. If you use `files` in `tsconfig.json` too, this issue will disappear for you.

**Comment by snapwich** [comment]
Unfortunately I can't use tsconfig.json "files" for my webpack typescript loader files, but it would be nice if I could share my tsconfig.json across my client and server-side code.  

Is there any harm that would come from having ts-node emulate tsc's behavior of ignoring the tsconfig.json "files" when the entry files are present on the command line?

**Comment by blakeembrey** [comment]
@snapwich Why not? What `ts-loader` are you using, I've reviewed them all at times. That's not what `tsc` does, when you specify files it ignore the entire `tsconfig.json`. You can emulate that with `--noProject` specified.

**Comment by snapwich** [comment]
@blakeembrey you're right. it looks like ````-noProject```` is the solution for me then.  Thanks again.
