### ISSUE TITLE
Unable to compile ES2017 (needed for native async support in node 7.6) 

### ISSUE THREAD

**Issue by mmc41** [TypeStrong/ts-node#280]
Node just released node 7.6 with native async support which I am eager to try out. Recent versions of typescript already supports es2017 and works fine but the otherwise great **ts-node** unfortunately provides an error: 

```
...node_modules/ts-node/src/index.ts:206
      throw new TSError(formatDiagnostics(configDiagnostics, cwd, ts, 0))
            ^
TSError: ⨯ Unable to compile TypeScript
Argument for '--target' option must be:  'es3', 'es5', 'es6', 'es2015' (6046) 
```

**Comment by blakeembrey** [comment]
This is an error from TypeScript, not `ts-node`. Maybe you can try updating your `typescript` version?

**Comment by jephir** [comment]
This happens because `target` is overriden to 'es5' in ts-node.

https://github.com/TypeStrong/ts-node/blob/b2e6990783b6a3bb6fc52d101e625f0a6f6d8861/src/index.ts#L419-L434

Use the `--compilerOptions '{"target":"es6"}'` flag to get it to work.

**Comment by blakeembrey** [comment]
No, it's not. Maybe you should learn how `extend` works, those are just default options if you don't submit any configuration. The default using TypeScript normally is ES3 anyway.

**Comment by intellix** [comment]
the --compilerOptions arg mentioned by jephir fixes this for me. 
I'm using this: https://github.com/RyanCavanaugh/learn-a

Perhaps it's a fresh issue caused by project references? I'm getting the following error:
```
TSError: ⨯ Unable to compile TypeScript:
error TS2468: Cannot find global value 'Promise'.
packages/api/src/index.ts(235,18): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
packages/api/src/index.ts(251,39): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
```

**Comment by blakeembrey** [comment]
@intellix You aren't specifying a `--project` so it's loading https://github.com/RyanCavanaugh/learn-a/blob/master/packages/tsconfig.json which has no configuration. There's no way for `ts-node` to automatically infer which `tsconfig.json` you should use right now - it's just the same rules as `tsc`. Loads from current directory, etc. No support for project references right now.
