### ISSUE TITLE
Files option ignored in tsconfig

### ISSUE THREAD

**Issue by moshie** [TypeStrong/ts-node#282]
I have a phantomjs file which needs to be compiled outside of the executed code (this file is being fired off as a child process)

I can't simply include the file in the executing code as phantomjs is a different process to node so none of the packages / functions are available.

ts-node from what I can see doesn't output the file I have specified in the tsconfig, so when the child_process comes to run it, the file doesn't exist.

I am unsure of how I can force ts-node to compile the file `"src/screenshot.phantomjs.ts"` before node runs?

I have run `tsc` and the file compiles fine?

```json
{
    "compilerOptions": {
        "target": "es5",
        "outDir": "dist",
        "module": "commonjs",
        "declaration": true,
        "noImplicitAny": false,
        "strictNullChecks": true,
        "removeComments": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "inlineSources": true
    },
    "exclude": [
        "node_modules"
    ],
    "files": [
        "src/screenshot.phantomjs.ts"
    ]
}
```

**Comment by blakeembrey** [comment]
If you want to compile files into JavaScript, you should be using `tsc`. Even if `ts-node` did compile "files", how would you use the output other than requiring it inside of node? This module is for running TypeScript files under `node`. If you really want to use child process with TypeScript files, use `ts-node` to execute it.
