### ISSUE TITLE
Importing  json file with suffix

### ISSUE THREAD

**Issue by fbarnard** [TypeStrong/ts-node#289]
Hi

i am trying to import a json file if i do it this way

`import * as config from "./../config.json!config"`

**d.ts**
`declare module "*!config" {

    const value: IConfig;

    export = value;
}`

It does not want to work but this way works

`import * as config from "./../config.json"`

**d.ts**
`declare module "*.json" {

    const value: IConfig;

    export = value;
}`

iI would prefer to use a suffix to denote the type (first example)

I get "Cannot find module './../config.json!config'"

thanks

**Comment by blakeembrey** [comment]
Node.js doesn't support any sort of `!` notation.
