### ISSUE TITLE
readConfig should enforce "module":"commonjs"

### ISSUE THREAD

**Issue by brad-jones** [TypeStrong/ts-node#293]
Until node supports es6 modules fully, it makes no sense to have typescript transpile to anything other than commonjs.

My project uses a tsconfig.json file with:
```json
{
    "compilerOptions": {
        ...
        "module": "es6",
        ...
    }
}

```
And thus ts-node fails with my typescript gulp file.

All I am suggesting is to add:
```js
result.config.compilerOptions.module = 'commonjs';
```

Alternatively if #4 was developed, it could possibly solve this issue as well.

**Comment by blakeembrey** [comment]
No thanks.

**Comment by brad-jones** [comment]
Some explanation would be nice...

Do you have a suggested work around for the problem?

**Comment by blakeembrey** [comment]
What didn't you like about the explanation? It's in the comment above.

**Comment by brad-jones** [comment]
Huh? All you said was "No thanks".

**Comment by blakeembrey** [comment]
Please just scroll up.

**Comment by brad-jones** [comment]
Ok now github has loaded your edited comment.

**Comment by blakeembrey** [comment]
No worries, I didn't add it initially when I hit enter but I edited it back in before you commented. Sorry for the confusion. I was trying to find a similar issue to this one from the past for reference, but couldn't find it. I'll try again now.

**Comment by blakeembrey** [comment]
See https://github.com/TypeStrong/ts-node/issues/212.

**Comment by blakeembrey** [comment]
By the way, are you using the CLI or with Gulp/mocha/etc? If you're using the CLI, it's very easy to use the `-P` option and TypeScript's new `extends` with `tsconfig.json`. It mostly resolved #4 for me to.

**Comment by brad-jones** [comment]
Using gulp. I noticed definitions were released for Gulp v4 recently so thought I would have a crack at a typescript build pipeline.

Right now I have done this:

_gulpfile.js_
```js
// Gulp tasks are written in typescript.
// We use https://github.com/TypeStrong/ts-node to transpile on the fly.
require('ts-node').register
({
    // Typechecking will be done by your IDE anyway,
    // so lets not bother doing it at runtime.
    fast: true,
    
    // Node does not yet understand ES6 modules
    compilerOptions:
    {
        module: "commonjs"
    }
});

// Load all tasks from the tasks directory.
require('require-dir')('./tasks', { recurse: true });
```

**Comment by blakeembrey** [comment]
Cool, that looks like it should work. FWIW, Gulp does load `gulpfile.ts` for you automatically. The issue there, however, is what #4 attempts to solve since there's no easy way to inject custom compiler options in that situation. The best thing to do there might be to use `tsconfig.json` with `extends` on your ES6 config file - not sure if you need the ES6 specific module in the editor and other automatic discovery situations?
