### ISSUE TITLE
Path mapping resolution support?

### ISSUE THREAD

**Issue by Axure** [TypeStrong/ts-node#294]
According to these issues:
- [Using baseUrl and paths on node](https://github.com/Microsoft/TypeScript/issues/9259)
- [Path mapping should relative path ?](https://github.com/Microsoft/TypeScript/issues/9910)
, TypeScript preserves the original module specifier when they are actually resolved via path mapping. But this will prevent `ts-node` to execute such code. A demo is [here](https://github.com/Axure/ts-node-path-mapping-demo).

The TS team has said that they won't change this, since making such code running is non of their business. So what is `ts-node`'s attitude towards this?

**Comment by Jontem** [comment]
As i understand it `ts-node will` not support this because isn't how node works. This topic has been discussed before in these issues #219 and #138. 

Out of that came the [tsconfig-paths](https://github.com/jonaskello/tsconfig-paths) package that acts as a plugin that you can use with `ts-node` to use path mappings with `node`.

**Comment by blakeembrey** [comment]
I personally don't have any desire to implement this in `ts-node`. It'd deviate from exactly what TypeScript is saying - this isn't something native in node or something TypeScript does, so `ts-node` shouldn't be doing it. I'd recommend using a plugin like `tsconfig-paths` which @Jontem mentioned above. I don't really want this module doing anything magical, it should just be a layer for doing it's job - running TypeScript on node as though you'd done `tsc && node`. I'd be happy to take a PR adding that module to the README though, but note that using path mapping means it'll make your project less portable.

**Comment by jonaskello** [comment]
@blakeembrey I did a PR adding `tsconfig-paths` information to the readme in #295.

**Comment by joonhocho** [comment]
I've created a compile-time solution. https://github.com/joonhocho/tscpaths

https://github.com/Microsoft/TypeScript/issues/15479#issuecomment-427539118
