### ISSUE TITLE
Is there a ts-node hashbang?

### ISSUE THREAD

**Issue by atrauzzi** [TypeStrong/ts-node#298]
If I wanted to use a `.ts` file as an entrypoint, wouldn't I want to have a hashbang that indicates such?

For nodejs scripts, you put this at the top of the file:

```
#!/usr/bin/env node
```

Wouldn't it then make sense to have;

```
#!/usr/bin/env ts-node
```

???

**Comment by blakeembrey** [comment]
It should work as you've described. See https://github.com/TypeStrong/ts-node/issues/73 and https://github.com/TypeStrong/ts-node/issues/116.
