### ISSUE TITLE
Global type defs from typings are not available

### ISSUE THREAD

**Issue by Ramblurr** [TypeStrong/ts-node#299]
Here on OSX, using `v3.0.2` global type defs aren't being picked up when using the standard mocha incantation: `mocha --opts src/test/mocha.opts "test/**/*ts"`

My tsconfig.json has:
```
 "include": [
    "typings/**/*.d.ts",
    "src/**/*.ts"
  ],
```

And the typings defined under `/typings` are all under `/typings/globals`. 

All type references of a global type result in a `ReferenceError` when ran under mocha+ts-node. (I thought it might have something to do with the fact that `test/` was a sibling of `src/` so I moved it under src to be a child, but the problem remains.) While the standard tsc build has no issues.

The project itself [is here](https://github.com/Ramblurr/screeps-typescript-starter), with the failing test at [test/global.test.ts](https://github.com/Ramblurr/screeps-typescript-starter/blob/master/test/global.test.ts). A clone, then `npm install; mocha` should illustrate the issue.

Perhaps I mis-understand how ts-node is supposed to work, but I would also expect these globals to be available in the REPL, but they aren't.

```
$ node ./node_modules/ts-node/dist/bin.js
> RESOURCE_ENERGY
ReferenceError: RESOURCE_ENERGY is not defined
```

One final observation, the other type defs in `node_modules/@types` are available: chai, and sinon, as they are imported in the tests without a problem. It's just the globals under `typings` that have the issue.

**Comment by blakeembrey** [comment]
A `ReferenceError` is JavaScript runtime. They can't magically appear because you have a definition, you actually need to put it in the global somehow (e.g. `global.RESOURCE_ENERGY = ''`).

**Comment by blakeembrey** [comment]
You can verify this by running `node` after `tsc`. You will get the same error for the same reason - `tsc` is only dealing with compile time and if you said something exists, it exists for the compiler. But you are now in charge of making sure it actually does exist at runtime.

**Comment by Ramblurr** [comment]
@blakeembrey Doh, of course. It was late last night.  I've got it working heh.

Thanks for the reply, and apologies for taking your time!
