### ISSUE TITLE
Allow multi-line REPL prompts like node

### ISSUE THREAD

**Issue by blakeembrey** [TypeStrong/ts-node#3]
Node appears to handle this by detecting syntax errors. I can probably catch compilation errors and check the error codes are syntax errors too and recover from that.

Relevant: https://github.com/joyent/node/blob/d13d7f74d794340ac5e126cfb4ce507fe0f803d5/lib/repl.js#L125-L129

**Comment by Igorbek** [comment]
@blakeembrey hey, do you have any update on this?

**Comment by blakeembrey** [comment]
See the linked issue in node.

**Comment by robey** [comment]
Looks like this still exists in ts 2.0.

**Comment by blakeembrey** [comment]
Yes, it's unrelated to TypeScript. There's https://github.com/nodejs/node/pull/6171 still pending to support this.

**Comment by blakeembrey** [comment]
Ok, I've implemented basic support for recoverable errors. There may be edge cases until https://github.com/nodejs/node/pull/6171 lands, but I've manually coded the recoverable TypeScript diagnostic codes into https://github.com/TypeStrong/ts-node/blob/master/src/_bin.ts#L362-L369 for now. If you find something that you think should work, let me know and it can be added to the list.
