### ISSUE TITLE
Strange issue with undefined exported class

### ISSUE THREAD

**Issue by atrauzzi** [TypeStrong/ts-node#305]
I'm encountering a strange issue when trying to run my application with `ts-node`.

```
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (native)
    at __extends (src\Suite\ProtocultureServiceProvider.js:7:9)
    at src\Suite\ProtocultureServiceProvider.js:52:5
    at Object.<anonymous> (src\Suite\ProtocultureServiceProvider.js:68:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```

I've been able to trace this specific error down to a single statement in the class that `ProtocultureServiceProvider` is having troubles importing:

https://github.com/atrauzzi/protoculture/blob/master/src/ServiceProvider.ts#L40-L41

I say this because when I comment out that code, although it breaks other things in my application, the import error goes away.

It's fairly easy to run my demo code for this project if you want, do the usual `[yarn|npm] install`, followed by `ts-node ./demo/console.ts`.

I'm totally out of ideas on what may be causing this!

**Comment by blakeembrey** [comment]
Please leave general support questions for StackOverflow or another medium. This doesn't look like it's caused by TypeScript or `ts-node`, and appears to be a general JavaScript runtime issue. If in doubt, please compile your project and run with `node`. If I had to guess, you probably have a circular dependency issue that results in the extended class being `undefined` at runtime.

**Comment by atrauzzi** [comment]
Yup, definitely appears to be a circular dependency issue.  Sorry, I didn't mean to do a support-style ticket.

At least this is here now! 😄
