### ISSUE TITLE
inside method class this return a Reference Error

### ISSUE THREAD

**Issue by joseSantacruz** [TypeStrong/ts-node#307]
Hi,

When instace a Class and inside the contructor of the class I try to assign a property the referece of **this** always return an error `ReferenceError: stru is not defined` and also the same error when I try to consume the property on a method but when I try to access to the property outside the class works fine.

Heres and example:

```javascript
Class Hello{
    mid: string;
    constructor(data: string){
     this.mid = data;
    }
    sayHello(){
     console.log(this.mid);
    }
}

let qw = new Hello('hola');
```

I'm using this command
```bash
mocha --compilers ts:ts-node/register -r tsconfig-paths/register test.ts
```

**Comment by blakeembrey** [comment]
I don't see any reference to `stru`, but this code would never run to start with - you need lowercase `class` not `Class`. Also, this isn't really a TypeScript support forum. I'm happy to help with issues you believe are legitimately caused by `ts-node`, but it seems like this is something from your code. If not, please provide a reproduction and a stack trace I can take a look.

**Comment by joseSantacruz** [comment]
yes I'm using class with lowercase but that is not the maybe I not explain myself on this image you can see the problem:

![image](https://cloud.githubusercontent.com/assets/11586276/24981504/a824ce1e-1fa2-11e7-9b15-adf75f33bcdc.png)

**Comment by blakeembrey** [comment]
Sorry, I'm not really sure what I can do with that image. Do you have a reproduction and/or stack trace? How is this code being executed?

**Comment by joseSantacruz** [comment]
OK the problem is when inside a class method I try to use `this` to access to the properties or class methods, always return `ReferenceError`so for example if I put on the constructor of the image `this.mid == '10000002036955013614148494909956'` returns **false** even when it should be **true**

**Comment by blakeembrey** [comment]
You still aren't providing enough information for anyone to help you. Please provide any of the pieces I asked for, thanks.
