### ISSUE TITLE
typeRoots not inferred correctly?

### ISSUE THREAD

**Issue by 42shadow42** [TypeStrong/ts-node#308]
I've experienced an issue similar to Issue #283 , in my case the node_modules folder is not at node_modules/@types, instead it is at ../node_modules/@types.

According to the documentation at: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

@types, typeRoots and types

By default all visible “@types” packages are included in your compilation. Packages in node_modules/@types of any enclosing folder are considered visible; specifically, that means packages within ./node_modules/@types/, ../node_modules/@types/, ../../node_modules/@types/, and so on.

This fix appears to have resolved the base case, but not the recursive search scenario. What would it take to make this fix apply recursively.

**Comment by blakeembrey** [comment]
Can you please verify that this works with `tsc`? I'm not really sure where it'd need to be fixed for that feature, so I'd be happy to accept a PR.

**Comment by 42shadow42** [comment]
Yes, tsc appears to behave as described. I'm not really in a great place to contribute the fix, but I'd assume a starting point would be to remove the patch from #283 and rethink the issue. The relevant part here seems to be that the bug DOES NOT occur on OSX. There are speculations as to why in #283 . 

In the meantime for anyone encountering this issue you can easily workaround the issue by being being explicit about typeRoots when working with ts-node.

**Comment by 42shadow42** [comment]
Actually, it is possible #285  fixes issue #283 , but #283 recreates the issue for the recursive situations. I'll investigate this when I get a chance.

**Comment by 42shadow42** [comment]
I updated to 2.1.2 and no longer have this problem directly using ts-node.

**Comment by paqogomez** [comment]
Could this error have resurfaced?  I'm on typescript 2.5.3.  On my mac the project compiles fine, but on the windows side I get: 

    [22:08:24]  build dev started ...
    [22:08:24]  clean started ...
    [22:08:24]  clean finished in less than 1 ms
    [22:08:24]  copy started ...
    [22:08:24]  transpile started ...
    [22:08:29]  typescript error
    [22:08:29]  typescript error
            Cannot find type definition file for 'node'.

            Cannot find type definition file for 'pako'.
