### ISSUE TITLE
inconsistent test coverage when running ts-node/register in conjunction with nyc

### ISSUE THREAD

**Issue by bcoe** [TypeStrong/ts-node#310]
I have a [fairly long standing issue on nyc](https://github.com/istanbuljs/nyc/issues/537), related to flappy test coverage when `ts-node/register` is used in conjunction with nyc.

My hunch is that it might be related to race conditions around require hooks.

@hzoo @blakeembrey @danez what's the current state of `pirates`; in relation to babel -- I think if we made an effort to get all three ecosystems (TypeStrong, Istanbul, Babel) using `pirates` we would ensure more stability across this giant swath of packages.

**Comment by bcoe** [comment]
CC: @JaKXz looping you in too; my gut is it would be good to have as many eyeballs as possible on this [load bearing module](https://github.com/ariporad/pirates).

**Comment by blakeembrey** [comment]
Let me know if you do find the issue. `ts-node` follows the pattern from `pirates` here: https://github.com/TypeStrong/ts-node/blob/c18692ab7355e9e0caff85d03da6d602c9702838/src/index.ts#L379-L400. I can't think of any difference that could cause this. On subsequent executions, it would be using the cache, but in that case I wouldn't expect the coverage to drop.

**Comment by blakeembrey** [comment]
@bcoe I see the original linked issue is closed. Did this get resolved?
