### ISSUE TITLE
Cannot run ts-node with a npm dependency

### ISSUE THREAD

**Issue by thesunlover** [TypeStrong/ts-node#312]
Hi, there and thanks for the useful tool.
I experience difficulties finding solution to run ts-node on a npm dependency that I created for my project.
It seems that ts-node always treats my TypeScript code as JS code and doesn't want typings for the variables.

Here are some examples I have already tried:

`ts-node --project ./node_modules/network-selector/tsconfig.json --no-cache ./node_modules/network-selector/networkProxy.ts`
`ts-node -n --project ./node_modules/network-selector/tsconfig.json --no-cache ./node_modules/network-selector/networkProxy.ts`
from `\node_modules\` directory:
`ts-node -n --project ./network-selector/tsconfig.json --no-cache ./network-selector/networkProxy.ts`

when I run the script from it's directory it works fine, but the output file will not be located properly

**Comment by thesunlover** [comment]
seems to be the same as #158.
Can someone update me if you've found a solution

**Comment by blakeembrey** [comment]
`ts-node` doesn't run files in the `node_modules` directory. That is noted in the issue you linked. Also see the README for more information: https://github.com/TypeStrong/ts-node#configuration-options (specially, see `ignore` where `node_modules` is the default).
