### ISSUE TITLE
Command-line works, invoking programatically via gulp does not with static methods...

### ISSUE THREAD

**Issue by digable1** [TypeStrong/ts-node#317]
I execute my ts-node from the Command Prompt (win10) - and everything works.

I try it from a gulp task, and I get a bunch of errors like the following:

<file_name (line,column)>: Property '<static method name>' does not exist on type '() => void'. (2339)

I'm using "require('ts-node').register();" so using the same tsconfig.json as the invocation from the command prompt.

Stack trace snippet:

    at getOutput (C:\ePlatformSustainment\angular2\node_modules\ts-node\src\index.ts:316:17)
    at C:\ePlatformSustainment\angular2\node_modules\ts-node\src\index.ts:347:18
    at Object.compile (C:\ePlatformSustainment\angular2\node_modules\ts-node\src\index.ts:474:19)
    at Module.m._compile (C:\ePlatformSustainment\angular2\node_modules\ts-node\src\index.ts:410:44)
    at Module.m._compile (C:\ePlatformSustainment\angular2\node_modules\ts-node\src\index.ts:410:23)
    at Module._extensions..js (module.js:580:10)

I did notice that the message description changed when I set the "module" attribute in tsconfig's compilerOptions, but it was still the same error (it's currently set to commonJS).

I'm suspecting it shouldn't do this, right?

**Comment by blakeembrey** [comment]
I'm going to guess your global and local versions are different. Please make sure it's not just that.

**Comment by digable1** [comment]
Nope.

Here is a reduction that causes it:

Gulp task file ts-node.js:

`var gulp = require('gulp');
var tsconfig = {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
};

require('ts-node').register(tsconfig);

gulp.task('ts-node-issue-demo', function() {
    require('/<my_project_root>/angular2/ts-node-issue/ts-node-issue-demo.ts');
});`

ts-node-issue-demo.ts:

`import { TsnodeIssueDemoStatics } from './ts-node-issue-demo-statics';

class TsnodeIssueDemo {
    private readonly buildTimeFeatureFlagsName = '/ePlatformSustainment/angular2/BuildtimeFeatureFlags.js';
    private readonly writtenFeatureFlagsName = './FeatureFlags.js';

    constructor() {
        console.log('Starting...');
        this.renderMessage();
    }

    renderMessage(): void {
        console.log(TsnodeIssueDemoStatics.getStaticMessage());
    }
}

new TsnodeIssueDemo();`

ts-node-issue-demo-statics.ts:

`export class TsnodeIssueDemoStatics {
    private static readonly staticMessage = 'Greetings and salutations for inhabitants of the whole planet';

    static getStaticMessage(): string {
        return TsnodeIssueDemoStatics.staticMessage;
    };
};`

The above worked via ts-node on the command prompt (win10).

Did not work within gulp.

Note:  the tsconfig object in the gulp task is copied and pasted from the persisted tsconfig.json on the file system.

**Comment by blakeembrey** [comment]
What version of ts-node and Typescript is used globally, and which versions are used locally? It's not really possible to run differently in each case, so please verify you don't have some differing environment globally vs locally. Have you tried running the bin file from your local node modules?

**Comment by digable1** [comment]
ts-node:  Globally - not installed.  Locally - "ts-node v2.1.2", "node v7.4.0"

tsc:  Globally - not installed.  Locally - "Version 2.2.2"

gulp:  Globally - "CLI version 3.9.1".  Locally - "Local version 3.9.1" (running gulp globally and locally gives the same messaging)

Which obviously means I've always been running ts-node (and subsequently tsc) from local node_modules.

I also just did a manual check between tsconfig.json and the "tsconfig" object in my example ts-node.js.  It checked out. 

I take it you can't reproduce this (with the reduction)?

**Comment by blakeembrey** [comment]
I haven't tested it. If you throw it in a repo I can clone it and test it much quicker. I didnt want to spend the time upfront putting it together on the weekend if it was broken because of something simple to figure out. 

The next issue I see from the code above is that your `tsconfig.json` content passed in wouldn't actually be used - it needs to be a key under options (pretty sure it's `compilerOptions` and mirrors the CLI options). However, it'd then result in loading your real configuration file from disk anyway so you shouldn't see any difference. Let me know if you manage to create a repo with the content I can use, I'll check it out then. Just note that both features use the same code path, so I'm sure it'll be some odd difference somewhere here occurring.

**Comment by digable1** [comment]
Ok, never mind.

This was part of a build process with a work project.  Therefore, I needed to do a lot of chopping in the process of sticking it in a repo somewhere.  So when I removed all the proprietary stuff that was cruft as far as this issue was concerned, extra stuff from package.json, unused gulp tasks for this purpose, and ran it - it worked programmatically as well.

So I'm obviously in a weird state when I try and invoke ts-node within our build process (it's doing some translation for use later in building).  Does the stack snippet from my first post give you any clues regarding where I might look?

Obviously I get to have much fun figuring out what got out of whack.

Sorry for false alarm.

**Comment by blakeembrey** [comment]
If there's anything before the last line the stack above, that should show you the file where the errors begin. It seems to be coming from the `.js` file, so maybe you have `allowJs` enabled in your `tsconfig.json` file? Aside from that, there's no a lot - the TypeScript error itself should be outputting the filenames which might give a location where the errors started to look at. If you're trying to find that specific file and these hints don't work, try going into the file in `node_modules` and adding a `console.log` just above where the stack starts (probably around https://github.com/TypeStrong/ts-node/blob/c18692ab7355e9e0caff85d03da6d602c9702838/src/index.ts#L395).
