### ISSUE TITLE
How to specify custom tsconfig.json when running Gulp?

### ISSUE THREAD

**Issue by atsu85** [TypeStrong/ts-node#318]
Hi,
when I run `gulp someTask` the `./tsconfig.json` file is used by default. The problem is that `./tsconfig.json` has `noImplicitAny: true` that makes sense for my projects sources, but causes lots of errors/warnings for gulp (no errors if i changed it to false).

So I created gulp/tsconfig.json file with different settings just for gulp. From the ts-node doc i see that it is possible to pass custom tsconfig.json
> --project, -P Path to resolve tsconfig.json from (or false to disable) (also process.env.TS_NODE_PROJECT)

, but i couldn't figure out how to tell ts-node+gulp that it should use another `./gulp/tsconfig.json` instead of default `tsconfig.json`.

**Comment by blakeembrey** [comment]
You either use environment variables, create a `.js` file that registers it yourself or use the `ts-node` executable with the flag set.

**Comment by MickL** [comment]
I've run in the same problem: I want to use the `--project` flag to select a different tsconfig.json but i cant do that when running gulp. @blakeembrey what do you mean by "or use the ts-node executable with the flag set"?

**Comment by veksa** [comment]
@MickL 
`ts-node -r tsconfig-paths/register ./tsconfig.json`
