### ISSUE TITLE
Typescripted mocha tests having less strict ts compiler settings than main code?

### ISSUE THREAD

**Issue by JasonKleban** [TypeStrong/ts-node#319]
This might be a dup - I see others discussing this topic, but I'm not sure they're exactly the same or how to apply their revelations.

I have the following project structure:

```
/
`-- src/
   `-- blah.ts
`-- test/
   `-- unit/
      `-- blah.test.ts
   `-- mocha.opts        // --compilers ts:ts-node/register,tsx:ts-node/register ⏎ --watch-extensions tsx,ts ⏎ --reporter dot ⏎ --recursive
   `-- tsconfig.json     // "noImplicitAny": false,
`-- tsconfig.json        // "noImplicitAny": true,
```

`tsc -p .` and `tsc -p ./test` both compile successfully.

`mocha test/unit` at root fails though, because ts-node is picking up the root tsconfig.json instead of the test/ tsconfig.json and for now the test code doesn't have to pass all the strictest checks.  And as long as the main project compiles, merely relaxing the restrictions on the tests which reference /src/blah.ts (already passing the stricter type-checks) should cause no problem.  But the test code doesn't itself adhere to those checks and so the tests fail to compile.

Shouldn't mocha be providing the right working directory to ts-node so that ts-node can discover the correct test/tsconfig.json?  So is this a shortcoming of mocha?  What exactly would mocha need to be doing differently here to support this use case?

I'm trying to get this working in a mixed Windows/Linux environment.

**Comment by blakeembrey** [comment]
No, your working directory should be where you execute something. It's not something mocha nor this tool should support directly (changing your cwd). Use the configuration options available in README - either use environment variables or the CLI tool to execute mocha (see https://github.com/TypeStrong/ts-node#configuration-options). If it's the `process.env` notation that didn't make sense, let me know what would make sense there and we can improve the documentation.

**Comment by JasonKleban** [comment]
Ok, how do I specify the ts-node configuration options in mocha.opts?  I assume I'd want to specify `-p ./test/` in mocha.opts but I thought I'd read in other open issues that this can't be done?

**Comment by blakeembrey** [comment]
You can't, that's configuring mocha. Use environment variables or execute from the `ts-node` CLI as mentioned in my previous comment. E.g. `ts-node -P ./test node_modules/.bin/_mocha` or `TS_NODE_PROJECT=./test mocha`.

**Comment by JasonKleban** [comment]
Ok, so if mocha were to support this, what would ts-node ideally get from mocha?  What would the ideal feature request be?

In a cross-platform developers' workflow, `ts-node -P ./test node_modules/.bin/_mocha` is awkward.  Setting a temporary environmental variable cross-platform seems complicated and involves extra dependencies.  Requiring changing directories is not intuitive or familiar.

**Comment by blakeembrey** [comment]
It can't get anything from mocha, it doesn't make sense. The only hacks would be to have mocha change the directory, but it's a temporary hack that wouldn't solve any underlying issue. I don't see what's wrong with the CLI option, I've used it cross platform for years with no issue.

**Comment by JasonKleban** [comment]
Why doesn't it make sense to pass an `-P ./test` argument from mocha.opts somehow to ts-node?

At runtime, mocha asks ts-node to jit compile and execute `./test/unit/blah.test.ts`?  So why can't ts-node either accept a specified `-P` argument or (probably worse:) find the closest tsconfig.json?

Being able to run `mocha` or `mocha test/unit` is how it works in a .js code situation.  

It's reasonable to strive to provide that familiar dev experience even if the source code needs a transformation first, no?  `npm run test` with that npm script as `ts-node -P ./test node_modules/.bin/_mocha` or `SET TS_NODE_PROJECT=./test && mocha test/unit` is ok but not great because the familiar `mocha` will fail and the `npm run test` is not flexible for specifying different mocha cli args as experimentation demands.

But besides that, when I run `ts-node -P ./test node_modules/.bin/_mocha` I get this error:

```
...\node_modules\.bin\_mocha:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at Object.<anonymous> (C:\Users\jkleban\AppData\Roaming\npm\node_modules\ts-node\src\_bin.ts:177:12)
    at Module._compile (module.js:570:32)
```

In cmd shell, variations on `SET TS_NODE_PROJECT=test && mocha test` all give variations of:
```
TypeError: The specified path does not exist: test
    at resolveSync (C:\Users\jkleban\AppData\Roaming\npm\node_modules\ts-node\node_modules\tsconfig\src\tsconfig.ts:72:9)
    at Object.loadSync (C:\Users\jkleban\AppData\Roaming\npm\node_modules\ts-node\node_modules\tsconfig\src\tsconfig.ts:140:16)
    at readConfig (C:\Users\jkleban\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:406:18)
    at Object.register (C:\Users\jkleban\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:176:18)
    at Object.<anonymous> (C:\Users\jkleban\AppData\Roaming\npm\node_modules\ts-node\register.js:1:15)
```

and when I try `SET TS_NODE_PROJECT=test ; mocha test/unit` in powershell I still get the same strict type errors as though test/tsconfig.json is being ignored still.  Maybe `SET` isn't the right thing for powershell, but it isn't complaining.  Is there something else I have to do?

if I try `cd test` and then either `mocha --opts ./mocha.opts ./` or `mocha --opts ./mocha.opts ./unit`, then I get a _runtime_ type error that I don't think I get otherwise (I will confirm this, maybe it's a legit module loading issue?), such as:

```
export class ValidationMessage<S> extends React.Component<ValidationMessagePropTypes, S> {
                                               ^
TypeError: Cannot read property 'Component' of undefined
```
(btw, I guess that's showing the source file without sourcemapping the column?)

**Comment by blakeembrey** [comment]
> At runtime, mocha asks ts-node to jit compile and execute ./test/unit/blah.test.ts? So why can't ts-node either accept a specified -P argument or (probably worse:) find the closest tsconfig.json?

Not really. Mocha has nothing to do with `ts-node`, it just uses `node` to load the file and run it. `ts-node` can already accept an argument, that's what the CLI and programmatic usages are for.

> It's reasonable to strive to provide that familiar dev experience even if the source code needs a transformation first, no?

Sure. You're welcome to come up with a reasonable specification for how this would work and submit it to mocha and then come back here and have it adopted. If such a specification did exist, I assume it would be valuable to all the other preprocessors too - such as Babel or CoffeeScript. The issue you are proposing to solve is non-trivial for adoption as you need a way to pass options to a module instead of directly requiring an executable. I'd look at Browserify for an example of how this can be solved, as the plugin system does this.

> not great because the familiar mocha will fail and the npm run test is not flexible for specifying different mocha cli args as experimentation demands.

You should probably get used to running with a local `mocha` instance anyway. You can also have multiple NPM scripts and pass additional arguments to any existing NPM script using `npm run x -- foo bar`.

> But besides that, when I run ts-node -P ./test node_modules/.bin/_mocha I get this error

You'd need to find the original `.js` file and not the NPM generated bin file for Windows. Probably something more like `node_modules/mocha/bin/_mocha` would be correct instead. This isn't an uncommon practice, you would like need to do it for things like istanbul.

**Comment by JasonKleban** [comment]
http://stackoverflow.com/questions/20049790/how-to-pass-compiler-options-to-mocha

Ok, I think I got this working for all my interests.  Perhaps you can point out any trouble I'll have using this method:

mocha.opts:
```
--compilers ts:test/mocha-hook,tsx:test/mocha-hook
--watch-extensions tsx,ts
--reporter dot
--recursive
```

mocha-hook.js
```
require('ts-node').register({ 
    project: 'test' 
})
```

It is not obvious to me that `--compilers` should work instead of `--require`, but the mocha docs state 

> If your ES6 modules have extension .js, you can npm install --save-dev babel-register and use mocha --require babel-register; --compilers is only necessary if you need to specify a file extension.

suggesting to me that this is a reasonable approach to add the ts and tsx extensions (which DON'T work when only using `--require`)

**Comment by blakeembrey** [comment]
They do work regardless of the configuration, but specifying the extensions explicitly means you don't need to configure `--watch-extensions` or change the glob extensions manually to pick up the files. It's convenient. However, that's how it's been recommended for a long time, see https://github.com/TypeStrong/ts-node#mocha.

As for the fix, it seems reasonable, that's what the programmatic usage is there for 😄

**Comment by JasonKleban** [comment]
Only in watch mode, I guess.   with merely --register (and --watch-extensions configured) `mocha` doesn't find any tests to run.
