### ISSUE TITLE
Cache defaults to disabled when run via ts-node/register

### ISSUE THREAD

**Issue by chrisleck** [TypeStrong/ts-node#322]
When run via the command line, `ts-node` defaults the `cache` property to `true`.  https://github.com/TypeStrong/ts-node/blob/master/src/_bin.ts#L104

When run inside mocha via `ts-node/register`, cache defaults to `false`.
https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L143

I believe caching should be enabled by default in both cases.  This is causing our team's mocha tests to take a really long time.  Forcing caching on speeds up testing by an order of magnitude or two.

**Comment by blakeembrey** [comment]
Probably a good idea to make it consistent. I'd just correct the default option here: https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L83. Feel free to submit a PR, something like `process.env['TS_NODE_CACHE'] ? yn(...) : true` might be reasonable.

**Comment by blakeembrey** [comment]
Fixed with https://github.com/TypeStrong/ts-node/pull/323.
