### ISSUE TITLE
Node definitions seem old - process.stdout.columns missing

### ISSUE THREAD

**Issue by arichiardi** [TypeStrong/ts-node#329]
Hello again, here on reporting duty :smile: 

I tried to execute `process.stdout.columns` in `ts-node` and it led to:

```
⨯ Unable to compile TypeScript
[eval].ts (1,16): Property 'columns' does not exist on type 'WritableStream'. (2339)
```

It seems that the type definitions are old, because the problem has been fixed upstream: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13508

Is there any no-go in trying to upgrade them (maybe I should just try it out) ?

**Comment by blakeembrey** [comment]
I don't understand the issue. Why don't you update your own node.js definition then? That error is from whatever definitions you're using with the REPL.

**Comment by blakeembrey** [comment]
Or is that example about running the REPL in the `ts-node` directory? Sorry, I'm not sure I followed correctly.

**Comment by arichiardi** [comment]
Look maybe this clarifies:

```
$ cat node_modules/@types/node/index.d.ts | grep -n10 columns
3738-declare module "tty" {
3739-    import * as net from "net";
3740-
3741-    export function isatty(fd: number): boolean;
3742-    export interface ReadStream extends net.Socket {
3743-        isRaw: boolean;
3744-        setRawMode(mode: boolean): void;
3745-        isTTY: boolean;
3746-    }
3747-    export interface WriteStream extends net.Socket {
3748:        columns: number;
3749-        rows: number;
3750-        isTTY: boolean;
3751-    }
3752-}
3753-
3754-declare module "domain" {
3755-    import * as events from "events";
3756-
3757-    export class Domain extends events.EventEmitter implements NodeJS.Domain {
3758-        run(fn: Function): void;
```

**Comment by blakeembrey** [comment]
That just tells me that it has nothing to do with this repo. That's your own definition for `node`, you are free to update it.

**Comment by arichiardi** [comment]
Yes exactly, my own definition file has it, so maybe the question is more, why `ts-node` is not using? I am still learning the node ecosystem so I might be doing newbie things here, please bare with me ok? :smile:

**Comment by arichiardi** [comment]
Also, I find this: https://github.com/TypeStrong/ts-node/blob/master/typings.json#L17
Again, not sure which one is picked up.

**Comment by blakeembrey** [comment]
I can't tell if it has it. The code snippet you sent me wasn't related to the error. Find `stdout` and check that. Either way, this is your definition - it's not one provided by `ts-node`.

**Comment by blakeembrey** [comment]
Typings does not put things in `node_modules` or get automatically installed, that file is coming from somewhere else. Please check your NPM dependencies, or just install `@types/node` yourself.

**Comment by blakeembrey** [comment]
Also, the latest definition on GitHub doesn't seem to have the property you're after either: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e251c1438825ba9ca10144270e3cd86dbbedaafe/types/node/index.d.ts#L370.

**Comment by arichiardi** [comment]
It does here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e251c1438825ba9ca10144270e3cd86dbbedaafe/types/node/index.d.ts#L3823

Not same line, maybe I need `master` there. I am following the dots in that file, I apologize for the noise...

**Comment by blakeembrey** [comment]
@arichiardi That is for the `tty` module, not the global `process` (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e251c1438825ba9ca10144270e3cd86dbbedaafe/types/node/index.d.ts#L3814). I'd check out a quick guide on writing TypeScript definitions to get a better understanding, but that `declare module "tty"` means it's creating a module called `"tty"` (those types are in a module and not global). You can get those types (and value) by importing from `tty`.

**Comment by arichiardi** [comment]
Ok. Thanks a lot. Very strange that I see the property if I execute `process.stdout` in `ts-node`.

**Comment by blakeembrey** [comment]
That's because it's the runtime vs the type system. They aren't in sync when you're using a user-contributed definition of a JavaScript (not natively TypeScript) project. Some things either aren't typed in various definitions or could be incorrect.

**Comment by blakeembrey** [comment]
The best thing you can do in those situations is try to make a PR to improve the definition yourself. It might not be too hard. Or you can open an issue on the definition and hope someone else will get around to fixing it for you.

**Comment by arichiardi** [comment]
Thanks for the suggestion, I will do that. I thought it had been solved here: DefinitelyTyped/DefinitelyTyped#13508 but then it is not. Thanks for your patience!

**Comment by blakeembrey** [comment]
It seems like it, but that's the node 6 definition only - it's possible that your using a different definition?

**Comment by arichiardi** [comment]
I am using `"@types/node": "7.0.12"` atm
