### ISSUE TITLE
Everything causes a 7006 error

### ISSUE THREAD

**Issue by thecodewarrior** [TypeStrong/ts-node#333]
I'm making a discord bot that will hot-swap modules, so I'm using typescript's require patch. The problem is, unless I turn off type checking by enabling fast mode I get spammed with a 7006 error for every parameter and member of the loaded class.

The module loading code (`file` is an absolute file path.) The for loop is never even reached as the compiler crashes before then, so that part shouldn't be the problem.
```typescript
require('ts-node').register({ project: path.join(__dirname, ".."), cache: false })
// ...
// ... more junk here. ^ these options are just my last-ditch efforts to make it work. It crashes with or without them
// ...
function loadModule(file: string) {
	console.log("Loading module `" + file + "`")
	let exports: any = require(file);
	for (var k in exports) {
		var botmodule = new exports[k](client);

		let existing = modules[file];
		modules[file] = botmodule;
		if (existing !== undefined) {
			botmodule.transfer(existing)
		}
	}
}
```

The dynamically loaded module:
```typescript
//module
export class MyClass {
    foobar(v: string): string { return "" }
}
```

The error:
```
modules/tmp.ts (5,12): Parameter 'v' implicitly has an 'any' type. (7006)
```

This is a deliberately stripped down test case, just to see if it is happening with even a simple module, and it is.

(also, dunno if it's related, but the line numbers are way off)

Here's the repo: http://github.com/thecodewarrior/OPMBotJS

**Comment by blakeembrey** [comment]
How I do replicate it? Cloning your repo and trying to run it results in an error loading `app/token.txt`.

**Comment by thecodewarrior** [comment]
I'll email you my token. After this process is over I'll just regenerate it. (it's an api token, so it's secret)

**Comment by blakeembrey** [comment]
Awesome, cheers! I realised the issue now - you've got `ts-node` registering twice. Once from using `ts-node` CLI, and another from the `require('ts-node').register(...)` call. This is resulting in it being compiled to JavaScript, then the output being compiled _again_ (hence no type signatures anymore, and the messed up line numbers). Not sure if there's an easy fix for making sure people don't register `ts-node` twice without breaking a legitimate use-case (if there is any).

**Comment by thecodewarrior** [comment]
Oh, so it will work without the register? If so that's great!

**Comment by blakeembrey** [comment]
If you're using the CLI, yes. You should only need the programmatic approach if you can't use the CLI for whichever reason.

**Comment by thecodewarrior** [comment]
But if I modify the .ts file and re-require it, will it still work? Right
now I'm only loading the modules once but I plan to hotswap them as I
update them. (Right now it automatically reloads the entire app whenever
something changes, but that will be changed)

**Comment by blakeembrey** [comment]
Yes, that will work. You have to make sure you clear the node.js require cache properly though.

**Comment by thecodewarrior** [comment]
Cool, thanks! :D
