### ISSUE TITLE
JS ReferenceError - TS Lib declared types issue

### ISSUE THREAD

**Issue by hyndsite** [TypeStrong/ts-node#334]
I am getting this JavaScript ReferenceError below.  Referenced type is in the lib.es6.d.ts file and its not throwing issues with other types in the same lib (e.g. JSON).

Attempting to use the Typescript declared type "File" (lib.dom.d.ts) in my Mocha test (see below) and when ts-node compiles using tsconfig.json file, the appropriate library is not being included/checked.

I have both es6 and dom libraries referenced in the "lib" tsconfig.json array (they both have a declared File type). (I have verified that the tsconfig.json is being used and there is no other tsconfig.json)

**--ERROR--**

ReferenceError: File is not defined

**-- NPM script --**

`mocha --compilers ts:ts-node/register tests/**/*.tests.ts`

**--Test---** 
`describe("SendFile Endpoint", () => {
       const file = new File(["test"], "filename"); //< -- File ref
       const formData: FormData;
       const error = new Error("error occurred sending file");
       const responseString = JSON.stringify({postId: 1}); //<--- no problem loading JSON
       .....`

**-- tsconfig.json --**
`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "sourceMap": true,
    "noImplicitAny": false,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "lib": ["es2015", "es6", "dom"],
    "jsx": "react",
    "types" : [ "node" , "reflect-metadata"],
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "include": [
    "node_modules/@types/**/index.d.ts",
    "src/**/*"
  ],
  "exclude": [
    "**/*.spec.ts"
  ]
}`

**Comment by blakeembrey** [comment]
You need to write code that can actually run on node for it to work. Try importing the variable you're trying to use.

**Comment by blakeembrey** [comment]
Actually, it looks like you're getting confused by the separation between the type system and runtime. Node.js has no class called `File` globally, that's something coming from the DOM. Not sure why the ES6 definition has it, I wasn't aware of it being added to the spec, but node.js doesn't have a DOM.

**Comment by hyndsite** [comment]
ok thanks.
