### ISSUE TITLE
Add tsnode.json config support

### ISSUE THREAD

**Issue by chrisleck** [TypeStrong/ts-node#335]
Since `mocha` doesn't give us the ability to use `ts-node` command line options or run code as part of the registration hook, it would be wonderful if `ts-node` looked at a `tsnode.json` config file for settings.

**Comment by blakeembrey** [comment]
See https://github.com/TypeStrong/ts-node/issues/4 too. How do you imagine this would work, as a fallback or default lookup? What do you think is limiting about using `tsconfig.json` and having it use `extends`?

**Comment by chrisleck** [comment]
I'm specifically interested in the `--fast` option, which AFAICT is not a `tsconfig.json` setting but rather something specific to `ts-node`.

I imagine this setting would take effect if not overridden via env var, CLI option, or register option.

**Comment by blakeembrey** [comment]
Would you prefer a separate file or using the existing `tsconfig.json` file? Separate is a bit trickier.

**Comment by chrisleck** [comment]
I'd prefer re-using `tsconfig.json` with a `ts-node` specific section if that's possible.  Would keep our config in one place.

**Comment by blakeembrey** [comment]
Do you mind if I close this in favour of the other issue? I'm always open to a PR 😄

**Comment by chrisleck** [comment]
SGTM
