### ISSUE TITLE
Show warnings but still run

### ISSUE THREAD

**Issue by laurentgoudet** [TypeStrong/ts-node#34]
Sometimes you want to just run something, while still displaying the warnings (e.g., missing type definitions) that you should fix once that your implementation is working.

**Comment by blakeembrey** [comment]
Ok, sounds reasonable. I don't think it'll be available until I do the refactor mentioned in https://github.com/TypeStrong/ts-node/issues/31#issuecomment-157452776 so give me a week or two, but it'll be a flag in the CLI - something like `ts-node --warn-only script.ts`.

**Comment by blakeembrey** [comment]
Just a note if anyone wants to work on this. Semantic errors (type errors) should warn, but I think syntactic errors should throw still since that blocks the emitter.

**Comment by esprehn** [comment]
Any progress on this? tsc supports this mode but ts-node doesn't.

**Comment by blakeembrey** [comment]
Feel free to submit a PR.

**Comment by blakeembrey** [comment]
Also, `tsc` definitely doesn't support this mode - `tsc` has no runtime to support this mode. Maybe you want something different.

**Comment by esprehn** [comment]
tsc can both emit code and still print warnings to the console. ts-node doesn't appear to have a way to show the warnings but still emit the code.

**Comment by blakeembrey** [comment]
Definitely, but `tsc` doesn't execute the code. Printing warnings while code is executing means they'll end up interleaved with your own logs. See the conversation and submit a PR if you want this feature. There's a "help wanted" label for that reason.

**Comment by kvcrawford** [comment]
There used to be the `disableWarnings` option that allowed ts-node to still run with warnings (though I believe it also hid those warnings). Whatever happened to that?

**Comment by felixfbecker** [comment]
It's very annoying that I can't run tests even if there is just a tiny unused variable somewhere.

**Comment by floribon** [comment]
+1 quite annoying

**Comment by blakeembrey** [comment]
@floribon There's a 👍 button you can click for this. It's quite annoying for everyone involved, but this is an open source project and everyone is welcome to contribute 😄

**Comment by floribon** [comment]
Ha yeah, sorry for being entitled! I totally respect your work and thank you a lot on behalf of everyone that sound like they just complain when their free toy doesn't work the way they like it.

+1 though, I was afraid the emoji would get missed :)

**Comment by blakeembrey** [comment]
Closed by https://github.com/TypeStrong/ts-node/pull/818.
