### ISSUE TITLE
Allow passing `--inspect-brk=5858` argument to node.js

### ISSUE THREAD

**Issue by Deilan** [TypeStrong/ts-node#342]
Right now `--inspect=5858` is being passed just fine. So it would be great to have an option to pass `--inspect-brk=5858` argument also as it's valid for node and useful for debugging.

**Comment by blakeembrey** [comment]
Feel free to add it here: https://github.com/TypeStrong/ts-node/blob/7dfb3e332bc1d2c3a164e2a48956991fb09377c1/src/bin.ts#L23.

**Comment by Deilan** [comment]
@blakeembrey Walk the talk :) #343

**Comment by jrop** [comment]
This seems to be broken in 6.1.0.  If I use the `--inspect-brk` flag, it drops me into a prompt:

```sh
me@myhost$ ts-node --inspect-brk index.ts
>
```

**Comment by blakeembrey** [comment]
This is no longer a feature. See the README for information.

**Comment by jrop** [comment]
@blakeembrey Thanks for the quick reply!
