### ISSUE TITLE
"unsupported extension" errors using ts-node@3.0.5

### ISSUE THREAD

**Issue by mauriciovigolo** [TypeStrong/ts-node#345]
after updating to ts-node@3.0.5, the following errors started to happen during the mocha tests:

```
.../node_modules/@types/mocha/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
.../node_modules/@types/node/package.json' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'. (6054)
```

```js
"scripts": {
  ....
 "test": "node_modules/.bin/mocha --compilers ts:ts-node/register ./tests/**/*.spec.ts"
  ....
}

```

npm version: 5.0.3
mocha: 3.4.2

If I rollback to ts-node@3.0.4, the tests work again.

Thanks!

**Comment by blakeembrey** [comment]
Please look at existing issues before opening another: https://github.com/TypeStrong/ts-node/issues/344.

**Comment by mauriciovigolo** [comment]
I checked it, but #344 wasn't there when I opened this issue. Thanks @blakeembrey.

**Comment by blakeembrey** [comment]
No problem 😄 I figured it might be a timing issue with being overrun at the same time. Thanks for opening the issue, it unfortunately just results in me doing a bunch of house keeping so I usually post a similar generic message (you weren't the only one to open, there was another after you too).
