### ISSUE TITLE
forever / node process managers

### ISSUE THREAD

**Issue by puppetmaster3** [TypeStrong/ts-node#350]
I'd like to use ts-node in production. In production, most people run a process manager, such as 'forever' ( ex: http://expressjs.com/en/advanced/pm.html )

How do I run a process manager w/ ts-node?

**Comment by blakeembrey** [comment]
I can't write out all the docs for you, you'll have to do some investigation yourself. Basically, change wherever `node` is to `ts-node`. Or `node -r ts-node/register`.

**Comment by mindjuice** [comment]
I needed to do the same thing, but also needed to pass some flags to `ts-node`.  Ended up it was as simple as this:

``` forever start -c "ts-node --type-check -r tsconfig-paths/register" src/server.ts```
