### ISSUE TITLE
Unable to load Electron package

### ISSUE THREAD

**Issue by michaelenger** [TypeStrong/ts-node#353]
I'm encountering a strange issue when trying to use `ts-node` with Electron. Instead of importing the package, it instead returns a string with the path to the Electron binary.

I'm able to replicate this easily with a blank project if I initialise a new node project and install `electron`, `ts-node`, and `typescript` (adding `mocha`as an example of a working module):
```shell
npm install --save-dev electron ts-node mocha typescript @types/mocha
```

The following code spits out the path to the Electron executable, but correctly outputs the complete mocha package:
```typescript
import * as electron from "electron";
import * as mocha from "mocha";

console.log("electron", electron);
console.log("mocha", mocha);
```

In case it matters I'm running the binary inside of node_modules, but I encountered this issue when trying to run it inside of mocha:
```shell
./node_modules/.bin/ts-node test.ts
```

I'm not sure if there is a compile setting I'm missing or if Electron is being difficult. The version of Electron is 1.6.10 and the version of `ts-node` is 3.0.6.

**Comment by blakeembrey** [comment]
`ts-node` is a node executable that loads `.tsx?` files, it's not the electron executable. See https://www.npmjs.com/package/electron#programmatic-usage. From the type definition point of view, it's impossible to correctly define both for node and electron - this is a decision from the TypeScript team and you're welcome to open an issue there.
