### ISSUE TITLE
Cache doesn't work properly with multithreaded usage

### ISSUE THREAD

**Issue by chrisleck** [TypeStrong/ts-node#355]
My team runs its test pass by forking off multiple parallel mocha processes.  When these run over the same code base, one process sometimes picks up an empty file from the cache that another process is in the middle of writing.

I believe a simple fix for this is to verify that the cached file size is non-zero before considering it valid.  I'm happy to submit a PR to that effect.

**Comment by blakeembrey** [comment]
Maybe this is naive, but if it's picking up an empty file couldn't it pick up the file at any other (non-empty) point?

**Comment by chrisleck** [comment]
Typically for FS writes (at least in file systems I'm familiar with), the file is first allocated with zero length, then the content write occurs growing the metadata size > 0.  There are streaming write systems which could potentially still run afoul of this problem, but this seems to solve the problem on my Mac OSX and CoreOS Linux machines.

**Comment by chrisleck** [comment]
This could be made more robust by saving some moniker in the file once it has been completely written and checking that before considering the file valid, or saving another file on disk to indicate the same.  The first of these would probably slow things down a bit by requiring a file scan to look up the information, but the last might be faster at the expense of twice the file count.

**Comment by blakeembrey** [comment]
Makes sense. This might be a good first step. Does it seem reasonable to switch to a single `.json` file as the cache in the future and use a lock file to avoid duplicate read/write?

**Comment by chrisleck** [comment]
I'm not quite sure I understand what you're proposing.  Do you mean store the state of the cache in a single `.json` file which is protected by a separate lock file?

If so, as long as that lock is only held when updating cache state, that seems worth a try.

**Comment by blakeembrey** [comment]
Pretty much, yes. Can attempt it later, but my thought is that the overhead of using the lockfile to coordinate the multiple processes could be avoided if the cache was a single file. 

> If so, as long as that lock is only held when updating cache state, that seems worth a try.

Wouldn't it also need it on read, so that this situation we have now doesn't occur again?

**Comment by chrisleck** [comment]
Sorry, yes - I was assuming a reader/writer lock.

**Comment by chrisleck** [comment]
Can we get https://github.com/TypeStrong/ts-node/pull/356 checked in and pushed as a temporary improvement?  That would really help my team out :)

**Comment by chrisleck** [comment]
Would you be ok taking a dependency on something like https://www.npmjs.com/package/fs-ext?

**Comment by blakeembrey** [comment]
What's it for? I think if it can solve your problem and doesn't break anything backward compatible (or does in a big forward thinking way so it's an obvious v4) I'm happy to do so.

**Comment by chrisleck** [comment]
Sorry for the delay - I was on vacation.  This would enable the use of cooperative file-system locking on the cache files as they're being written to.

**Comment by blakeembrey** [comment]
How's that compare to something like `lockfile`? I'm happy to improve the situation, my only fear is decreasing the performance which has been an issue for some time (hence a cache and suggesting the locking solution combined with moving to a single file cache to mitigate any perf overhead).

**Comment by chrisleck** [comment]
`lockfile` works if you want a separate lock file rather than locking the cache file itself.  Do you imagine one lockfile per cache file?  I don't see how this would work well with a single cache file - parallel builds would serialize on each other as the single file gets locked.

**Comment by blakeembrey** [comment]
So your thought is keeping separate cache files of each content and locking each one on read/write? My reasoning was that it'd be a single cost at startup by using a single file, instead of a consistent cost throughout the entire runtime, but I might be thinking about this incorrectly.

**Comment by chrisleck** [comment]
Moving to a single file would block parallel compilers behind that single file.  I believe we need to keep individual cache files for this to work properly.

**Comment by chrisleck** [comment]
I'll try putting together a PR for this and send it your way.

**Comment by blakeembrey** [comment]
> Moving to a single file would block parallel compilers behind that single file.

It depends. If they are all the same project, there isn't any real advantage I see from re-using the cache in parallel anyway.

> I'll try putting together a PR for this and send it your way.

Absolutely. Would be curious on what your thoughts are for a "fast" default (no type checking), it might alleviate a need for caching by default.

**Comment by chrisleck** [comment]
RE: same project: the benefit is when a project runs a bunch of compile steps in parallel where they share some underlying shared code (as is the case for my repo).  Specifically, we run our ~9500 mocha unit tests in batches through 8 parallel threads.  Some of these parallel tests end up requiring the same files.  Without some form of locking on the cache files, the tests clobber each other attempting to write to the cache.  Without the cache being enabled, we pay the cost of pre-compiling the same files over and over across batches.

RE: fast default: we want type checking enabled in our testing.

**Comment by blakeembrey** [comment]
Makes sense. As a default, would it be detrimental (e.g. instead of `--fast`, there'd be `--type-check` or similar)?

Another idea - what if we check that the file ends in a valid source map before using it? That might be the perfect compromise since it's always at the end of the file.

**Comment by chrisleck** [comment]
On Jul 19, 2017 5:49 PM, "Blake Embrey" <notifications@github.com> wrote:

Makes sense. As a default, would it be detrimental (e.g. instead of --fast,
there'd be --type-check or similar)?

Happy to go either way on default behavior, as long as I can turn it on in
mocha via env var.

Another idea - what if we check that the file ends in a valid source map
before using it? That might be the perfect compromise since it's always at
the end of the file.

That does sound like a great idea and eliminates the need for any locking :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/TypeStrong/ts-node/issues/355#issuecomment-316564394>,
or mute the thread

**Comment by chrisleck** [comment]
https://github.com/TypeStrong/ts-node/pull/394

**Comment by blakeembrey** [comment]
I believe this has been solved 😄 Let me know if it wasn't and I'll re-open.
