### ISSUE TITLE
`tsconfig.json` is not read from `./test` dir

### ISSUE THREAD

**Issue by ianp** [TypeStrong/ts-node#358]
If I have my project structured like so:
```
/project_dir
    /src
        tsconfig.json
    /test
        tsconfig.json
    package.json
```
and my test script is `mocha -r ts-node/register --colors --recursive 'test/**/*.test.ts'` then when I try to run `yarn test` (or `npm test`) then the config file isn’t picked up (i.e. I get _Promise not defined_ errors, amongst others).

Shouldn‘t the parent path be searched for config files to apply?

**Comment by blakeembrey** [comment]
It sure is. Your parent directory is the working directory though. It's impossible to magically infer that you really wanted some child directory config. That's what the config options are for.
