### ISSUE TITLE
Put cache in to `.ts-node/...`

### ISSUE THREAD

**Issue by whitecolor** [TypeStrong/ts-node#359]
It would be better to put cache in to single folder for example `.ts-node`, first it won't pollute so much, and also it would make possible when launching inside containers in dev mode, made this folder container volume, that will be separated from source code FS.

**Comment by blakeembrey** [comment]
Where does this folder live? What's different than today? What about just setting the directory yourself?

**Comment by whitecolor** [comment]
Currently ts-node creates some folders like `ts-node-432849jklnj43u40932984j`, can those folders be placed in one folder?

**Comment by blakeembrey** [comment]
See https://github.com/TypeStrong/ts-node/pull/267. It's used to avoid conflicts between users.

**Comment by whitecolor** [comment]
Ok, thanks, `--cache-directory` works for me.

**Comment by whitecolor** [comment]
@blakeembrey what do you think about default location for cache directories to be inside os.tmpdir() to keep things more clean?

**Comment by blakeembrey** [comment]
It is, isn't it?

**Comment by whitecolor** [comment]
hm, ok, I wonder why then I got sometimes situation where `ts-node-{hash}` was created in the project folders.

**Comment by blakeembrey** [comment]
That shouldn't happen unless you've set the `--cache-directory`. Let me know if you manage to replicate the issue.

**Comment by dguo** [comment]
I was able to replicate the issue. It occurs when I run ts-node in a npm script in Docker. It appears to have the same root cause (https://github.com/npm/npm/issues/4531) as https://github.com/TypeStrong/ts-node/issues/405. The suggested fix of npm config set unsafe-perm true worked for me.
