### ISSUE TITLE
number.ToLocaleString doesn't work

### ISSUE THREAD

**Issue by swimmadude66** [TypeStrong/ts-node#364]
I just recently started converting my company's test framework over to using ts-node and found a really strange issue.

I have a section of my code which uses the number.`toLocaleString` method to convert a number to a string in the italian number format (commas for decimals).  When run with our old framework, or in the app post-compile, the code works as expected. However, when run in `ts-node` it returns the US format of the input number.

Simple test case
```
function P3(decimal) {
    return decimal.toLocaleString('it', {
        minimumFractionDigits: 3,
        maximumFractionDigits: 3,
        style: 'percent'
    });
}

console.log(P3(0.0285));
```

running that snippet in your browser or a node REPL will return `2,850%` While running it with `ts-node` yields `2.850%`

**Comment by blakeembrey** [comment]
Hey! Thanks for the issue. This looks like a general node.js question, so I'm going to have to ask you to check their issues, StackOverflow or the node.js docs. Feel free to report what you find back here.
