### ISSUE TITLE
Using with Mocha breaks Sinon

### ISSUE THREAD

**Issue by aendrew** [TypeStrong/ts-node#365]
I've run into an issue where using `ts-node` with Mocha via the `--compilers ts:ts-node/register` flag causes Sinon not work:

*index.ts*
```js
import {readFileSync} from 'fs';

export default function() {
    return readFileSync(`${__dirname}/fixture.txt`, {encoding: 'utf-8'});
}
```

*index.spec.ts*
```js
describe('stubbing aModule', () => {
  let readFileSyncStub: sinon.SinonStub;

  // This is where everything dies
  beforeEach(() => {
    readFileSyncStub = sinon.stub(fs, 'readFileSync').returns('boo-urns');
  });

  afterEach(() => {
    readFileSyncStub.restore();
  });

  it('returns boo-urns', () => {
    const result = aModule();
    result.should.equal('boo-urns');
  });
});
```
*Mocha output*
```
> tsnode-mocha-sinon-test-case@1.0.0 test /Users/aendrew/Projects/tsnode-mocha-sinon-test-case
> mocha --compilers ts:ts-node/register ./index.spec.ts



  stubbing aModule
    stubbed behaviour
      1) "before each" hook for "returns boo-urns"
      2) "after each" hook for "returns boo-urns"


  0 passing (22ms)
  2 failing
```

Very frustratingly, no error message whatsoever is reported, even when running with `DEBUG=*`.

**However**, if you transpile to ES2017, everything runs flawlessly. This leads me to believe the issue is with `ts-node` itself.

I have a full test-case here: https://github.com/aendrew/tsnode-mocha-sinon-test-case, including instructions on how to run it.

**Update:** Should be noted I've been using Node8 for all of this. However, I tried downgrading to 6 and have the same issue, however, this time with slightly more in terms of error messaging:

```
  1) stubbing aModule stubbed behaviour "before each" hook for "returns boo-urns":
     TypeError: Cannot read property 'sections' of undefined


  2) stubbing aModule stubbed behaviour "after each" hook for "returns boo-urns":
     TypeError: Cannot read property 'restore' of undefined
```

The bit about sections in the first TypeError is illuminating as I think it implies the issue may have something to do with sourcemaps.

**Comment by aendrew** [comment]
This seems to be fixed in 3.1.0 by #368. THANK YOU! 🎉  🎊  🙌

**Comment by blakeembrey** [comment]
That's interesting... Glad it's fixed anyway 😄

**Comment by aendrew** [comment]
@blakeembrey FWIW, I still get weird Sinon spy counts on `fs.readFileSync` when using `ts-node`, even if I restore the stubbed method in the `afterEach` block, and this doesn't occur if I transpile and then run my tests. Seems like there's something weird with the order that `ts-node` is running the code — however, that's probably a separate issue.

**Comment by blakeembrey** [comment]
Ah, I understand the original issue better now. This is probably expected if you're stubbing a native module. The native module is used by `ts-node`. I'm not sure there's any way around that - it's used by TypeScript for type definition resolution and was previously used for source maps (hence that fixing your issue and now I understand). This could also be broken if you stubbed other functions such as `path` or `os`.
