### ISSUE TITLE
Got Error In Vs Code Terminal

### ISSUE THREAD

**Issue by Mugesh-Rajaram** [TypeStrong/ts-node#370]
Hi Team,
     I'm getting error in Vs Code terminal that **ts-node' is not recognized as an internal or external command, operable program or batch file** while i'm trying to start my application like **npm run dev** and i have install **ts-node** in my node project locally not globally and my package.json is given below. Can anyone help on this. 

{
	"name": "tsnode",
	"version": "1.0.0",
	"description": "",
	"scripts": {
		"dev": "nodemon --exec 'ts-node --cache-directory .tscache' ./server.ts",
		"start": "ts-node --fast ./server.ts"
	},
	"author": "Mugesh Rajaram",
	"license": "ISC",
	"dependencies": {
		"body-parser": "^1.17.1",
		"chalk": "^1.1.3",
		"express": "^4.15.2",
		"nodemon": "^1.11.0",
		"ts-node": "^3.0.4",
		"typescript": "^2.3.4"
	}
}

**Comment by blakeembrey** [comment]
This seems like a general question not particularly related to `ts-node` and may better asked on StackOverflow. Have you tried `npm run dev` in your regular terminal? Have you tried double quotes instead of single quotes? I'm not really familiar with Windows shell.

**Comment by Mugesh-Rajaram** [comment]
@blakeembrey where i want use single quotes? in the run script

**Comment by blakeembrey** [comment]
Double quotes, not single quotes, yes.

**Comment by Mugesh-Rajaram** [comment]
@blakeembrey already it is in double quotes only is that right or i want to change anything
`"scripts": {
"dev": "nodemon --exec 'ts-node --cache-directory .tscache' ./server.ts",
"start": "ts-node --fast ./server.ts"
},`

**Comment by blakeembrey** [comment]
Do `"nodemon --exec \"ts-node --cache-directory .tscache\" ./server.ts"`. I'm going to have to request either a reproducible demo or ask on StackOverflow. It seems like a Windows shell specific question, probably related to some sort of path set up. Seems like it shouldn't happen using NPM scripts, but I can't think of anything else right now and don't use Windows myself.
