### ISSUE TITLE
Two different command line bugs / usability could be improved

### ISSUE THREAD

**Issue by ORESoftware** [TypeStrong/ts-node#373]
1. When I use it this way:

```bash
ts-node --ignoreWarnings "${TEST_PATH}"

EXIT_CODE=$?
echo "exit code => ${EXIT_CODE}"
```
then `ts-node` bizarrely will start interpreting the bash code below the ts-node line as input. It's really strange.

2. Because the above wasn't working, when I use it this way

```bash
echo "$(cat "${SUMAN_CHILD_TEST_PATH}")" | ts-node --ignoreWarnings

```

then I get this output:

```console
⨯ Unable to compile TypeScript
[eval].ts (10,17): Property 'times' does not exist on type 'Number'. (2339)
[eval].ts (12,19): Parameter 't' implicitly has an 'any' type. (7006).
```

Expectation:
I would expect both commands to work, and to execute the file with node even if there are compile errors. In the first case, I would not expect ts-node to interpret code below the line as input (I will try adding a semi-colon). 

Hypthesis - it seems like the `--ignoreWarnings` flag is not working or I am using it incorrectly.

**Comment by ORESoftware** [comment]
I hesitate to say this, but I will say it anyway, I have seen a lot of problems with minimist and commander as command line option parsers. Trent Mick of Bunyan and Joyent fame, wrote dashdash, and I use that. He wrote it for a reason.

**Comment by ORESoftware** [comment]
Ok, so I read the docs again, and yeah I was using it wrong

I expected --ignoreWarnings to mean --ignoreAllWarnings

So my question is -

how can we ingore all warnings?

I'd like to call this in Bash

```bash
export TS_NODE_IGNORE_WARNINGS="all warnings"
```

so that ts-node will always execute a file

**Comment by ORESoftware** [comment]
Ok, my bad, I can't read, so I see these two options:

--disableWarnings, -D Ignore all TypeScript errors (also process.env.TS_NODE_DISABLE_WARNINGS)

--fast, -F Use TypeScript's transpileModule mode (no type checking, but faster compilation) (also process.env.TS_NODE_FAST)

but it doesn't specify what we should set these env variables to...I now assume if I set them to anything non-empty it will work, about to try it out.

**Comment by ORESoftware** [comment]
Ok so this is what I leave you with lol, I have this:

```bash
export TS_NODE_DISABLE_WARNINGS="yes";
export TS_NODE_FAST="yes";

ts-node "${TEST_PATH}";
```

and apparently it's not picking up those env variables, perhaps I should set them to a value other than "yes" to get them to work? :)

thx

**Comment by blakeembrey** [comment]
Ignore warnings is a list, as mentioned in https://github.com/TypeStrong/ts-node#configuration-options. Generally you'd use either the CLI options _or_ the environment variables, but I can enable it so you can use both.
