### ISSUE TITLE
Pretty error messages when using `require("ts-node").register()`?

### ISSUE THREAD

**Issue by mattpap** [TypeStrong/ts-node#374]
When using ts-node in builds (gulp) or tests (mocha), it produces ugly error messages by default, like this:
```
node_modules/ts-node/src/index.ts:296
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
gulp/paths.ts (1,7): ';' expected. (1005)
    at getOutput (node_modules/ts-node/src/index.ts:296:15)
    at node_modules/ts-node/src/index.ts:325:16
    at Object.compile (node_modules/ts-node/src/index.ts:479:11)
    at Module.m._compile (node_modules/ts-node/src/index.ts:379:43)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:382:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```
I'm using the following code:
```
const {TSError} = require("ts-node")
const chalk = require("chalk")

function prettyTSError(error) {
  const title = `${chalk.red('⨯')} Unable to compile TypeScript:`
  return `${chalk.bold(title)}\n${error.diagnostics.map((line) => line.message).join('\n')}`
}

module.constructor.prototype.require = function(modulePath) {
  try {
    return this.constructor._load(modulePath, this)
  } catch (err) {
    if (err instanceof TSError) {
      console.error(prettyTSError(err))
      process.exit(1)
    } else
      throw err 
  }
}
```
(mostly borrowed from `src/_bin.ts`), prior to:
```
require("ts-node").register({project: ...});
```
to improve this. However, doing this every time I use ts-node is inefficient, and also I would prefer not to modify `require()` if I really don't need to. Is there a built-in way to achieve this? Maybe this could be considered for a new feature, perhaps behind a configuration option?

**Comment by blakeembrey** [comment]
This could be a flag, but it's not something I intend to enable by default. Just because an error is thrown, it doesn't mean it should exit - for instance, someone might be using `try..catch` on the require or building something like `mocha` with a "watch" option.

**Comment by blakeembrey** [comment]
I could just export the function used in the bin directory and let people hook that up themselves too. Would that be reasonable?

**Comment by mattpap** [comment]
Yes, that would be reasonable.

**Comment by blakeembrey** [comment]
Actually, there was a reason I removed this code from the codebase. I'd need to review the logs to check why, but I think it was a theory on causing a source map issue. However, you can also improve your code by using `process.on('uncaughtException', (err) => ...)` instead of hooking `require`.

**Comment by blakeembrey** [comment]
See https://github.com/TypeStrong/ts-node/pull/376. Can add a little extra function that you could pass directly to `uncaughtException`. Something like:

```
function printUncaughtException (err) {
  if (err.name === 'TSError') {
    printError(err)
  }
}
```

**Comment by blakeembrey** [comment]
I'm going to close it with https://github.com/TypeStrong/ts-node/pull/376, but feel free to let me know if there's anything else I can do to help make the experience better.
