### ISSUE TITLE
Using inside docker

### ISSUE THREAD

**Issue by AngelMunoz** [TypeStrong/ts-node#378]
Hello guys I'm having a bit of troubles using 
```js
// index.js
require('ts-node/register')
require('./src/server')
```
inside a dockerized applicaion

locally it works like a charm having ts-node installed in dev-dependencies in my package.json
however inside the docker container I can't just make it work at all saying

`Error: Cannot find module 'ts-node/register'`

which is really weird because I have my Dockerfile to install it globally then locally then dev-dependencies and yet nothing
(I've also tried all of those separately same result)
you can check the repro repo [here](https://github.com/AngelMunoz/palabrator-api/tree/docker-branch)
and run `docker-compose up` (of course you need docker installed)
has anyone found this issue? or a way to work it out?

PS: I also tried to run ts-node directly as command instead of programatically and that did work but programatically just nothing

**Comment by stelcheck** [comment]
Do you still need help? I run ts-node within docker without issues with https://github.com/mage/mage using https://github.com/mage/mage-console (which essentially wraps around ts-node).

https://github.com/AngelMunoz/palabrator-api/tree/docker-branch Seems deleted, so unless you provide more details, I don't know if I can be of any further help.

**Comment by AngelMunoz** [comment]
yeah I deleted the repo, my bad sorry I will take a look at your repo thanks I don't really need it anymore But I will try to use it again
