### ISSUE TITLE
Issue with type 'component' 

### ISSUE THREAD

**Issue by ritox842** [TypeStrong/ts-node#379]
Hello.

I use'd to have an interface with type component witch work just fine on version 3.1.0.
I just upgraded to version 3.2.0 and is seems that it's not compiling because of it.
If I change the interface from component to 'any' it does compile.

I do prefer to use type 'component'. 
Can you check it on next version? 

Thanks.

**Comment by blakeembrey** [comment]
You need to provide more context to your issues. What do you want me to check? Can you add a code example? Why do you believe this is related to `ts-node`?

**Comment by blakeembrey** [comment]
Closing as unanswered.
