### ISSUE TITLE
Cannot Compile Code with node_modules Anywhere in Path

### ISSUE THREAD

**Issue by cmain** [TypeStrong/ts-node#380]
This is probably pretty uncommon, but since ts-node looks for node_modules anywhere in the absolute file path and ignores those files for compilation by default, you have to make sure that your files do not have a parent node_modules directory anywhere in their path.  I saw this issue because I had a folder named node_modules for modules that I created, and ts-node would not compile any files for new projects that I started under that folder.  

Renaming the parent folder fixed it, which arguably is the best solution.

**Comment by blakeembrey** [comment]
This is the expected behaviour and I'm not exactly sure what this issue is about, so I'm going to close it. If there's a question/issue you have, feel free to follow up.
