### ISSUE TITLE
REPL with custom tsconfig

### ISSUE THREAD

**Issue by rsxdalv** [TypeStrong/ts-node#382]
Currently, if you launch `ts-node -p tsconfig.server.json` the REPL mode is bypassed, and instead it errs for the lack of files. 
Correct me if I'm wrong.

**Comment by blakeembrey** [comment]
Do you mean with an upper case P?

**Comment by rsxdalv** [comment]
Thank you very much!

Might I suggest adding a footnote at configuration options (README.md) to warn about default node parameters clashing if using the incorrect case? 
Silly, I know, but that's what we users are, sometimes.

**Comment by blakeembrey** [comment]
Something like https://github.com/TypeStrong/ts-node#configuration-options is?

**Comment by rsxdalv** [comment]
Makes no reminder that there are still default node CLI flags.

**Comment by blakeembrey** [comment]
If there's something you think it should say, definitely submit a PR.

**Comment by rsxdalv** [comment]
https://github.com/TypeStrong/ts-node/pull/386
