### ISSUE TITLE
Not be able to use lodash with ts-node

### ISSUE THREAD

**Issue by aminpaks** [TypeStrong/ts-node#384]
I cloned [this project](https://github.com/EnterpriseJSTutorial/vscode-ts-node-debugging) and added line below in `index.ts`, plus installed `lodash-es`.
```ts
import { values } from 'lodash-es';
```

Now either running it from shell or vscode debugger, it gives me this error:
```
export { default as add } from './add.js';
^^^^^^
SyntaxError: Unexpected token export
...
```

Not sure what I'm doing wrong!

**index.ts**
```ts

import { Person } from './person';
import { values } from 'lodash-es';

let person = new Person('Bob', 34);

console.log(person.getGreeting());
console.log(values(person));
```

Any advice?

**Comment by blakeembrey** [comment]
Use `lodash`, not `lodash-es`. Node.js doesn't understand ES6 modules yet.
