### ISSUE TITLE
Question: is it possible to specify custom path to tsconfig?

### ISSUE THREAD

**Issue by sharikovvladislav** [TypeStrong/ts-node#388]
Hi! 

I use it like this:
```
require('ts-node').register({
  project: 'e2e'
});
```

This requires `e2e/tsconfig.json` by default. I can not find an option to change tsconfig filename. Is is possible?

**Comment by blakeembrey** [comment]
Set `project` to a filename instead of a folder. Feel free to update the docs if that's unclear, but it's pretty much how `tsc` works too.

**Comment by sharikovvladislav** [comment]
@blakeembrey  OK thank you! I am bot sure, may he it is unclear for me because my English is not perfect. 

I had doubts because phrase says that project is a path to tsconfig.json. That fact that type script configuration file name is specified explicitly caused my doubts I think.

**Comment by blakeembrey** [comment]
No, absolutely. I can see the reason it's not clear, but I don't have a better name for `tsconfig.json`.

**Comment by sharikovvladislav** [comment]
"No" what?

I have `tsconfig.e2e.json`.

You name it explicitly: `tsconfig.json`. If config name was more common, I think nobody will have problem there. For example: "path to typescript configuration file".

**Comment by blakeembrey** [comment]
Feel free to submit a PR.

**Comment by sharikovvladislav** [comment]
https://github.com/TypeStrong/ts-node/pull/392

What do you think?

**Comment by sharikovvladislav** [comment]
Fixed in #392
