### ISSUE TITLE
module resolution at runtime is confusing

### ISSUE THREAD

**Issue by sodiumjoe** [TypeStrong/ts-node#389]
Here's the minimal repro:

`index.ts`:
```typescript
import { foo } from './foo';

console.log(foo);
```

`foo.ts`:
```typescript
export const foo = 'ts';
```

`foo.json`:
```json
{
  "foo": "json"
}
```

`package.json`:
```json
{
  "dependencies": {
    "ts-node": "^3.2.0",
    "typescript": "^2.4.1"
  }
}
```

```bash
$ yarn
...
$ npx ts-node index.ts
json

$ tsc index.ts
$ node index.js
ts

$ npx ts-node index.ts
ts
```

AFAICT, `ts-node` defers to node's native require before resolving its internally compiled modules, which means the `.json` file on disk wins. I think this should be considered a bug though, since the module resolution is different from typescript's, and behavior between running `ts-node` and running `tsc` with `node` diverges.

**Comment by blakeembrey** [comment]
This is expected and not a bug.

**Comment by sodiumjoe** [comment]
Thanks for the response. I don't think I explained the issue clearly enough.

The problem is that running `ts-node` at dev time could have different results from running `tsc` to build production code and running that built javascript.

I'm not suggesting changing the way node.js requires. I'm suggesting `ts-node` behavior should match the behavior of `tsc && node`.

If you're saying this is a known issue but it's still a `wontfix`, I understand, it's a pretty weird edge case and I already have a workaround for my own case, I just wanted to make sure I explained the problem clearly. I think taking a close look at the minimal repro is probably the best way to understand.

**Comment by blakeembrey** [comment]
Thanks for the extra explanation, I understand better now. Unfortunately I think this is still `wontfix`. I've given a similar answer with a different feature before (`.js` actually resolves over `.ts`, but TypeScript uses `.ts` over `.js`). I just wouldn't want to get into a situation where I'm messing with the node.js internal require pattern. The two approaches I saw was:

1. Mess with the object keys of `require.extensions` to force `.ts` first (this may have unintended side-effects in the ecosystem, such as tools like https://github.com/maxogden/dependency-check anyway which mirror node.js require order)
2. Try to check `.ts` before every file load (obviously bad when the `.ts` file doesn't exist, doubling every require time)

**Comment by sodiumjoe** [comment]
Ok, thanks for your explanation. Unfortunate, but understandable. Also, thanks for the great package!
