### ISSUE TITLE
Source mapping fails for .tsx files with compiler option: {jsx: 'react'}

### ISSUE THREAD

**Issue by bradlord** [TypeStrong/ts-node#393]
`ts-node` is generating an invalid source map source map when TypeScript's `jsx` option is set to `'react'`. The comment looks something like this:

```//# sourceMappingURLdata:application/json;[...]```

instead of 

```//# sourceMappingURL=data:application/json;[...]```

Note that the `=` is missing after `sourceMappingURL`. The culprit seems to be in the [updateOutput](https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L509-L514) function. That function is responsible for replacing the file name in the source map content with the Base 64 encoded version of the source map. It assumes that the length of the source map's filename is 4 characters longer than the input file's base name. Unfortunately, that is not true for .tsx files when the `jsx` option is set to `'react'`.

For example, suppose we have a file foo.tsx. The length of that filename is 7, so `updateOutput` replaces the last 11 (= 7 + 4) of the compiled JS file with the Base 64 encoded source map. As a result, it replaces this:

```//# sourceMappingURL=foo.js.map```
with this:
```//# sourceMappingURLdata:application/json;[...]```

This issue doesn't occur in .ts files, since the length of the source map filename (e.g. foo.js.map) is equal to the length of the original filename (foo.ts) plus 4. It also doesn't occur when the `jsx` option is set to `'preserve'`, since the filename lengths also differ by 4 characters (foo.jsx.map vs foo.tsx).

**Comment by bradlord** [comment]
I don't have time to do a pull request, at the moment, but I have success in writing an [alternate implementation](https://github.com/bradlord/ts-node/blob/master/src/index.ts#L512-L525) of `updateOutput` which does not make assumptions about the length of the source map's filename:

````function updateOutput (outputText: string, fileName: string, sourceMap: string) {
  const base64Map = new Buffer(updateSourceMap(sourceMap, fileName), 'utf8').toString('base64')
  const sourceMapContent = `data:application/json;charset=utf-8;base64,${base64Map}`
  const baseFileName = basename(fileName, extname(fileName))

  const lastLineBreakIndex = outputText.lastIndexOf('\n')
  const contentBody = outputText.substr(0, lastLineBreakIndex)
  const origLastLine = outputText.substr(lastLineBreakIndex + 1)

  const sourceMapRegexp = RegExp(`^//# sourceMappingURL=${baseFileName}\.[^\d]+\.map$`)
  const newLastLine = origLastLine.replace(sourceMapRegexp, `//# sourceMappingURL=${sourceMapContent}`)

  return [contentBody, newLastLine].join('\n')
}```

**Comment by blakeembrey** [comment]
Thanks for the catch, I'll need to make sure I test this in the future. This is definitely a recent regression (last couple of months), apologies for that.

**Comment by dan-j** [comment]
I was just about to report this! I've been having trouble using ts-babel-node, got it working (version incompatibilities between that and this module) thought everything was fine and then BAM! Didn't work for .tsx files! :expressionless:

Do you need any effort to fix it? Might be able to contribute something tomorrow?

**Comment by blakeembrey** [comment]
Feel free to give https://github.com/TypeStrong/ts-node/releases/tag/v3.2.1 a go!
