### ISSUE TITLE
ts-node@3.2.1 "freezes" on large file imports

### ISSUE THREAD

**Issue by flohil** [TypeStrong/ts-node#397]
Since using ts-node@3.2.1, I can't import large javascript files any longer.
I am using typescript@2.4.2 on a Ubuntu 16.04 machine with node@6.11.0.

If I do an import like `import * as brick_bodies from './brick_bodies'`,
ts-node freezes and the node process keeps running at 100% cpu load.

brick_bodies.js is a big javascript file (~80000 lines) which exports an array of json objects.

The import statement used to work with ts-node@3.2.0.

**Reproduction**
Clone [https://github.com/flohil/ts-node_import_test](https://github.com/flohil/ts-node_import_test), cd into the cloned directory and run 'npm install' to install ts-node@3.2.1 and typescript@2.4.2 and 'npm test' to invoke the import statement.
The process should freeze/hang during the import statement.

To verify that the import worked with ts-node@3.2.0, be sure to delete the ts-node cache folder (for me:  /tmp/ts-nodeXXX), install ts-node@3.2.0 and rerun 'npm test'.

The process should now finish and output the last json object in the array.

**Comment by blakeembrey** [comment]
Thanks for the report. The demo was super useful for me to verify that this was a problem. Give https://github.com/TypeStrong/ts-node/releases/tag/v3.2.2 a go, it seems to have resolved your issue 😄
