### ISSUE TITLE
Strange Compilation Issue

### ISSUE THREAD

**Issue by DarthDerrr** [TypeStrong/ts-node#399]
Hi.

I have a strange issue trying to use typescript, mocha and nyc. I think I made a project as simple as it could possibly be, but I get an error from ts-node when trying to run coverage (npm run test). Just running the mocha unit tests works (npm run test:unit) though.

I got this to work when transpiling typescript first to a lib directory and running tests against that directory but I ended up with coverage results in both my lib and src folders which just seemed strange. I'd prefer to keep the set up as simple as possible.

Any help would be very appreciated! Below are relevant files.
Thanks.

My one function in the src directory:
`export default function simple(): string[] {
	return [];
}
`

and my one test:

```
import { assert } from "chai";
import { suite, test } from "mocha-typescript";
import simple from "./simple";

@suite("simple test class") class SimpleTest {
	@test("pass param") passParam(): void {
		// assert.isNotNull(simple(1));
		assert.isNotNull(simple());
	}
}
```

and test/mocha.opts:
```
--compilers ts:ts-node/register,tsx:ts-node/register
--ui mocha-typescript
--require source-map-support/register
--full-trace
--bail
src/**/*.test.ts
```

Screenshot of the error when running 'npm run test':

![capture](https://user-images.githubusercontent.com/7090818/28895027-bdc11e4e-77a4-11e7-8dc4-35283729c911.PNG)

My Project:

[testissue.zip](https://github.com/TypeStrong/ts-node/files/1195309/testissue.zip)

**Comment by blakeembrey** [comment]
Looks like the loaders are bundled in the wrong order. `ts-node` defers to the built-in `.js` loader, which is probably `nyc` and is adding the coverage to the file. Have you tried reading the `nyc` docs or using `nyc --require` instead of mocha extensions?

**Comment by blakeembrey** [comment]
Check out https://istanbul.js.org/docs/tutorials/typescript/, it might help.

**Comment by DarthDerrr** [comment]
Thanks @blakeembrey. That tutorial helped.
