### ISSUE TITLE
"Failed to load external module ts-node/register" on Travis CI build

### ISSUE THREAD

**Issue by peterjuras** [TypeStrong/ts-node#40]
Hi,

I'm trying to test a generator project and I'm receiving errors when my gulpfiles are written in TypeScript.

You can look at the logs of the tests on [Travis](https://travis-ci.org/peterjuras/slush-react-express/builds/93446840). It fails to load the ts-node/register module to parse the gulpfile.ts.

Everything seems to work fine on node 5 and higher but it fails to load the ts-node/register module on node versions below that. On my local machine (node v4.2.1) everything works fine.

Do you know what the reason could be? I'm trying to run the following [testfile](https://github.com/peterjuras/slush-react-express/blob/jspm/tests/full-builds.js).

**Comment by blakeembrey** [comment]
Not really sure. The only correlation there is NPM 3, which is released as part of node v5.  Can you be sure that it's installed at that point in the time? This functionality is being provided as part of https://github.com/js-cli/js-rechoir.

**Comment by peterjuras** [comment]
NPM was the issue, it works now with npm > 3!

Thanks for the quick reply!

**Comment by blakeembrey** [comment]
Weird. Does that mean NPM v2 was wiping out the previous `node_modules`? I am curious on the real culprit here, but if it's solved feel free to close :smile:

**Comment by peterjuras** [comment]
I think I'll close this for now, since we have a workaround and I can live with requiring npm > 3 for this scenario. Let's wait until someone comes around who can't upgrade :)
