### ISSUE TITLE
TS-node should not create a .v8flags[hash].json file in the root of the project

### ISSUE THREAD

**Issue by yveskaufmann** [TypeStrong/ts-node#405]
Hi!

When using ts-node then its creates v8flags[hash].json file in the root of my npm based project.
Is there an option to to set the location for the v8flags[hash].json file ?

Thanks

Yves

**Comment by blakeembrey** [comment]
What node version are you on? That file comes from https://github.com/js-cli/js-v8flags, but it should be set based on your home directory. I am not support node < 4.

**Comment by dguo** [comment]
For anyone else who runs into this issue in the future, the cause appears to be running ts-node within an npm script within Docker. See https://github.com/npm/npm/issues/4531. The suggested fix of `npm config set unsafe-perm true` worked for me.
