### ISSUE TITLE
Excluded files in tsconfig.json sometimes not honored

### ISSUE THREAD

**Issue by peterjuras** [TypeStrong/ts-node#41]
Hi again :)

I noticed some weird behavior while running some tests on travis. It seems that the exclude property in tsconfig.json is sometimes not honored.

[This here](https://travis-ci.org/peterjuras/slush-react-express/jobs/93445280) is the failing test on travis. You can see that it complains about duplicate typings, although jspm_packages is excluded in the [tsconfig.json](https://github.com/peterjuras/slush-react-express/blob/jspm/templates/full/typescript/tsconfig.json). Also, [this test](https://travis-ci.org/peterjuras/slush-react-express/jobs/93445279) here passes without any errors although they are both run from the [same codebase](https://travis-ci.org/peterjuras/slush-react-express/builds/93445278).

Is this a bug or do I have a faulty configuration?

**Comment by blakeembrey** [comment]
Are you able to replicate this on a smaller codebase? I would love to look into it next week. I haven't seen anything personally like this and it shouldn't be possible. The `tsconfig` files resolver is here: https://github.com/TypeStrong/tsconfig

**Comment by peterjuras** [comment]
It worked fine all the time except once, so I'm not sure if I'm able to reproduce it that quickly again. But I'll keep my eyes on it and see if it happens again.

**Comment by peterjuras** [comment]
I'm closing this until this happens again. I have a feeling that the tsconfig.json was either not there or corrupted.
