### ISSUE TITLE
Errors the 2nd time I run ts-node (using jasmine-ts) because of cache issue

### ISSUE THREAD

**Issue by xnnkmd** [TypeStrong/ts-node#411]
I have a jasmine-ts project (backed by ts-node) that succed the first time it runs but if I make a small insignicant change to the code and re-run the test it breaks with typescript compilation issues unless I clean  ts-node's cache. BTW: Compiles fine with tsc.

I guess this is ts-node related?

I am using typescript 2.3.4, ts-node 3.3.0 and jasmine-ts 0.2.1

**Comment by blakeembrey** [comment]
Can you share the error or a reproducible demo?

**Comment by cmloegcmluin** [comment]
I have been experiencing the same problem. I am not sure how to capture a reproducible moment, but I will try.

**Comment by mikelehen** [comment]
Oh, it's worth noting that we're using version 3.3.0 and so type-checking is enabled by default (and we do indeed want it enabled). I verified that with TS_NODE_FAST=YES set, then the error goes away (and presumably would by default on 4.x as well).

**Comment by mikelehen** [comment]
Strangely, my problem (described above with the firebase-js-sdk repo) does not reproduce with 4.1.0. Instead I get kind of an inverse problem. If I make a module declaration change in A.ts that should cause B.ts not to compile, B.ts still compiles (even though I am using ts-node/register/type-check). Even if I change A.ts and B.ts at the same time (so both cached files are invalidated), it still compiles even though there's a type error. But if I clear the cache completely, it recognizes the type error and fails to compile. Not sure what's going on.

**Comment by cspotcode** [comment]
Closed as outdated.  We removed caching a while ago.  When we re-add it, it may only be allowed for transpile-only, or we might lean on TS's incremental mode, due to issues like the above.
