### ISSUE TITLE
--expose-http2 node.js CLI argument doesn't seem to work

### ISSUE THREAD

**Issue by kemalcany** [TypeStrong/ts-node#416]
Hi guys,

Thanks for maintaining this awesome project!

I couldn't get ts-node to start my server with the [--expose-http2](https://nodejs.org/api/cli.html#cli_expose_http2) node.js default CLI argument (from v.8.4.0 onward, currently in experimental stage)

Expected behaviour is the server to start and give a warning like below.
`
(node:8404) ExperimentalWarning: The http2 module is an experimental API.
`

But right now, nothing happens. No error messages return and the server script is not executed.
```
C:\>ts-node --expose-http2 server.ts
>
{}
>
```

I am unable to provide a working repo unfortunately, but it should be pretty simple to test it with any existing repo (in an environment with node 8.4.0) just by putting the argument (--expose-http2)

Could this behaviour is because the experimental arguments are not supported?

Thanks for your help!!!

FYI: ts-node version 3.3.0

**Comment by blakeembrey** [comment]
You'll need to add it to the list here: https://github.com/TypeStrong/ts-node/blob/master/src/bin.ts#L19. It'll be released with 4.0 of `ts-node`. For now, you can use `node -r ts-node/register` instead.
