### ISSUE TITLE
[Feature Request] Support custom node options

### ISSUE THREAD

**Issue by k8w** [TypeStrong/ts-node#418]
For example, I want to use `ts-node` with node option `--expose-gc`.
But it seems ts-node not support `--expose-gc`

**Comment by blakeembrey** [comment]
Feel free to submit a PR to https://github.com/TypeStrong/ts-node/blob/2ee95755a2013e88d8b6cc92aa6d34b6d32bc203/src/bin.ts#L19. You can use `-gc` for now.

**Comment by JesseRussell411** [comment]
--expose-gc doesn't work anymore. I think it was removed by this #536
