### ISSUE TITLE
ts-node tries to compile .scss files

### ISSUE THREAD

**Issue by datoml** [TypeStrong/ts-node#42]
Hello,

I tried to add my styles via require in my components like
require('./App.scss');

But I get this error:
SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

Is there any chance I can mark them to exclude?

**Comment by blakeembrey** [comment]
This isn't `ts-node`, but `node` itself. You don't normally `require` text files with node. Maybe you should be using the filesystem API? What are you trying to do?

**Comment by datoml** [comment]
Oh thanks. I looked through the code and though about node itsef.
I am trying to require sass files in my react component and using this loader for webpack:
https://github.com/jtangelder/sass-loader

Seems like this doesnt work with server side rendering.

**Comment by blakeembrey** [comment]
Webpack isn't really node though. If you want to execute that in node, you need to compile the output using webpack. At that point, you won't need `ts-node` anyway though since the TypeScript will also be compiled along with it.

**Comment by datoml** [comment]
Good to know. So when I want to use server side rendering I am not allowed to do that :).
