### ISSUE TITLE
The meaning of TS_NODE_FAST is wrong

### ISSUE THREAD

**Issue by sixmen** [TypeStrong/ts-node#420]
I found something wrong in #412.
( https://github.com/TypeStrong/ts-node/pull/412/files#diff-f41e9d04a45c83f3b6f6e630f10117feR100 )

I think that `typeCheck: yn(process.env['TS_NODE_FAST'])` should be `typeCheck: yn(process.env['TS_NODE_TYPE_CHECK'])` or `typeCheck: !yn(process.env['TS_NODE_FAST'])`

**Comment by blakeembrey** [comment]
Thanks for the catch. Feel free to submit a PR 👍
