### ISSUE TITLE
ts-node cannot find module

### ISSUE THREAD

**Issue by tedcurrent** [TypeStrong/ts-node#422]
I have two files:
- `src/app/index.ts`
- `src/config.ts`

Within `index.ts`:
```
import { getConfig } from "config";  
getConfig();
```
Within `config.ts`:
```
export const getConfig = () => console.log("hello world!");
```
I have a `tsconfig.json` file:
```
{
  "compilerOptions": {
    "outDir": "./ts-build/",
    "module": "commonjs",
    "moduleResolution": "node",
    "baseUrl": "src",
    "target": "es5"
  }
}
```
Running `ts-node ./src/app/index.ts` throws me: `Error: Cannot find module 'config'`. Setting `moduleResolution` to `classic` doesn't change anything.

Versions:
```
"ts-node": "^3.3.0",
"typescript": "^2.5.2"
```

Any ideas if this is a ts-node issue, typescript issue or did I do something wrong?

**Comment by blakeembrey** [comment]
Have you tried compiling with regular TypeScript? Otherwise, I'd guess you haven't written a definition file - this is the standard error from TypeScript when it can't find the definition for a module.

**Comment by blakeembrey** [comment]
Actually, it looks like you expect it to find `config.ts` from `app/index.ts`? You should use relative paths `import {} from '../config'`.

**Comment by tedcurrent** [comment]
Thanks for the reply @blakeembrey. I've run this with `tsc --traceResolution` and the resolution works fine as seen here:
```
======== Resolving module 'config' from 'C:/Dev/test-ts-node/src/app/index.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
'baseUrl' option is set to 'C:/Dev/test-ts-node/src', using this value to resolve non-relative module name 'config'.
Resolving module name 'config' relative to base url 'C:/Dev/test-ts-node/src' - 'C:/Dev/test-ts-node/src/config'.
Loading module as file / folder, candidate module location 'C:/Dev/test-ts-node/src/config', target file type 'TypeScript'.
File 'C:/Dev/test-ts-node/src/config.ts' exist - use it as a name resolution result.
======== Module name 'config' was successfully resolved to 'C:/Dev/test-ts-node/src/config.ts'. ========
```
What I actually discovered was that I have to have the environment variable `NODE_PATH` set to `src` also. I ended up running the following: `NODE_PATH=./src ts-node ./src/app/index.ts`.

Now I know we can't set environment variables in tsconfig, this would be convenient and isn't a ts-node concern. However, do you have any thoughts if this could be somehow settable on the ts-node side? I'm running nodemon in development and there it's easy to set.

**Comment by blakeembrey** [comment]
Environment variables don't really have anything to do with `ts-node`. You can set it just like you are, or before `nodemon` if you wanted. You can also modify the require function in node.js using https://github.com/TypeStrong/ts-node#loading-tsconfigjson if you wanted to. I don't intend to have `ts-node` have the ability to alter the runtime require behaviour of node.js in any way directly.

**Comment by tedcurrent** [comment]
Alright, thanks for the comments!

**Comment by ashok-sc** [comment]
Does ts-node not handle non-relative paths? I'm trying to use this strategy to import modules: https://goenning.net/2017/07/21/how-to-avoid-relative-path-hell-javascript-typescript-projects/. Basically I don't want to use relative paths, but ts-node fails saying it cannot find the module. Is this not supported?

**Comment by blakeembrey** [comment]
@ashok-sc See the note in the README under https://github.com/TypeStrong/ts-node#loading-tsconfigjson. It's not provided directly by `ts-node`, but it's easily plugged in.

**Comment by electricessence** [comment]
@blakeembrey Before I open another issue I want to be sure I'm not going insane because I currently cannot get ts-node to do anything worthwhile.  I've been beating my head bloody for days searching, reading and experimenting with every config I can think of.

If it's not one thing it's another.  But most of my woes seem to be related to importing other modules.
In the case of gulp for example, I'm loading other modules and registering tasks with gulp but it can't even get past the imports:
```
TSError: ⨯ Unable to compile TypeScript
_gulp\tests.ts (1,43): Cannot find module 'gulp-typescript-helper'. (2307)
_gulp\tests.ts (2,23): Cannot find module './constants/TaskNames'. (2307)
_gulp\tests.ts (3,23): Cannot find module 'gulp'. (2307)
```

This is the branch I'm currently working on:
https://github.com/electricessence/TypeScript.NET/tree/next

I can't get mocha to work either. :(

**Comment by blakeembrey** [comment]
@electricessence Have you tried updating `ts-node`? If that fails I can look further into it, but the version you have listed in your `package.json` is over a year old.

**Comment by electricessence** [comment]
@blakeembrey Wow ok.  That was odd.  (I had thought I updated everything.)  My first attempt to update took it from 1.6 to 1.7.  Then I updated global and it jumped to 5.0.   Then I uninstalled and installed again and got the project up to 5.  Now everything works. 😄 Thank you.

**Comment by hyphen-wrex** [comment]
Removing `module` and `target` fields from `tsconfig.json` worked for me.

**Comment by MikaelEdebro** [comment]
@tedcurrent solution did the trick for me. I also hade NODE_PATH=src in my .env file, so adding it before the ts-node call solved it. I'm using ts-node together with nodemon, so my code is:

nodemon.json
```json
{
  "ignore": ["**/*.test.ts", "**/*.spec.ts", ".git", "node_modules"],
  "watch": ["./src"],
  "exec": "set NODE_PATH=./src node --inspect -r ./node_modules/.bin/ts-node/register ./src/index.ts",
  "ext": "ts"
}
```
Note that Windows users need to do `set NODE_PATH`.

**Comment by SephReed** [comment]
I'm stuck on this too.  My tsconfig has this:

```
"paths": {
			"@middleware": ["../middleware/src"]
		},
```

And I'm able to pull interfaces/types from it.  But nothing else.

**Comment by stephen-smith** [comment]
Stuck here, too.
```
% npx ts-node src/queue.bench.ts
⨯ Unable to compile TypeScript:
src/queue.bench.ts:5:20 - error TS2307: Cannot find module 'benny'.

5 import * as b from "benny";
                     ~~~~~~~
```

Loading the module use plain node works:
```
% node
> require('benny')
{ add: { [Function: add] only: [Function], skip: [Function] },
  complete: [Function: complete],
  cycle: [Function: cycle],
  save: [Function: save],
  suite: [Function: suite],
  default:
   { add: { [Function: add] only: [Function], skip: [Function] },
     complete: [Function: complete],
     cycle: [Function: cycle],
     save: [Function: save],
     suite: [Function: suite] } }
```

Adding `--files` doesn't help.  Using `node -t ts-node/register` instead of `npc ts-node` gives same error.  Not sure why ts-node doesn't want to load the module.

Types are available under node_modules:
```
% find node_modules -path '*benny*' -name '*.d.ts'
node_modules/benny/lib/internal/common-types.d.ts
node_modules/benny/lib/internal/format.d.ts
node_modules/benny/lib/internal/getCaseResult.d.ts
node_modules/benny/lib/internal/getSummary.d.ts
node_modules/benny/lib/internal/prepareFileContent.d.ts
node_modules/benny/lib/add.d.ts
node_modules/benny/lib/complete.d.ts
node_modules/benny/lib/cycle.d.ts
node_modules/benny/lib/index.d.ts
node_modules/benny/lib/save.d.ts
node_modules/benny/lib/suite.d.ts
```

**Comment by abinici** [comment]
I also ran into this issue in my NestJS project when I tried enabling debugging in VSCode. I managed to solve this by changing my nodemon.json to:

```
{
  "watch": ["src"],
  "ext": "ts",
  "ignore": ["src/**/*.spec.ts"],
  "exec": "node -r tsconfig-paths/register -r ts-node/register src/main.ts"
}
```

It was the part `-r tsconfig-paths/register` that fixed it. This parameter will convert paths into physical file paths.

**Comment by MitchTalmadge** [comment]
Thank you @abinici, you are my hero. No idea how you figured that out.

**Comment by cspotcode** [comment]
tsconfig-paths is mentioned in our README.

**Comment by MitchTalmadge** [comment]
Ah you are correct, I didn't see that at all I guess because I just assumed it already followed the tsconfig paths. For the most part in fact it seemed like they were being obeyed without the tsconfig-paths register. Maybe I am not understanding things fully. It's working now though.

**Comment by SephReed** [comment]
A year later, dealing with this again.   This thing _needs_ to throw a more directive error.

Am I suppose to install tslib?  Maybe put some typings somewhere... what was it again?   Why isn't fs already there...

**Comment by blakeembrey** [comment]
@SephReed What is your comment in relation to?

**Comment by SephReed** [comment]
This https://github.com/TypeStrong/ts-node/issues/1012

**Comment by dbwodlf3** [comment]
ts-node always works from pwd. you need to set basedir in tsconfig.json and work with tsconfig-paths.

**Comment by danielo515** [comment]
> ts-node always works from pwd. you need to set basedir in tsconfig.json and work with tsconfig-paths.

That is exactly what I did and I am still having that problem. Not sure if the problem lies on the fact that I'm using require to import a file that then uses import. Here is my tsconfig:

```
{
  "compilerOptions": {
    "outDir": "./dist",
    "jsx": "react",
    "allowJs": true,
    "esModuleInterop": true,
    "target": "es6",
    "baseUrl": "./src",
    "module": "esnext",
    "moduleResolution": "Node",
    "sourceMap": true,
    // NOTE: this is only temporary until we actually can add all typescript types!
    "skipLibCheck": true,
    "paths": {
      "react": ["../node_modules/react"],
      "redux": ["redux/*"],
      "testUtils": ["testUtils"],
      "spring/*": ["../../spring/*"],
      "spring": ["../../spring/src"]
    },
    "lib": ["es2020", "DOM"]
  },
  "include": ["./src/**/*", "./types"],
  "exclude": ["node_modules"],
  "ts-node": {
    "compilerOptions": {
      "paths": {
        "ukStrings": ["./src/ukStrings.ts"]
      },
      "module": "CommonJS",
      "target": "es2017"
    }
  }
}
```

As you can see, I have a path specified for ts-node. However, when I require a file `require(fullPathToFile)` that then imports `ukStrings` I get a can not compile error, telling me that it can't find the ukStrings file.

**Comment by cprcrack** [comment]
You can use the [module-alias](https://www.npmjs.com/package/module-alias) package as described in https://dev.to/larswaechter/path-aliases-with-typescript-in-nodejs-4353

**Comment by alainosorio** [comment]
Hi, 

I'm having the same issue from the first post, long story short I'm converting a nodejs app to typescript, I run the app with:

`ts-node-esm .\\src\\server.ts`

This is my tsconfig.json

{
  "compilerOptions": {
    /* Docs: [https://www.typescriptlang.org/tsconfig](https://www.typescriptlang.org/tsconfig) */
    "target": "ES2020",
    "module": "ESNext",
    "outDir": "bin",
    "rootDir": "src",
    "strict": true,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "checkJs": true,
    "allowJs": true,
    "moduleResolution": "node",
    "types": ["node"],
    "lib": ["es6"],
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "allowUnreachableCode": true,
    "useUnknownInCatchVariables": false // TypeScript 4.4+ only!
  },
  "include": ["src/**/*.ts", "src/**/*.js"],
  "exclude": ["node_modules", "<node_internals>/**"],
  "esm": true
}

Any help would be great!

**Comment by ffy** [comment]
I met the problem: `Error: Cannot find module '@app/lib/prisma_client'`, and I add the following code in the tsconfig.json:

```
{
  "ts-node": {
    // Do not forget to `npm i -D tsconfig-paths`
    "require": ["tsconfig-paths/register"]
  }
}
```

then re-run `ts-node src/index.ts`, everything is good now!
reference: [paths and baseUrl](https://github.com/TypeStrong/ts-node#paths-and-baseurl)
and the full tsconfig.json is here:

```json
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "baseUrl": "./src",
    "paths": {
      "@app/*": ["*"]
    },
    "outDir": "./dist",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules"],
  "ts-node": {
    "require": ["tsconfig-paths/register"]
  }
}
```

**Comment by thomas-void0** [comment]
> 
thx，this question tried me tolong.

**Comment by dwil618** [comment]
I had pretty much the same issue as the OP, but using **esm**. I didn't get anywhere with the solutions in the comments here but [this blog post](https://codingbeautydev.com/blog/ts-node-unknown-file-extension-ts/) did help.

Specifically, adding `"experimentalSpecifierResolution": "node"` in my ts-config under ts-node resolved my issue.

Full ts-config:
```json
{
  "compilerOptions": {
    "target": "ES2019",
    "lib": [
      "es2019",
      "DOM"
    ],
    "module": "ESNext",
    "declaration": true,
    "strict": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": false,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
    "isolatedModules": true,
    "typeRoots": [
      "./node_modules/@types"
    ],
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "moduleResolution": "node"
  },
  "ts-node": {
    "esm": true,
    "experimentalSpecifierResolution": "node",
    "transpileOnly": true
  }
}
```

**Comment by sagargulati** [comment]
This is my tsconfig.json
```
{
  "compilerOptions": {
    "target": "es6",
    "lib": ["es5", "es6", "dom"],
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "module": "commonjs",
    "moduleResolution": "node",
    // "baseUrl": "src/",
    "typeRoots": ["./src/types", "./node_modules/@types"],
    "resolveJsonModule": true,
    "outDir": "./dist",
    "removeComments": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "skipLibCheck": true,
    "paths": {
      "@libs/*": ["./src/libs/*"],
      "@locales/*": ["./src/locales/*"],
      "@models/*": ["./src/models/*"],
      "@routes/*": ["./src/routes/*"],
      "@utils/*": ["./src/utils/*"],
      // "@src/*": ["*"],
    }
  },
  "include": ["./src/**/*.tsx", "./src/**/*.ts"],
  "exclude": ["node_modules", "test/**/*.ts"],
  "ts-node": {
    "esm": true,
    "experimentalSpecifierResolution": "node",
    "transpileOnly": true,
    "require": ["tsconfig-paths/register"]
  },
}
```

I am trying to use Typescript with express.js
However, in my VScode on Mac, I'm still getting an error **Error: Cannot find module '@utils/Helpers'**

**Comment by byleese** [comment]
Thank you [dwil618](https://github.com/dwil618)

It works in windows node v18

 "ts-node": {
     "esm": true,
     "experimentalSpecifierResolution": "node",
     "transpileOnly": true
  }

**Comment by tombohub** [comment]
> Thank you [dwil618](https://github.com/dwil618)
> 
> It works in windows node v18
> 
> "ts-node": { "esm": true, "experimentalSpecifierResolution": "node", "transpileOnly": true }

@byleese what is this , where do you put this?

**Comment by xreider** [comment]
**tsconfig.json**

```
{
  "compilerOptions": {
    "target": "es2017" /* Set the JavaScript language version for emitted JavaScript and include compatible library declarations. */,
    "lib": [
      "es2017",
      "esnext.asynciterable"
    ] /* Specify a set of bundled library declaration files that describe the target runtime environment. */,
    "module": "commonjs" /* Specify what module code is generated. */,
    "rootDir": "." /* Specify the root folder within your source files. */,
    "moduleResolution": "Node" /* Specify how TypeScript looks up a file from a given module specifier. */,
    "baseUrl": "./" /* Specify the base directory to resolve non-relative module names. */,
    "paths": {
      "@src/*": ["./src/*"],
      "@prisma/*": ["./prisma/*"]
    } /* Specify a set of entries that re-map imports to additional lookup locations. */,
    "typeRoots": [
      "src/types/libraries/",
      "node_modules/@types"
    ] /* Specify multiple folders that act like './node_modules/@types'. */,
    "resolveJsonModule": true /* Enable importing .json files. */,
    "declaration": true /* Generate .d.ts files from TypeScript and JavaScript files in your project. */,
    "sourceMap": true /* Create source map files for emitted JavaScript files. */,
    "outDir": "./dist" /* Specify an output folder for all emitted files. */,
    "importHelpers": true /* Allow importing helper functions from tslib once per project, instead of including them per-file. */,
    "allowSyntheticDefaultImports": true /* Allow 'import x from y' when a module doesn't have a default export. */,
    "esModuleInterop": true /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables 'allowSyntheticDefaultImports' for type compatibility. */,
    "forceConsistentCasingInFileNames": true /* Ensure that casing is correct in imports. */,
    "strict": true /* Enable all strict type-checking options. */,
    "useUnknownInCatchVariables": true /* Default catch clause variables as 'unknown' instead of 'any'. */,
    "skipLibCheck": true /* Skip type checking all .d.ts files. */
  },
  "include": ["src/**/*", ".env"],
  "exclude": ["node_modules", "src/http", "src/logs", "src/tests"],
  "ts-node": {
    "require": ["tsconfig-paths/register"]
  }
}
```

**package.json**
```
{
  "name": "server",
  "scripts": {
    "dev": "ts-node src/index.ts",
    "build": "tsc && tsc-alias",
    "start": "node dist/src/index.js"
  },
  "devDependencies": {
    "@types/node": "^20.12.12",
    "ts-node": "^10.9.2",
    "tsc-alias": "^1.8.10",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.4.5"
  },
  "version": "1.0.0",
  "main": "index.ts",
  "license": "MIT"
}



```
