### ISSUE TITLE
Can ts-node work with standard-things/esm?

### ISSUE THREAD

**Issue by sgwatgit** [TypeStrong/ts-node#424]
I realize ts-node does not support ES modules because node does not (yet), so I would like to use esm as the compat layer for using ES modules in node.
https://github.com/standard-things/esm

main.ts
```
require = require('@std/esm')(module, { cjs: true, esm: 'js' });

const PI = require('./test').default;

console.log(PI);
```

test.ts
```
const PI = 3.14;

export default PI;
```

tsconfig.json
```
{
    "compilerOptions": {
        "module": "es2015",
        "moduleResolution": "node",
        "target": "es2015",
        "allowJs": true,
        "lib": [
            "es2017",
            "dom"
        ],
    }
}
```
I'm running `ts-node -P ./tsconfig.json ./main.ts`

Error
```
..\app\node_modules\source-map-support\source-map-support.js:372
  return error + stack.map(function(frame) {
               ^

TypeError: Cannot convert object to primitive value
    at Function.prepareStackTrace (..\app\node_modules\source-map-support\source-map-support.js:372:16)
    at process.emit (..\app\node_modules\source-map-support\source-map-support.js:422:51)
    at process._fatalException (bootstrap_node.js:332:26)
```
The paths in the error above were truncated by me - they were printed as absolute filesystem paths.

When I compile this code using `tsc -p ./tsconfig.json` I can then run `$ node main.js` with an output of `3.14`, so I feel the issue is how I'm using `ts-node` or limitations in the package.

Thanks!

**Comment by blakeembrey** [comment]
You should open an issue at `source-map-support`, which is how we map the JavaScript runtime errors to correct line numbers. The error in your stack trace starts here: https://github.com/evanw/node-source-map-support/blob/b9b5a5576272916237a253393220770c858685d6/source-map-support.js#L422. Looks like whatever it being thrown can not be stringified, I'd say `source-map-support` should be using `String()` or `toString` here to be explicit.

**Comment by blakeembrey** [comment]
Can you log and find out what error object is being thrown at that line?

**Comment by sgwatgit** [comment]
@blakeembrey Definitely, I'll add some more info here shortly! Thanks

I figured the issue was with `node-source-map-support` but I'm so new to `ts-node` I wasn't sure what the interplay was.

I realize I'm playing on bleeding edges here so I don't expect a reasonable solution (if any) - just exploring my options.
