### ISSUE TITLE
should read tsconfig.json

### ISSUE THREAD

**Issue by ninja-** [TypeStrong/ts-node#434]
ts-node should read tsconfig.json file closest to the running directory, not use the pointless TS_NODE_COMPILER_OPTIONS
(for example I have experimentalDecorators: true etc. so I can't run unit tests with ts-node & intellij without adding a hack in form of ts_node_compiler_options)

**Comment by blakeembrey** [comment]
That is how it works. If you're not actually in the current working directory with your `tsconfig.json` file, use the `project` option.
