### ISSUE TITLE
ts-node console.trace prints `[object Object]` for strings

### ISSUE THREAD

**Issue by raymondfeng** [TypeStrong/ts-node#441]
With a very simple `t.ts` as follows:
```
console.trace('a');
```
$ ts-node t
```
[object Object]
    at Object.<anonymous> (/private/tmp/t.js:2:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at Object.<anonymous> (/Users/rfeng/.nvm/versions/node/v8.6.0/lib/node_modules/ts-node/src/_bin.ts:182:12)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
```

Please note `[object Object]` is printed out instead of `a`.

tsc compiles the code to `console.trace('a');` and it works as expected.

BTW, console.log does NOT have the same issue.

**Comment by blakeembrey** [comment]
I'd suggest making the issue over at https://github.com/evanw/node-source-map-support. I can replicate it with source map support enabled (default) and it's resolved when disabled.

**Comment by blakeembrey** [comment]
I can also make the issue if you don't want to, just let me know 😄

**Comment by blakeembrey** [comment]
For the interim, if this is urgent, would you like a flag that can disable source map support?

**Comment by raymondfeng** [comment]
@blakeembrey Can you explain why this issue has to do with https://github.com/evanw/node-source-map-support? It's not about the stacktrace, but the printed out value of a string.

**Comment by blakeembrey** [comment]
See my message when I closed the issue. It happens with source map support enabled, it doesn’t happen if it’s disabled.

**Comment by raymondfeng** [comment]
@blakeembrey Thanks for the explanation. Do you mind opening an issue against https://github.com/evanw/node-source-map-support? You are closer to that code :-).

**Comment by blakeembrey** [comment]
Sure, no problem. I haven't had a chance to investigate why just yet, but I imagine the same issue is happing on all projects using `source-map-support` (e.g. Babel and CoffeeScript also). Opening it now, will link back to here.

**Comment by Somebi** [comment]
bump v11.3.0, bug still persists
