### ISSUE TITLE
How do I debug an app?

### ISSUE THREAD

**Issue by basharov** [TypeStrong/ts-node#442]
I found that I can debug a nodejs app with inspect argument as explained in docs: https://nodejs.org/api/debugger.html.

The command is like this:
```
node inspect myscript.js
```

Can I debug a TypeScript in a similar fashion?

**Comment by blakeembrey** [comment]
You can use `--inspect`, I haven't released a fix to allow `ts-node inspect` directly, if that's what you're asking: https://github.com/TypeStrong/ts-node/pull/426.
