### ISSUE TITLE
I get error "Cannot find module" if I use non-relative module imports and set baseUrl

### ISSUE THREAD

**Issue by pomadin** [TypeStrong/ts-node#448]
Hi,

I prefer to use non-relative module imports in my code. The typescript compiles the project and the tests well. I could setup my test run in two steps, the 1st one transpiles ts code into js and the 2nd one runs mocha for the built code. Of course, I have used some plugin on the last step to adjust module resolving (aliasing) due to non-relative imports. But I would like to setup the same in one step run using ts-node. Unfortunately, when I try to run mocha via ts-node I get the error: "Cannot find module" for any non-relative module import.

Can I use ts-node for my scenario or I have to keep using two steps test run? The relative imports is not an option for me. 

I have created a project [mocha-tests.zip](https://github.com/TypeStrong/ts-node/files/1404682/mocha-tests.zip) depicting my issue. It is well compiled by `npm run build` or `tsc`, but I have got the error if I run `npm test` or `mocha`. Even `ts-node ./test/math.spec.ts` will fail on module resolving not on mocha stuff. 

Main Package Versions:
- ts-node: "3.3.0"
- typescript: "2.5.3"

**Comment by blakeembrey** [comment]
Please use the `tsconfig-paths` module linked in the README if you want to do this.

**Comment by pomadin** [comment]
Thank you, I missed that in README. It helps me.
