### ISSUE TITLE
Unable to use REPL

### ISSUE THREAD

**Issue by pelotom** [TypeStrong/ts-node#453]
TypeScript version: 2.5.3

```
» ts-node
> const x = 3
Thrown: ⨯ Unable to compile TypeScript
[eval].ts: Cannot find name 'exports'. (2304)
[eval].ts (0,11): Cannot find name 'module'. (2304)
```

**Comment by blakeembrey** [comment]
Duplicate of https://github.com/TypeStrong/ts-node/issues/437.

**Comment by pelotom** [comment]
Is there any timetable for a new release with this fix?

**Comment by blakeembrey** [comment]
When all other major tasks are done, so no. Is it very difficult to install a type definition until then?

**Comment by pelotom** [comment]
Nope, I just wasn’t aware of what the fix was.

**Comment by blakeembrey** [comment]
No problem, I thought it was in the linked issue but it was in the duplicate of that duplicate. See https://github.com/TypeStrong/ts-node/issues/351#issuecomment-307178924.
