### ISSUE TITLE
ts-node -r @std/esm index.js is not supported

### ISSUE THREAD

**Issue by motss** [TypeStrong/ts-node#463]
Title says it all.

**Comment by blakeembrey** [comment]
The title doesn’t really say it all if you’d like help. What’s the error? What’s your config file look like? Is there anything in `index.js` I need to replicate? I believe someone logged an issue about this in the past, it might be worth looking for that too.

**Comment by blakeembrey** [comment]
See https://github.com/TypeStrong/ts-node/issues/424 also.

**Comment by jdalton** [comment]
I've confirmed `ts-node` works with `-r` [`esm`](https://github.com/standard-things/esm) now. This issue can be closed.

**Comment by havenchyk** [comment]
@blakeembrey @motss  would you be so kind to close the issue? :)
