### ISSUE TITLE
Error when use symlink with node_modules

### ISSUE THREAD

**Issue by k8w** [TypeStrong/ts-node#464]
**Problem**
File structure:
```
|- __shared
    |- ShareClass.ts
|- backend
    |- <shared>  // symlink to ../__shared
    |- index.ts
```

__shared/ShareClass.ts
```ts
import XXX from 'some-node-modules';
...
```

backend/index.ts
```ts
import XXX from './shared/ShareClass';
```

```
ts-node index.ts
```

It will throw error:
> TSError: ⨯ Unable to compile TypeScript
..\__shared\ShareObj.ts (1,26): Cannot find module 'tsrpc-protocol'. (2307)

**Expect**
`shared/ShareObj.ts` is treated as its symlink path.

**Demo**
A demo project [here](https://github.com/k8w/ts-node-symlink-problem)

```
cd backend
npm install
ts-node index.ts
```

**Comment by blakeembrey** [comment]
Can you add your comment to https://github.com/TypeStrong/ts-node/issues/396? I believe it'd be the same issue and I'd love to have it fixed if someone wants to submit a PR.
