### ISSUE TITLE
mocha, ts-node and recursively loading files

### ISSUE THREAD

**Issue by alexpchin** [TypeStrong/ts-node#466]
Using this script:

    "test": "./node_modules/mocha/bin/mocha --recursive --require ts-node/register ./test/**/*.spec.ts --opts ./test/mocha.opts",

 I've tried to load some test files inside the tree:

    .
    ├── controllers
    │   ├── admin
    │   │   └── users.spec.ts
    │   ├── authentications.spec.ts

The `authentications.spec.ts` test file gets loaded but the `users.spec.ts` doesn't.

My mocha.opts file looks like just:

    --timeout 5000

I've also tried to remove the `--recursive` flag and just have a glob but it doesn't work.

I can't work out whether the problem is with `ts-node` or with `mocha`?

Any ideas?

**Comment by blakeembrey** [comment]
This isn't related to `ts-node`, but I'd bet it's your shell. Just quote your glob so mocha expands it instead of your shell.
