### ISSUE TITLE
Official logo for ts-node?

### ISSUE THREAD

**Issue by kumarashwin** [TypeStrong/ts-node#470]
We use `ts-node` heavily at my workplace and we're on the cusp of launching a major production application. As a little something for myself and my coworkers, to show support and pride for this project, I was planning to make a `ts-node` sticker as a gift for us all.

**Since there isn't a ts-node logo at the moment, I would like to understand if there is perhaps interest in having one?**

### Idea 1

![ts-node-logo](https://user-images.githubusercontent.com/12243763/33518868-6e2595c4-d76a-11e7-8260-31b4e8110c93.png)

### Idea 2

![new-logo-ts-node](https://user-images.githubusercontent.com/12243763/40760176-7f92ceb8-6463-11e8-9c4b-f65907c613ae.png)

**Comment by ORESoftware** [comment]
nice work :)

**Comment by stelcheck** [comment]
Outside of the visual reference, might be nice to include the word "node" somewhere, so not to confuse newcomers into thinking this is a TypeScript logo.

**Comment by blakeembrey** [comment]
Love the logo and would be happy to add it to the README 😄 Agree with @stelcheck that adding `node` somewhere on there is probably a good idea - it definitely looks like it could be the TS logo as is.

**Comment by kumarashwin** [comment]
@stelcheck @blakeembrey Thanks for the support. Will take your comments into account and work on perhaps another similar logo that could include what you guys are suggesting.

**Comment by blakeembrey** [comment]
@kumarashwin I don't suppose you have the logo in SVG or the original somewhere we can use?

**Comment by kumarashwin** [comment]
@blakeembrey I completely forgot about this! I see that I'd promised to come up with another design based on you guys' suggestion.

I'll look for the original and also see if I can do up the idea I had in mind for including `node` so you guys can see if you'd like to use it.

**Comment by blakeembrey** [comment]
Thank you 😄 If you don't have the time, feel free just to share the original and I can take a look.

**Comment by kumarashwin** [comment]
Sorry for the delay! Finally had some time today to look into this again. I didn't have access to the computer on which the .svgs for the image above are stored but I should be able to look at it tomorrow and retrieve them.

In the mean-time, here's another idea I had based on your suggestions:

![new-logo-ts-node](https://user-images.githubusercontent.com/12243763/40760176-7f92ceb8-6463-11e8-9c4b-f65907c613ae.png)

**Comment by blakeembrey** [comment]
@kumarashwin Looks great 👍 With your permission and the SVGs, I'm happy to use this on the README. Feel free to submit a PR also, it's reasonably easy to do (ref: https://raw.githubusercontent.com/serviejs/popsicle/master/README.md).

**Comment by stelcheck** [comment]
Already put a +1, but looks really good!

**Comment by kumarashwin** [comment]
Awesome! I failed to comment earlier but I was unable to find the older logo in it's `.svg` :sweat_smile: 

So I'm quite happy you guys like the new one. I'll locate it and have it PRed. :+1:

**Comment by blakeembrey** [comment]
Closed with https://github.com/TypeStrong/ts-node/pull/607.

**Comment by kumarashwin** [comment]
Sticker time!

**Comment by blakeembrey** [comment]
@kumarashwin Good idea! If anyone wants stickers, let me know (or 👍 this comment) and I'll see what I can do.

**Comment by lmbd92** [comment]
Wow I need the same style but for a js-node logo, I love this one
