### ISSUE TITLE
Bug/feature:  ts-node should work with NODE_OPTIONS

### ISSUE THREAD

**Issue by ORESoftware** [TypeStrong/ts-node#471]
This works:

```bash
ts-node --inspect-brk foo.ts  # ❤️
```

but this doesn't

```bash
NODE_OPTIONS="--inspect-brk" ts-node foo.ts #  💥
```

I think it's because `ts-node` starts a child process, and because of that, we get an "address already in use" error. See the Node.js help issue attached.

Just try it for yourself and you will see the problem.

**Comment by ORESoftware** [comment]
I see this:

<img width="291" alt="screenshot 2017-12-03 14 53 07" src="https://user-images.githubusercontent.com/11139560/33530802-c7d97016-d839-11e7-8955-3879eabcb455.png">

perhaps `_ts-node` is for debugging? I am curious what that's for

**Comment by ORESoftware** [comment]
I think what would be most useful is to highlight which env variable can trip ts-node to go into debug mode. I was looking at the source:

https://github.com/TypeStrong/ts-node/blob/master/src/bin.ts#L19

looks like `ts-node --inspect-brk foo.ts` should do the trick

but I'd also like to see an env option for that if possible (I think the new node-options initiative will make that possible)

so maybe have this documented:

`NODE_OPTIONS="--inspect-brk" ts-node --inspect-brk foo.ts`

**Comment by ORESoftware** [comment]
See this issue for reference: https://github.com/nodejs/help/issues/1007

**Comment by stelcheck** [comment]
I think the best option would be to wrap or convert https://github.com/TypeStrong/ts-node/blob/master/src/bin.ts into a bash/cmd script.

**Comment by ORESoftware** [comment]
@stelcheck I think the problem is that `ts-node` spawns a child process

https://github.com/TypeStrong/ts-node/blob/master/src/bin.ts#L53

so what we need is that spawned child process to debug on a different port than the parent process.

**Comment by stelcheck** [comment]
Why even spawn a port on the `bin` process? That process should not even *react* to NODE_OPTIONS; I can't think of a case where you'd want that as a user. This is why I was suggesting to either replace or wrap that file with a bash/sh/cmd file; these do not react to NODE_OPTIONS, and in the case of wrapping, options could then be forwarded the proper way to the spawned child process.

**Comment by ORESoftware** [comment]
dude I am so confused

this is ergonomic

`NODE_OPTIONS="--inspect-brk" ts-node foo.ts`

but it breaks... try it.

are you suggesting something more ergonomic, or less? Sounds like the latter to me. Perhaps demo the code you are talking about.

**Comment by stelcheck** [comment]
Apologies for the confusion.

I am suggesting a way to patch `ts-node`'s code in a way that should solve your issue. Should we do that, running `NODE_OPTIONS="--inspect-brk"` should start working correctly as-is.

And please don't call me dude.

**Comment by stelcheck** [comment]
Actually, the simplest thing might just be to introduce a `TS_NODE_OPTIONS` environment variable which would be passed as `NODE_OPTIONS` to the spawned process. @blakeembrey would that be acceptable to you?

**Comment by stelcheck** [comment]
I preemptively created a PR implementing that behavior. @ORESoftware feel free to give it a spin and let me know if this would fix your current issue.

**Comment by blakeembrey** [comment]
For now, can you use `ts-node -r ts-node/register`? I'm hesitant to go too much further on the different node.js shell spawning tricks in use right now.

**Comment by ORESoftware** [comment]
@blakeembrey - in this case my node.js process is spawning children and I need to debug the children using Node.js exec flags, so it's not just about loading `ts-node/register`

**Comment by stelcheck** [comment]
https://github.com/TypeStrong/ts-node/pull/499 Would allow you to use NODE_OPTIONS off the bat instead of using TS_NODE_OPTIONS

**Comment by ORESoftware** [comment]
cool I am all for anything that werks

**Comment by blakeembrey** [comment]
Closing with https://github.com/TypeStrong/ts-node/pull/536 as I won't be supporting the subprocess behaviour anymore.
