### ISSUE TITLE
How to import 3-rd JS package which without declaration?

### ISSUE THREAD

**Issue by zheeeng** [TypeStrong/ts-node#473]
Once my tsconfig.json set `"noImplicitAny": true,`, ts-node repl will report `Thrown: ⨯ Unable to compile TypeScript`

**Comment by zheeeng** [comment]
I found that problem is that I set "types" option cause ts-node can't handle other libs.

**Comment by stelcheck** [comment]
@zheeeng Have a look at https://stackoverflow.com/a/35171227/262831 - this should solve your issue.

**Comment by zheeeng** [comment]
@stelcheck Thks for your help. `declaration` doesn't solve my problem, the 'type' option in tsconfig.json cause 3-rd JS package can't be complied. And 'noImplicitAny' cause another compiling problem.

**Comment by stelcheck** [comment]
Arguably, ts-node could safely override `noImplicitAnyP` when in REPL mode... that would indeed make it much easier to use it I think.

As for the `types` configuration entry, @zheeeng I am not sure what you are trying to say. Could you try rephrasing what you meant?

**Comment by zheeeng** [comment]
@stelcheck In `tsconfig.json` I setted `types: [mocha]`. That exclude other type definitions and cause ts-node to work normally. My bad.

**Comment by stelcheck** [comment]
Right. As soon as you put one types, you now need to put *all* types explicitly indeed.

**Comment by blakeembrey** [comment]
Looks resolved?
