### ISSUE TITLE
ts-node exits prematurely (before all callbacks have processed)

### ISSUE THREAD

**Issue by gregjacobs** [TypeStrong/ts-node#474]
`ts-node` seems to exit even while asynchronous tasks are still being performed.

For instance, this `ts-node` command exits immediately:

```
ts-node --eval "function wait() { setTimeout( wait, 1000 ); } wait();"
```

While using the regular `node` executable properly keeps it alive forever:

```
node --eval "function wait() { setTimeout( wait, 1000 ); } wait();"
```

Using ts-node v3.3.0 and node v8.9.2

**Comment by gregjacobs** [comment]
Worked around this for the moment using `node` and the `'ts-node/register'` module:


```
node --require ts-node/register waiter.ts
```

waiter.ts:

```ts
function wait( time: number ) {
    setTimeout( () => wait( time ), time );
}
wait( 1000 );
```

In this case the script stays alive.

**Comment by blakeembrey** [comment]
Thanks for the report. I believe there’s duplicate issues and a couple of PRs for this already, can you test the PRs and see if it works?

**Comment by stelcheck** [comment]
@gregjacobs https://github.com/TypeStrong/ts-node/pull/477 Should solve your issue.

**Comment by gregjacobs** [comment]
Great, glad to hear! Tested with 4.0.0 and seems to work. Thanks guys!
