### ISSUE TITLE
Some minimist args passed from cli are null not undefined

### ISSUE THREAD

**Issue by whitecolor** [TypeStrong/ts-node#483]
![image](https://user-images.githubusercontent.com/736697/33961557-537699f8-e070-11e7-9eef-8ea734d74dec.png)

And here they are checked to be `undefined`, so for example `cache` doesn't work by default.
https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L172

**Comment by blakeembrey** [comment]
Feel free to submit a PR. Mini ist has caused me a lot of pain and I’d love to refactor that one day.

**Comment by MuthukumarHelios** [comment]
hi @whitecolor  and @blakeembrey 
I am very curious about the above issue...
But i cannot understand the Question  might be lack of knowledge 
ts-node/dist$ls
`_bin.d.ts  bin.js       index.d.ts    index.spec.d.ts
bin.d.ts   _bin.js.map  index.js      index.spec.js
_bin.js    bin.js.map   index.js.map  index.spec.js.map
`

on the above .ts file which file you are running

**Comment by blakeembrey** [comment]
Closing with https://github.com/TypeStrong/ts-node/pull/536.
