### ISSUE TITLE
ts-node not working with async functions

### ISSUE THREAD

**Issue by ORESoftware** [TypeStrong/ts-node#485]
I am getting this error:

```bash
 [suman child stderr]  /Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/test/src/dev/node/2.test.js:47
 [suman child stderr]       before(async function (h) {
 [suman child stderr]              ^^^^^
 [suman child stderr] SyntaxError: missing ) after argument list
 [suman child stderr]     at createScript (vm.js:56:10)
```

after using this code:

```js
  require('ts-node').register({
    ignore: /node_modules/
  });
```

what am I doing wrong?

**Comment by blakeembrey** [comment]
You need to provide a full reproduction or more context. The error message I can see says nothing about async, it says your missing a parenthesis.

**Comment by blakeembrey** [comment]
I'm going to close this issue. I can only guess that you've tried to put the `async` function in the same file as the register?

**Comment by ORESoftware** [comment]
@blakeembrey yeah I actually don't know what it was, it wasn't because `async` function was in the file as the register call, it was something else. But now it's working, probably some sort of operator error on my part

**Comment by ORESoftware** [comment]
eh it only started working again because I switched to nodejs version 9 - it says missing parenthesis, because it can't parse async functions, not because there is a missing parenthesis.

**Comment by ORESoftware** [comment]
**oh I know what's up -** 

I was feeding ts-node a .js file instead of a .ts file, so it wasn't transpiling it, even though it needed to be transpiled...

how can I tell ts-node to transpile .js files too?

please lmk thx
