### ISSUE TITLE
Repl stopped working after 4.0.0

### ISSUE THREAD

**Issue by saadataz** [TypeStrong/ts-node#487]
simply running `ts-node` no longer opens REPL terminal
Rolling back to 3.3.0 fixed it

**Comment by stelcheck** [comment]
Seems to work for me. Can you specify the platform, node version you are running, and any additional contextual information that might help us figure out your issue?

**Comment by blakeembrey** [comment]
Possibly the same issue as https://github.com/TypeStrong/ts-node/issues/480?

**Comment by nwayve** [comment]
I just ran across this issue today as well.
```
> npm i -g ts-node
+ ts-node@4.02
> ts-node
// No REPL, just returns to the prompt
> npm r -g ts-node
> npm i -g ts-node@3.x
+ ts-node@3.3.0
> ts-node
> // in REPL
```
```
> npm --versions
{ myProject: '1.0.0',
  npm: '5.6.0',
  ares: '1.13.0',
  cldr: '32.0',
  http_parser: '2.7.0',
  icu: '60.1',
  modules: '59',
  nghttp2: '1.25.0',
  node: '9.3.0',
  openssl: '1.0.2n',
  tz: '2017c',
  unicode: '10.0',
  uv: '1.18.0',
  v8: '6.2.414.46-node.15',
  zlib: '1.2.11' }
> tsc -v
Version 2.6.2
```
```
> systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.16299 N/A Build 16299
```

Issue #480 was closed with "Upgrade to latest ts-node" but from what I can tell, `4.0.2` is the latest as of this post.  Hope this info helps.

**Comment by Nbsaw** [comment]
Same Issues

**Comment by stelcheck** [comment]
@Nbsaw @nwayve Could you try to test #489 and see if this solves your issue?

**Comment by nwayve** [comment]
@stelcheck That worked for me.
```
> npm i -g ts-node@*
+ 4.0.2
> ts-node
// No REPL as expected
```
Went into `/node_modules/ts-node/dist/bin.js` and set `detached: true` to `detached: process.platform !== 'win32'`

```
> ts-node
> // REPL!
```

Awesome find, thank you!

**Comment by Nbsaw** [comment]
@stelcheck worked for me .

**Comment by blakeembrey** [comment]
Closing with https://github.com/TypeStrong/ts-node/pull/536.
