### ISSUE TITLE
Enable --type-check option by default again

### ISSUE THREAD

**Issue by sanex3339** [TypeStrong/ts-node#493]
Hi. After 4.0.0 version, i got many problems with `--type-check` option that disabled by default.
Now in all mocha tests (running with CLI or with WebStorm IDE Interface) i should add `TS_NODE_TYPE_CHECK` environment variable, because without that all tests are failing due to `typescript` compile errors.

It is possible to revert back this change or add more global way (through config file) to enable `typeCheck` option?

**Comment by stelcheck** [comment]
You might want to see https://github.com/TypeStrong/ts-node/pull/412 - you should be able to use the register specified there.

It seems that type-check was disable so that the default behavior may remain fast.

**Comment by blakeembrey** [comment]
The things you ask for already exist, you just need to check the README. There's config options listed in https://github.com/TypeStrong/ts-node#configuration-options and there's also `ts-node/register/type-check` defined in https://github.com/TypeStrong/ts-node#programmatic. Feel free to open a PR if these docs are inadequate.

**Comment by blakeembrey** [comment]
> because without that all tests are failing due to typescript compile errors.

What does this mean? It's failing because of TypeScript compile errors when there's no type checking?

**Comment by sanex3339** [comment]
thank you. `ts-node/register/type-check` works.
