### ISSUE TITLE
Metadata for cyclic imports cannot be resolved after v4.0.0

### ISSUE THREAD

**Issue by KurtGokhan** [TypeStrong/ts-node#495]
Related to Microsoft/TypeScript#4521 and rbuckton/reflect-metadata#12, metadata for cyclic dependencies cannot be resolved. However if a factory method is used to define the type, we could somehow overcome this. 

So in Typescript this may fail:

```
class Car {
  @Field(Person) owner: Person;
}
class Person {
  @Field() car: Car;
}
```

But this used to work:

```
class Car {
  @Field(() => Person) owner: Person;
}
class Person {
  @Field() car: Car;
}
```

This used to work in v3.3.0 but not in later versions. 
I will try to create a reproducing repo. Maybe you have an idea what might have changed in the mean time?

**Comment by blakeembrey** [comment]
What do you mean that it fails? What is the command you're running?

**Comment by KurtGokhan** [comment]
Basically when you have a code with cyclic dependencies like this:

```typescript
```

**Comment by KurtGokhan** [comment]
Ignore my previous comment. The problem was with `Reflect.getMetadata`. So instead of expected output:

> Class 'Car' has a field named 'owner' with type 'undefined'
> Class 'Person' has a field named 'car' with type 'Car'

I was getting:

> Class 'Car' has a field named 'owner' with type 'Object'
> Class 'Person' has a field named 'car' with type 'Car'

Noticed that also some built-in types like `Buffer` were not recognized.

The difference between 3.x and 4.x is the default of `type-check` flag. Solved my problem using `type-check` flag.

**Comment by blakeembrey** [comment]
Right, that makes sense. You'd need to type information for reflection. Thanks for the update!

**Comment by janis-r** [comment]
Hello!
Can anyone elaborate on this one? I'm currently solving exactly the same problem of `undefined` types coming from Reflect metadata and even though we're currently using `awesome-typescript-loader` I'd be more than happy to upgrade webpack config to use `ts-loader` if that gives me all declared metadata without need to hack anything in code layout.
Only problem is that I cannot find any mention of `type-check` flag within `ts-loader` docs. So what exactly should be done to get this one working?

**Comment by KurtGokhan** [comment]
@janis-r this issue is exclusively on _ts-node_ and _node.js_ side. You do not seem to be using _ts-node_ but your issue might be related to Microsoft/TypeScript#4521 and rbuckton/reflect-metadata#12.
