### ISSUE TITLE
Cannot write to stdout in v4 on Windows

### ISSUE THREAD

**Issue by rminster** [TypeStrong/ts-node#498]
After upgrading ts-node to v4.0.0, v4.0.1 or v4.0.2, I cannot write to stdout in Windows.  I had this issue on Node v6.3.0, v8.6.0 and v8.9.3.  For example, these commands print nothing...

```
ts-node -e "console.log('Hello, world!')"
```

```
ts-node -v
```

**Comment by stelcheck** [comment]
This is related to #480

**Comment by blakeembrey** [comment]
Closing as duplicate of https://github.com/TypeStrong/ts-node/issues/480.
