### ISSUE TITLE
Typescript strict mode support

### ISSUE THREAD

**Issue by joelsmedberg** [TypeStrong/ts-node#500]
Hi, maybe it's just me who's missed something but it doesn't seem to support strict mode and nullable types like

```
function doSomething(str: string | undefined | null): string | undefined {
    ...
}
```
Is this on the planned for anytime soon? Guessing it's pretty much ts 2.6 support.
Sorry if I'm way off..
cheers

**Comment by blakeembrey** [comment]
What do you mean by "it's not supported"? If TypeScript supports it, it's supported in `ts-node`. If it's the lack of type checking being enabled that's the issue, use `ts-node --type-check`.
