### ISSUE TITLE
Missing IPC chanel

### ISSUE THREAD

**Issue by arthot** [TypeStrong/ts-node#501]
Hi, I've noticed yet another problem with a `spawn` of child process. 
For now *ts-node* has the following option while creating a child node: [`stdio: 'inherit'`](https://github.com/TypeStrong/ts-node/blob/89d62aa53fc969e0fbf8c4e4e5b63d2339856b7c/src/bin.ts#L71). 
And according [node.js docs](https://nodejs.org/api/child_process.html#child_process_options_stdio) it means "no **IPC**" (Inter-process communication)

In reality this breaks a communication with yet another parent:

parent.js:
```
const cp = require('child_process');
cp.fork('child.ts', [], {
        env: process.env,
        execPath: 'node_modules/.bin/ts-node'
    });
```

child.ts:
```
if (!process.send)
    console.log('IPC is not enabled');
else
    console.log('IPC is enabled')
```

will produce **IPC is not enabled**

See more details in the [sample repository](https://github.com/arthot/ts-node-ipc-issue) with proper environment.

So I propose to replace the `stdio` option value with `['inherit', 'inherit', 'inherit', 'ipc']` in order to enable IPC. I think it's quite safe change because according the stdio doc

> the child is launched with the IPC channel unreferenced until the child registers an event handler for the process

After such modification the sample will produce **IPC is enabled**

If someone is wondering about real-life use case sample: 

1.  npm start 
2.  webpack build client source 
3.  run server api + webpack dev server
4.  wait until the server will start 
5.  open browser

In this chain *wait until the server will start* is usually implemented in IPC way like `process.send('online')` and ts-node breaks this for now

PR #502

**Comment by blakeembrey** [comment]
Thanks for the awesome writeup! I think I'll just kill child processes instead, the amount of hacks is become unmanageable and recommending `node -r ts-node/register` seems more ideal for advanced usage. Thanks!

**Comment by arthot** [comment]
Yep, if you have plans to remove child process in near future you can close this issue, because 
```
cp.fork('child.ts', [], {
    env: process.env,
    execArgv: ['-r', 'ts-node/register']
});
```
also produces **IPC is enabled**

**Comment by blakeembrey** [comment]
Closing with https://github.com/TypeStrong/ts-node/pull/536. Thanks for your patience!
