### ISSUE TITLE
JSON, arsing error

### ISSUE THREAD

**Issue by SalathielGenese** [TypeStrong/ts-node#508]
Please, parse `tsconfig` using `jsonc` format instead of default `json`.

I almost gave up testing with `jasmine` because of a trailing comma.

Thanks, guy

**Comment by blakeembrey** [comment]
The config file is parsed using TypeScript, I'm not sure what the issue is? Can you please explain what you'd like to see changed.

**Comment by SalathielGenese** [comment]
@blakeembrey 

They were trailling semicolon and comments in my tsconfig... Which tsc itself handle well through `jsonc` spec format.

At  first, I was thinking JASMINE wasn't working as expected (since I wanted to setup Jasmine for TS raw files)... But after 04 days of unsuccessful attempts, I tried to debug it myself and found that the issue came from the way ts-node parses the `tsconfig.jscon` file (or may be the API used).

I removed the comments and trailling commas and started enjoy testing with Jasmine.

**Comment by ralphcallaway** [comment]
@blakeembrey any chance this could get re-opened? the ts community seems to operate primarily with the json with comments format, seems like it's worth trying to honor that in the tsconfig.json file ... as a ts noob i'd be lost without the comments people add in the config files

**Comment by blakeembrey** [comment]
@ralphcallaway The `tsconfig.json` file is parsed with TypeScript. What would I reopen this for if it's not an issue?

**Comment by ralphcallaway** [comment]
@blakeembrey i'll double check my version and make sure that's not the issue, glad to hear this is already working in the current version
