### ISSUE TITLE
child process living despite of parent process interrupted.

### ISSUE THREAD

**Issue by everedifice** [TypeStrong/ts-node#509]
When i interrupt below typescript code by press Ctrl+C

Spawned child process living despite of parent process interrupted.

```typescript
// test.ts
import {spawn} from 'child_process';
spawn('npx', ['ng', 'serve'], {stdio: 'inherit'});
```

I tested ts-node v4.1.0, node v8.9.1, typescript v2.4.2 environment.

I tested same code with native javascript and execute by `node` command with below code

Child process killed successfully after parent process interrupted.

```javascript
// test.js
require('child_process').spawn('npx', ['ng', 'serve'], {stdio: 'inherit'});
```

**Comment by endel** [comment]
Seems related to https://github.com/TypeStrong/ts-node/issues/519 and https://github.com/TypeStrong/ts-node/pull/419 😢

**Comment by blakeembrey** [comment]
Closing with the deletion of child processes in https://github.com/TypeStrong/ts-node/pull/536.
