### ISSUE TITLE
ts-node breaks Date reflection mechanism

### ISSUE THREAD

**Issue by 19majkel94** [TypeStrong/ts-node#511]
```ts
import "reflect-metadata";

const CollectMetadata: PropertyDecorator = (target, propertyKey) => {
    const ReflectType = Reflect.getMetadata("design:type", target, propertyKey);
    console.log(ReflectType);
    console.log(ReflectType === Date);
}

class Test {
    @CollectMetadata
    property: Date;
}
```

ts-node output:
```
PS E:\#Programowanie\#GitHub\type-graphql> npx ts-node src/date.ts
E:\#Programowanie\#GitHub\type-graphql\node_modules\ts-node\dist\bin.js
[Function: Object]
false
```
tsc and node output:
```
PS E:\#Programowanie\#GitHub\type-graphql> npx tsc; node build/date.js
E:\#Programowanie\#GitHub\type-graphql\node_modules\typescript\bin\tsc
[Function: Date]
true
```
I have no idea what's going on, how can we check the emitted js files?
I'm using ts-node `4.1.0` 😉

**Comment by 19majkel94** [comment]
ping @blakeembrey after a week 😜

**Comment by blakeembrey** [comment]
Try using `--type-check` if you want type information.

**Comment by 19majkel94** [comment]
Ok, it works but why only `Date` reflection is broke in this mode? What does `--type-check` do? 😕 Why no "Use TypeScript with type checking" affect on this case?

**Comment by 4F2E4A2E** [comment]
@blakeembrey why did you close this issue? Does it mean it's not a bug? Will this be covered somehow or is the param workaround the final solution?

**Comment by GeeWee** [comment]
What does the --type-check flag do? We're having the same issue in ts-jest.

**Comment by blakeembrey** [comment]
It does what it sounds like. It uses the TypeScript compiler to compile using the language services and type system information. Without it is only a single file transpile. If you don't have type information, you won't be able to get features that are required by having type information (such as reflecting type information as metadata).

It is not a bug, if you want type information the solution is to enable type information.

**Comment by 19majkel94** [comment]
> I would imagine every type information reflection would not work with type information, but perhaps it's only type information from external files? I have not verified this.

I've tested it and every single reflection works (classes from external files, String, Number, Boolean, etc.), only the `Date` is reflected as `Object` in this mode. That's why it's weird, should we bump the question to the TS team?

**Comment by blakeembrey** [comment]
@19majkel94 Without using `--type-check`? That's really interesting interesting, I expected an all or nothing case since the transpiler mode is a really quick `x -> y` operation without validation of types. Feel free to ping someone on the TS team, I'm not sure I'll have enough time to investigate the behaviour myself.

**Comment by dpaquette** [comment]
I am running in to this problem too. I am using the `--type-check` flag to work around the issue but that is causing performance issues as sometimes `ts-node --type-check .\app.ts` takes several minutes to run. For comparison, `ts-node .\app.ts` takes ~5 seconds to run. I can consistently reproduce the slow compile time by using the `--no-cache` flag: `ts-node --type-check --no-cache .\app.ts`.

As @19majkel94 noted, the only type that doesn't get reflected properly when skipping type checking is `Date` properties. All other types are reflected properly.

**Comment by An1mus** [comment]
Can you please clarify this Issue, since I'm new.

If I'll use ts-node --type-check, terminal will wait for TS input. 
But If I need to run unit tests, I need to specify this flag for constant usage. 
How is that possible to do?

**Comment by blakeembrey** [comment]
@An1mus Please read the documentation, it's in the README (you can use environment variables or if you're using by file you can use `ts-node/register/type-check`). If you need something else, please provide enough information for someone to assist you.

**Comment by kalani96746** [comment]
Iʻm not able to get decorator metadata data when using ts-node and I am in fact using --type-check and its still being this way...
