### ISSUE TITLE
graceful shutdown using child processes

### ISSUE THREAD

**Issue by endel** [TypeStrong/ts-node#519]
Whilst issue https://github.com/TypeStrong/ts-node/issues/457 has been fixed on `ts-node@4.1.x`, the behaviour is still wrong when using child processes. (cluster module)

I've updated my sample project to demonstrate the issue here: https://github.com/endel/ts-node-graceful-shutdown-issue

## `ts-node` behaviour:

SIGINT can be catched only for the master process.

```
$ ./node_modules/.bin/ts-node index.ts
^CShutting down MASTER...
MASTER has been shut down.
```

## `node` behaviour:

SIGINT can be catched for master and child process.

```
$ node index.js
^CShutting down CHILD...
Shutting down MASTER...
CHILD has been shut down.
MASTER has been shut down.
```

Related pull request: https://github.com/TypeStrong/ts-node/pull/419

**Comment by jwhitmarsh** [comment]
I was just about to open an issue, but I think this is related - i'm getting issues when running with the `--inspect` flag. Stopping and starting a process throws `Starting inspector on 127.0.0.1:9229 failed: address already in use` - presumably because the inspector is a child process which hasn't been stopped?

**Comment by jwhitmarsh** [comment]
After a bit more digging around in the issues it seems as though `node --inspect -r ts-node/register` works, which is perhaps expected?

**Comment by blakeembrey** [comment]
Closing with https://github.com/TypeStrong/ts-node/pull/536. Pushing people toward `node -r ts-node/register` for advanced usage since there's been a bunch of drawbacks with both approaches I've taken for supporting node.js flags natively.
