### ISSUE TITLE
TypeError: pubnub_1.default is not a constructor

### ISSUE THREAD

**Issue by soulmachine** [TypeStrong/ts-node#520]
I'm not sure this issue is related to pubnub or ts-node, but when I use pubnub with ts-node together, it will throw out the following error:

```
TypeError: pubnub_1.default is not a constructor
```

My code is:

```typescript
import Pubnub from "pubnub"
const pubnub = new Pubnub({
  subscribeKey: "sub-c-52a9ab50-291b-11e5-baaa-0619f8945a4f"
})
```

And my `tsconfig.json` is:

```json
{
  "compilerOptions": {
    "strict": true,
    "lib": ["es6"],
    "typeRoots": [
      "./node_modules/@types/",
      "./src/@types/"
    ]
  }
}
```

I've already installed types for pubnub,

```
npm install pubnub --save
npm install @types/pubnub --save-dev
```

I guess I need to change some configurations in `tsconfig.json`, any ideas?

**Comment by NaridaL** [comment]
The correct import is `import pubnub = require('pubnub')`.

**Comment by soulmachine** [comment]
@NaridaL By doing so you're importing it as a normal JavaScript library and you lose type checking

**Comment by soulmachine** [comment]
@NaridaL Thanks! 

> When importing a module using export =, TypeScript-specific import module = require("module") must be used to import the module.

But in this file [types/pubnub/index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pubnub/index.d.ts), pubnub is exported by `export default Pubnub;` instead of `export = Pubnub;`

**Comment by kantlove** [comment]
Check this pull request DefinitelyTyped/DefinitelyTyped#23085, the export statement is now updated to `export = Pubnub`

**Comment by soulmachine** [comment]
@kantlove Thanks, it does solve the problem!

**Comment by eddietindame** [comment]
Hi,

I can't get this working in my Jest tests. Seems to work fine in my app, but when testing I get `TypeError: pubnub_1.default is not a constructor`.

I am unable to import via `import pubnub = require('pubnub')` because then I get:
`'import =' is not supported by @babel/plugin-transform-typescript
    Please consider using 'import <moduleName> from '<moduleName>';' alongside Typescript's --allowSyntheticDefaultImports option.`

And of course I cannot do as it suggests, because PubNub doesn't like it.

What is the recommended solution?

Thanks

**Comment by cspotcode** [comment]
Sounds like you're not using ts-node.

**Comment by KhanhPham2411** [comment]
![Image](https://user-images.githubusercontent.com/12913151/140639998-e87924fe-2df9-46a0-8a90-308d3d055e58.png)
Just add this setting in your ts.config
`"esModuleInterop": true,`

**Comment by abhilashnamdeo** [comment]
> ![Image](https://user-images.githubusercontent.com/12913151/140639998-e87924fe-2df9-46a0-8a90-308d3d055e58.png) Just add this setting in your ts.config `"esModuleInterop": true,`

Getting application crash after adding this.
