### ISSUE TITLE
Can't pass node flags

### ISSUE THREAD

**Issue by phiresky** [TypeStrong/ts-node#522]
I'm trying to run a file with `ts-node --harmony-async-iteration file.ts` but it just drops me to a node REPL. There seem to be multiple issues regarding similar stuff, but I can't find any information on what the current state is.

**Comment by ORESoftware** [comment]
check out this issue: https://github.com/TypeStrong/ts-node/issues/471

**Comment by blakeembrey** [comment]
Try `node --harmony-async-iteration --require ts-node/register file.ts` instead.

**Comment by slikts** [comment]
The above command results in `Error: Cannot find module 'ts-node/register'`

**Comment by blakeembrey** [comment]
@slikts Did you install `ts-node` first?

**Comment by slikts** [comment]
IIRC it turned that it needed to be installed locally while I had it installed globally.
