### ISSUE TITLE
issue in compiling modernizr and jsdom, in a mocha test

### ISSUE THREAD

**Issue by nebeleh** [TypeStrong/ts-node#524]
I have a small [repo](https://github.com/nebeleh/ts-node-test) for testing a couple of modules using `mocha` and `ts-node`.

`src/myclass.ts`:
```typescript
import * as Modernizr from "modernizr";

export class MyClass {
    public sum(a: number, b: number) {
        return a + b;
    }

    public modern(): boolean {
        if (Modernizr.webgl) {
            return true;
        }
        return false;
    }
}
```

`src/myclass.spec.ts`:
```typescript
import "mocha";
import {expect} from "chai";
import {MyClass} from "./myclass";

it("normal test", () => {
    const instance = new MyClass();
    expect(instance.sum(1, 2)).to.equal(3);
});

it("modernizer test", () => {
    const instance = new MyClass();
    expect(instance.modern()).to.equal(false);
})
```

One of my modules uses [modernizr](https://modernizr.com/). When I use `npm run test` everything works fine, however, I need to implement and test modules that use client-side methods like `atob` as well. For that, I have installed `jsdom` and `jsdom-global` and use these build patterns in my `package.json`:

```json
"scripts": {
  "test": "mocha -r ts-node/register src/**/*.spec.ts",
  "domtest": "mocha -r ts-node/register -r jsdom-global/register src/**/*.spec.ts"
}
```
but when I compile my code via `npm run domtest`, modernizr does not compile correctly and I get this error:

```bash
/tmp/tsnode_mocha/node_modules/modernizr/lib/build.js:135
  requirejs.define('metadata', [], function() {return metadata;});
            ^
TypeError: requirejs.define is not a function
```

Any ideas on what's causing this problem and how to resolve it? Thanks.

**Comment by nebeleh** [comment]
I was able to resolve this issue, but the solution is non-intuitive and I'm not sure why.

So the only way I could both use `jsdom` functions and load `modernizr` was to avoid registering `jsdom` in my `mocha` commands, i.e., I had to only use `"test": "mocha -r ts-node/register src/**/*.spec.ts"`. But then in my test file, I can use `require("jsdom-global")()` and it will solve the problem.

Interestingly, if I import both `jsdom` and `modernizr` in my test file, `jsdom` should be called after `modernizr` or otherwise it won't compile. So this works:

```typescript
import {expect} from "chair";
import * as Modernizr from "modernizr";
import {MyClass} from "./myclass";
require("jsdom-global")();

it("modernizer test", () => {
    const instance = new MyClass();
    Modernizr.webgl = true;
    expect(instance.modern()).to.equal(true);
});
```

but this doesn't:
```typescript
import {expect} from "chair";
require("jsdom-global")();
import * as Modernizr from "modernizr";
import {MyClass} from "./myclass";
```

**Comment by danthegoodman** [comment]
@nebeleh I pulled down your repo, and after a little bit of playing around I got it running in plain node. The issue exists there too, so it's not a ts-node issue.

In any case, it looks like it's an issue with requirejs and jsdom: https://github.com/jsdom/jsdom/issues/643

**Comment by nebeleh** [comment]
thanks for looking into it.

**Comment by ArthurianX** [comment]
@nebeleh - did you ever find what the issue was ?

**Comment by nebeleh** [comment]
not really

**Comment by cspotcode** [comment]
Closing since looks like this was not a ts-node issue.
