### ISSUE TITLE
typescript browser error

### ISSUE THREAD

**Issue by sshraki** [TypeStrong/ts-node#528]
ReferenceError: require is not defined  [Learn More]      polyfills.js%20line%20120%20%3E%20eval:1:1
ReferenceError: exports is not defined  [Learn More]      vendor.js:1:1
ReferenceError: exports is not defined [Learn More]       app.js:1:1

im getting this error on browser any one can help ??

**Comment by blakeembrey** [comment]
This repo is for `ts-node` and doesn't have anything to do with running in a browser.
