### ISSUE TITLE
require imports javascript if exist instead of typescript

### ISSUE THREAD

**Issue by cuarti** [TypeStrong/ts-node#529]
When you import/require a module from the typescript file called from ts-node, it imports typescript if javascript doesn't exist, otherwise execute javascript instead of typescript.

In my case, I have a webpage in typescript and compiled to javascript to execute it in development and production, because is faster instead of execute typescript directly. I have some typescript scripts to test actions and modify some data of database. 
The problem is that this scripts use modules from webpage, that have its javascript compiled files, so when I execute scripts from ts-node this imported files are old versions and to use the new ones I need to have a tsc --watch executed, but with watcher I don't need ts-node because I can execute javascript versions of scripts.
I don't want to execute the watcher to not have another process executed with a lot of inotify watching files.

I don't know if someone of you has had this problem. I've tried to solve it in a fork, but when I create a new object with extensions instead of add the new ones to original object, I have an error when ts-node tries to execute the typescript file target, not the imports. The error is basicaly that don't use the typescript register or it doesn't compile well.

**Comment by crammag** [comment]
If I understood properly your problem, you need that TS extension has a greater priority than JS extension. I fixed it on my [fork](https://github.com/crammag/ts-node), could you check if this solves your problem? If so, later I will create the PR to this repo.

**Comment by cuarti** [comment]
Yes it works, is a little bit ugly deleting and reassigning properties, but works. I supose that internally NodeJS gets the pointer of require.extensions so the only method to fix is reassign the properties.

**Comment by crammag** [comment]
Okay, creating PR. If someone finds a better way, i'll be glad to hear it.

**Comment by crammag** [comment]
I had to close the PR because I found a bug on this approach, I'll try to solve it as soon as posible and then reopen the PR.

**Comment by blakeembrey** [comment]
We should definitely document this in the README but I don't intend to change the functionality of core node.js for this. There may be unintended side effects of mutating something people rely on globally.

**Comment by cuarti** [comment]
So, if you have compiled files and change some required typescript by your executed file, it doesn't work and you have to compile .ts to .js.
I understand what you say but with it ts-node is unnecessary, because only works for marginal cases, when you only modify the executed file or you don't have the compiled js.

**Comment by bluelovers** [comment]
https://github.com/TypeStrong/ts-node/pull/649

**Comment by G-Rath** [comment]
Any progress on this one? At the very least this should be documented, as it's easy to miss.

Ideally, it'd be great if it could be resolved, as otherwise you have to delete every compiled js file, which can be a bit of a pain at times :/

**Comment by blakeembrey** [comment]
@G-Rath You're welcome to submit a PR for either of those requests.

**Comment by G-Rath** [comment]
Does #649 not solve this problem? The PR trail ends with the author requesting assistance from one of the contributors, without reply.

I'm happy to try and champion the PR if/when I get the time, but would like to know what I'd actually need to do for it first :)

**Comment by blakeembrey** [comment]
@G-Rath That PR works for me. Right now it's conflicting and could probably be easily updated, but it would be nice to have a test to ensure the feature doesn't break accidentally in the future.

**Comment by G-Rath** [comment]
@blakeembrey I've written two tests that I think should cover it:

```
    it('should import js before ts by default', function (done) {
      exec(`${BIN_EXEC} tests/import-order/file`, function (err, stdout) {
        expect(err).to.equal(null)
        expect(stdout).to.equal('Hello, JavaScript!\n')

        return done()
      })
    })

    it('should import ts before js when unsafe-ext-order is true', function (done) {
      exec(`${BIN_EXEC} --unsafe-ext-order tests/import-order/file`, function (err, stdout) {
        expect(err).to.equal(null)
        expect(stdout).to.equal('Hello, TypeScript!\n')

        return done()
      })
    })
```

I'm not sure what the best way to push this up is however, without involving @bluelovers (who might not be around?).

I'm happy to cherry-pick his branch into my own fork, and open a new PR if you'd like. While the PR is functional, I feel there's some implementation and grammatical changes that should be made to improve it (such as using arrow functions, and `includes` instead of `indexOf`), which I'm happy to do.

Let me know how you'd like to proceed, and whether the above two tests are enough :)

(Also, feel free to bash on my test names - ideally I'd have wrapped them in `describe` blocks, but I opted to try and follow the existing test structure).

---

On an aside, I had one of the tests fail for me: "it should pipe into an eval script", which expects `${BIN_EXEC} --transpile-only -pe 'process.stdin.isTTY'` to return `undefined`, but for me on Windows it returns `'process.stdin.isTTY'` :/

**Comment by blakeembrey** [comment]
@G-Rath Feel free to run with it and branch from his work, it LGTM. Also open to a better name than `--unsafe-ext-reorder`, I think I've come around on the naming of it. Let's make sure it's in the README/help dialog also.

**Comment by G-Rath** [comment]
@blakeembrey 

Will do -what about `--prefer-ts-ext`:

```
`--prefer-ts-ext`:

Changes the order of file extensions that are used when attempting to `require` a file from `.js > .json > .ts > .tsx` to `.ts > .tsx > .js > .json`. 

This is useful when you're working with both JS & TS files of the same name, as the default extension order results in Node requiring the JS file instead of your TS files.

When this flag is provided, ts-node will change the extension order so that TypeScript files are loaded first. This is not done by default as it can break builds; such as if a `node_module` package includes both a `.ts` & `.js` file.
```

Actually, having written this out, I just realised this is likely going to cause some big(ger) problems, as I'm pretty sure `*.d.ts` files will be picked up by this, which'll some packages include next to their `.ts` files :/

Regardless, I'll make those changes when I get a chance - let me know if you're happy with the new flag name.

**Comment by bluelovers** [comment]
0.0 good thing for see this keep process

**Comment by G-Rath** [comment]
@blakeembrey if you've got a quick second, could you confirm the minimal node version supported by `ts-node`? #720 leads me to think it's `>=6`, but just want to make sure before I use `Array#includes`, as that'll break on `>=4` :joy:

**Comment by bluelovers** [comment]
hmm i don't know lol

**Comment by blakeembrey** [comment]
Yes, currently 6.0. The `.d.ts` case works because it only searches for the extension (e.g. `.ts` not `.d.ts`). It’s not necessary to add a test for this since regular TS file loading would act the same way, but also don’t mind if you’ve already got it.

**Comment by G-Rath** [comment]
@blakeembrey doing a quick glance over the README, I think it might be a good idea to add a heading about this, something like "Help! My code changes are not being applied!", explaining that Node looks for files w/ `.js` extension first.

Happy to make a PR if you're happy to merge it :)

**Comment by blakeembrey** [comment]
@G-Rath Absolutely, PRs accepted 😄
