### ISSUE TITLE
Ignore node_modules without ignoring project/node_modules

### ISSUE THREAD

**Issue by Kaba2** [TypeStrong/ts-node#535]
I'd like to ignore the `node_modules/` path in ts-node (--ignore), but not ignore the `project/node_modules/` path. Is this possible? A similar thing is possible, for example, in .gitignore where you can say `node_modules/` followed by  `!project/node_modules/`.

**Comment by blakeembrey** [comment]
Should currently be `--no-ignore` mentioned in https://github.com/TypeStrong/ts-node#configuration-options. Will be `--skip-ignore` in a future release.

**Comment by blakeembrey** [comment]
Oh, I see, it's a bit more complex than that. I'm honestly not sure but probably using a messy regexp could work? Something with a negation possibly, but you'll probably have to explore that for yourself (or just disable for now).
