### ISSUE TITLE
in newest version 5.0.0 debugging is not possible using --inspect parameter

### ISSUE THREAD

**Issue by michalchochol** [TypeStrong/ts-node#537]
In ts-node@5.0.0 --inspect parameter does not work anymore. It was working in previous ts-node version.

**Comment by RanadeepPolavarapu** [comment]
I am having same issue. Nothing about `--inspect` was mentioned in changelog either.

**Comment by egoroof** [comment]
`node --inspect -r ts-node/register path/to/ts` works for me

**Comment by blakeembrey** [comment]
That’s the intent. Please check the README or change log or more info and use the node command above for inspecting and other node.js flags.

**Comment by michalchochol** [comment]
Unfortunately this solution does not work with pm2, which uses ts-node by default to run typescript and passes arguments to ts-node via node_args property.

**Comment by blakeembrey** [comment]
Can you provide a reference or code snippet so I can verify that claim? Seems like a simple thing to fix.

**Comment by michalchochol** [comment]
Hi,

lets assume we have ts-node installed locally via npm and very simple app-test to run:

```
let fun = () => {console.log('app.js'); setTimeout(fun, 1000);}; 
fun();
```

Normally to run and debug app using node:

`node --inspect=7000 app-test.js` 			//works OK with debugger 

`node --inspect=7000 -r ts-node/register app-test.ts`  	//works OK with debugger


To run and debug using pm2 (without typescript installed internally in pm2):

`pm2 start --node-args="--inspect=7000" app-test.js` 	//works OK with debugger 

`pm2 start app-test.ts` 					// does not work

`pm2 start --node-args="--inspect=7000 -r ts-node/register" app-test.ts` 	// does not work

Last two examples do not work, because by default pm2 uses ts-node interpreter to run typescript -> https://github.com/Unitech/pm2/blob/master/lib/API/interpreter.json

If we install typescript in pm2 by: _pm2 install typescript_ it also installs the latest version of ts-node.

So now we can normally start our script like this:

`pm2 start app-test.ts` // works OK

`pm2 start --node-args="--inspect=7000 -r ts-node/register" app-test.ts` // still does not work

Last example not work beacause --node-args are passed to ts-node interpreter and finally ignored. It was working ok with ts-node@4.1.0:

`pm2 start --node-args="--inspect=7000" app-test.ts`

**Comment by blakeembrey** [comment]
Seems like you should submit a fix to `pm2`. The feature of using node flags via the CLI was an explicit decision and won’t be enabled in future releases.

**Comment by michalchochol** [comment]
I don't think so it is so simple, but I'm going to try :) Thanks for your time and great project - ts-node really helps and saves a lot of development time.

**Comment by marcj** [comment]
Any solution yet to start newest ts-node with inspect via pm2?

**Comment by majelbstoat** [comment]
I can't see in the documentation how to combine both a `--preserve-symlinks` arg for node, and a `--project` arg for ts-node.

`node -r ts-node/register --preserve-symlinks --project tsconfig.server.json` says `unknown arg --project` which makes sense.

`ts-node --project tsconfig.server.json --preserve-symlinks` doesn't work, probably for the same reason `--inspect` doesn't work.

**Comment by blakeembrey** [comment]
@majelbstoat Unfortunately it's not possible to combine both, that's a limitation with using node.js `--require`. You need to use environment variables instead.

**Comment by Nilos** [comment]
For everyone looking into this in the future:

Node supports passing almost any command line options using an environment variable called
`NODE_OPTIONS`: https://nodejs.org/api/cli.html#cli_node_options_options

**Comment by blakeembrey** [comment]
@Nilos Both ways are possible. You can do `TS_NODE_PROJECT=xxx node --require ts-node/register --extra-args index.ts` or `NODE_OPTIONS=xxx ts-node --project=xxx --extra-args index.ts`. I documented the first approach in the README, but the second is equally valid, just uses the `ts-node` executable instead of the `node` executable. Can you share why you think one is easier than the other since they both require environment variables?

**Comment by Nilos** [comment]
@blakeembrey I did not know about the TS_NODE_PROJECT option. Is every command line option for ts-node controllable this way?

I actually think TS_NODE_PROJECT is better as my node application spawns other node application which would inherit the options which breaks the sub-processes.

**Comment by blakeembrey** [comment]
@Nilos See https://github.com/TypeStrong/ts-node#cli-and-programmatic-options.

**Comment by agborkowski** [comment]
nodemon config.json
````json
{ "exec": "node --inspect -r ts-node/register ./src/index.ts" }
````
works well

**Comment by impmja** [comment]
Thanks @agborkowski , your solution works indeed! :+1:

**Comment by eddyekofo94** [comment]
@agborkowski Thank you very much brother. God bless

**Comment by elliottsj** [comment]
As an alternative to environment variables or `ts-node/register`, you can pass options in this form:

```
node [node options] ./node_modules/.bin/ts-node [ts-node options] [script.ts]
```

e.g.

```
node --inspect-brk ./node_modules/.bin/ts-node --transpile-only script.ts
```

**Comment by GerbenRampaart** [comment]
@agborkowski Not all heroes wear capes. +1

**Comment by yleflour** [comment]
If you want to keep using pm2, the `NODE_OPTIONS` env variable works well.

Here is my configuration (after running `pm2 install typescript`)

```yaml
apps:
  - name: my-app
    script: ./src/index.ts
    watch:
      - src
    env:
      NODE_OPTIONS: --inspect
```

**Comment by hejiaji** [comment]
![image](https://user-images.githubusercontent.com/19968961/48109836-28f9c300-e29d-11e8-8461-fadd91bf2a2e.png)


Why is that?

**Comment by blakeembrey** [comment]
@hejiaji You are probably emitting ES6 modules instead of CommonJS? I don't think it has anything to do with `ts-node/register` vs `ts-node` CLI. I'd need more information if that's not the cause.

**Comment by hejiaji** [comment]
Oh right! thanks @blakeembrey , then to more specific on my question:
i have a command like this
```ts-node --typeCheck --project tsconfig.server.json --files true server/index.ts```
How can i transfer to node command completely?
```node -r ts-node/register server/index.ts``` cannot indicate the --project and --file arguments.

**Comment by hejiaji** [comment]
Figured it out!! using Environment variable to tackle this!


```export TS_NODE_PROJECT=tsconfig.server.json; export TS_NODE_FILES=true && node -r ts-node/register --inspect server/index.ts ```

Thanks @blakeembrey

**Comment by creadicted** [comment]
@hejiaji can you give a bit more detail how you solved that? 
I also have to specify a ts-config since i have to use a different target.

**Comment by adrian-moisa** [comment]
> ```shell
> node --inspect -r ts-node/register path/to/ts
> ```

How can I also provide the ` --project ./tsconfig-server.json` arg for ts-node ? I really need to have a different tsconfig because of react native.

**Comment by marcj** [comment]
@adrian-moisa `export TS_NODE_PROJECT=./tsconfig-server.json ts-node path/to/ts`.

**Comment by michalchochol** [comment]
@yleflour perfect solution :) thanks a lot 

> If you want to keep using pm2, the `NODE_OPTIONS` env variable works well.
> 
> Here is my configuration (after running `pm2 install typescript`)
> 
> ```yaml
> apps:
>   - name: my-app
>     script: ./src/index.ts
>     watch:
>       - src
>     env:
>       NODE_OPTIONS: --inspect
> ```

**Comment by Evilart86** [comment]
This helps me to configure Webstorm Debuger
node version: 12.3.1
ts-node version: 8.5.4

![image](https://user-images.githubusercontent.com/20624473/71786513-d89f0200-3014-11ea-8486-627ea4364bdc.png)

**Comment by bhumit070** [comment]
> ```shell
> node --inspect -r ts-node/register path/to/ts
> ```

in this approach I am using command like this for typescript 

nodemon --watch 'src/**/*.ts' --exec node --inspect -r ts-node/register src/index.ts

now I want to pass arguments to ts-node how can I do that can you please help me with that 

I want to pass --files arguments to this but in my case I don't think so it is working I am trying like this

nodemon --watch 'src/**/*.ts' --exec node --inspect -r ts-node/register --files src/index.ts

**Comment by SishaarRao** [comment]
@bhumit070 If you look at the [ts-node documentation for the --files option](https://github.com/TypeStrong/ts-node#files) you can see that there are two ways to enable a setting, either via a flag or via an environment variable.

> Environment: TS_NODE_FILES

I would suggest you pass your argument as
```
TS_NODE_FILES=true nodemon --watch 'src/**/*.ts' --exec node --inspect -r ts-node/register --files src/index.ts
```
