### ISSUE TITLE
issue with running 5.0.0 via vs-code

### ISSUE THREAD

**Issue by bradzacher** [TypeStrong/ts-node#539]
I have the following launch config:
```JSON
        {
            "type": "node",
            "request": "launch",
            "protocol": "inspector",
            "name": "Debug ts-node",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/ts-node",
            "args": [
                "${workspaceFolder}/src/main.ts",
            ],
            "sourceMaps": true
        }
```

This worked fine in v`4.x.y`.
However I tried upgrading to v`5.0.0` and it doesn't launch.
I did a quick debug and found that it's due how minimist collects arguments.

the command that gets run by vscode for the above config is:
```
<path>/node_modules/.bin/ts-node --inspect=12386 --debug-brk <path>/src/main.ts
```

minimist collects the arguments as follows:
```JSON
{
	"_": [],
    "inspect": 12386,
    "debug-brk": "<path>/src/main.ts"
}
```

so then ts-node never executes, because as far as it's concerned no script was provided.

**Comment by warseph** [comment]
Same issue here on 5.0.0, just running `ts-node --inspect src/index.ts` opens the REPL instead of running the script.

**Comment by blakeembrey** [comment]
There are no more advanced flags supported by `ts-node`. Use `node -r ts-node/register` for advanced functionality. It's also documented in the README, feel free to submit a PR if that documentation is not adequate.

**Comment by blakeembrey** [comment]
I think changing `runtimeExecutable` to `node` and `args` to `["-r", "ts-node/register"]` should be enough, right? Please let me know if that works, happy to add this to the documentation.
