### ISSUE TITLE
ts-node fails when trying to execute a script not included in 'rootDir' of tsconfig.json

### ISSUE THREAD

**Issue by ogwh** [TypeStrong/ts-node#540]
I have separate scripts and src directories. With project source files being in src/ it's the dir set as rootDir and included with the includes option in the tsconfig.

Because ts-node loads everything in the tsconfig file this means that scripts under scripts/ cannot be executed.

Additionally when using the --skip-project option ts-node just drops to a REPL and doesn't run the script. Even if that option did work it would end up skipping all of the other tsconfig settings that /should/ be applied.

Can ts-node gain an option that ignores rootDir and everything outside of compilerOptions in the tsconfig and is there a workaround for this? I can't put the scripts dir under src/ because I don't want it included in the output directory or even being considered when the actual project itself is being compiled!

Thanks.

**Comment by blakeembrey** [comment]
I can ignore error `6059` but I can't replicate any of your other issues. Using `--skip-project` on this repo skips the `tsconfig.json` file and doesn't open the REPL.

**Comment by blakeembrey** [comment]
Also, you can't just ignore everything outside of `compilerOptions` because of type definitions and other features. I'll have a PR for ignoring the root dir warning, but I'd like to understand how you got the REPL issue - can you share the command you were running?

**Comment by ogwh** [comment]
Apologies for the barely comprehensible language in the original report. I'm going to say I was tired at the time but that might be a lie!

The command and output is:

```
lenny$ ts-node --skip-project scripts/generate-nested-key.ts
>
```

Where > is the REPL prompt.

Version info is:

```
lenny$ ts-node --version
ts-node v4.1.0
node v8.9.4
typescript v2.7.2
```

I'll update to the latest versions of all three and retest. Thanks for the fix with #544!

**Comment by blakeembrey** [comment]
Awesome, thanks. That makes a lot more sense now, `--skip-project` isn't an option with `ts-node` 4.x.

**Comment by ogwh** [comment]
Ah. I must have read the wrong docs.

I was just about to say I checked out master and everything works perfectly now! Thanks. :-)
