### ISSUE TITLE
ts-node --inspect does not work on 5.0.0

### ISSUE THREAD

**Issue by xueeey** [TypeStrong/ts-node#543]
```
$ ts-node --inspect==5858 src/index.ts
Server started at http://localhost:8080
```

Works fine with v4.1.0

**Comment by blakeembrey** [comment]
Duplicate of https://github.com/TypeStrong/ts-node/issues/537. Please search before opening another issue, especially since the issue directly before this is the exact same.

**Comment by gyerts** [comment]
ts-node --files ./src/index.ts --inspect

**Comment by benbieler** [comment]
you need to use something like this: `**node inspect=9999 -r** ts-node src/index.ts`
