### ISSUE TITLE
What is the current way to pass flags to node? (e.g preserve-symlinks)

### ISSUE THREAD

**Issue by kirillgroshkov** [TypeStrong/ts-node#550]
I'd like to pass flags down to node, e.g `preserve-symlinks`. How can I do that?

In the past I've seen ppl reported success with `--preserve-symlinks` or `--preserveSymlinks` but it doesn't work anymore.

**Comment by blakeembrey** [comment]
Please check the README: https://github.com/TypeStrong/ts-node#programmatic.
