### ISSUE TITLE
ts-node starts REPL when using --inspect

### ISSUE THREAD

**Issue by johan-gorter** [TypeStrong/ts-node#552]
The following command ran fine with ts-node 4.1 on windows
`ts-node --inspect our/file.ts`

With ts-node 5.0, this command seems to ignore the last argument and starts the REPL instead. Changing the command to the following solves this problem for now:
`ts-node --inspect -- our/file.ts`

I cannot think of any reason why the `--` should be required here.

**Comment by blakeembrey** [comment]
Neither of those work on 5.0, please check the README, changelog or past issue before creating an issue. Refs:

* https://github.com/TypeStrong/ts-node#programmatic
* https://github.com/TypeStrong/ts-node/releases/tag/v5.0.0
* https://github.com/TypeStrong/ts-node/issues/549

**Comment by gyerts** [comment]
ts-node --files ./src/index.ts --inspect
