### ISSUE TITLE
Pass arguments from programmatic invocation

### ISSUE THREAD

**Issue by froodley** [TypeStrong/ts-node#556]
Hi, just a question I couldn't find an answer to...

I'm trying to replicate a command line invocation of ts-node where I pass CLI arguments into the script:
`ts-node script.ts --arg val1`
Works great.  Thanks!

But I want to do the same now from a gulp task.
`require('ts-node').register(tsConfig);
require('script.ts --arg val1');`

... does not work, as expected.  So how can I acheive the same from Gulp?  I don't want to use child_process.spawn as I have a developer who uses Windows and spawn doesn't work reliably.

**Comment by blakeembrey** [comment]
You can’t pass arguments like that through require. You can just make whatever your doing a function instead and pass the function whatever you want.

**Comment by froodley** [comment]
*slaps forehead* thanks

after invoking it as a cli script a few hundred times I had stopped thinking of it
