### ISSUE TITLE
Stabilizing ES6 Modules

### ISSUE THREAD

**Issue by jpike88** [TypeStrong/ts-node#560]
The --experimental-modules flag seems to be something that has been a thing for quite a while. Is there any plan to stabilise things to the point where this flag won't be necessary?

As more developers start making use of it in production (like myself), which by the way, works flawlessly, there is the growing need for support in other tools like Typescript. Problem is, they won't take it seriously because of it's Stability:1 status.

Now I know there are some issues present, but a basic implementation of the modules is proven in production and really revolutionises how codebases can be structured. The elimination of circular dependencies in stateless applications (which I imagine the majority of NodeJS uses encompass) is a game changer for encouraging tighter coding practices. It's probably the most profound change that NodeJS has brought in years IMO.

So, why isn't getting this out the door faster a priority?

**Comment by blakeembrey** [comment]
Submit a PR, this is an OSS project maintained by unpaid volunteers.
