### ISSUE TITLE
Testing with mocha and defining project with TS_NODE_PROJECT fails

### ISSUE THREAD

**Issue by Tokimon** [TypeStrong/ts-node#561]
Hi

I have a project, a library, of small convenience methods for JS and I use Mocha for my unit testing with the following command:

```
cross-env TS_NODE_PROJECT=./test nyc mocha --compilers ts:ts-node/register ./test/*.spec.ts
```

Which has worked well until I updated to `ts-node` version **5.0.1**. 

Now it it has started failing with the error message that it cannot find my test folder.

So I wanted to know if you could tell me why it is failing?

**Note**  
I use NYC (Istanbul) for code coverage, but the compilation fails even if I remove that from the command.

### My Library set up

```
MyLibrary
|- test
|  |- <*.spec.ts>
|  |- tsconfig.json
|- <*.ts>
|- tsconfig.json
```

All my main files are in the root of the project and all the test files are in a test folder.

As I am compiling the tests a bit differently than the main files I have added a `tsconfig.json` in the root of the test folder and I am (trying to) instructing the TS compiler to use the _test_ folder `tsconfig.json` for the compilation.

### test/tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "target": "es2017",
    "lib": ["es5", "es6", "dom"],
    "moduleResolution": "node",
    "allowJs": false,
    "outDir": "."
  },

  "include": [
    "../*.ts"
  ],

  "exclude": [
    "node_modules",
    "../test/**/*.ts"
  ]
}
```

### Error Message thrown
```
C:\projects\MyLibrary\node_modules\ts-node\src\index.ts:453
        throw new TSError([formatDiagnostic(result.error, cwd, ts, 0)])
              ^
TSError: Γ¿» Unable to compile TypeScript
The specified path does not exist: 'C:\projects\MyLibrary\test'. (5058)
    at readConfig (C:\projects\MyLibrary\node_modules\ts-node\src\index.ts:453:15)
    at Object.register (C:\projects\MyLibrary\node_modules\ts-node\src\index.ts:209:18)
    at Object.<anonymous> (C:\projects\MyLibrary\node_modules\ts-node\register\index.js:1:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at program.compilers.forEach.c (C:\projects\MyLibrary\node_modules\mocha\bin\_mocha:459:3)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\projects\MyLibrary\node_modules\mocha\bin\_mocha:451:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by blakeembrey** [comment]
It needs to be a path to a configuration file, not just a directory now. Open to accepting a PR for supporting a directory again. This should have been documented in the release changelog and is reflected in the README (on mobile so didn’t double check the changelog).

**Comment by blakeembrey** [comment]
Updated https://github.com/TypeStrong/ts-node/releases/tag/v5.0.0.

**Comment by Tokimon** [comment]
Arh ok thank you for clarifying this. I will correct my path then.

**Comment by duvet86** [comment]
Hi, it's not working after setting a path to a config file.
`SET TS_NODE_PROJECT=./test/tsconfig.json && mocha -r ts-node/register -r tsconfig-paths/register test/**/*.ts`

Still getting
![image](https://user-images.githubusercontent.com/5604548/39416933-53b9dc20-4c83-11e8-8bae-138f78b05ffd.png)

"mocha": "^5.1.1",
"ts-node": "^6.0.0",
"tsconfig-paths": "^3.3.1",

**Comment by duvet86** [comment]
You are definitely right, removing the space fixes it.
`SET TS_NODE_PROJECT=./test/tsconfig.json&& mocha -r ts-node/register -r tsconfig-paths/register test/**/*.ts`

Last question why setting the inline option doesn't work?
`mocha -r ts-node/register --project /test/tsconfig.json -r tsconfig-paths/register  test/**/*.ts`

**Comment by blakeembrey** [comment]
Because `--project` is not a mocha argument.
