### ISSUE TITLE
update typescript version or unlock it?

### ISSUE THREAD

**Issue by atian25** [TypeStrong/ts-node#562]
https://github.com/TypeStrong/ts-node/blob/master/package-lock.json#L1143

```bash
➜  npm info typescript version
2.8.1
```

**Comment by blakeembrey** [comment]
I don't understand the issue, you'll need to elaborate if you want support.

**Comment by atian25** [comment]
sorry, I found that this modules has a `package-lock.json` and lock `typescript` with an old version `2.7.2`, could you upgrade it to the newest version ?

**Comment by blakeembrey** [comment]
That file doesn't affect you though, is there a reason you think I should update?

**Comment by atian25** [comment]
oh, sorry, it's a dev dep,  really sorry.
