### ISSUE TITLE
System is not defined

### ISSUE THREAD

**Issue by lcoenen** [TypeStrong/ts-node#563]
Hi!

Maybe I'm missing something, I'm using `ts-node` 5.0.1, `tsc` 2.7.2 and node v6.11.3. I can't use `ts-node` at all - everytime I'm trying to do something, I get an error: 

    Reference Error: System is not defined

Any idea how to fix that?

**Comment by blakeembrey** [comment]
Use commonjs for your `module` instead of `system`.
