### ISSUE TITLE
Using nyc (istanbul) with ts-node/register don't check coverage properly in versions from 3.3.0

### ISSUE THREAD

**Issue by cibergarri** [TypeStrong/ts-node#564]
Using nyc for checking code coverage doesn't cover class field declarations when using ts-node > 3.3.0.
![image](https://user-images.githubusercontent.com/20155564/38250696-beb331dc-374f-11e8-972e-5f471175696b.png)

Issue description in nyc repository:
https://github.com/istanbuljs/nyc/issues/802

Downgrading ts-node package to version 3.3.0 fixes the issue.

**Comment by blakeembrey** [comment]
Can you somehow test it by requiring `ts-node/require/type-check` instead? It seems there's a few unhandled issues with the non-type-check mode in these edge cases.

**Comment by cibergarri** [comment]
hi @blakeembrey! 
Yes, It works! I Just want to point out that you have committed a typo, for those who come with the same issue

It should be:
`"require": [
            "ts-node/register/type-check"
        ],`

(register instead of require)

Anyway, thank you very much for your help
