### ISSUE TITLE
ts-node triggers UnhandledPromiseRejectionWarning in TypeORM

### ISSUE THREAD

**Issue by darkbasic** [TypeStrong/ts-node#569]
https://github.com/darkbasic/typeorm-repro3

To run the repo you will first have to install PostgreSQL, then run the daemon and execute `createdb test` to create the db.
Finally `npm start`, which will execute `nodemon --exec ./node_modules/.bin/ts-node -- ./index.ts`.

Running the app with ts-node will result in the following error:
```
(node:14506) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): DataTypeNotSupportedError: Data type "Object" in "Recipient.receivedAt" is not supported by "postgres" database.
(node:14506) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If I run the very same app with `tsc && node index.js` you'll get no error at all.

NOTE: you'll have to switch the `ormconfig.json` ts extensions back to js first:

```diff
diff --git a/ormconfig.json b/ormconfig.json
index 029b87c..707125c 100644
--- a/ormconfig.json
+++ b/ormconfig.json
@@ -8,13 +8,13 @@
    "synchronize": true,
    "logging": false,
    "entities": [
-      "entity/**/*.ts"
+      "entity/**/*.js"
    ],
    "migrations": [
-      "migration/**/*.ts"
+      "migration/**/*.js"
    ],
    "subscribers": [
-      "subscriber/**/*.ts"
+      "subscriber/**/*.js"
    ],
    "cli": {
       "entitiesDir": "entity",
```

**Comment by blakeembrey** [comment]
Probably a duplicate of https://github.com/TypeStrong/ts-node/issues/432? Try with `--type-check`?

**Comment by darkbasic** [comment]
`--typeCheck` indeed did the trick! Why isn't it enabled by default?

**Comment by blakeembrey** [comment]
Because it's slow and not usually necessary. The default is going to be changed back because this issue has been reported a number of times.
