### ISSUE TITLE
Empty source files are marked as not found

### ISSUE THREAD

**Issue by stelcheck** [TypeStrong/ts-node#571]
At compile-time, ts-node will report any empty source file as not found:

```plaintext
File '/home/stelcheck/Sources/megadata/test/events/Whatever.ts' not found. (6053)
```

This error appears to occur regardless of whether a source file is even imported.

**Comment by blakeembrey** [comment]
That's interesting. Do you have a quick repro I can use? Are you sure nothing is traversing a directory and doing requires or something else?

**Comment by stelcheck** [comment]
https://github.com/Wizcorp/megadata/pull/22 Is where a flag was raised

**Comment by blakeembrey** [comment]
@stelcheck High level, this is possibly a valid. Would need to clone and run `tsc` to check, `tsc` runs on `src` while `ts-node` is running on the entire project. Going to clone and test. I think there's two solutions:

1. Use `ts-node/register/transpile-only`
2. Enable filtering for `.d.ts` inputs only (old behaviour)

**Comment by dekryptic** [comment]
Any updates on this? I'm using 6.0.0 and getting:

```
⨯ Unable to compile TypeScript
File '{myPath}/index.ts' not found. (6053)
```

**Comment by CFitzsimons** [comment]
I just wanted to say I'm brand new to typescript and without this issue I wouldn't have figured out what the problem was.  

Workaround for me until this is fixed was to just drop a single comment into each 'empty' `.ts` file.

**Comment by blakeembrey** [comment]
@dekryptic I don't think it works as expected, 5.x just meant no type checking by default. If you expect zero type checking, then sure! But you will be missing compiler errors now.

@stelcheck I managed to take a look just now and it was an easy fix, sorry I didn't read my source earlier and notice the obvious issue - I'm using truthy checks on contents which would ignore empty strings.

**Comment by dekryptic** [comment]
@blakeembrey I don't understand. Type checking is working for me at 5.0.1, but I have no errors when a file is empty.

I still have to try the update though.

**Comment by blakeembrey** [comment]
@dekryptic The update would fix it, but how are you using `5.x` then? Are you using it with `--type-check` enabled?
