### ISSUE TITLE
why not support path map?

### ISSUE THREAD

**Issue by wjtGitHub** [TypeStrong/ts-node#578]
# why not support path map?

**Comment by ORESoftware** [comment]
what is path map?

**Comment by wjtGitHub** [comment]
![image](https://user-images.githubusercontent.com/17404628/39284226-de5c6f88-4944-11e8-94e8-329e195dc525.png)
@ORESoftware

**Comment by ORESoftware** [comment]
I think I get it

**Comment by wjtGitHub** [comment]
@blakeembrey

**Comment by blakeembrey** [comment]
https://github.com/TypeStrong/ts-node#loading-tsconfigjson

**Comment by wjtGitHub** [comment]
@blakeembrey can you help me ?
