### ISSUE TITLE
why not support path map? err

### ISSUE THREAD

**Issue by wjtGitHub** [TypeStrong/ts-node#579]
# err
# according to the document
![image](https://user-images.githubusercontent.com/17404628/39292539-11a7d282-4969-11e8-8964-b1dab31ed0cf.png)
![image](https://user-images.githubusercontent.com/17404628/39292548-15c25a4a-4969-11e8-8ae2-fdd07a0032aa.png)

@blakeembrey

**Comment by blakeembrey** [comment]
Read the README, I responded in your previous issue: https://github.com/TypeStrong/ts-node/issues/578.

**Comment by wjtGitHub** [comment]
thank you @blakeembrey .I got it
