### ISSUE TITLE
Are some configs from tsconfig.json ignored?

### ISSUE THREAD

**Issue by kswope** [TypeStrong/ts-node#580]
I don't think I'm seeing docs about this, but I'm definitely seeing ts-node ignore settings like noUnusedLocals and noUnusedParameters.  If I run tsc in the same directory its seeing these configs.

**Comment by blakeembrey** [comment]
What version are you using?

**Comment by kswope** [comment]
I'm useless,

I was using the nest.js starter project here
https://github.com/nestjs/typescript-starter.git
which uses ts-node 4.1.0

And confirming the bug against my own installed version which was 5.0.1

Not realizing that I just needed to upgrade.

FIXED: upgraded to ts-node v6.0.2 , both globally and in project, which even one you are using.
