### ISSUE TITLE
Importing JS that uses `instanceof` doesn't work.

### ISSUE THREAD

**Issue by ccorcos** [TypeStrong/ts-node#583]
Create a file `test.js`. Yes, a javascript file. This is to simulate using an external library.

```js
module.exports = {
	isArray: function(x) {
		return x instanceof Array
	},
}
```

Now open up the REPL and try to use it:

```
$ ./node_modules/.bin/ts-node
> import * as t from "./test"
{}
> t.isArray([])
false
```

Took me a while to track this down and caused a lot of confusion!

**Comment by blakeembrey** [comment]
Looks like it's only from the REPL and related to context somehow, I'll have to see how node.js is using the REPL here and why imports are in a different context to the regular REPL.
