### ISSUE TITLE
Feature request: Beautiful stack traces

### ISSUE THREAD

**Issue by timsuchanek** [TypeStrong/ts-node#589]
A majority of the time spent in debugging is to actually find the spot the error occurred at.
As described [here](https://umaar.com/dev-tips/142-better-node-stack-trace/), with [`callsite-record` ](https://github.com/inikulin/callsite-record)you can add the source code context of where the error happened.

![image](https://user-images.githubusercontent.com/1094804/39995589-fd1e38f2-577c-11e8-94de-435af6434b3e.png)

This would decrease debugging time and increase developer happiness :)

I would also be up for a PR, if the authors of this package are up for that.

**Comment by blakeembrey** [comment]
What type of errors are you talking about? TypeScript compiler errors or runtime errors?

**Comment by capaj** [comment]
@blakeembrey  I don't know if I am doing something wrong, but I don't get any stack traces fro runtime errors when I am running `ts-node`, just error messages. This makes it awful to actually debug what went wrong.
For example:
```
capaj@capaj-i7-4771:~/git_projects/tests/type-gql$ npx ts-node sample-query.ts
this.schema.getQueryType is not a function
```

**Comment by blakeembrey** [comment]
@capaj Also resolved in the issue you reported, but it's an issue with `npx` (https://github.com/TypeStrong/ts-node/issues/592) and not `ts-node`.

**Comment by welkie** [comment]
@blakeembrey Looks like run time errors. I think this would look great when it comes to helping debugging, to see where errors come from. I'm fairly new to the logging ecosystem though. I wonder if this would cause issues with the stack traces being sent to files instead of an interactive console.

**Comment by blakeembrey** [comment]
Unfortunately if it’s runtime errors, I think that’s outside the domain of what this module should be doing. For compiler errors though, I’d love to have prettier error output if it doesn’t break dependents. And that requirement is a little tricky.

**Comment by blakeembrey** [comment]
Closing now, seems like anyone wanting this could just use https://github.com/inikulin/callsite-record and it'd work compiled or in-memory with `ts-node`.
