### ISSUE TITLE
Unable to access perf_hooks

### ISSUE THREAD

**Issue by benlesh** [TypeStrong/ts-node#599]
`perf_hooks` is a Node API. Not sure what I need to do to access it.

I'm sure I'm just doing something wrong or missing a step. Thank you for your time.

### Code to reproduce

test.ts
```ts
import { performance } from 'perf_hooks';

console.log(performance.now());
```

Run:
```
ts-node test.ts
```

Versions:

```
ts-node v6.0.5
node v10.2.1
typescript v2.8.3
```

### Expected result

Console logs some millesecond timestamp

### Actual result:

Unable to compile TypeScript: `Cannot find module 'perf_hooks'`

**Comment by blakeembrey** [comment]
It’d be an outdated definition, someone would need to update the node.js definition on DefinitelyTyped to add the module definition.
