### ISSUE TITLE
Unable to specify configuration when launching via vscode launch.json

### ISSUE THREAD

**Issue by WillAvudim** [TypeStrong/ts-node#604]
I am running node.js VSCode debugger against the recommended configuration (straight from the documentation):

```
        {
            "type": "node",
            "request": "launch",
            "name": "Node.js (<Current>.ts)",
            "protocol": "inspector",
            "args": [
                "${relativeFile}"
            ],
            "cwd": "${workspaceRoot}",
            "runtimeArgs": [
                "-r",
                "ts-node/register"
            ],
            "internalConsoleOptions": "openOnSessionStart"
        },
```

And I cannot figure out how to specify the ts-code arguments.

Even such an innocuous config change as specifying the --ignoreDiagnostics argument, which supposedly should merely disable warnings, lead to the VSCode failure to start the process:

```
            "runtimeArgs": [
                "-r",
                "ts-node/register",
                "--ignoreDiagnostics"
            ],
```

Are configuration options supported in any form when the process is being started for debugging from under VSCode?

**Comment by blakeembrey** [comment]
Use environment variables or use the `ts-node` executable directly. `ts-node` flags don’t mean anything to the node.js executable.
