### ISSUE TITLE
Unable to start ts-node on Windows

### ISSUE THREAD

**Issue by AleksandarAleksandrov** [TypeStrong/ts-node#606]
I'm using `nodemon` to watch for changes in my project. 
In the `nodemon.json` file I have the following configuration:

```json
{
    "watch": [
        "server/**/*.ts"
    ],
    "execMap": {
        "ts": "ts-node --compilerOptions '{\"module\":\"commonjs\"}'"
    }
}
```

When trying to start the server `nodemon server/index.ts` , this is the error I get:

```log
> nodemon server/index.ts[nodemon] 1.17.5[nodemon] to restart at any time, enter `rs`[nodemon] watching: server/**/*.ts
[nodemon] starting `ts-node --compilerOptions '{"module":"commonjs"}' server/index.ts`
undefined:1'{module:commonjs}'
^
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)    at Object.parse (C:\pp\habit\web\node_modules\ts-node\dist\index.js:83:45)    at Object.<anonymous> (C:\pp\habit\web\node_modules\ts-node\dist\bin.js:64:30)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)    at Function.Module._load (internal/modules/cjs/loader.js:543:3)    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)    at startup (internal/bootstrap/node.js:238:19)
[nodemon] app crashed - waiting for file changes before starting...
```

It seems the `compilerOptions` are not being passed to the command on windows. Any idea how to solve this 🤔

**Comment by blakeembrey** [comment]
It seems they are being passed, otherwise there wouldn’t be an error. And, if you look at the error you provided, it appears the double quotes are being stripped. I’m not a Windows expert, but I think you may need to escape your double quotes within the string so they are not removed by the Windows shell. Can you try that?

**Comment by AleksandarAleksandrov** [comment]
Yes that was the problem thank you 👍 
For anyone interested this is how you should pass the parameters on windows:
```json
{
    "watch": [
        "server/**/*.ts"
    ],
    "execMap": {
        "ts": "ts-node --compilerOptions {\"\"\"module\"\"\":\"\"\"commonjs\"\"\"}"
    }
}
```

**Comment by blakeembrey** [comment]
Awesome, glad to here. I'm actually not really sure why it's the case. Feel free to comment if you know what's going on or have a link to documentation that could be used in the README for future issues.

**Comment by fasfsfgs** [comment]
This way the script is not running on linux. Is there any way to make it cross-os?

**Comment by sebr74** [comment]
@fasfsfgs , the only way I found to make it work on windows without resorting to that ugly as hell and non-portable triple quote escaping is to use environment variables:
`set TS_NODE_COMPILER_OPTIONS={"module":"commonjs"}` on windows worked for me and I removed the -O from the script invocation.

**Comment by jamiehaywood** [comment]
any update on making this cross OS?

**Comment by cspotcode** [comment]
@jamiehaywood it already works on Windows.  As described above, you will need to obey the escaping rules for whatever shell you're using, and this rule applies to all CLI tools across OSes, not just `ts-node`.

What change, exactly, are you proposing?

**Comment by fasfsfgs** [comment]
I managed to make it crossOS with those "ugly as hell" escapes and [cross-env](https://www.npmjs.com/package/cross-env) module.

`cross-env TS_NODE_COMPILER_OPTIONS={\\\"module\\\":\\\"commonjs\\\"} ts-node`

**Comment by cspotcode** [comment]
Remember you can specify all typescript and ts-node options in your tsconfig file, too.

For example:
```
{
  "ts-node": {
    "skipIgnore": true, // ts-node options
    "compilerOptions": {/* ts-node overrides if you need ts-node to use different compiler options than tsc.  This is usually not necessary */}
  },
  "compilerOptions": {/* ... */}
}
```
