### ISSUE TITLE
ts-node exits when there are typescript errors

### ISSUE THREAD

**Issue by jardakotesovec** [TypeStrong/ts-node#609]
I am new to typescript and I am migrating javascript project (express server) over to typescript.

When I use tsc, it outputs many typescript errors (as I am in process of addressing these errors), but still outputs js files, which can be run and thats great as it takes time to adapt the code base. I can't figure out why ts-node does not behave same way and exits based on these typescript errors.

tsc has `--noEmitOnError` option if someone wants to be strict and not emit the js files. I would expect same from ts-node. Meaning that it shows the errors but still run the thing if `noEmitOnError` is `false` and only exit on type errors when `noEmitOnError` is `true`.

I am surprised that I could not find any discussion on this topic as I would expect many people run into this issue.

**Comment by blakeembrey** [comment]
See https://github.com/TypeStrong/ts-node/issues/34. You’re welcome to submit a PR, but since only a few of people out of millions of downloads have expressed a need for this it doesn’t seem high priority. I don’t know what the semantics of it really be if the compiler is outputting error messages in between application logs.

**Comment by rkdrnf** [comment]
Is this issue solved or just closed?
There's a case tsc compiles without error and ts-node exits without any error log.
In this case, user cannot find what goes wrong with ts-node.
I hope ts-node emits error when ts-node exits!

**Comment by blakeembrey** [comment]
That’s literally how it works today. Maybe you have no errors if you say TypeScript compiles? Why would you expect an error when there’s no error?

**Comment by kvcrawford** [comment]
We've run into the same problem. ts-node used to kind of support this feature with the `disableWarnings` option in v3.3.0 (except it also hid the errors).

Our codebase is being refactored into TypeScript, and there are some type errors, and this prevents our test suite with Mocha using ts-node from running at all. 

As for error messages being interleaved with the rest of the application logging, it's probably more useful than anything for the case of running a test suite.

**Comment by blakeembrey** [comment]
@kvcrawford You're welcome to submit a PR. Also happy to enable `disableWarnings` again.

**Comment by kvcrawford** [comment]
@blakeembrey if you could enable `disableWarnings` again that would be awesome. We'll also consider investing some time in a PR for #34

**Comment by soundyogi** [comment]
Is this implemented?

**Comment by lake2** [comment]
same question + 1

**Comment by raykyri** [comment]
@lake2 @soundyogi The parameter is `--log-error`.
