### ISSUE TITLE
TS_NODE_CACHE_DIRECTORY environment variable does not get applied

### ISSUE THREAD

**Issue by gtramontina** [TypeStrong/ts-node#611]
Hi there,
First of all, thank you all for putting this module together! 👏

Now onto the issue: setting the `TS_NODE_CACHE_DIRECTORY` environment variable does not do anything. Digging deeper, I noticed we're doing the following:

We do have the defaults being set on `bin.ts`, but not all… It looks like `minimist` actually sets the missing properties to `undefined`.

https://github.com/TypeStrong/ts-node/blob/22915fdc8486b3531442d2ebb8fcdb084986cd76/src/bin.ts#L59-L65

Within `index.ts`, when we're actually registering, we do this:
https://github.com/TypeStrong/ts-node/blob/22915fdc8486b3531442d2ebb8fcdb084986cd76/src/index.ts#L191

What happens here is that `opts` actually contains a value: `undefined` (set by `minimist`?), which ends up overriding the default value that got set by the environment variable here:

https://github.com/TypeStrong/ts-node/blob/22915fdc8486b3531442d2ebb8fcdb084986cd76/src/index.ts#L103

It looks like the same would happen with these other environment variables, given that on `bin.ts` we're only setting a few:

```
TS_NODE_PRETTY
TS_NODE_CACHE_DIRECTORY
TS_NODE_COMPILER
TS_NODE_COMPILER_OPTIONS
TS_NODE_IGNORE
TS_NODE_PROJECT
TS_NODE_IGNORE_DIAGNOSTICS
```

---

I wonder why we're setting only a few default properties on `bin.ts`… Would the following cause any issues?

```ts
default: DEFAULTS
```

Happy to contribute with a PR…

**Comment by blakeembrey** [comment]
Thanks for the heads up 👍 I've got a patch ready and should be released today. The `undefined` comes from creating a custom object based on `argv` where not all `argv` may be set - I've opted to keep things there for now. I could also do `Object.assign(argv, { ... })` but I didn't like the idea when I first wrote it of passing a bunch of unknown flags. Probably the best would be to combine it with `pick` or something similar to avoid this.

**Comment by gtramontina** [comment]
Thank you very much for the prompt fix! I can confirm it is working now! Cheers!

**Comment by mcoimbra** [comment]
@gtramontina sorry if this is off-topic, but how are you applying this environment variable?
Is it possible to set it in a bash script (export TS_NODE_CACHE_DIRECTORY=/my/custom/path) before calling npm?

**Comment by gtramontina** [comment]
Apologies, @mcoimbra. I don't quite recall what this was all about. 😅

But what you have should be enough to thave the env. variable set.
