### ISSUE TITLE
Resolve imports using baseUrl?

### ISSUE THREAD

**Issue by oleersoy** [TypeStrong/ts-node#613]
I asked about this [on stackoverflow](https://stackoverflow.com/questions/50958749/should-ts-node-examine-the-baseurl-tsconfig-json-property) first, just to make sure I'm not missing something.

**Comment by blakeembrey** [comment]
Try https://www.npmjs.com/package/tsconfig-paths.

**Comment by oleersoy** [comment]
Sweet - Thanks!  I updated the SO with an answer.
