### ISSUE TITLE
How to don't skip `files`?

### ISSUE THREAD

**Issue by freezy** [TypeStrong/ts-node#618]
v7.0.0 breaks all my merge declarations. I could get it partly to work by adding them to `tsconfig.json`'s `files` and using the `--files` option when running `ts-node`, but that doesn't work when running tests with [nyc](https://github.com/istanbuljs/nyc) or in general when loading via `node` and `--require`.

How do I get the old behavior back?

**Comment by blakeembrey** [comment]
Use environment variables, as documented in the README.

**Comment by blakeembrey** [comment]
Or use the CLI to execute the NYC bin command.

**Comment by freezy** [comment]
Right. But then I still need to add every declaration to `files`. Right now I just have the path of my types in `compilerOptions.paths` and it works great with `tsc` as well as with `ts-node` <v7.

Anyway, a short note in the release notes how to migrate would have saved me a lot of time.

**Comment by sanex3339** [comment]
Same thing. Looking for the easy way to fix declarations merging

**Comment by freezy** [comment]
It seems the same issue as #615 and #616, there are some workarounds there.

**Comment by blakeembrey** [comment]
You asked how to get the old behaviour back and it’s the files flag. You don’t need to change anything in your config, it’s the only thing that changed with v7. Also, if you’re using paths correctly, it should already be working - the change doesn’t affect type definition resolution, only default loading of all the files referenced from the config.

**Comment by freezy** [comment]
Well, I've found that out too, but I didn't find anything in the doc that the `--files` flag not only applies to `tsconfig.json`'s `files` option but *also* seems to apply to `compilerOptions.paths`.

**Comment by blakeembrey** [comment]
I don’t follow, it only does apply to files/includes/excludes. It does not apply to compiler options such as paths.
