### ISSUE TITLE
On tsconfig.json 'files' handling

### ISSUE THREAD

**Issue by dcodeIO** [TypeStrong/ts-node#620]
> **Tip:** `ts-node` differs slightly from `tsc`. It will not load files from `tsconfig.json` by default. Instead, `ts-node` starts from the input file and discovers the rest of the project tree through imports and references.

This is unfortunate for me. Essentially, I have a project where I can't add `/// <reference`s to the sources because the target (JS or WASM) is interchangeable, and the necessary declarations are added through extending different base `tsconfig.json`s, relying on `files` being included.

Is there a way to force the old behavior in new versions of `ts-node`?

**Comment by blakeembrey** [comment]
Yes, you can read the documentation or search existing issues. Tip: https://github.com/TypeStrong/ts-node#cli-and-programmatic-options.

FWIW, no it should not be necessary to use `files` and, if it is, maybe you can share why it's necessary and someone can attempt to help you out with your configuration.

**Comment by dcodeIO** [comment]
> FWIW, no it should not be necessary to use files and, if it is, maybe you can share why it's necessary and someone can attempt to help you out with your configuration.

Thank you for your fast response. The project I was talking about is [AssemblyScript](https://github.com/AssemblyScript/assemblyscript), a TypeScript to WebAssembly compiler, where sources can be compiled to either WebAssembly with `asc` or JavaScript with `tsc` (and run with `ts-node`). Depending on the target, it is necessary to pull in different files via the `files` property within a target-specific `tsconfig.json`, but this property is ignored since `ts-node` 7. The reason why references within the sources cannot be used is because these would be invalid for the respective other target.

I did read the documentation, but wasn't able to spot a way to make `ts-node` honor the `files` property as it was before. Maybe you can point me in the right direction?

**Comment by blakeembrey** [comment]
Couldn’t you use types or references to achieve this? Check the section on configuration, there’s a files flag.

**Comment by blakeembrey** [comment]
Can you link me to some places I should look on how you’re expecting to use `ts-node`?

**Comment by dcodeIO** [comment]
What I am doing for the compiler itself now is to [use the files configuration setting explicitly](https://github.com/AssemblyScript/assemblyscript/blob/82da2d1f6dab93a5729433b07fa994c2d712ba57/cli/asc.js#L28-L34) with the duplicated array of files as you suggested.

However, if a user of the compiler wants to run their own portable application with `ts-node` now, he has to do the same and cannot simply extend [portable.json](https://github.com/AssemblyScript/assemblyscript/blob/82da2d1f6dab93a5729433b07fa994c2d712ba57/std/portable.json) from within their `tsconfig.json` that used to set up everything without having to worry about any additional files.

Regarding types and references: One of the necessary additional files is a .js file that sets up the environment to mimic some things one would also have when compiling to WebAssembly. The definition file could be injected by other means I think, but the JS file is difficult. Any ideas?

**Comment by blakeembrey** [comment]
Files is a boolean flag that, when enables, reads the files from configuration. It doesn’t accept a list of files. If that’s unclear in the README, can you let me know and I’ll try to improve it.

I don’t understand how you use the Javascript file - that was never how TypeScript or `ts-node` works - the additional files were for the compiler, not runtime.

**Comment by dcodeIO** [comment]
> Files is a boolean flag that, when enables, reads the files from configuration. It doesn’t accept a list of files. If that’s unclear in the README, can you let me know and I’ll try to improve it.

The documentation is actually clear on this. My mistake.

> I don’t understand how you use the Javascript file - that was never how TypeScript or ts-node works - the additional files were for the compiler, not runtime.

Might well be that I am using some things in unintended ways, and it just so happened to work with `ts-node` 6 even though it wasn't intended. I guess I can live with `--files` being a flag, as you explained. Thank you for your time!
