### ISSUE TITLE
Tsconfig not found when launched from parent directory

### ISSUE THREAD

**Issue by weeco** [TypeStrong/ts-node#623]
I've got a mono repository with multiple microservices but a single VSCode launch.json. Each microservice has it's own tsconfig.json , however I am not sure how I could tell ts-node where to look for the right tsconfig.json as it always looks for the tsconfig in the repository's root directory.

**My launch.json:**

```
{
  "version": "0.2.0",
  "configurations": [
      {
          "type": "node",
          "request": "launch",
          "name": "REST Api",
          "runtimeArgs": [
              "--nolazy",
              "-r",
              "${workspaceRoot}\\rest-api\\node_modules\\ts-node\\register"
          ],
          "args": [
              "${workspaceRoot}\\rest-api\\src\\main.ts"
          ],
          "outputCapture": "std"
      }
  ]
}
```

**Project structure:**

- .vscode
  - launch.json
- rest-api
  - src
    - main.ts
  - tsconfig.json
  - package.json
- microservice b
  - src
    - main.ts
  - tsconfig.json
  - package.json

How can I launch ts-node so that it will pickup the according tsconfig.json?

**Comment by blakeembrey** [comment]
You can use environment variables. See the README section for configuration on what variable to set.
