### ISSUE TITLE
Cant find .d.ts on version 7.0.0

### ISSUE THREAD

**Issue by milewski** [TypeStrong/ts-node#626]
now that `tsconfig.json` is skip by default in version `7.0.0` how do i do to add it back? my code stopped working due to typescript cant find any of the typings i have set on my `.d.ts` files

the flag `--project` doesnt seems to work with, here is how i am using ts-node

```js
mocha --require ts-node/register --require test/Mocha.env.ts 'test/api/**/*.ts' --exit --no-timeouts
```

**Comment by blakeembrey** [comment]
Use environment variables. Check the README or past issues for more info.
