### ISSUE TITLE
ts-node 7.0.0 doesn't include typings from `typings` folder

### ISSUE THREAD

**Issue by squidfunk** [TypeStrong/ts-node#628]
The newest version of `ts-node` doesn't respect the `typings` folder. I'm writing Karma tests in TypeScript and use module augmentations in the `typings` folder to marry Karma with Webpack. However, since I updated to version 7.0.0, the typings are not loaded anymore. The last working version was 6.2.0. This results in errors like:

```
02 07 2018 13:32:03.703:ERROR [config]: Invalid config file!
  TSError: ⨯ Unable to compile TypeScript:
tests/karma.conf.ts(61,5): error TS2345: Argument of type '{ autoWatch?: boolean | undefined; autoWatchBatchDelay?: number | undefined; basePath: string; br...' is not assignable to parameter of type 'ConfigOptions'.
  Object literal may only specify known properties, and 'webpack' does not exist in type 'ConfigOptions'.
```

This is not only true for augmented modules, but for all declarations defined in `typings`. The workaround is to revert back to `ts-node` 6.2.0.

My project [karma-viewport](https://github.com/squidfunk/karma-viewport) uses `ts-node` 5.0.1. If you check out the repository, update the version of `ts-node` to 7.0.0 and type `make test`, you wil see the exact error.

**Comment by AbhilashSrivastava** [comment]
Found out the same issue, with my project as well.
Doesnt automatically import the custom typings settings.

Facing this issue for version 7.0.0, before that it was working fine.



<img width="916" alt="screen shot 2018-07-02 at 7 04 46 pm" src="https://user-images.githubusercontent.com/8490725/42167196-db528f64-7e2a-11e8-83fd-6f6d7b9efa84.png">


Global object is custom defined & has __Config__ defined in itself. 
Please do let me know if any update for resolving this or any workaround would help.

Thanks

**Comment by blakeembrey** [comment]
See the README, changelog and search existing issues before creating a new one please.

**Comment by squidfunk** [comment]
Thanks. Found it after some digging.

To anybody experiencing the same issue: Prepend commands that use `ts-node` implicitly (e.g. Karma, Webpack) with `TS_NODE_FILES=true`, i.e.:

```
TS_NODE_FILES=true ./node_modules/.bin/karma start karma.conf.ts
```
