### ISSUE TITLE
Source maps and transpile-only

### ISSUE THREAD

**Issue by Crazometer** [TypeStrong/ts-node#629]
I recently updated from ts-node v4 to v7 and have noticed sourcemaps behaving weirdly depending on if `transpile-only` is set.

I used to generate code coverage using.

`nyc mocha \"src/**/*.spec.*s\" --recursive --require ts-node/register --require source-map-support/register`

This worked fine on v4 and v7. The changelog says to preserve the old v4 behaviour and for performance to use the `transpile-only` flag.

`nyc mocha \"src/**/*.spec.*s\" --recursive --require ts-node/register/transpile-only --require source-map-support/register`

This runs without trouble but the code highlighting becomes faulty.

<img width="297" alt="image" src="https://user-images.githubusercontent.com/5444465/42204947-6f5d45c6-7ee6-11e8-9b05-7c1e64f4fbbe.png">

Not using `transpile-only` the block is correctly fully covered. This happened across many files. As the issue disappears when I don't use the flag and did not happen previously in v4 it looks like a ts-node error.

**Comment by Crazometer** [comment]
I upgraded TypeScript to `2.9.2` as well. However I believe the fault to be in ts-node because toggling the `transpile-only` flag is enough to change the source-map output. e.g

typescript | ts-node | transpile-only | correct source map
--|----|-----|---
2.9.2 | 7 | enabled | false
2.9.2 | 7 | disabled | true
2.9.2 | 4 | NA | true

**Comment by blakeembrey** [comment]
The output comes from TypeScript, not `ts-node`. If it’s easily reproducible, can you check and report the issue to TypeScript.

**Comment by Crazometer** [comment]
Does `transpile-only` correspond to a specific TypeScript compiler flag? I'm not sure what I would report there.

**Comment by blakeembrey** [comment]
It translates to an exposed function called `transpileModule`.

**Comment by Crazometer** [comment]
Thanks for the help. Ended up being a problem with `nyc`.
