### ISSUE TITLE
Version 7.0.0 stopped working

### ISSUE THREAD

**Issue by LiborVilimekMassive** [TypeStrong/ts-node#630]
This error starts with 7.0.0 version:

> TSError: ⨯ Unable to compile TypeScript:
> src/app.ts(47,9): error TS2551: Property 'state' does not exist on type 'Request'. Did you mean 'stale'?
> src/app.ts(52,9): error TS2551: Property 'state' does not exist on type 'Request'. Did you mean 'stale'?
> src/app.ts(52,58): error TS2551: Property 'state' does not exist on type 'Request'. Did you mean 'stale'?
> src/app.ts(52,94): error TS2551: Property 'state' does not exist on type 'Request'. Did you mean 'stale'?
> 
>     at createTSError (node_modules\ts-node\src\index.ts:261:12)
>     at getOutput (node_modules\ts-node\src\index.ts:367:40)
>     at Object.compile (node_modules\ts-node\src\index.ts:557:11)
>     at Module.m._compile (node_modules\ts-node\src\index.ts:439:43)
>     at Object.require.extensions.(anonymous function) [as .ts] (node_modules\ts-node\src\index.ts:442:12)
>     at require (internal/module.js:11:18)
>     at Object.exports.prepare (test\lib\utils\initSetup.ts:7:20)
>     at Context.before (test\component\addPurchaseData.spec.ts:13:31)
> 

Example of code that uses state variable in express

```
export function initialLog(req: express.Request, res: express.Response, next: express.NextFunction) {
    req.state.logger.info({ req, res }, 'Initial Info');
    return next();
}
```

This is "standard" error if you do not `hack` the express.Request a bit, because it does not have .state object on its own. To achieve that, we have src/models/express-addition.ts file with this inside

```
import { State } from './index';

declare module 'express' {
    interface Request {
        state: State;
    }
}
```

This file is actually not imported anywhere in a project, but its enough for typescript to update Request object with `state` property.

This was working properly before we updated to 7.0.0, 

Just reverted back to 6.2.0 and everything is fine

We use it together with mocha for test with `--require ts-node/register -P tsconfig.json`

**Comment by blakeembrey** [comment]
Please read the README, check past issues and review the changelog before opening a new issue. You may find your issue has already been reported.

**Comment by LiborVilimekMassive** [comment]
I did that

On main page: CTRL+F -> changelog -> nothing
Readme does not help much either. Not sure how I should find that my issue is in this `--files Load files from tsconfig.json on startup (TS_NODE_FILES, default: false)`

**Comment by LiborVilimekMassive** [comment]
Ah thanks, I missed that Releases tab (well I was put there by Google few times, but never actually use it from main Repo)

**Comment by blakeembrey** [comment]
Yeah, it's very inconsistent across different projects unfortunately. I tend to say changelog to mean all the possible things (e.g. some use `releases.md`, `history.md`, `CHANGELOG`, GitHub releases). I'll try to clarify that in the future by specifying "GitHub releases" or something similar.
