### ISSUE TITLE
Global and GlobalAugmented not working

### ISSUE THREAD

**Issue by bilby91** [TypeStrong/ts-node#635]
Hello,

I'm trying to use `ts-node` to workaround an issue in jest that doesn't allow `globalSetup` and `globalTeardown` using typescript.

My project compiles correctly using `tsc`, now, when I use `ts-node` to require the code, my global files seem to be ignored. 

I have `globals.d.ts` and `globalsAugmented.d.ts`.

In `globals.d.ts` I do multiple global `declare type` and in the `globalsAugmented.d.ts` I define other global interfaces that depend on other modules I have in the system.

My project is splited in two different `tsconfig.json` files. My main one and a secondary for the tests. The tests tsconfig extend the main one. Could this be generating issues ? As I mentioned before, `tsc` is able to compile without issue with both of them.

Thanks!

**Comment by blakeembrey** [comment]
Why wouldn't you use path mapping or types? Those are the solutions TypeScript envisioned to solve what you want to do. There's also triple-slash references.

If all those aren't suitable to you, there's this:

> --files Load files from tsconfig.json on startup (TS_NODE_FILES, default: false)

**Comment by blakeembrey** [comment]
Types are for your globals and path mapping for imports. I’m sure there’s better information in the links in the README though since it points to the TypeScript docs. It does, however, require a specific structure for the types to be detected automatically and used.

**Comment by bilby91** [comment]
@blakeembrey Thanks for the quick reply again!

I think I got your point. I basically need to explicitly declare in the `types` array the path to `globals.d.ts` and `globalsAugmented.d.ts` right ? I would also need to add the `node_modules/@types` and `node_modules` so that I don't loose the default behaviour.

Thanks again! 

:)

**Comment by blakeembrey** [comment]
I'll work on updating the README with better examples today 👍

**Comment by Tronix117** [comment]
Hey, even with the Readme, I can't get around augmenting global.

I am using Loopback which have really bad typings, and was able to augment everything in this modules without any troubles.

However, in our app, we have `global.app` which is shared everywhere, so I need to be able to augment the Global interface.

Previously I was doing:

```
declare namespace NodeJS {
  interface Global {
    app: any
  }
}
```

however with the new system I can't get that to work, even embedded into a subfolder in `./types`


tsconfig:
```json
    ...
    "typeRoots": [
      "./types",
      "./node_modules/@types"
    ]
    ...
```

**Comment by IgorSzymanski** [comment]
@Tronix117 how did you figure it out?

**Comment by Tronix117** [comment]
@IgorSzymanski I'm not sure what I did, but it is working... Here's what I got

**./types/app/index.d.ts**
```
declare global {
  namespace NodeJS {
    interface Global {
      app: any
    }
  }
}
```

**./ts-config.json**
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "typeRoots": [
      "./types",
      "./node_modules/@types"
    ]
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by lednhatkhanh** [comment]
By naming the file `index.d.ts` and put it inside the `app` folder solved the issue
