### ISSUE TITLE
Do not correspond to the line numbers on error 

### ISSUE THREAD

**Issue by khusamov** [TypeStrong/ts-node#636]
Hello!
Why does the line number in the console not match the line number in the code?

![image](https://user-images.githubusercontent.com/4146998/42496002-728d488a-842d-11e8-9120-9a7b58cfb819.png)

But if you comment out the string ' Util.promisify(Hg.clone);`, then there is no error with the line number.

![image](https://user-images.githubusercontent.com/4146998/42496036-870ba13a-842d-11e8-9a48-5dd311abd3b5.png)

How to fix?

It is not by chance due to the fact that the module hg does not have a file with a description of the types under the typescript?

Or maybe due to the fact that hg is written on coffee-script?

Found the cause of the problem. It turns out the module hg is written to coffeescript. And it compiles during the execution of the script. And because of him such problems.

I compiled it. And inserted already in the compiled form. And the problem disappeared. Now all the lines match!!!

**Comment by blakeembrey** [comment]
There's not anything `ts-node` can do if another module has decided to take control of formatting error stacks away from this library. It's most likely, as you found, that CoffeeScript does something specific to error handling that results in it trying to handle all errors through and blocks `ts-node` from the regular re-formatting it does. This feature is provided by `source-map-support`, so if both modules use that library, it _should_ work.
