### ISSUE TITLE
Can't use ts-node@7.0.0

### ISSUE THREAD

**Issue by ShayBox** [TypeStrong/ts-node#637]
ts-node@7.0.0 doesn't follow files/includes rules in tsconfig.json (Not the problem).
I tried baseUrl & paths, but because of those rules now ts/ts-node can't find for typings in node_modules.
I can not add the files flag, as I use `node -r ts-node/register`, adding --no-cache or --files flags will try and add them to node, which doesn't exist on node.
And I will not use a deprecated workaround to get my project to work: (The --files flag/env).

How do I officially fix this, I tried adding `node_modules/*` to the paths as well, doesn't fix it. it just doesn't look for typings.

And when it's done uploading & processing, here's a video showing it: https://youtu.be/UJYrkN_SL8A

**Comment by blakeembrey** [comment]
You can use `typeRoots`, see README. You can also use environment variables in places you can't use flags, see README also.
