### ISSUE TITLE
Exception not shown in VS Code if thrown after console.log()

### ISSUE THREAD

**Issue by mohd-akram** [TypeStrong/ts-node#638]
The following code doesn't show an exception for me when debugging in VS Code:

```javascript
console.log('');
throw new Error('error');
```

Removing `console.log('')` causes the exception to appear in the Debug Console. The following also works fine:

```javascript
console.log('');
throw 'error';
```

I'm using the VS Code launch configuration mentioned in the README.

`node --version`: `v10.6.0`
`code --version`: `1.25.0`
`"ts-node": "^7.0.0"`

**Comment by blakeembrey** [comment]
Can you share your configuration? I’m not very familiar with this feature.

**Comment by mohd-akram** [comment]
`tsconfig.json` and VS Code settings are blank. Here's the `launch.json` for VS Code:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Launch Program",
      "runtimeArgs": [
        "-r",
        "ts-node/register"
      ],
      "args": [
        "${workspaceFolder}/test.ts"
      ]
    }
  ]
}
```

**Comment by mohd-akram** [comment]
After debugging for a while, I've narrowed it down to [this line](https://github.com/TypeStrong/ts-node/blob/55741b643d917e47db164cd7dbab2fba25042619/src/index.ts#L215) which installs source map support. Commenting it out causes the exception to show properly. I've confirmed that this isn't a VS Code issue by trying the same thing in the Chromium debugger (`node -r ts-node/register --inspect-brk test.ts`).

**Comment by blakeembrey** [comment]
You might want to report the issue on that module.

**Comment by mohd-akram** [comment]
It is indeed a problem there. I'm curious why this library is needed in the first place though. The stack traces are correct for me without it.

**Comment by blakeembrey** [comment]
They aren’t for me, hence the addition. Are you looking at stack traces in the console or in VS code - I bet the inspector protocol does source code mapping for you.

**Comment by blakeembrey** [comment]
Feel free to link the issue back to here so the others can track the progress if they run into the same issue 👍

**Comment by mohd-akram** [comment]
As a workaround, you can add `"outputCapture": "std"` to `launch.json` in VS Code.
