### ISSUE TITLE
Isn't require.extensions deprecated?

### ISSUE THREAD

**Issue by liuxh0** [TypeStrong/ts-node#641]
Hi everyone.

I've noticed that we register ts by calling `require.extensions`. But isn't it already [deprecated since v0.10.6](https://nodejs.org/api/modules.html#modules_require_extensions)?  

https://github.com/TypeStrong/ts-node/blob/743e80feca64b77887d7551568c2c4b777e2cad6/src/index.ts#L429

May be a fool question. If I missed something, please tell me :-)

**Comment by blakeembrey** [comment]
Yes. There’s no other way to make it work.

**Comment by ahonn** [comment]
Why not use `Module._extensions [ext]`?

**Comment by blakeembrey** [comment]
@ahonn 

<img width="348" alt="image" src="https://user-images.githubusercontent.com/1088987/58376154-4aa85800-7f18-11e9-9127-5caaaff4d919.png">

**Comment by ahonn** [comment]
@blakeembrey But `require.extensions` already deprecated

**Comment by blakeembrey** [comment]
@ahonn They're literally the same object, they're both deprecated. Just because one isn't in the docs doesn't mean it's not deprecated, it means it was never meant to be used to start with. That's what `_` prefixes mean, they aren't meant for public use.
