### ISSUE TITLE
ts-node seems to turn off caching completely when rebuilding caches, not even using any newly cached imports during that build.

### ISSUE THREAD

**Issue by JaSpr** [TypeStrong/ts-node#642]
When the cache has to be replaced in typescript, ts-node build goes from around 15 seconds to 15 minutes (literally 60x the amount of time it normally takes).  From viewing the logs with TS_NODE_DEBUG on, it appears to be looping over the same exact files over and over again.  While I understand that it might come across code that has already been imported elsewhere, it should only have to follow the dependency tree on a given import once during build, and be able to use the cache the second time it comes across that same import in another location during the same build.

It seriously seems like typescript is clearing the cache and starting over, but that ts-node somehow prevents it from using any of the NEW cache items during that build.

Note that this is only happening in our behavioral tests, where we use ts-node.  Our jest and webpack builds all use ts-loader through webpack, and we do not have this issue whatsoever.

As a note, we *are* already running with TS_NODE_TRANSPILE_ONLY=true
ts-node: 3.3.0
typescript: 2.9.2

**Comment by JaSpr** [comment]
tsconfig.json 

```{
  "compileOnSave": false,
  "compilerOptions": {
    "jsx": "react",
    "sourceMap": true,
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "paths": {
      "app/*": ["app/*"],
      "test/*": ["../test/*"]
    },
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": false,
    "experimentalDecorators": false,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017.object",
      "es2016",
      "dom"
    ],
    "noImplicitAny": false,
    "suppressImplicitAnyIndexErrors": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by JaSpr** [comment]
This is using the cli argument `--compiler ts:ts-node/register`

**Comment by blakeembrey** [comment]
You’re three major releases behind and that flag does not exist on your version. Have you tried updating?

**Comment by JaSpr** [comment]
I have now. I can't believe I've spent so much time looking into this and didn't even consider a version check.

Everything works as intended now! Thanks!
