### ISSUE TITLE
Can't paste a function

### ISSUE THREAD

**Issue by jtth** [TypeStrong/ts-node#644]
If I run `ts-node` from within my project, and I paste the line `function makeSignObject(signs: Array<string>): Array<object> {` into the repl, I expected that it would, like node, let me finish writing the function definition on a new line. Instead, it reports `[eval].ts(2,1): error TS1005: '}' expected.
[eval].ts(1,48): error TS2355: A function whose declared type is neither 'void' nor 'any' must return a value.` 

How do you paste functions into ts-node and use it as an actual repl?

**Comment by blakeembrey** [comment]
It looks like this is because the TypeScript compiler has changed how it works and is reporting a new error code on lines even with an open parenthesis. You need to add the code to https://github.com/TypeStrong/ts-node/blob/743e80feca64b77887d7551568c2c4b777e2cad6/src/bin.ts#L384.

**Comment by blakeembrey** [comment]
Looks like it works with this change, but you can get stuck if you closed the `}` without resolving these errors.
