### ISSUE TITLE
raw file import

### ISSUE THREAD

**Issue by dakom** [TypeStrong/ts-node#652]
It seems that `ts-node` doesn't support raw file import - e.g. these examples from [the handbook](https://www.typescriptlang.org/docs/handbook/modules.html)

```
//ambient.d.ts
declare module "*!text" {
    const content: string;
    export default content;
}

//main.ts
import fileContent from "./xyz.txt!text";
```

Is it possible to support this at the transpilation level, without relying on manual/runtime file reading?

**Comment by blakeembrey** [comment]
You still need the appropriate handling in node.js, see the README for more information.

**Comment by wspringer** [comment]
> You still need the appropriate handling in node.js, see the README for more information.

I have no idea what that means.

**Comment by coyotte508** [comment]
Maybe use the programmatic approach of `ts-node` with the custom transformers?

**Comment by coyotte508** [comment]
You can do this directly in nodejs, by overloading `require("module")._load`.

For example, with this file `raw-loader.js`:

```js
const path = require('path')
const fs = require('fs')
const REQUIRE_PATH_TEST = /\.txt$/

/* eslint-disable no-underscore-dangle */

/**
 * Node will load all matched files as raw strings
 *
 * @param {RegExp} pathMatcher
 */
function register(pathMatcher = REQUIRE_PATH_TEST) {
  const Module = require('module')
  const orginalLoad = Module._load
  const cwd = process.cwd()
  Module._load = function (request, _parent) {
    if (request.match(pathMatcher)) {
      return fs.readFileSync(path.join(path.dirname(_parent ? _parent.filename : cwd), request), 'utf8')
    }
    return orginalLoad.apply(this, arguments)
  }

  return () => {
    Module._load = orginalLoad
  }
}

module.exports = {
  register,
}
```

You just need to do `require('raw-loader.js').register(/\.txt$/)` at the top of your application, before the `.txt` files are imported.

Depending on your tsconfig, you may need to change:

```
      return fs.readFileSync(path.join(path.dirname(_parent ? _parent.filename : cwd), request), 'utf8')
```

to

```
      return { default: fs.readFileSync(path.join(path.dirname(_parent ? _parent.filename : cwd), request), 'utf8') }
```

You can also create a file that calls the register function and just load it like that:

```
ts-node --require register.js index.ts
```

**Comment by livestatio** [comment]
Has anyone ever resolved this issue? I am still getting the very same error here.

**Comment by art049** [comment]
Thanks, @coyotte508, this is working perfectly !
For anyone having the same issue I had to do a few changes to handle imports:

Here is my `register-loader.js` file:
```js
const path = require("path");
const fs = require("fs");
const REQUIRE_PATH_TEST = /\.txt$/;

function register() {
  const Module = require("module");
  const orginalLoad = Module._load;
  const cwd = process.cwd();
  Module._load = function (request, _parent) {
    if (request.match(REQUIRE_PATH_TEST)) {
      return fs.readFileSync(
        path.join(path.dirname(_parent ? _parent.filename : cwd), request),
        "utf8"
      );
    }
    return orginalLoad.apply(this, arguments);
  };

  return () => {
    Module._load = orginalLoad;
  };
}
register();
```

Then, simply run I added this to my `tsconfig.json`:
```diff
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
      // Not relevant here
  },
+  "ts-node": {
+   "require": ["tsconfig-paths/register", "./register-ejs-loader.js"],
+ }
}
```
Then this works like a charm:
```bash
ts-node  scripts/myFancyScriptImportingTxt.ts 
```

**Comment by conancat** [comment]
thank you @coyotte508 and @art049, this works for me, appreciate your help! 

If anyone stumbles upon this thread and is trying to import files as strings with ts-node and is still having trouble, here's what I did: 

First, create a types declaration file in your project. For me I'm trying to import HTML files as string, so I created a `html.d.ts` with the following content: 

```
declare module '*.html' {
    const value: string;
    export default value;
}
```

If you're using a build system like webpack or esbuild you should update the config for them to support text loaders. For now, I'm trying to make this work with ts-node, so I needed to create a file that contains the `register()` function above provided by @art049 and @coyotte508 above in the same location with my tsconfig.json file, as well as add these configurations to the end of my tsconfig.json: 

```
{ 
   ...,  
   "ts-node": {
        "files": true,
        "require": ["./tsnode.registerLoader.js"]
    }
}
```

Note that you need the `"files": true` configuration in order for ts-node to pick up type declaration files in your project.
