### ISSUE TITLE
Is lineOffset in compile() unused?

### ISSUE THREAD

**Issue by webmaster128** [TypeStrong/ts-node#661]
I was reviewing https://github.com/TypeStrong/ts-node/blob/6df09a937a22ce4b67435b49cbed0e726575b84c/src/index.ts and if I am not entirely blind, lineOffset from 

```
export interface Register {
    cwd: string;
    extensions: string[];
    cachedir: string;
    ts: TSCommon;
    compile(code: string, fileName: string, lineOffset?: number): string;
    getTypeInfo(code: string, fileName: string, position: number): TypeInfo;
}
```

appears to be unused. Is that correct? I was also setting the value to 9999999 in a custom repl implementation and everything worked as before.

**Comment by blakeembrey** [comment]
Currently used, yes. It used to work before I had to move some of the TypeScript functionality around and it unfortunately broke.

**Comment by blakeembrey** [comment]
Most likely it's a matter of fixing up the diagnostic formatter, it broke when I moved to using the official TypeScript utility for formatting diagnostic messages.

**Comment by blakeembrey** [comment]
Ref: https://github.com/TypeStrong/ts-node/commit/2e44bc0be11a9b4ee2a9e31bcacd97a710128c4d#diff-f41e9d04a45c83f3b6f6e630f10117feL601. Closing since this only appears to be a question.

**Comment by webmaster128** [comment]
Thank you very much for the detail response. Yes, just a question and is done for now. I can simply my caller code, which is great. Will think about it more when continuing to work on the repl.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
