### ISSUE TITLE
(Gulpfile.ts) Requiring external module ts-node/register

### ISSUE THREAD

**Issue by khusamov** [TypeStrong/ts-node#662]
How to get rid of this error?

```
[15:27:43] Requiring external module ts-node/register
***\gulpfile.ts:1
(function (exports, require, module, __filename, __dirname) { import Gulp from 'gulp';
                                                              ^^^^^^
```

**package.json**

```json
{
  "scripts": {
    "postbuild": "gulp postbuild",
  },
  "devDependencies": {
    "@types/gulp": "^4.0.5",
    "@types/node": "^10.5.7",
    "gulp": "^4.0.0",
    "ts-node": "^7.0.1",
    "typescript": "^2.9.2"
  }
}

```

**Comment by khusamov** [comment]
```
> gulp --require ts-node/register postbuild

[16:11:15] Requiring external module ts-node/register
```

**Comment by blakeembrey** [comment]
What's your `tsconfig.json`? You don't need to register it anyway either, gulp already uses it by default when it sees `.ts`.

**Comment by davidshen84** [comment]
Hi,

I was able to run `gulp` directly with my *gulpfile.ts* file. Until recently I update the npm packages. I got this error again. It feels like even though gulp claim it required the `ts-node/register` module, it does nothing. I guess there's a version incompatibility issue.

## Version Info.
 
    node --version
    v11.14.0

    ts-node@8.3.0
    typescript@3.4.5
    gulp@4.0.2

**Comment by eharvey328** [comment]
@davidshen84 Same thing happened to me. It was because in my tsconfig: `"module": "esnext"` was added. Removing this at the root tsconfig and adding it to my tsconfig.app solved it.

**Comment by davidshen84** [comment]
@eharvey328 , thanks a lot!

**Comment by timerg** [comment]
For me, it was because of `"type": "module"` in the `package.json`.
