### ISSUE TITLE
ts-node used in VSCode debug

### ISSUE THREAD

**Issue by stevennzhou** [TypeStrong/ts-node#664]
Hi, I have problem that I write these config in vscode launch file.
```javascript
  "type": "node",
  "request": "launch",
  "name": "launch",
  "runtimeArgs": ["-r", "ts-node/register"],
  "args": [
    "${workspaceRoot}\\ts-express\\src\\server.ts",
    "-P",
    "${workspaceRoot}\\ts-express\\tsconfig.json"
  ],
  "sourceMaps": true
```
I want to figure tsconfig.json by myself, but unfortunately it can not work!
thx~

**Comment by blakeembrey** [comment]
The argument is being passed to `node`, not `ts-node`, here. You either need to change the executable to be `ts-node` instead of `node`, or use environment variables. Also, even when using `ts-node`, the configuration never comes after the script path.
