### ISSUE TITLE
Readline support

### ISSUE THREAD

**Issue by wcauchois** [TypeStrong/ts-node#665]
Could readline support be added to `ts-node`? It would make working with it much nicer. Things like using the arrow keys to browse command history, and keeping a history of entered commands in a file or something like that.

I've tried using `rlwrap` with `ts-node`, but it's kind of finnicky -- sometimes it gets into a weird state. I'm on Mac OS X -- if anyone knows the right parameters to rlwrap to get it to work seamlessly with ts-node, that would also be appreciated.

**Comment by blakeembrey** [comment]
You're welcome to submit a PR 👍

**Comment by cspotcode** [comment]
9.0.0 added support for `NODE_NO_READLINE`, which is probably all we need to do to support this, or at least have parity with vanilla node. #1090
