### ISSUE TITLE
`SyntaxError: Unexpected token import` when running in an Electron <webview> element.

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/ts-node#666]
This might be an issue with what Electron is doing with `require`, but when I try to run my HTML page in an Electron `<webview>`, `ts-node` doesn't seem to do anything. However, it works fine if I instead use Electron's `new BrowserWindow` API instead of a `<webview>`. The error happens in my app file, not in node_modules

More details in this comment: https://github.com/TypeStrong/ts-node/issues/621#issuecomment-413625109

This might be a problem with Electron instead of ts-node, but I'm not sure.

**Comment by blakeembrey** [comment]
Can you provide configuration info and version info? Not sure right now, may be something more Electron specific due to output based on what you’ve said.

**Comment by trusktr** [comment]
I discovered and posted in the other thread, that ts-node in fact _does_ work in a `<webview>` in another app, so I'm trying to find out what the difference is. I'm stepping through ts-node in the debugger at the moment.

I noticed `process.cwd` isn't the same in the app that is broken. Both apps are loading the same `.ts` files though. This makes me wonder if it's using a different tsconfig than what I'm expecting.

As for my tsconfig, it works great in one app, so that can't be an issue. Maybe it's in fact reading a different one... I may be onto something, still investigating...

**Comment by trusktr** [comment]
I'm willing to be that this works fine with `@babel/plugin-transform-typescript` due to Babel's method of finding `.babelrc` files starting from the file being compiled and working it's way up the file tree.

**Comment by trusktr** [comment]
If I could pass a tsconfig object into ts-node's `register` function, then the entry point in project A could supply it's own config.

**Comment by trusktr** [comment]
Oh, I see `compilerOptions`, giving that a go...

**Comment by trusktr** [comment]
That worked! 🎉 

So in the entry point of project A, I added

```js
	compilerOptions: require('./tsconfig.json').compilerOptions
```

so that it uses it's own local config. This works great because this is the entry point for the `<webview>`, so by it specifying it's own compilerOptions it won't break anything else, which runs in Node contexts in other windows.

**Comment by blakeembrey** [comment]
You can also specify the path to exactly via the project option.
