### ISSUE TITLE
-P flag doesn't seem to be respecting tsconfig location

### ISSUE THREAD

**Issue by richardbourne-ct** [TypeStrong/ts-node#667]
The relevant snippet from my `package.json`:

```
{
    ...
    "scripts": {
        "test": "mocha -r ts-node/register -P test/tsconfig.json test/**/*.test.ts",
         ...
    }
}
```

Unless I'm misunderstanding, the `-P` flag should point ts-node at the `tsconfig.json` in my `test/` folder. This, however, is not the case.

Reason I want to do this is so I can compile modules 'normally' with `esnext` in my regular `tsconfig` but allow for `commonjs` compilation when running Mocha tests through Node.

I have confirmed that swapping `esnext` for `commonjs` in my main `tsconfig` runs the tests successfully.

As a side note, I've also tried:

`
    "test": "mocha -r ts-node/register -O '{\"module\":\"commonjs\"}' test/**/*.test.ts",
`

to no avail - both attempts result in:

```
(function (exports, require, module, __filename, __dirname) { import { hello } from "./hello-world";
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
```

**Comment by blakeembrey** [comment]
It works fine, you're passing the CLI flag to `mocha` though which doesn't understand the flag, only `ts-node` does. You can use environment variables as a work around, or run the command with `ts-node`.

**Comment by blakeembrey** [comment]
I believe it'd look something like `ts-node -P ... node_modules/.bin/_mocha` to run it via `ts-node`, and the environments variables are documented in the README.

**Comment by richardbourne-ct** [comment]
Bah! Thanks - it was pretty late when I posted that, apologies for the dumb question.
