### ISSUE TITLE
Cache doesn't take modified dependencies into account

### ISSUE THREAD

**Issue by mihe** [TypeStrong/ts-node#672]
Not sure if this is by design or not, but it seems the caching doesn't take modifications of the code you're importing into account at all when calculating the hash.

I just had a problem where my Mocha tests (that are written in TypeScript, using `-r ts-node/register`) were still running just fine despite the fact that I'd changed the signature of the functions I was importing and testing.

With the cache disabled I got the compilation errors I was expecting.

If this is the intended behavior I would consider it somewhat dangerous to have the cache enabled by default.

**Comment by blakeembrey** [comment]
@mihe This is a very good point. I'll think about how this may be solved, and if I come up with nothing, disable/remove in the next release.

**Comment by crysislinux** [comment]
I am not sure if I hit the same problem.

My project can run with --no-cache, but not without it.

**Comment by webuniverseio** [comment]
Not sure in which version this got fixed, but I had trouble with 9.1.1 release, I end up using `--prefer-ts-exts=true` which is skipping js cache and using ts files instead
