### ISSUE TITLE
How to type-check with ts-node?

### ISSUE THREAD

**Issue by ericmorand** [TypeStrong/ts-node#673]
I keep on reading everywhere that we can use ts-node to type-check TypeScript sources. But there is nothing about it in the documentation.

Are the internet wrong? Or is it something that was removed?

**Comment by blakeembrey** [comment]
It type checks by default.

**Comment by blakeembrey** [comment]
Feel free to follow up with clarification on your question and I'll append to my answer. Since I've answered to the best of the ability right now, I'm going to close the issue.
