### ISSUE TITLE
Triple slash reference directive to built in lib with transpileOnly doesn't work

### ISSUE THREAD

**Issue by kwonoj** [TypeStrong/ts-node#685]
I'm trying to use `/// <reference lib="..." />` directive (https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#-reference-lib--reference-directives) with TSC 3.x, and tyring to solve compilation issue with ts-node but couldn't find right configuration.

Repro can be found at https://github.com/kwonoj/ts-node-slash-ref , `npm install` and `npm run test:normal` / `npm run test:notranspile` shows difference: it shares same config, only setting `TS_NODE_TRANSPILE_ONLY=true` is different.

When it's not enabled, compilation works successfully. When it's enabled, it emits diagnostics error:

```
C:\github\ts-node-slash-ref\node_modules\ts-node\src\index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS6053: File 'lib.dom.d.ts' not found.

    at createTSError (C:\github\ts-node-slash-ref\node_modules\ts-node\src\index.ts:261:12)
    at getOutput (C:\github\ts-node-slash-ref\node_modules\ts-node\src\index.ts:298:38)
....
```

Any way to pass compilation with `TS_NODE_TRANSPILE_ONLY`? (disabling option is no-go for my code unfortunately) Not sure if this known or dupe, feel freely close if that's cases.

**Comment by blakeembrey** [comment]
@kwonoj Seems like it may be an issue with TypeScript, I'd need to look further to be sure. Perhaps an option was added. All the code for this is https://github.com/TypeStrong/ts-node/blob/3ff4a69181a3695b3896a250a5dcd8027f818543/src/index.ts#L287-L292. It's not complex when in transpile mode, since it's not meant to do any type checking.

**Comment by cspotcode** [comment]
Seems like it might be a TS bug.

```
import * as ts from 'typescript';

const result = ts.transpileModule(`/// <reference lib="dom" />`, {
  reportDiagnostics: true
});
// Reports diagnostic:
// File 'lib.dom.d.ts' not found.

const result2 = ts.transpileModule(`/// <reference lib="nonsense" />`, {
  reportDiagnostics: true
});
// Does not report any diagnostics
```

@kwonoj You might want to file this as a TypeScript bug.
