### ISSUE TITLE
How to add the --transpile-only to "--nolazy -r ts-node/register" when debug in IDE

### ISSUE THREAD

**Issue by wildtang** [TypeStrong/ts-node#686]
I am debugging a TypeScript project in VS Code or WebStorm as NodeJS configuration.
In node parameters, I input:

    `--nolazy -r ts-node/register`

but If I add --transpile-only to the line above head or tail, 
Node report bad option: --transpile-only when I launch the debugger.

How can I add --transpile-only or -T in this situation? Thanks.

**Comment by blakeembrey** [comment]
It’s in the README. Use a different file to require or environment variables.
