### ISSUE TITLE
E2E typescript tests are not being transpiled after Angular upgrade Ask

### ISSUE THREAD

**Issue by akisiel1** [TypeStrong/ts-node#687]
Hi!

I have a problem with e2e tests after the upgrade to the Angular 6. Problem is described in more details on StackOverflow: 
https://stackoverflow.com/questions/52420169/e2e-typescript-tests-are-not-being-transpiled-after-angular-upgrade

I think it might be problem on angular-cli or ts-node side. 

I use `"ts-node": "7.0.1"` and `"typescript": "2.9.2"`

Can anyone look at it?

**Comment by blakeembrey** [comment]
When reporting an issue, please try to narrow down the cause or have something reproducible, especially if you believe it's a bug in `ts-node`. Based on your StackOverflow post, it's an issue with your types:

```
e2e/....e2e-spec.ts(27,111): error TS2322: Type '0' is not assignable to type '{ label: number; sent: () => any; trys: any[]; ops: any[]; }'.
```

**Comment by akisiel1** [comment]
Hi @blakeembrey !

Sorry if the task's description is too wide, but the problem is pretty complex. If you might see on the bottom, there is a note that proves that it is not a problem of my types, but of not transpiled files.

**Comment by blakeembrey** [comment]
Your problem is your module output in your configuration then. Node.js can’t execute ES2015 modules, you need the module to output CommonJS.

**Comment by akisiel1** [comment]
Hi!

I have finally found that the problem was in one of the npm packages. I needed to downgrade:
```
"tsconfig-paths": "3.6.0",
"ts-node": "~5.0.1",
"tsickle": ">=0.25.5",
"tslib": "^1.7.1",
"tslint": "~5.9.1",
```

and upgrade:
```
"protractor-image-comparison": "^2.0.0",
```

I don't know which package caused that issue, unfortunately I didn't have more time to investigate that.
