### ISSUE TITLE
Execute function in typescript file transpiled

### ISSUE THREAD

**Issue by simpert** [TypeStrong/ts-node#689]
Is there a way to (in a single process, single command) tell `ts-node` to execute a function in the transpiled `typescript`?

I am just discovered `ts-node` traditionally for running my `mocha` tests but I am learning it can play a bigger role in my projects since it allows to execute `typescript` without having to deal with *Pesky* ugly `javascript` files.

I am thinking of having a `tasks.ts` file filled with functions. If I can run a command that will execute one of those functions then I can get rid of Grunt and run everything from `npm scripts`.

Currently I can have a directory of task typescript files but having a single file would be nice.

**Comment by blakeembrey** [comment]
It's node.js with TypeScript transpilation. It will just run whatever file you want it to. If you want to run a function, you'd need to call that function. If you want a file that does more things you want to support configuration via CLI flags or something else. Anything else is outside of scope for `ts-node`.
