### ISSUE TITLE
Add `tsconfig-paths` to documentation

### ISSUE THREAD

**Issue by darcyparker** [TypeStrong/ts-node#704]
I learned about [tsconfig\-paths](https://github.com/dividab/tsconfig-paths) in https://github.com/TypeStrong/ts-node/issues/138.

Path mappings are very useful, so using `tsconfig-paths` is often a must have for me when using `ts-node`.

I think it would be helpful to list of useful modules like [tsconfig\-paths](https://github.com/dividab/tsconfig-paths) in the [README\.md](https://github.com/TypeStrong/ts-node/blob/master/README.md). (Similar to recommendations made for [Watching and Restarting](https://github.com/TypeStrong/ts-node/blob/master/README.md#watching-and-restarting).)

EDIT from @cspotcode: marked this ticket as "help wanted" with a list of tasks here: https://github.com/TypeStrong/ts-node/issues/704#issuecomment-864211793

**Comment by cspotcode** [comment]
@blakeembrey do you think this is adequately covered by this page?  https://typestrong.org/ts-node/docs/paths

**Comment by rayfoss** [comment]
@cspotcode it's informative... but it should probably contain some samples of common scenarios

I can't get the linter to shut up, about this: import mongo from '#src/mongodb.js'
it's not a trivial problem in deeply nested multilevel projects with files of the similar names.

Here's my setup...
```
"imports": {
    "#src/*": "./src/*"
  },
```

```
"compilerOptions": {
	  "module": "ESNext",
	  "allowJs": true,
	  "moduleResolution": "node",
	  ...
	  "baseUrl": ".",
	  "paths": {
	    "#src/*": ["src/*"]
	  }
}
"ts-node": {
	  // Do not forget to `npm i -D tsconfig-paths`
	  "require": ["tsconfig-paths/register"]
}
```

**Comment by cspotcode** [comment]
@rayfoss how about this as a plan forward?  I think it strikes a balance between improving the docs, saving the team's limited time resources, and giving users agency to help each other.  It effectively solves the core problem which is: "make this work for users"

- Create an official discussion thread for paths and tsconfig-paths usage
- Link to this discussion thread from that docs page
- Encourage users to share working configurations in that thread
- If / when certain configurations emerge as the best, clearest examples, we look at adding them to the website

If that plan sounds good, I can mark this ticket as "help wanted" and allow the community to tackle all of those tasks.
