### ISSUE TITLE
Cannot find module 'typescript'

### ISSUE THREAD

**Issue by s97712** [TypeStrong/ts-node#707]
when I execute: `$ npx ts-node`, it throwing
`Cannot find module 'typescript'`
how should I fix that?

`tsconfig.json`
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2017",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "preserveConstEnums": true,
    "outDir": "dist"
  },
  "include": [
    "src/**/*"
  ]
}
```
`src/index.ts`
```
console.log("test");
```

`package.json`
```
{
  "name": "agent",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "start": "tsc && node dist/index.js",
    "dev": "nodemon --watch 'src/**/*.ts' -e ts,tsx --exec 'ts-node' ./src/index.ts",
    "debug": "nodemon --inspect --watch 'src/**/*' -e ts,tsx --exec 'ts-node' ./src/index.ts"
  },
  "dependencies": {
    "@types/koa-router": "^7.0.32",
    "koa": "^2.5.3",
    "koa-router": "^7.4.0",
    "nodemon": "^1.18.4",
    "pg": "^7.5.0"
  },
  "devDependencies": {
    "@types/koa": "^2.0.46",
    "@types/pg": "^7.4.11",
    "ts-node": "^7.0.1"
  }
}
```

**Comment by s97712** [comment]
I try to run `npx ts-node -e 'console.log("test")'`, it still throwing
`Cannot find module 'typescript'`

**Comment by blakeembrey** [comment]
TypeScript is required if you want to compile using `ts-node`.

**Comment by mbujold** [comment]
I have this issue with typescript installed globally.

Here is the error:

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.register (C:\Users\marcb\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:208:28)
    at Object.<anonymous> (C:\Users\marcb\AppData\Roaming\npm\node_modules\ts-node\src\bin.ts:108:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vipor-rest@0.1.0 dev: `ts-node ./src/server.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vipor-rest@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\marcb\AppData\Roaming\npm-cache\_logs\2019-01-23T10_03_59_349Z-debug.log

Happens with the following packages:
ts-node@8.0.1
typescript@3.2.4

**Comment by s97712** [comment]
ts-node need installed globally too. or both installed locally

**Comment by hwanpenn** [comment]
same problem

**Comment by dance2die** [comment]
Same issue (not sure if it's due to NVM though).

![image](https://user-images.githubusercontent.com/8465237/51700164-73592900-1fdc-11e9-9224-653521357bff.png)

**Comment by Antarian** [comment]
Please reopen this ticket. I have same issue here with typescript installed globally in Docker:
```
> ts-node ./lib/server.ts

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at Object.register (/usr/local/lib/node_modules/ts-node/src/index.ts:208:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/src/bin.ts:108:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
Docker install error with ts-node:
```
Step 3/6 : RUN npm install -g typescript
 ---> Running in 3f1f32de6b7b
/usr/local/bin/tsc -> /usr/local/lib/node_modules/typescript/bin/tsc
/usr/local/bin/tsserver -> /usr/local/lib/node_modules/typescript/bin/tsserver
+ typescript@3.2.4
added 1 package from 1 contributor in 2.642s
Removing intermediate container 3f1f32de6b7b
 ---> 09f7d5c94179
Step 4/6 : RUN npm install -g ts-node
 ---> Running in 9f64cad9eb11
/usr/local/bin/ts-node -> /usr/local/lib/node_modules/ts-node/dist/bin.js
npm WARN ts-node@8.0.1 requires a peer of typescript@>=2.0 but none is installed. You must install peer dependencies yourself.

+ ts-node@8.0.1
added 9 packages from 42 contributors in 1.79s
Removing intermediate container 9f64cad9eb11
 ---> 798210c18452
```

**Comment by blakeembrey** [comment]
You'll need to install `typescript` locally since v8, it's using `require.resolve` which has its own separate limitations but is used to resolve a different issue. That means `typescript` is resolved from where you're running it right now.

**Comment by adueck** [comment]
@blakeembrey It would be really nice to be able to run this with `typescript` installed globally. I would love to be able to quickly run `.ts` files in node without having to init a project, install `typescript` again etc.

**Comment by blakeembrey** [comment]
@adueck It makes sense, but isn't going to happen in 8.0 right now. I could put it behind a flag though. See reasoning in https://github.com/TypeStrong/ts-node/issues/697.

**Comment by Redfish52** [comment]
> 
> 
> @blakeembrey It would be really nice to be able to run this with `typescript` installed globally. I would love to be able to quickly run `.ts` files in node without having to init a project, install `typescript` again etc.

I would really like too

**Comment by blakeembrey** [comment]
@Redfish52 There's a 👍 button if you just want to chime in and aren't contributing to the issue. 

For anyone else, I'd like to know if a flag is adequate enough for now.

**Comment by ORESoftware** [comment]
@blakeembrey putting it behind a flag would be just fine for me, sounds good

**Comment by codler** [comment]
Why do it need to be behind a flag? Cant you just do a fallback if typescript isn't installed locally, search for globally?

**Comment by blakeembrey** [comment]
@codler That creates an inconsistent environment for people, e.g. a dev environment may have it installed locally and another person not installed locally. This can create simple misunderstandings and more issues.

**Comment by codler** [comment]
Hm, locally is bound to a project in package.json, and when its bound to project I cant see how the other person wouldn't have it locally also without installed the project wrongly.

**Comment by blakeembrey** [comment]
What about if you never did `npm install`? That'll use both the global `ts-node` and globally `typescript` automatically. What about if someone else didn't add it in the `package.json`? Right now, I'm against trying to automatically resolve via two different paths and not sure what value it'd really add.

**Comment by Redfish52** [comment]
As a temporary solution I used these settings:
`"code-runner.executorMap": {
        "typescript": "tsc $fileName && node $fileNameWithoutExt"
    }`

**Comment by blakeembrey** [comment]
@Redfish52 I'm not sure what that's working around, but `npm install typescript` is the "fix" here.

**Comment by jajaperson** [comment]
Any progress on the flag?

**Comment by jajaperson** [comment]
What if you defaulted to using the global `typescript` module when `ts-node` is installed globally?

**Comment by blakeembrey** [comment]
@jajaperson https://github.com/TypeStrong/ts-node/issues/707#issuecomment-459048669.

**Comment by Deamon87** [comment]
I have stumbled across this same issue just now. 
```
    "ts-loader": "^6.0.3",
    "ts-node": "^8.3.0",
```
In ts file:
```
import ts from 'typescript';
```
tsconfig:
```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "ES6",
    "target": "es6",
    "jsx": "react"
  }
}
```
If I change module to 
```
"module": "commonjs"
```
it is able to find typescript. But with "es6" option it magically loses this ability

**Comment by hamad-Adel** [comment]
I solve this problem by reinstalling typescript globally
npm i -g typescript

**Comment by basickarl** [comment]
I had to do a reinstall of my local node modules then it worked.

**Comment by Haixiang6123** [comment]
I tried to reinstall the `typescript` globally, and it works!
Try:
```
yarn global add typescript
```
or
```
npm i -g typescript
```
Try one way, and if it still don't work, then try the other way.

**Comment by MagnusBrzenk** [comment]
This isn't working for me. I have `ts-node` and `tsc` installed locally, but when I run: ```
./node_modules/.bin/ts-node --compiler-options "{\"module\": \"commonjs\",\"lib\":[\"es2015\",\"dom\"]}" main.ts`, I get the message `Error: Cannot find module 'typescript'...
```
This is so confusing -- why can't `ts-node` "see" `tsc` which are both in `node_modules/.bin` ?

**Comment by EhsanSarshar** [comment]
yarn add -D typescript

**Comment by KarmaBlackshaw** [comment]
[This](https://stackoverflow.com/questions/44611526/how-to-fix-cannot-find-module-typescript-in-angular-4) did the trick for me.

**Comment by matinhu** [comment]
> [This](https://stackoverflow.com/questions/44611526/how-to-fix-cannot-find-module-typescript-in-angular-4) did the trick for me.
> 
> > For me just running the below command is not enough (though a valid first step):
> 
> `npm install -g typescript`
> 
> > The following command is what you need (I think deleting node_modules works too but the below command is quicker).
> 
> `npm link typescript`

i have no idea why this occurred, but the command `npm link typescript` saved my day;
thank you!

**Comment by cspotcode** [comment]
You should also be able to do a normal `npm install typescript`.

Typically, folks in the npm ecosystem will recommend installing
dependencies locally per-project, tracking version numbers in
package.json.  (that's what the above command does)

This allows projects to function in isolation without potentially being
broken by a different globally-installed version number.

`npm link typescript` creates a symlink from your local project pointing at
the globally-installed version of typescript.  So it's as if your globally
installed typescript was also installed locally.

`npm install typescript`, on the other hand, will install locally and track
the version number in your `package.json`.  This means others can quickly
`npm install` and automatically get the same local environment as you,
which simplifies on-boarding and makes everything more predictable and
obvious.

**Comment by Jood80** [comment]
I fixed mine by typing
```npm i -D @types/node typescript ts-node```

**Comment by Wandersonelias** [comment]
@Jood80 thanks also fixed my error
npm i -D @types/node typescript ts-node

**Comment by installH** [comment]
直接进入blinker-js目录，然后运行 npm install typescript 就能解决问了！

**Comment by TheGrandPB** [comment]
> I fixed mine by typing
> `npm i -D @types/node typescript ts-node`

this worked for me as well ,thank you!

**Comment by mildmojo** [comment]
Once in a while, I'm in a stripped-down environment where I'd like to run `ts-node` via `npx` [without permanently installing](https://nodejs.dev/learn/the-npx-nodejs-package-runner#installation-less-command-execution) anything (e.g. `kubectl exec -it prod-api /bin/sh`). Since `typescript` isn't a dependency, the temporary package downloaded by `npx ts-node` throws this error.

You can get around this by telling `npx` to also download a temporary copy of `typescript`:

```
npx -p typescript -p ts-node ts-node
```

(tested with npx v6.14.8)

**Comment by cspotcode** [comment]
The new npm installs peer dependencies automatically.  Does that mean the
new npx also auto-installs it?  I haven't tested this but I've been
wondering if this new auto-install behavior is good or bad for ts-node.  It
sounds like in your case it's a good thing.

**Comment by mildmojo** [comment]
@cspotcode Ah, yep, updating to npm v7.12.0, I see `npx` is deprecated in favor of a stripped-down version invoked with `npm x`. It now interactively prompts about downloading packages, suppressed with `-y`, so this gets me a REPL without errors in the new npm:

```
npm x -y ts-node
```

**Comment by cspotcode** [comment]
@mildmojo Thanks, this is good to know and I'm sure will help other people as well..  I added it to the discussion forum to make it easy to find.  #1305

**Comment by rosnk** [comment]
had "ts-node" and "typescript" installed globally. was still showing error. 

i was missing tsconfig.json file.... which you can generate by running

`tsc --init`

**Comment by aifeelit** [comment]
npm i typescript
works always the best
