### ISSUE TITLE
support -r esm preferably as tsconfig property

### ISSUE THREAD

**Issue by AllNamesRTaken** [TypeStrong/ts-node#709]
Using node this works as stated [here](https://github.com/TypeStrong/ts-node#programmatic)
`node -r esm -r ts-node src\randomWord.ts`
where 
1. ts-config is set to module: "es2015" 
2. randomWord.ts is importing a library that is es6

but this do not work ( as esm has to be loaded before ts-node ).

Could the ts-node cli not be aware of the ts-config module setting and use esm out of the box?

**Comment by blakeembrey** [comment]
@AllNamesRTaken I'm not sure I quite understand the issue or request. I'll try and address the different points:

* It should be `-r ts-node/register`
* How does it "not work"? It is loaded before `ts-node` in your above example
* No, ESM is a third-party dependency and node.js supports ESM natively in some versions without need of a dependency - this would not work properly if this library enforced `esm` onto people (plus it's very easy to include yourself)
