### ISSUE TITLE
Type declaration merging doesn't work

### ISSUE THREAD

**Issue by vladrmnv** [TypeStrong/ts-node#715]
I've tried to extend the standard Express Request interface, VSCode is picking up the declaration, but when I run `ts-node index.ts` I get :
```
/Users/vladr/.nvm/versions/node/v10.6.0/lib/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts(6,9): error TS2339: Property 'addedProperty' does not exist on type 'Request'.
index.ts(7,21): error TS2339: Property 'addedProperty' does not exist on type 'Request'.
```

However running `tsc` works fine. Also this is only a problem with ts-node@7, if I add `TS_NODE_FILES=true` it works as expected.

Here is a test repo to reporoduce the error:
https://github.com/vladrmnv/ts-node-broken-declaration-merging

**Comment by blakeembrey** [comment]
Thanks for the detailed report. This is actually expected. See https://github.com/TypeStrong/ts-node#help-my-types-are-missing. Specifically, you're using `typeRoots` for a non-global definition, you should either write it as a global or use `paths`.

**Comment by john-kurkowski** [comment]
How to make it global? [The linked TypeScript documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html) doesn't mention how. Googling for "typescript global declaration" turns up [this example](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html). It's unclear what in all that file's names and comments does the trick. @vladrmnv did you figure it out?

**Comment by john-kurkowski** [comment]
How to make it global? [The README's linked TypeScript documentation](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types) doesn't mention how. Googling for "typescript global declaration" turns up [this example](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-modifying-module-d-ts.html). It's unclear what in all that file's names and comments does the trick. @vladrmnv did you figure it out?

**Comment by blakeembrey** [comment]
@john-kurkowski That's a great point, feel free to make a PR updating the documentation around this. I do feel it's confusing from TypeScript's perspective and lacks some good documentation. The difference is around how you define it. Once you add `export` at the top-level, it turns into a "module". Same rules as TypeScript around regular `.ts` files.

Module:

```ts
export const bar: string
```

Global:

```ts
declare module "module" {
  export const bar: string
}
```

In general, using a global is a hack and may conflict but is handing for quick fixes. Using `paths` is a better long-term solution but requires more work usually to write it out correctly.

**Comment by john-kurkowski** [comment]
`paths` is documented in the section of the README he linked to. See [these lines](https://github.com/TypeStrong/ts-node/blame/9d15a728653f2c0c6eff00d6628947dd5d956e01/README.md#L178-L189).

**Comment by john-kurkowski** [comment]
@vladrmnv `paths` is documented in the section of the README he linked to. See [these lines](https://github.com/TypeStrong/ts-node/blame/9d15a728653f2c0c6eff00d6628947dd5d956e01/README.md#L178-L189).

**Comment by vladrmnv** [comment]
@john-kurkowski yep, tried that, bug how would I merge my custom definition with the existing definitions? Such as in my `express` example?

**Comment by tbinna** [comment]
@vladrmnv  @john-kurkowski did anyone of you figured this out and could post a sample of what needs to be changed? I still don't get it. How can I add a prop to the `express` Request type declaration and have declaration merging working? I only get it to either pick up the default express declarations or my custom declaration but I don't get it to merge them.

**Comment by anishpateluk** [comment]
I'm also having the same issue, with declaration merging for koa types though. Strange thing is that this works when use ts-node inside a docker image but not when running locally on my mac. Some global typescript issue maybe?

**Comment by saoudrizwan** [comment]
Thanks to [this comment](https://github.com/TypeStrong/ts-node/issues/745#issuecomment-447605203) by @blakeembrey, I got my declaration merges working! All you need to do is put `"./typings"` before `"./node_modules/@types"`. 

```javascript
"typeRoots": ["./typings", "./node_modules/@types"]
```

**Comment by antonovicha** [comment]
Here is a working example for those who still struggling (like I was for past few hours):

`@types/express/index.d.ts`: (MUST be \<module-name\>/index.d.ts)
```typescript
declare namespace Express { // MUST be namespace, and not declare module "Express" { 
  export interface Request {
    Bla: string;
  }
}
```

`tsconfig.json`:
```typescript
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es2016",
    "typeRoots" : [
      "@types", // custom merged types MUST be first in a list
      "node_modules/@types",
    ]
  }
}
```

If you are using "paths" in `tsconfig.json` you also MUST provide library mapping like that:
```
    "baseUrl": ".",
    "paths": {
      ...
      "express": ["@types/*"]
    }
```

Afterwards I was able to run `tsc -p .`, `ts-node index.ts` and `ts-node-dev index.ts` successfully.

**Comment by antonovicha** [comment]
Extra information. TypeScript guys favor `baseUrl` + `paths` over `typeRoots`. The later is supposed to be used for migration. See https://github.com/microsoft/TypeScript/issues/22217#issuecomment-370019383.

**Comment by iriekun** [comment]
@antonovicha this is awesome! you have really saved my day!!! thanks a lot

**Comment by mi-mazouz** [comment]
can't make it work for process.env

my @types/node/process.d.ts
```
declare namespace NodeJS {
  export interface ProcessEnv {
     TOTO: string;
  }
}
```

my tsconfig.json
```

{
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "es6",
    "skipLibCheck": true,
    "strict": true,
    "noImplicitAny": true,
    "allowJs": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "resolveJsonModule": true,
    "outDir": "build",
    "baseUrl": ".",
    "rootDir": "src",
    "experimentalDecorators": true,
    "paths": {
      "node": ["/src/v1/@types/node/*"]
    }
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

I'm getting "No overload matches this call." error

**Comment by jivan99** [comment]
@antonovicha 
You really saved my day. Thanks a lot.

**Comment by yusunglee2074** [comment]
ts-node src/index.ts

All of the above doesn't work with me.
IDE said there are no errors.
But when I run scripts can't find the merged type.

https://github.com/TypeStrong/ts-node/issues/745#issuecomment-465027695
The above link was my candy.

**Comment by russell0430** [comment]
> Here is a working example for those who still struggling (like I was for past few hours):
> 
> `@types/express/index.d.ts`: (MUST be <module-name>/index.d.ts)
> 
> ```ts
> declare namespace Express { // MUST be namespace, and not declare module "Express" { 
>   export interface Request {
>     Bla: string;
>   }
> }
> ```
> 
> `tsconfig.json`:
> 
> ```ts
> {
>   "compilerOptions": {
>     "module": "commonjs",
>     "target": "es2016",
>     "typeRoots" : [
>       "@types", // custom merged types MUST be first in a list
>       "node_modules/@types",
>     ]
>   }
> }
> ```
> 
> If you are using "paths" in `tsconfig.json` you also MUST provide library mapping like that:
> 
> ```
>     "baseUrl": ".",
>     "paths": {
>       ...
>       "express": ["@types/*"]
>     }
> ```
> 
> Afterwards I was able to run `tsc -p .`, `ts-node index.ts` and `ts-node-dev index.ts` successfully.

this does work! Thanks a lot !
