### ISSUE TITLE
Use with Node.js REPL module

### ISSUE THREAD

**Issue by mponizil** [TypeStrong/ts-node#717]
I'm using the [Node.js REPL module](https://nodejs.org/api/repl.html) to run a script that drops me into a REPL at the end. But once I'm dropped in, the REPL expects JS instead of Typescript.

It seems like this should be solvable using a [custom evaluation function](https://nodejs.org/api/repl.html#repl_custom_evaluation_functions):

```
repl.start({
  eval: (cmd, context, filename, callback) => {
    callback(null, compileTS(cmd, context, filename))
  }
})
```

Though I couldn't figure out what I might be able to use for `compileTS()`. Ideally it runs with the same settings as the `ts-node` command that initiated the process, so it doesn't seem as simple as `require('typescript').transpileModule(...)` or something. Any ideas?

Thank you!

**Comment by blakeembrey** [comment]
@mponizil May be relevant to exposing something like https://github.com/TypeStrong/ts-node/issues/711#issuecomment-433104488. That way you can import the current `ts-node` compile instance and use that?

**Comment by mponizil** [comment]
@blakeembrey that sounds promising. I don't have any familiarity with `ts-node` internals, but after a quick scan (I'm guessing we'd want to expose [`service`](https://github.com/TypeStrong/ts-node/blob/master/src/bin.ts#L106)?), I don't quite see how the source would be able to access it. Is there some global scope you're thinking it could be attached to?

Happy to take a try at a PR if I can wrap my head around what needs to be done :)

**Comment by blakeembrey** [comment]
Yep, something like that. It may be via a require initially, something specific to import the “global” instance before we start adding to the global. I’ll look at doing a PR for this today and get it out in 8.0.

**Comment by blakeembrey** [comment]
This was fixed with https://github.com/TypeStrong/ts-node/releases/tag/v8.5.0 by exposing both `create` and global `symbol` for usage with `compile`.
