### ISSUE TITLE
The part of readme about gulp makes no sense

### ISSUE THREAD

**Issue by TokugawaTakesi** [TypeStrong/ts-node#727]
Thank your for the providing the TypeScript support for NodeJS.

Unfortunately, I did not understand how to to work with gulpfile from below explanation in readme:

![image](https://user-images.githubusercontent.com/41653501/48127788-ebf6f600-e2c7-11e8-97b7-dbedafe3f05f.png)

I already have the `gulpfile.ts` and just want to run it. What should I do? Please explain it in the readme.
(You can use below example when update the readme).

```
import {Gulpclass, Task} from "gulpfile.ts/Annotations";
import * as gulp from "gulp";

@Gulpclass()
export class Gulpfile {

  @Task('default')
  defaultTask(callback: Function) {
    console.log('OK');
    callback();
  }
}
```

**Comment by blakeembrey** [comment]
There’s nothing you need to do other than install it. Just run `gulp` and it will use `ts-node` automatically for TypeScript - same with Webpack and many other CLIs. What exactly is your issue?

**Comment by TokugawaTakesi** [comment]
Thank you for the answer! Do you mean that I can import 'ts-node' in gulpfile.js and use it as object with methods?

**Comment by blakeembrey** [comment]
Unfortunately you’d need to use environment variables, they can be found in the README. This is an unfortunate limitation of the “register” hook ecosystem and node “require” - there’s no built in way to pass configuration around.

**Comment by TokugawaTakesi** [comment]
Two matches for `environment variable` search results in readme.
Do you mean this example ?
`ts-node --project src/tsconfig.json hello-world.ts`

O'K, but `gulp taskname --project src/tsconfig.json` will not work, will it?

I appreciate your time, so please give me some link as hint and I'll continue the solution myself.
Thank you for the reaction on this issue!

**Comment by blakeembrey** [comment]
Info about environment variables can be found online, e.g. https://en.wikipedia.org/wiki/Environment_variable. You use it like `TS_NODE_PROJECT="src/tsconfig.json" gulp taskname`.

**Comment by TokugawaTakesi** [comment]
O'K, thank you for the conversation!
Good luck to you in the future development!
