### ISSUE TITLE
error TS1149 when "forceConsistentCasingInFilesNames" is true

### ISSUE THREAD

**Issue by ManfredLange** [TypeStrong/ts-node#728]
## Details
When trying to debug mocha tests using ts-node it fails with compile error TS1149 "Unable to compile TypeScript" and then error TS1149: File name 'c:/projects/learn/vs-code-mocha/node_modules/@types/chai/index.d.ts' differs from already included file name 'C:/projects/learn/vs-code-mocha/node_modules/@types/chai/index.d.ts' only in casing." Note the difference in casing for the drive letter.

## Steps to Reproduce

1. Create simple typescript project with one class under test and one file containing mocha tests
2. If present in tsconfig.json remove "forceConsistentCasingInFileNames"
3. Debugging tests works
4. In file tsconfig.json add "forceConsistentCasingInFileNames" and set its value to "true"
5. Debugging tests fails with compile error

## Expected behavior
TypeScript compiler option "forceConsistentCasingInFileNames" value should not break compiling TypeScript code.

Note that `npm run test` compiles and runs the tests and the tests pass.

## Environment
VS Code 1.28.2
Architecture: x64 (Windows 10)
@types/mocha: 5.2.5
mocha: 5.2.0
ts-node: 7.0.1
typescript: 3.1.6

## Key Files
Repository with complete example is available at https://github.com/ManfredLange/vs-code-mocha
### Debugger Launch Configuration
````
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Mocha Tests",
            "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
            "args":[
                "--require", "ts-node/register",
                "-u", "tdd",
                "--timeout", "999999",
                "--colors",
                "--recursive",
                "${workspaceFolder}/src/**/*.ts"
            ]
        }
    ]
}
````

### package.json
```
{
  "name": "vs-code-mocha",
  "version": "1.0.0",
  "description": "Project to learn how to enable and run mocha tests in VS Code",
  "main": "index.js",
  "scripts": {
    "compile": "tsc -p .",
    "test": "npm run compile && npm run test:micro",
    "test:micro": "mocha --require ts-node/register --exit \"./src/**/*.micro.ts\""
  },
  "author": "Manfred Lange",
  "license": "ISC",
  "devDependencies": {
    "@types/chai": "^4.1.7",
    "@types/mocha": "^5.2.5",
    "chai": "^4.2.0",
    "mocha": "^5.2.0",
    "ts-node": "^7.0.1",
    "typescript": "^3.1.6"
  }
}
```
### tsconfig.json
```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "sourceMap": true,
        "outDir": "./dist",
        "moduleResolution": "node",
        "forceConsistentCasingInFileNames": true
    },
    "exclude": [
        "dist"
    ]
}
```

**Comment by mbrowne** [comment]
Possibly related, FYI: https://github.com/Microsoft/TypeScript/issues/28769

**Comment by cspotcode** [comment]
I pulled down the reproduction, upgraded ts-node, mocha, and TypeScript, and it does not seem to reproduce anymore.  I'm guessing that if it was a bug, it has since been fixed.
