### ISSUE TITLE
Can't redefine a function

### ISSUE THREAD

**Issue by vemv** [TypeStrong/ts-node#729]
(Similar but possibly different / easier than https://github.com/TypeStrong/ts-node/issues/472)

A popular workflow in the Lisp/Clojure community is "REPL-driven development", by which you develop things at the REPL first, repeatedly (re)defining functions at a granular level, until each function is deemed correct.

Errors like `[eval].ts(17,10): error TS2393: Duplicate function implementation.` impair this workflow, and make `ts-node` less useful for such a crowd.

Is there any way to disable this behavior?

Thanks - Victor

**Comment by blakeembrey** [comment]
Unfortunately this may be tricky to do. We need to use a single file for TypeScript so it knows the names are all in scope, and TypeScript doesn’t like overriding a name like this. One easy trick is just ignore that error code - either by default in the REPL or just your own REPL. The same could be done for variables, and rewrite variables to always be mutable. Not entirely sure but let me know if ignoring the error for now is good enough, then we could intro the behaviour behind a flag.
