### ISSUE TITLE
Shebang support

### ISSUE THREAD

**Issue by nevir** [TypeStrong/ts-node#73]
Would be awesome to be able to use `ts-node` as a shebang script:

```
#!/usr/bin/env ts-node
console.log('ohai from TypeScript');
```

**Comment by blakeembrey** [comment]
@nevir Works for me, what's your issue?

**Comment by blakeembrey** [comment]
Closing as it appears to work.

**Comment by thed0ctor** [comment]
This doesn't seem to work when the file is without an extension for whatever reason. Thoughts?

**Comment by blakeembrey** [comment]
It works, but you still need the `.ts` extension. See https://github.com/TypeStrong/ts-node/issues/116.

**Comment by b1zzu** [comment]
Also if you don't want to install ts-node globally:
```
#!/usr/bin/env -S node -r "ts-node/register"
```

**Comment by ORESoftware** [comment]
without the ts extension, I assume you could do something like

```
#!/bin/bash
ts-node whatever

```

**Comment by VanTanev** [comment]
A bit more complete version of @ORESoftware's example above:
```bash
#!/usr/bin/env bash
/usr/bin/env ts-node whatever.ts "$@"

```

**Comment by troywweber7** [comment]
What's the best way to add the project flag to the shebang?

**Comment by cspotcode** [comment]
Pretty sure it's in the readme.  I'm on mobile at the moment.

**Comment by troywweber7** [comment]
Ahh. I see. I need to use ts-node-script. So in an Nx project, if I'm making a publishable lib, it creates 2-3 tsconfig files. Obviously, when it is published node would run the CLI, but for testing purposes, I was thinking it would be nice to run it with ts-node from inside the same mono-repo... It might not pick up the tsconfig.lib.json, but it sounds pick up the tsconfig.json and if that isn't good enough, I can probably just build it before using it in mono-repo.

**Comment by cspotcode** [comment]
Yeah, we also let you override some "compilerOptions" within a tsconfig's
`"ts-node": {}` object.  So you can tell the compiler to behave differently
in ts-node if needed.  I think this is in the readme too, but if you find
the readme is insufficient, feel free to file a ticket so we can improve it.

**Comment by micalevisk** [comment]
another one
- with flags
- with [`tsconfig-paths`](https://www.npmjs.com/package/tsconfig-paths)
- using `npx` (so you don't wan to install ts-node globally)
- using another `tsconfig.json` file

```ts
#!/usr/bin/env -S TS_NODE_PROJECT="src/tsconfig.json" npx ts-node --transpile-only --files -r tsconfig-paths/register

const foo: string = 'bar'
console.log(foo)
```

**Comment by cspotcode** [comment]
You can also move the `transpileOnly`, `files`, and `-r` into your `src/tsconfig.json`, which simplifies the shebang to:

```
#!/usr/bin/env -S npx ts-node -p ./src/tsconfig.json
```

**Comment by nocke** [comment]
I had luck with

`sudo ln -sf ~/.npm-global/bin/ts-node /bin/ts-node`

thereafter `#!/bin/env ts-node` works.

* as does `#!/bin/ts-node` which is closer to `#!/bin/bash`, but I would stick with the former, since is more common and others are less likely having to adapt it. 
* nb1: I am aware, that `/bin` ist just a link to `/usr/bin` probably on most linuxes, just a cosmetic choice where to link to.)
* nb2: If someone works with `ts-node` under a different account on your machine, he might encounter rights issues from this linking into a personal folder. Unless you are suffently generous with `chmod` on your `~/.npm-global`.
