### ISSUE TITLE
Can't augment a module multiple times

### ISSUE THREAD

**Issue by ericleb010** [TypeStrong/ts-node#730]
I wasn't sure whether this was a Typescript behaviour or a ts-node behaviour, so I opted to start here. Sorry in advance if there was a misunderstanding.

I have a project that makes use of a "common" repo for duplicated Typescript code across the project. I thought that as part of this exercise, I'd split out an augmentation for a third-party module (Express.js) to span between this "common" repo and the other "container" repos for modularity. But it looks like that's not possible for some reason.

```
|- tsconfig.json
|- definitions
|    |- express
|    |    |- index.d.ts
|- common
|    |- definitions
|    |    |- express
|    |    |    |- index.d.ts
|- node_modules
|    |- @types 
|    |    |- ...
|- server.ts
```

The two index.d.ts files:

```ts
import * as express from "express";

declare module "express-serve-static-core" {
	export interface Response {
		body?: any;
        }
}
```

```ts
import * as express from "express";

declare module "express-serve-static-core" {
	export interface Response {
		error?: Error;
        }
}
```

And the `tsconfig.json`:

```json
{
        "compilerOptions": {
                "typeRoots": [
			"./definitions",
			"./common/definitions",
			"./node_modules/@types"
		],
                ...
        }
}
```

What seems to happen is that the Express module is augmented by the first subdirectory passed in to `typeRoots`, and the other is completely ignored. I verified this by swapping their order.

This example works under `tsc`, so I'm wondering why multiple augmentations broke `ts-node` in my case.

**Comment by blakeembrey** [comment]
@ericleb010 I'm guessing this is because with `typeRoots`, `express` is resolved to the first one and never the second one. To get around this, you could reference the second one from the first one using `/// <reference />`. I think it probably works in TypeScript because it's enumerating all your files anyway, so it discovers the module augmentation through regular compilation.
