### ISSUE TITLE
string[] is not iterable

### ISSUE THREAD

**Issue by linxiaowu66** [TypeStrong/ts-node#733]
Hi, guys
   I am using ts-node to do unit test, related versions as following:
   ts-node: 7.0.1
   typescript: 3.1.0

  When I define this parameter as following:

```
  class Test{
  constructor(private readonly test: string[]) {}

  testMethod() {
    return ['test', ...this.test]
  }
}
```

the above code will report error:

```
TypeError: this.test is not iterable
```

can anyone check this error ? is it a bug or my fault ?

Thanks

**Comment by blakeembrey** [comment]
This sounds like a general TypeScript and node.js question and not an issue with `ts-node`. I’d like to minimise general questions here and you can direct questions like these to StackOverflow.

For reference, this is a runtime error. The variable is undefined, hence not an iterable.
