### ISSUE TITLE
Add --check option to mirror node's analogue

### ISSUE THREAD

**Issue by qfox** [TypeStrong/ts-node#741]
`node` has `--check` option that checks executability of passed arguments.
```
$ node --help | grep check
  -c, --check                syntax check script without executing
```

Would be great to mirror this functionality in `ts-node`.

Is this possible at all?

**Comment by blakeembrey** [comment]
@zxqfox It should be possible, yes. Welcome to accepting a PR. Do you know if `--check` follows `require()` though?

**Comment by cspotcode** [comment]
Is this worth doing?  What's the use-case?

I assume that if it was a high-value feature, we would have received a PR by now, given the ease with which it can be implemented using our public API.  I suspect that anyone with this use-case can instead rely on `tsc --noEmit`.

**Comment by cspotcode** [comment]
Closing because `tsc --noEmit` is the recommended way to typecheck without execution.  And the `--transpileOnly` / `--typecheck` flags might be renamed to `--check` / `--no-check` in the next major.
