### ISSUE TITLE
Can't extend express Request type

### ISSUE THREAD

**Issue by brunolm** [TypeStrong/ts-node#745]
I've tried [this][1], [this][2], etc

```ts
// ./typings/express/index.d.ts
declare namespace Express {
  export interface Request {
     token?: string
  }
}
```

Example usage:

```ts
import * as express from 'express'

(req: express.Request, res: express.Response, next: express.NextFunction) => {

  const foo = req.token

}
```

It does work if I compile directly (`tsc -p .`), it does work in Visual Code, but when I try to run with `ts-node` I always get:

>  error TS2339: Property 'token' does not exist on type 'Request'.

Any idea how can I make it work with ts-node?

Versions: `ts-node@7.0.1` `typescript@3.0.1`

  [1]: https://stackoverflow.com/a/40762463/340760
  [2]: https://stackoverflow.com/q/51086613/340760

https://stackoverflow.com/q/53765895/340760

**Comment by brunolm** [comment]
```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "noImplicitAny": false,
    "sourceMap": true,
    "outDir": "dist",
    "experimentalDecorators": true,
    "esModuleInterop": true
  },
  "exclude": ["node_modules"]
}
```

I also tried with `"typeRoots": ["./node_modules/@types", "./typings"]`

**Comment by blakeembrey** [comment]
@brunolm That wouldn't work because it'd just discover the first one, not all of them. You can always use the `/// <reference />` directive to resolve the one you specifically want to extend (and put your `typeRoots` first, otherwise you're just resolving `@types` anyway - it may even work by just switching the order of `typeRoots` above and no need for `reference` since one is a module and the other definition is global).

**Comment by 3mard** [comment]
As this is confusing a lot of people to get right, I'd suggest setting up a working example in the docs

**Comment by brunolm** [comment]
I don't fully understand why that's required now. I can confirm that this worked before:

versions
```
"typescript": "2.3.4",
"ts-node": "3.0.4",
```

tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es6",
    "noImplicitAny": false,
    "sourceMap": true
  }
}
```

typings/foo.d.ts
```ts
declare module Express {
  export interface Request {
    knex: any;
    config: any;
    client: { id: number; name: string; };
  }
}
```

**Comment by blakeembrey** [comment]
Please see the README and CHANGELOG, and possibly search past issues to find why it was changed.

**Comment by blakeembrey** [comment]
There is also an example in the README for adding custom types and modules. If you’d like to expand upon it, please feel free to submit a PR!

**Comment by blakeembrey** [comment]
Just checked and we should invert the resolution order of types so it works as expected here.

**Comment by henrikra** [comment]
With `--files` in `ts-node` command local declaration files are recognized. Example command: `ts-node --files src/index.ts`

Can you guys @3mard @blakeembrey tell WHY this works? I would like understand more :)

**Comment by brunolm** [comment]
I gave up and started to do this:

```ts
req['token'] = 'foo'
```

And then casting to something when needed.

**Comment by 3mard** [comment]
@henrikra I think this is a design decision that was made to optimize ts-node (why include .d.ts files that your app are not using anyway ?) 

https://github.com/TypeStrong/ts-node/blob/master/src/index.ts#L481

**Comment by 3mard** [comment]
@brunolm  @henrikra I created this repo example https://github.com/3mard/ts-node-example for extending express request

**Comment by saoudrizwan** [comment]
Thanks to [this comment](https://github.com/TypeStrong/ts-node/issues/745#issuecomment-447602446) by @blakeembrey, I got my declaration merges working! All you need to do is put `"./typings"` before `"./node_modules/@types"`. 

```javascript
"typeRoots": ["./typings", "./node_modules/@types"]
```

**Comment by nosuchip** [comment]
For those who came here from Google and attempting to extend Express request with kinda `class`, not elementary types (like in great example by @3mard  [here](https://github.com/TypeStrong/ts-node/issues/745#issuecomment-465174217)) here is like to Stackoverflow post with solution: https://stackoverflow.com/a/51114250/291372

In short:
- it will not work (due import module treated as "local"):
```
import { Session } from '../../session';

declare namespace Express {
  interface Request {
    session: string;
  }
}
```
- it will work (module treated as "ambient" that extends existing global module):
```
declare namespace Express {
  interface Request {
    session: import('../../session').Session;
  }
}
```

**Comment by vschoener** [comment]
@saoudrizwan Thanks it works :)

**Comment by marcosfede** [comment]
This worked for me:
- create express.d.ts file in typings folder with contents
```typescript
declare module 'express-serve-static-core' {
  interface Request {
    foo?: string
  }
}
```
make sure you don't have any unimported types in the .d.ts folder, it will fail silently

**Comment by brunolm** [comment]
@marcosfede your code makes everything be an `any`

![image](https://user-images.githubusercontent.com/706078/70711872-429be400-1cc1-11ea-8925-58bb3030bfaf.png)

If I delete your file the types work again.

**Comment by itsgracian** [comment]
> Thanks to [this comment](https://github.com/TypeStrong/ts-node/issues/745#issuecomment-447602446) by @blakeembrey, I got my declaration merges working! All you need to do is put `"./typings"` before `"./node_modules/@types"`.
> 
> ```js
> "typeRoots": ["./typings", "./node_modules/@types"]
> ```

this will not work when you add jest in your code.

**Comment by marcellsimon** [comment]
> > Thanks to [this comment](https://github.com/TypeStrong/ts-node/issues/745#issuecomment-447602446) by @blakeembrey, I got my declaration merges working! All you need to do is put `"./typings"` before `"./node_modules/@types"`.
> > ```js
> > "typeRoots": ["./typings", "./node_modules/@types"]
> > ```
> 
> Still not working
> ![Screen Shot 2020-01-17 at 23 24 41](https://user-images.githubusercontent.com/27460888/72647242-be541500-3980-11ea-8b82-5f0285c8925e.png)
> 
> I solved this issues like this
> `(req as any).something = object;`
> it works for me

Same. I can't make it work. Neither solution helps. Yours is an ugly hack but works for sure.

**Comment by itsgracian** [comment]
> > > Thanks to [this comment](https://github.com/TypeStrong/ts-node/issues/745#issuecomment-447602446) by @blakeembrey, I got my declaration merges working! All you need to do is put `"./typings"` before `"./node_modules/@types"`.
> > > ```js
> > > "typeRoots": ["./typings", "./node_modules/@types"]
> > > ```
> > 
> > 
> > Still not working
> > ![Screen Shot 2020-01-17 at 23 24 41](https://user-images.githubusercontent.com/27460888/72647242-be541500-3980-11ea-8b82-5f0285c8925e.png)
> > I solved this issues like this
> > `(req as any).something = object;`
> > it works for me
> 
> Same. I can't make it work. Neither solution helps. Yours is an ugly hack but works for sure.
> 
> My problem is that VSCode recognizes it, and all is green. But when I try to run it with ts-node, it gives the error.

or you can add your type. for example
`interface IUser{
username: string;
email: string;
address: string[];
}`

> const userInfo = (req as IUser).user

**Comment by HarishAnkolekar24** [comment]
The following worked for me:

// project-root/src/types/express/index.d.ts
```
declare global {
    namespace Express {
        interface Request {
            token?: string
        }
    }
}

```
// project-root/tsconfig.json
```
{
	...
	"files": ["./src/types"]
}

```

And then run 'ts-node --files ./src/server.ts'.
As ts-node does not use files because of slows startup time, we need to tell it explicitly. Hence '--files' is necessary here.

**Comment by brunolm** [comment]
VSCode gives me:

> Augmentations for the global scope can only be directly nested in external modules or ambient module declarations.ts(2669)

**Comment by HarishAnkolekar24** [comment]
You need to import or export something to indicate that the file is a module.
If you are not importing anything then simply add
```typescript
export {};
```
in that file, then the error should be gone.

**Comment by shane-js** [comment]
To help anyways who is just looking for something else to try here is what worked for me when trying to extend ExpressJS' Request. I had to have tried more than a dozen things before getting this to work:

- Flip the order of what everyone is recommending in the "typeRoots" of your tsconfig.json (and don't forget to drop the src pathing if you have a rootDir setting in tsconfig such as "./src"). Example:
```javascript 
"typeRoots": [
      "./node_modules/@types",
      "./your-custom-types-dir"
]
```

- Example of custom extension ('./your-custom-types-dir/express/index.d.ts"). I had to use inline import and default exports to use classes as a type in my experience so that is shown too:
```javascript 
declare global {
  namespace Express {
    interface Request {
      customBasicProperty: string,
      customClassProperty: import("../path/to/CustomClass").default;
    }
  }
}
```


- Update your nodemon.json file to add the "--files" command to ts-node, example:
```javascript 
{
  "restartable": "rs",
  "ignore": [".git", "node_modules/**/node_modules"],
  "verbose": true,
  "exec": "ts-node --files",
  "watch": ["src/"],
  "env": {
    "NODE_ENV": "development"
  },
  "ext": "js,json,ts"
}
```

**Comment by joshuanwafor** [comment]
> The following worked for me:
> 
> ```ts
> // project-root/src/types/express/index.d.ts
> declare global {
>     namespace Express {
>         interface Request {
>             token?: string
>         }
>     }
> }
> ```
> 
> And then run
> 
> > ts-node --files ./src/server.ts
> 
> As ts-node does not use files because of slows startup time, we need to tell it explicitly. Hence '--_files_' is necessary here.

Worked for me. Thank you so much

**Comment by joaoromeira** [comment]
Works for me... I add "--files" flag in the run command "ts-node --files index.ts", and create express.d.ts with the follow content.

declare namespace Express {
  export interface Request {
    user_id: number;
  }
}

**Comment by galletafromjell666** [comment]
An alternative to using the `--files` tag with ts-node could be adding the ts-node property to the `tsconfig.json`:

_tsconfig.json_
```json
{
  "ts-node": {
    "files": true
  },
  "compilerOptions":{
    // ...
  }
}
```

**Comment by pufex** [comment]
@galletafromjell666 thanks bro! Worked for me :D

**Comment by scandela** [comment]
> Thanks to [this comment](https://github.com/TypeStrong/ts-node/issues/745#issuecomment-447602446) by @blakeembrey, I got my declaration merges working! All you need to do is put `"./typings"` before `"./node_modules/@types"`.
> 
> ```js
> "typeRoots": ["./typings", "./node_modules/@types"]
> ```

That also worked for me, thanks!

**Comment by LexxLuey** [comment]
> An alternative to using the `--files` tag with ts-node could be adding the ts-node property to the `tsconfig.json`:
> 
> _tsconfig.json_
> 
> ```json
> {
>   "ts-node": {
>     "files": true
>   },
>   "compilerOptions":{
>     // ...
>   }
> }
> ```

You are the man. To God honest I tried every single solution until I at last tried yours and it worked. Saved me from pulling all my hair. If I may, why did the other solutions not work?

**Comment by Hussein-Ali-6** [comment]
> To help anyone who is just looking for something else to try here is what worked for me when trying to extend ExpressJS' Request. I had to have tried more than a dozen things before getting this to work:
> 
> * Flip the order of what everyone is recommending in the "typeRoots" of your tsconfig.json (and don't forget to drop the src pathing if you have a rootDir setting in tsconfig such as "./src"). Example:
> 
> ```js
> "typeRoots": [
>       "./node_modules/@types",
>       "./your-custom-types-dir"
> ]
> ```
> 
> * Example of custom extension ('./your-custom-types-dir/express/index.d.ts"). I had to use inline import and default exports to use classes as a type in my experience so that is shown too:
> 
> ```js
> declare global {
>   namespace Express {
>     interface Request {
>       customBasicProperty: string,
>       customClassProperty: import("../path/to/CustomClass").default;
>     }
>   }
> }
> ```
> 
> * Update your nodemon.json file to add the "--files" command to ts-node, example:
> 
> ```js
> {
>   "restartable": "rs",
>   "ignore": [".git", "node_modules/**/node_modules"],
>   "verbose": true,
>   "exec": "ts-node --files",
>   "watch": ["src/"],
>   "env": {
>     "NODE_ENV": "development"
>   },
>   "ext": "js,json,ts"
> }
> ```

Saved my life, it works perfectly for me, Thank you

**Comment by ramses44-17** [comment]
> An alternative to using the `--files` tag with ts-node could be adding the ts-node property to the `tsconfig.json`:
> 
> _tsconfig.json_
> 
> {
>   "ts-node": {
>     "files": true
>   },
>   "compilerOptions":{
>     // ...
>   }
> }

it work for me too
