### ISSUE TITLE
TS2321 when using ts-node

### ISSUE THREAD

**Issue by Diluka** [TypeStrong/ts-node#753]
typescript version: `3.2.2`
ts-node version: `7.0.1`

TSError: ⨯ Unable to compile TypeScript:
`error TS2321: Excessive stack depth comparing types 'any' and 'FilteredModelAttributes<T>'.`

using lib `sequelize-typescript`

run `tsc` with no error but `ts-node .` fails

**Comment by blakeembrey** [comment]
@Diluka Do you have a way to reproduce this? I haven't seen it before.

**Comment by Diluka** [comment]
Sorry, I can not now. I forget how to produce this error.

**Comment by Yann-P** [comment]
This just happened to me using gulp and gulp-typescript. I solved it by using tsc (node_modules/typescript/bin/tsc) to compile.
