### ISSUE TITLE
When using date.now() it's always fetching the time on which server started 

### ISSUE THREAD

**Issue by ayushpratap2494** [TypeStrong/ts-node#756]
The issue is that I am always getting the time on which server started whenever I call Date.now() 

![dateissue](https://user-images.githubusercontent.com/32447637/51163817-f97cbd80-18c0-11e9-9eac-8c656186fd1b.png)
![dtissue](https://user-images.githubusercontent.com/32447637/51163818-f97cbd80-18c0-11e9-887f-cc4545bdfdf7.png)

**Comment by blakeembrey** [comment]
@ayushpratap2494 This isn't an issue with `ts-node`. You're calling `Date.now()` and that returns a static number.

**Comment by blakeembrey** [comment]
FWIW, `Date.now()` and `new Date().getTime()` return the same things and you should have a type error on your code using a `number` in `Date` position with `date.dateParse`.

**Comment by ayushpratap2494** [comment]
Thanku so much It was an error of mongoose thanks for resolving
