### ISSUE TITLE
Error: Cannot find module 'arg'

### ISSUE THREAD

**Issue by fwh1990** [TypeStrong/ts-node#762]
Error happened after upgrade to version 8.0.0

The package 'arg' is in your devDependencies now.

**Comment by blakeembrey** [comment]
Thanks for the catch, fixed with https://github.com/TypeStrong/ts-node/commit/9f2eee90c08bd6013e338a97f5ca167bd39f5881 and publishing now. Keep getting caught by the fact that once it's in `dev` it doesn't move into normal dependencies automatically when you `npm install -S`.

**Comment by blakeembrey** [comment]
Fixed with 8.0.1.
