### ISSUE TITLE
`--compilerOptions` became unsupported?

### ISSUE THREAD

**Issue by ipanasenko** [TypeStrong/ts-node#763]
Hi! I've updated to v8, and my scripts don't run: `Error: Unknown or unexpected option: --compilerOptions`

I couldn't find anything in release notes about this change, any help/info is appreciated.

Thanks!

**Comment by blakeembrey** [comment]
Reflected the change in release notes. Previously both `--compiler-options` and `--compilerOptions` was supported, now it's only `--compiler-options`.
