### ISSUE TITLE
Import imports .json file over .ts file

### ISSUE THREAD

**Issue by mauro0x52** [TypeStrong/ts-node#769]
Not a big issue, but funny.

If I have two files, `config.json` and `config.ts`, and an import like this:
`import config from './config'`
it imports the `config.json` instead of `config.ts`.

This only happened with ts-node. I tried setting up `resolveJsonModule = false` in `tsconfig.json`, but still imports `config.json`. 

With tsc, it imports `config.ts` normally, unless I explicitly import using `import config from './config.json'`.

**Comment by blakeembrey** [comment]
This is just how `ts-node` works, see https://github.com/TypeStrong/ts-node#how-it-works for a little more info. Someone tried to add support for a hack around this in https://github.com/TypeStrong/ts-node/pull/649 which we could land. Closing in favour of https://github.com/TypeStrong/ts-node/issues/529.
