### ISSUE TITLE
[meta] propose new TypeStrong project?

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#770]
I'm sorry for the issue spam; I wasn't sure where else to ask this.

Is there a place to propose a new TypeStrong project?  Somewhere I can ask the organization?

I've been playing around with exposing some new `tsc`-like capabilities: command-line experiences with features that `tsc` doesn't have.  For example, `tsc`-style compilation but skipping the typechecker.  Or running `tsc` but emitting diagnostics as JSON.  Or computing and applying all quick-fixes matching a grep pattern.  I'm imagining a drop-in replacement for `tsc` that supports extra `--flags` and modes.  This sounds similar to what the TypeScript team talked about on their 2019 roadmap.

I just created [tsc-to](https://www.npmjs.com/package/tsc-to) which is like `tsc` but with `--transpile-only` turned on.  But ideally this isn't a one-off project, and there's a go-to community-supported `tsc` alternative that supports a bunch of command-line flags.

**Comment by blakeembrey** [comment]
@cspotcode We do have https://github.com/TypeStrong/discussions, but this is fine 😄 I think this could make sense, let me look more into it but I think you'd be welcome to move it into the org and I can add you as a member. How do you see it being used typically?

**Comment by cspotcode** [comment]
Doh, sorry I missed that!  I'll move this question to "discussions" with an answer to your question, and close this issue.
