### ISSUE TITLE
Adding environment variable TS_NODE=true

### ISSUE THREAD

**Issue by thetutlage** [TypeStrong/ts-node#771]
## Proposal
I would like to propose, if we can add `TS_NODE` environment variable, every time, the process is started using `ts-node`.

## Why it's needed?
Let's say I am building a script, which behaves differently based upon the runtime (Typescript or Javascript), using `TS_NODE` I can make the decision. For example: 

- internally loading file with extension `.ts` or `.js` 
- Differently handling the exports of Typescript and regular Javascript
- and so on.

**Comment by blakeembrey** [comment]
What is the definition of "started using `ts-node`". Is it using the register hook, calling register in code or explicitly using `ts-node` via the CLI?

**Comment by thetutlage** [comment]
I believe both. The idea is to drop an artifact, which can help scripts/modules at runtime distinguish the existence of `ts-node`

**Comment by blakeembrey** [comment]
How would you feel about something added to `process` instead? E.g. `process.ts` or `process[TS_NODE_SYMBOL]`?

**Comment by blakeembrey** [comment]
@thetutlage Do you have any issues with it being a symbol vs a property? I'd be a lot more comfortable starting with a symbol to test this out, since it won't affect anyone else or runtimes.

**Comment by thetutlage** [comment]
Yeah, I am okay with the symbol, until it is accessible using `Symbol.for()`

**Comment by thetutlage** [comment]
@blakeembrey Did you get chance to look into it? I am happy raising a PR for same :)

**Comment by blakeembrey** [comment]
@thetutlage I did not, happy to accept a PR!

**Comment by blakeembrey** [comment]
Isn't `Symbol.for()` global though? Shouldn't we create a `Symbol()` regularly?

**Comment by blakeembrey** [comment]
Closed with https://github.com/TypeStrong/ts-node/commit/b681e2457c7acc28fcbba638a8dac6ecf27846e3.
