### ISSUE TITLE
Question: does ts-node use my version of typescript?

### ISSUE THREAD

**Issue by petermorlion** [TypeStrong/ts-node#772]
I'm sorry if this is documented somewhere, but I can't find it.

If I create a project with typescript version 2, and then use ts-node. Will ts-node use my local version of typescript, or will it use its own version 3?

I ask because we're using ts-node to run tests, but want to be sure that we deploy the same code that we used under test. If our code under test is compiled by ts-node using Typescript 3, but we deploy code that was compiled using Typescript 2, then there is a difference.

**Comment by blakeembrey** [comment]
Yes. This module does not come with TypeScript.
