### ISSUE TITLE
Wrong link path to error in vs code debug console

### ISSUE THREAD

**Issue by Niyarlatotep** [TypeStrong/ts-node#773]
I have following launch settings:
```
{
    "type": "node",
    "request": "launch",
    "name": "TestTS",
    "runtimeArgs": [
        "-r",
        "ts-node/register/transpile-only"
    ],
    "args": [
        "${workspaceFolder}/localTest.ts"
    ],
    "env": {"TS_NODE_FILES": "true"}
}
```

and localTest.ts contains next code with error:
```
function foo(obj: any){
    obj.test();
}
let myobj = {};
foo(myobj);
```
when i get output in debug console there is a link to the line with problem, but it references to source-map-support.js:441 (line 441) in "\node_modules\ts-node\node_modules\source-map-support\source-map-support.js". I expected it would references to localTest.ts:2:9. It works well in webstorm IDE.

VS code debug console output:
![vs-code](https://user-images.githubusercontent.com/18496247/52106366-8f278500-2603-11e9-8409-48933c9f3dfb.png)
WebStorm debug console output:
![webstorm](https://user-images.githubusercontent.com/18496247/52106533-373d4e00-2604-11e9-87b3-4fd6471d4ac7.png)

**Comment by blakeembrey** [comment]
What is the stack trace you're seeing? What do you mean by it works well in webstorm IDE - what works well? Using `ts-node` in an IDE?

**Comment by Niyarlatotep** [comment]
@blakeembrey Thanks for the quick response! Sorry for bad explanation. I've added screenshots of VS code output and WebStorm output, as you can see they have different link to the problem file's line (to the mistake's line). I pointed at it by red arrow. I don't know if it's VS Code's problems or not cause if i run simple js file with error, it points correctly at mistake's place.

**Comment by blakeembrey** [comment]
@Niyarlatotep There seems to be a different opinion between WebStorm and VS Code in the stack trace, is that working fine? As for the `source-map-support.js` output, I can only assume that's irrelevant and related to how the source maps are built into the error message on the fly. The commands look identical, the only other thing I can think of is that these are running different node.js versions.

**Comment by Niyarlatotep** [comment]
@blakeembrey ts-node works fine, thanks for such a greate tool, it's very useful. It only points at wrong error line in VS code, shows wrong stack trace. Node.js version is the same for both IDEs. By the way i chacked the same code by compling it from ts to js using tsc compiler with source map generating and when i run it shows correct stack trace so i think ts-node or likely source-map-support.js generates not ordinar stack trace. Unfourtanatly i'm not good at these kind of things. Should i try to redirect this issue to source-map-supoort team?

Console output after compilation from ts into js using tsc compiler with source map generating:
```
TypeError: obj.test is not a function
localTest.ts:2
    at foo (c:\tests\test\localTest.ts:2:9)
    at Object.<anonymous> (c:\tests\test\localTest.ts:5:1)
    at Module._compile (internal/modules/cjs/loader.js:686:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```
