### ISSUE TITLE
can't find peer dependency typescript

### ISSUE THREAD

**Issue by mvolkmann** [TypeStrong/ts-node#775]
I see the error when I enter these commands:

npm i -g typescript
tsc -v # outputs Version 3.3.1
npm i -g ts-node

This outputs:
npm WARN ts-node@8.0.2 requires a peer of typescript@>=2.0 but none is installed. You must install peer dependencies yourself.

**Comment by blakeembrey** [comment]
This is pinned on the main issue page (https://github.com/TypeStrong/ts-node/issues/765) and in the README (https://github.com/TypeStrong/ts-node#installation, though this could be clarified). You must install `typescript` locally for it to work right now.
