### ISSUE TITLE
ts-node 8: "Error: Unknown or unexpected option: --xyz" on inline compiler-options

### ISSUE THREAD

**Issue by mirismaili** [TypeStrong/ts-node#784]
Thanks for good tool.

This command works with `ts-node v7.0.0`:
```
ts-node --moduleResolution node --lib es2018,dom --target es6 distribution/test.ts
```

But when I update to `ts-node v8.0.2` it breaks:

> $ ts-node --moduleResolution node --lib es2018,dom --target es6 distribution/test.ts
> ...\node_modules\arg\index.js:92
>                                                 throw err;
>                                                 ^
> 
> Error: Unknown or unexpected option: --moduleResolution
>     at arg (D:\Devel\WebstormProjects\Paradise\node_modules\arg\index.js:90:19)
>     at Object.<anonymous> (D:\Devel\WebstormProjects\Paradise\node_modules\ts-node\dist\bin.js:14:12)
>     at Module._compile (internal/modules/cjs/loader.js:689:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
>     at Module.load (internal/modules/cjs/loader.js:599:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

Same behavior for other compiler-options: `--lib` and `--target`. It always throws at first.

**How to use compiler-options inline?**

**Comment by blakeembrey** [comment]
@mirismaili That command definitely did not work in 7.0, it just didn't error. The documentation is in the README: https://github.com/TypeStrong/ts-node#cli-and-programmatic-options.
