### ISSUE TITLE
Add interactive mode

### ISSUE THREAD

**Issue by masad-frost** [TypeStrong/ts-node#785]
In `node` you can load a file then drop into the repl.
`node -i -r ./main.js`
You can also run arbitrary code
`node -i -e "console.log('ho')"`

**Comment by 3mard** [comment]
How about ` node -r ts-node/register `

**Comment by blakeembrey** [comment]
This seems like a reasonable enough addition. I think the first example may just work as is though, if you exclude `-i`.

**Comment by masad-frost** [comment]
Yeah, that works. Good enough for me :dancer:

**Comment by WillAvudim** [comment]
Confirm, simply running 
```
\`npm bin\`/ts-node -r ./tools/my_lib.ts
```
Executes my_lib and drops into the REPL.

**Comment by blakeembrey** [comment]
Closed with https://github.com/TypeStrong/ts-node/pull/894.
