### ISSUE TITLE
node -r ts-node/register not equal to ts-node for repl and eval.

### ISSUE THREAD

**Issue by Pokute** [TypeStrong/ts-node#787]
`ts-node -e 'const i:number = 1'` works all right

`node -r ts-node/register -e 'const i:number = 1'` reports `SyntaxError: Missing initializer in const declaration`. This is after setting up a new npm project with ts-node and typescript packages.

Same happens with repl instead of eval.

**Comment by blakeembrey** [comment]
This is just a limitation of `ts-node` and the node.js REPL, it's not possible to hook into the node.js REPL on startup.
