### ISSUE TITLE
npm WARN ts-node@8.0.2 requires a peer of typescript@>=2.0 but none is installed

### ISSUE THREAD

**Issue by papb** [TypeStrong/ts-node#788]
I've seen issue #775 already, which was closed as a duplicate of #765. That issue is currently closed, but looks like the problem persists, unless I am missing something obvious (for which I apologize in advance).

Steps to reproduce:

* `npm i -g typescript`
* `tsc -v` gives `3.3.3333`
* `npm i -g ts-node` gives `npm WARN ts-node@8.0.2 requires a peer of typescript@>=2.0 but none is installed`
* `ts-node` gives `Error: Cannot find module 'typescript'`

The issues mentioned above seem to suggest that `typescript` and `ts-node` should be installed locally; but the README says that `ts-node` can be installed globally.

Am I missing something? Thanks :)

**Comment by blakeembrey** [comment]
It's described in the issue you linked to: https://github.com/TypeStrong/ts-node/issues/765#issuecomment-457448247. You can install `ts-node` globally, you can not install `typescript` globally. It's was definitely a bug when released, but it's part of 8.x now and I'm not in a rush to change this.

**Comment by papb** [comment]
@blakeembrey - Fair enough, but at least this should be stated clearly somewhere. I will open a PR, please take a look :)
