### ISSUE TITLE
Import performance issure(v8.0.2)

### ISSUE THREAD

**Issue by yujiang** [TypeStrong/ts-node#790]
I write a very simple test for import 
test_import.ts
`console.time("import lib")
import {add} from "./test_importlib"
console.timeEnd("import lib")
function test2()
{
    let c = add(1,2)
    console.log(c)
}`
test_importlib.ts
`export function add(x:number,y:number){
    return x+y;
}`

in a clean envirment, import takes 10ms that's ok (when compiled use tsc, takes 1ms)
but after npm install many other package
import takes >150ms even 500ms

**Comment by yujiang** [comment]
The package.json like:
`
{
  "name": "west",
  "version": "1.0.0",
  "description": "west game server",
  "main": "index.js",
  "dependencies": {
    "colors": "^1.3.0",
    "level": "^3.0.2",
    "lodash": "^4.17.10",
    "log4js": "latest",
    "mysql2": "^1.5.3",
    "node-xlsx": "^0.14.1",
    "socket.io": "^2.2.0",
    "socket.io-client": "^2.2.0",
    "sprintf-js": "^1.1.1",
    "typescript": "^3.3.3333"
  },
  "devDependencies": {
    "@types/node-xlsx": "^0.12.0",
    "@types/leveldown": "^1.7.0",
    "@types/levelup": "0.0.30",
    "@types/mysql": "^2.15.4",
    "@types/socket.io": "^1.4.33",
    "@types/socket.io-client": "^1.4.32",
    "@types/sprintf-js": "^1.1.0"
  },
  "author": "",
  "license": "ISC"
}
`

**Comment by blakeembrey** [comment]
This is mostly discussed in https://github.com/TypeStrong/ts-node/issues/754.
