### ISSUE TITLE
Add a method for running ts-node with global typescript dependency

### ISSUE THREAD

**Issue by Eeemil** [TypeStrong/ts-node#794]
As seen in https://github.com/TypeStrong/ts-node/issues/707 , there is a demand for running ts-node with typescript as a global dependency.
As a first step, a flag could be implemented.
For my particular use-case, I just want to run `ts-node` (no flags) and get a REPL where I can test short snippets of code.

**Comment by blakeembrey** [comment]
Resolved with https://github.com/TypeStrong/ts-node/releases/tag/v8.0.3.
