### ISSUE TITLE
how to run profile with ts-node?

### ISSUE THREAD

**Issue by qianqians** [TypeStrong/ts-node#795]
i run my server code with ts-code, now i need do profile test, how to do it with ts-node?

**Comment by blakeembrey** [comment]
You can always use `node -r ts-node/register` and do anything you want in node.js, see https://github.com/TypeStrong/ts-node#programmatic.

**Comment by goktugyil** [comment]
@qianqians were you able to make this work? Blake's comment seems to be missing some crucial information

**Comment by goktugyil** [comment]
In terminal: `node -r ts-node/register --prof`

**Comment by dsaf** [comment]
@blakeembrey could you please give a full profiling example?

**Comment by blakeembrey** [comment]
@dsaf You should read the node.js docs. I don’t really do any profiling in node.js and am not an expert in all things, so I’m not able to just figure this one out for you.

**Comment by dsaf** [comment]
OK, no worries.
