### ISSUE TITLE
Question: Duplicate identifier on update to 0.6.2

### ISSUE THREAD

**Issue by d3viant0ne** [TypeStrong/ts-node#80]
When updating from 0.5.5 to 0.6.2 `npm install` throws a bunch of ...

`typings/main/ambient/async/index.d.ts (27,5): Duplicate identifier 'started'. (2300)
typings/main/ambient/async/index.d.ts (30,5): Duplicate identifier 'concurrency'. (2300)
typings/main/ambient/async/index.d.ts (35,5): Duplicate identifier 'saturated'. (2300)
`

Mind you this is a very truncated list. I haven't looked into why it's happening yet, at this point i'm curious if someone has seen it happen.

- Fresh checkout of the angular2-seed
- Update ts-node to 0.6.2 from 0.5.5
- `npm install`

Typescript v1.8.7
Typings v0.7.9

**Comment by blakeembrey** [comment]
You might need to provide links to reproduce the issue. I'm going to guess you actually have duplicate identifiers.

**Comment by d3viant0ne** [comment]
@blakeembrey - It was the same general issues as Microsoft/TypeScript#6475

In the end, I just has to tool around with the tsconfig `"exclude" :` until I got the semantics right.

**From**
`
  "exclude": [
    "node_modules",
    "typings/browser.d.ts",
    "typings/browser/**"
  ],
`

**To**
`
  "exclude": [
    "node_modules",
    "typings/browser.d.ts",
    "typings/browser"
  ],
`

Kind of an odd issue but hey, whatever works. Thanks for the quick response  :)

**Comment by blakeembrey** [comment]
Ah, yes. The `tsconfig.json` exclude shouldn't be globs. Glad you sorted it out :smile:
