### ISSUE TITLE
Type query in REPL fails when followed by a semicolon

### ISSUE THREAD

**Issue by NicoleRauch** [TypeStrong/ts-node#800]
I have encountered this weird behaviour:

```
$ ts-node --version
v8.0.3
$ ts-node
> const x = 7;
undefined
> .type x
const x: 7
> .type x;

> 
```

I.e. when I use `.type` without semicolon, it gives me the desired answer, but when I use it with semicolon, I do not get an answer.

I would prefer to get an answer in both cases because it is confusing to be forced to use this specific command in a certain way while other TypeScript statements can be executed in both ways.

**Comment by blakeembrey** [comment]
The command isn’t code though, a semicolon isn’t a value. You are welcome to submit a PR if you feel strongly though.
