### ISSUE TITLE
tsconfig.json typeRoots relative to CWD rather than tsconfig.json.

### ISSUE THREAD

**Issue by MicahZoltu** [TypeStrong/ts-node#804]
Project structure:
```
project-root/
-- node_modules/
-- scripts/
  -- typings/
    -- foo/
      -- index.d.ts
  -- main.ts
  -- tsconfig.json
```
tsconfig.json
```json
{
  "compilerOptions": {
    ...
    "typeRoots": [ "../node_modules/@types", "./typings" ],
}
```
If I run `npx ts-node scripts/main.ts` it cannot find the module `foo`.  If I instead run `cd scripts && npx ts-node main.ts` it has no problem.

Potentially related, the foo module is just some type definitions, it doesn't correspond to any actually compilable module in node_modules or elsewhere.

**Comment by MicahZoltu** [comment]
Figured out my issue (or at least a workaround).  I need to specify a project file when it isn't in the CWD.  I had assumed that ts-node would walk the directory tree up from the provided file until it found a `tsconfig.json` (in my case, it would have found it next to `main.ts`).  However, it appears this is not the case.

**Comment by blakeembrey** [comment]
This is by design, it search for a config file the same way `tsc` does.
