### ISSUE TITLE
Default Target

### ISSUE THREAD

**Issue by nahtnam** [TypeStrong/ts-node#809]
Hello,

I was wondering what the default target for `ts-node` is? I am running into a weird issue where typescript complains about how "Class constructor Route cannot be invoked without 'new'". To fix this I had to run the command like so: `ts-node -O "{ \"target\": \"es2015\" }" src/index.ts`

I have two questions about this:
1. Why do I need to provide the target as `es2015`? I assumed that is the default since when you run `tsc --init` that is what is prefilled.
2. Why do the flags need to be provided before the file name? I spent about half an hour messing around with this before I figured it out thanks to this issue: https://github.com/TypeStrong/ts-node/issues/541 Why is this not support or at least documented?

Thank you!

**Comment by blakeembrey** [comment]
1. ES5 but that sounds irrelevant to calling new.
2. That’s how node.js also works, is it confusing there? There’s an obvious difference between flags for this module and flags for the script you’re running, that’s why the script args always go after the script file name. Same with node.

**Comment by blakeembrey** [comment]
You’re welcome to submit a PR with documentation you feel is adequate.

**Comment by nahtnam** [comment]
Isn't it kind of weird for `ts-node` to default to ES5, and `tsc --init` to default to ES6? I believe the `new` issue occurs because ES5 transpiles the classes whereas ES6 natively supports them and leaves them alone. The discrepancy between the libraries I use which are transpiled to ES6 and so when I try to use them, `ts-node` tries to transpiles the classes and somehow messes them up.

Turns out it is documented in the README: "You can set options by passing them before the script path, via programmatic usage or via environment variables." Would you be opposed to a PR that added this message to the CLI help options?

**Comment by blakeembrey** [comment]
At this point it probably could and should be ES2015, this is an old library and TypeScript wasn’t always ES2015 by default either. It would just need to be in the next major version. As for docs, I’m welcome to adding whatever you think is necessary but I can’t comment on it without seeing it. It shouldn’t be too verbose as there’s already a lot of docs.
