### ISSUE TITLE
[feature request] integrate npx-style runner

### ISSUE THREAD

**Issue by uvero** [TypeStrong/ts-node#810]
What could really help me is something like _npm's npx_ integrated in ts-node. I'll explain:

One common thing I do is write _Jasmine_ tests in TypeScript.

I could, for one, compile these using tsc and run them using `npx jasmine [blah blah blah]`.

A bit tedious to do, but that's what pipelines and things like gulp are for, sure.

I could also, as I've seen advised online, use `[npx] ts-node ./node-modules/jasmine/bin/jasmine.js [blah blah blah]`.

A bit tedious to write, but still works, and also, that's what _npm scripts_ are for, sure.

But still, what is would want is something like:

`[npx] ts-node --npx jasmine [blah blah blah]`.

Is there an already-existing feature of ts-node I'm missing that does that? And if not, could that feature be added?

I plan to try to fork and do it myself and then PR if I have the time if it's not implemented yet, but I'm not going to have enough time for that soon, so if the development team can do something like that, that would be awesome.

Thanks in advance,
Yuval D.

**Comment by cspotcode** [comment]
@uvero did you ever prototype this?  How'd it go?  Did you find that the feature offered enough benefit compared to `ts-node ./node-modules/jasmine/bin/jasmine.js` to be worth the extra complexity?

**Comment by cspotcode** [comment]
In the spirit of triaging and focusing on high-value issues, I'm closing this issue.  `NODE_OPTIONS` is mentioned in our documentation and achieves pretty much the same effect.

https://typestrong.org/ts-node/docs/recipes/other
