### ISSUE TITLE
Should tsBuildInfoFile and incremental options are removed in fixConfig function?

### ISSUE THREAD

**Issue by timocov** [TypeStrong/ts-node#811]
It looks like `ts-node` removes some compiler options that doesn't work with `ts-node` in https://github.com/TypeStrong/ts-node/blob/8706c31430cc23862f2043b43fba7a3c3ca4b2c6/src/index.ts#L424-L444, right?

Setting `tsBuildInfoFile` compiler option (in my case for composite project) fail build with `Emit skipped` error. Should this option (quite possible that `incremental` should be removed too?) be removed along with other options in that function?

Related issue: #656

**Comment by whitecolor** [comment]
Wonder if `incremental` compilation can be supported by ts-node?

**Comment by blakeembrey** [comment]
@whitecolor I think that'd be really awesome, but I don't think the APIs are currently exposed.

@timocov Absolutely, feel free to make a PR.

**Comment by timocov** [comment]
@blakeembrey 👌. I just created #815 with removing these properties.

**Comment by whitecolor** [comment]
@blakeembrey the issue that tracks it
https://github.com/Microsoft/TypeScript/issues/29978
