### ISSUE TITLE
Custom typings when used with existing ones

### ISSUE THREAD

**Issue by farzadmf** [TypeStrong/ts-node#814]
Hi,

I know there are questions about custom typings, but I think my issue is different. I know how to organize my `typings` in directories etc. as mentioned in the README, and for libraries with no types, that works fine.

But, in my case, I need to *override* the typings that are already available for a module. To be more specific, I'm using `inquirer`, which already has `@types/inquirer` available, but I've created this folder structure:

```
tsconfig.json
typings
+-- inquirer
    +-- index.d.ts
```

Also, I've set up `typeRoots`:
```jsonc
"compilerOptions": {
  // ...
  "typeRoots": [
    "./node_modules/@types",
    "./typings"
  ]
}
```

And in my `index.d.ts`, I have the following:
```typescript
import * as inquirer from 'inquirer';

declare module 'inquirer' {
  interface AutoComplete<T = Answers> {
    // interface definition
  }
}
```

And I'm using it in my code:
```typescript
const myQuestion: inquirer.AutoComplete = {
  // ...
}
```

But, when I run my app (using `ts-node -r tsconfig-paths/register main.ts`), I see an error saying this:
```
error TS2694: Namespace 'inquirer' has no exported member 'AutoComplete'.
```

So, it seems that it's somehow "defaulting" to `@types/inquirer`, not seeing my "override" one

**Comment by blakeembrey** [comment]
@farzadmf TypeScript doesn't have the concept of overriding a type. Are you sure you want to override and not augment it? If you do want to augment it, you should probably call the directory something different, e.g. `inquirer-autocomplete`. Also, did you specify the type locations in your `tsconfig.json`.

**Comment by farzadmf** [comment]
Thank you @blakeembrey for your amazingly fast response! :)

Sorry, my bad, I chose the wrong word, I actually meant augmenting. And, as you suggested, renaming it to something different seems to resolve the issue.

So, considering that Typescript seems to be fine with my module having the same name, is there a way to also make it work under `ts-node`?

**Comment by blakeembrey** [comment]
@farzadmf Did you specify the type paths in your `tsconfig.json`?

**Comment by farzadmf** [comment]
@blakeembrey Yes, as I mentioned in my question, I have set `typeRoots`:

```json
"typeRoots": [
  "./node_modules/@types",
  "./typings"
]
```

**Comment by blakeembrey** [comment]
@farzadmf I'm sorry, that wasn't there when I first reviewed the issue (also emails don't update when you edit, that's where I usually read first). Are you saying it doesn't work even after the rename?

**Comment by farzadmf** [comment]
@blakeembrey No, actually the rename is fine (thank you for that). I was just wondering if I'm able to *augment* the definition. Because, in theory, if I augment, I should be able to import my "agumented"(added) interface from `inquirer` and not `inquirer-autocomplete`, right?

**Comment by blakeembrey** [comment]
@farzadmf You already did augment the definition and it's correct/works. You can't rename it the same because TypeScript would resolve the first one (it's reading your `typeRoots` configuration). It works with `tsc` probably because you have that file picked up somewhere in your `include` or another wildcard. `ts-node` doesn't use the entire project by default, only the entry file, so does not magically find the file like `tsc`.

**Comment by farzadmf** [comment]
Thank you @blakeembrey for your help
