### ISSUE TITLE
-r ts-node/register and allowSyntheticDefaultImports = true?

### ISSUE THREAD

**Issue by MarcWeber** [TypeStrong/ts-node#816]
Readme says for --inspect node -r should be used.
How pass options like allowSyntheticDefaultImports to the node -r version ?

**Comment by blakeembrey** [comment]
Use environment flags, mentioned in the README.

**Comment by MarcWeber** [comment]
I tried ```export TS_NODE_COMPILER_OPTIONS='{ "allowSyntheticDefaultImports": true  }'``` but with atob and deep-equal I still get failures such as:
```atob_1.default is not a function```
The json is read by node, because causing JSON syntax errors makes it fail and talk about the syntax error. Am I still missing s.th ?

**Comment by blakeembrey** [comment]
Read https://www.typescriptlang.org/docs/handbook/compiler-options.html and see:

> Allow default imports from modules with no default export. This does not affect code emit, just typechecking.
