### ISSUE TITLE
How to run universal code importing .css files?

### ISSUE THREAD

**Issue by MarcWeber** [TypeStrong/ts-node#827]
If you have a file index.ts
```
import "foo.css"

```
Many bundlers will cause the .css files to be loaded. There are some universal libraries out there.
How to make ts-node ignore it without using the bundler ? AFAIK node -r .. is one of the best ways to debug typescript which is why I'm asking. You could map them all to an empty dummy module or so. I didn't find a configuration. If there is a solution it would be nice if it could be added to the README. I saw that webpack has some kind of special config which can be passed.

**Comment by blakeembrey** [comment]
> You could map them all to an empty dummy module or so.

This one. You're welcome to add it to the README, e.g. something like https://github.com/TypeStrong/ts-node/issues/576#issuecomment-384359471. I'm sure there's also npm packages available for this also, but it won't be built into this package. This package also isn't related to Webpack in any way.
