### ISSUE TITLE
Unable to specify other options than transpile-only and type-check when running node cli and registering ts-node

### ISSUE THREAD

**Issue by Timppe** [TypeStrong/ts-node#830]
We have a case where we need to use some extra node options and therefore we run ts-node like:
`node --max_old_space_size=8192 -r ts-node/register ./server.ts`

However, is there supposed to be a way how to specify options for ts-node, other than transpile-only and type-check which can only be done because there are dedicated files for them in the register folder?

I created my own files.js file in a similar manner and ran 
`node --max_old_space_size=8192 -r ts-node/register/files ./server.ts`
and got what I wanted. Is this the only way? Doesn't seem so flexible and extensible to simply add files for having the possibility to add options to ts-node.

**Comment by blakeembrey** [comment]
I’m most definitely aware that this is limiting, not just to you. Unfortunately there’s no other way possible, otherwise it would be provided. The README covers all the possibilities, e.g. environment variables. If you come up with something else, feel free to submit an issue or PR.
