### ISSUE TITLE
(new CustomError) instanceof CustomError => false

### ISSUE THREAD

**Issue by ken0x0a** [TypeStrong/ts-node#833]
Maybe related to https://github.com/TypeStrong/ts-node/issues/583

```
(new CustomError) instanceof CustomError
// => false 
// should be `true` but will get `false` @ ts-node
// `true` @ node
```

In addition, `constructor` also works unexpectedly.
```
(new WithoutConstructorError).constructor === WithoutConstructorError // => false
(new WithoutConstructorError).constructor === Error // => true
```

I've tested using following code.
Adding `constructor` in class did not change result.
```ts
class WithoutConstructorError extends Error {}

(new Error).name
(new WithoutConstructorError).name

(new Error) instanceof Error
(new Error) instanceof WithoutConstructorError
(new WithoutConstructorError) instanceof WithoutConstructorError
(new WithoutConstructorError) instanceof Error

(new Error).constructor === Error
(new Error).constructor === WithoutConstructorError
(new WithoutConstructorError).constructor === WithoutConstructorError
(new WithoutConstructorError).constructor === Error
```

**Comment by blakeembrey** [comment]
I think this may be related to your target ES version, but I’ll investigate more when I have a chance. Are you specifying a custom target at all?

**Comment by iam4x** [comment]
I was having a similar issue, narrowed it down to nodejs itself! Might be relevant https://github.com/nodejs/node/issues/27859 ?

**Comment by ken0x0a** [comment]
@blakeembrey Thank you for your reply!

I'm sorry I didn't notice.

Actually I didn't understand what you mean, but I tried target ES versions (es5, es2015, es2018), and got same result.


With following configuration
```
    "target": "es5"
    "module": "commonjs"
```

```
> class WithoutConstructorError extends Error {}
'use strict'
>
undefined
> (new Error).name
'Error'
> (new WithoutConstructorError).name
'Error'
>
```

With following configuration also same result
```
    "target": "es2015" or "es2018"
    "module": "commonjs"
```

**Comment by ken0x0a** [comment]
@iam4x Thank you for your reply!

Since I got expected result @ `node`, I guess that is not the something.

**Comment by davoam** [comment]
> I think this may be related to your target ES version, but I’ll investigate more when I have a chance. Are you specifying a custom target at all?

In my case changing target from `es5` to `es2018` helped

**Comment by blakeembrey** [comment]
Thanks @davoam, I'm going to close this issue since it's most likely related to emitted output. It's a reason I've always used something like https://www.npmjs.com/package/make-error in custom projects.
