### ISSUE TITLE
mocha ts-node can't find realtive tsconfig file 

### ISSUE THREAD

**Issue by oreporan** [TypeStrong/ts-node#839]
Hey, I have a lerna setup where I have one tsconfig and I want each package to point at the same tsconfig found in the root.

However when I pass 

`mocha --require ts-node/register --project ../../tsconfig.json`

I get:

` node_modules/.bin/tscofig.json: No such file or directory`

Seems that only if the tsconfig file is sitting next to the `package.json` it works, any other path fails

Also I notice that if I give some non-existant file name like

`mocha --require ts-node/register --project fake.json`

It won't yell "no such file or directory", so I guess its falling back to some default location?

Versions:

`"ts-node": "^8.2.0",`
`"mocha": "^3.4.2",`
MacOS

**Comment by blakeembrey** [comment]
That’s because mocha doesn’t understand your CLI flag that’s intended for this package. Try environment variables for this use case instead.

**Comment by oreporan** [comment]
Ok will do
thx
