### ISSUE TITLE
readline stdout cannot be muted

### ISSUE THREAD

**Issue by SOF3** [TypeStrong/ts-node#840]
Consider this test file `readline-test.ts`:
```typescript
import * as rl from "readline"
import {Writable} from "stream"

const rli = rl.createInterface({
	input: process.stdin,
	output: new Writable({
		write: (chunk, encoding, callback) => {
			callback()
		}
	}),
	terminal: true,
})

rli.question("Hello: ", answer => {
	console.error("Answer: " + answer)
})
```

## Normal behaviour
Try `tsc readline-test.ts && node readline-test`. Typing anything to the terminal does not get displayed, despite `console.error("Answer: " + answer)` displays the input correctly. 

## ts-node behaviour
Try `ts-node readline-test`. Typing anything to the terminal gets displayed.

I have tested this on Windows cmd.exe as well as on Git Bash.

**Comment by cspotcode** [comment]
I'm unable to reproduce this, and it's an old issue, so I'm going to (optimistically) close it.  I suspect it might be an issue with older Windows terminals, with a particular terminal emulator, with a particular version of node, with an older npm emitting a different flavor of cmd shim, or it's an issue that was somehow fixed for unrelated reasons in a newer ts-node release.

If it's still affecting you, let us know and we can re-open.
