### ISSUE TITLE
Unexpected token ' in JSON at position 0

### ISSUE THREAD

**Issue by josesaranda** [TypeStrong/ts-node#841]
```
ts-node -O '{"module": "commonjs"}' ./scripts/generateTranslationFiles.ts
undefined:1
'{module:
^

SyntaxError: Unexpected token ' in JSON at position 0
```

What i'm doing wrong?

**Comment by blakeembrey** [comment]
What shell are you using? Any other information to debug? This seems like an issue with your environment in some way.

**Comment by josesaranda** [comment]
Since you ask me for that i tried to run that command in many differents ways.

I work on **Windows 10**, and i tried to run `ts-node -O '{"module": "commonjs"}' ./scripts/generateTranslationFiles.ts` in _PowerShell_ and traditional _CMD_. That doesn't work.

Thanks in advance.

**Comment by blakeembrey** [comment]
Did you try using double quotes and escaping? IIRC Windows shells act differently in terms of quotes.

**Comment by josesaranda** [comment]
Thanks for your quick response. I solve this issue using the new ubuntu subsystem for Windows. Thanks you a lot.

**Comment by hanshou101** [comment]
When using Win10 cmd, you need to use three double quotes to represent the original double quotes.

**Comment by NookieGrey** [comment]
How I should ise ts-node on windows cmd and linux?
`ts-node -O \"{\"module\":\"commonjs\"}\"`
returns also error
```
{module:commonjs}
 ^

SyntaxError: Unexpected token m in JSON at position 1
```

**Comment by cspotcode** [comment]
@trongtran810 check out the debugging guide here: https://github.com/TypeStrong/ts-node/discussions/1182
