### ISSUE TITLE
.d.ts files in node_modules/@types are ignored in repl

### ISSUE THREAD

**Issue by kevinbarabash** [TypeStrong/ts-node#844]
I ran `ts-node` and loaded the `fs` module and tried to get the type of some of the functions but everything was typed as `any`:
```
> const fs = require("fs")
'use strict'
> .type fs.readFileSync
any
> 
```
Does the `ts-node` repl support getting types from node modules?  I double checked that `node_modules/@types/node/fs.d.ts` does exist.

**Comment by blakeembrey** [comment]
This is actually because you used `const fs = require('fs')` which is the expected type (`require` is typed as returning `any`). If you want this to work with TypeScript, you must use TypeScript imports like usual, e.g. `import * as fs from 'fs'`.

**Comment by thw0rted** [comment]
Is it possible to have `require` typed based on its module specifier argument?  VSCode (or, I guess the TS language service it relies on) is somehow able to type Kevin's example correctly -- `fs` is `typeof module "fs"`, not `any`.

**Comment by blakeembrey** [comment]
Are you putting that code in JS or TS? If you can reproduce it with the typescript compiler, I’ll consider this a bug, but my guess is they’ve built something to handle it in JS files.
