### ISSUE TITLE
feature request: export functions for transpiling with and without type checks.

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/ts-node#845]
I see that `ts-node` uses the TypeScript compiler API to compile with or without checks (somehow? I didn't know TS could transpile without type checks). Would you mind exporting this functionality, so I could, for example, pass in a source file and transpile it with or without type checks (without registering a `require` hook)?

**Comment by blakeembrey** [comment]
@trusktr That's definitely a possibility, but the TypeScript compiler is actually pretty easy to use in this case. Why not use it directly? E.g. https://github.com/TypeStrong/ts-node/blob/629525474fb548fddb7a90a48ab795a9199b1997/src/index.ts#L278-L283.

**Comment by blakeembrey** [comment]
If you want this you'll probably need to submit a sample PR or respond with a proposal API, I'm just not 100% sure how this would be supported without adding maintenance overhead to the current package (though I believe it's possible once I understand more).

**Comment by blakeembrey** [comment]
Check out https://github.com/TypeStrong/ts-node/commit/be8e2e13a8f0b62439bb34c528509e5643fe42af and let me know if it works for you.
