### ISSUE TITLE
'Emit skipped' on fork and TypeORM

### ISSUE THREAD

**Issue by viandanteoscuro** [TypeStrong/ts-node#848]
* **Node.js Version**: 12.4.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: TypeORM 0.2.14

Hi,

i fork my node process with this line:

```js
fork("process-child.ts", [], { execArgv: ['node_modules\\ts-node\\dist\\bin.js'] });
```

And all works prefctly.. but when i add to the child-process the TypeORM functionalities, i have the "Emit skipped" error at this line of ts.-node:

```js
C:\Users\...\Code\Projects\service\node_modules\ts-node\src\index.ts:365
        throw new TypeError(`${relative(cwd, fileName)}: Emit skipped`)
```

If i remove the typeorm part all works ok.

I follow the instructions from typeorm site, and the simple connection is:

```js
DB.initDatabase({}).then(() => {
        (<any>process).send({ "msg": "Connected!!" });
});
```

How can i resolve (the best solution for me is not remove typeorm from child, to avoid big data exchange from child to parent and viceversa)?

**Comment by fchengjin** [comment]
Have you solved it?
