### ISSUE TITLE
Does not support local file paths in package.json

### ISSUE THREAD

**Issue by al6x** [TypeStrong/ts-node#855]
NPM [support local file path](https://stackoverflow.com/questions/15806241/how-to-specify-local-modules-as-npm-package-dependencies) package declaration in `package.json`

I specified the following dependency in my project. The VS Code can see the `mypackage` correctly, if you click on some function that's imported from there like `mypackage/somefile` - it will navigate there correctly etc.

```
{
  ...
  "dependencies": {
    "mypackage": "file:/myprojects/mylocalpackage"
  }
}
```

But when I ran it with `ts-node` it throw an error that it can't find `mypackage/somefile` package.

**Comment by blakeembrey** [comment]
Can you make a reproducible example? I haven't had any issues with doing the same thing.

**Comment by alexeypetrushin** [comment]
Sure https://github.com/alexeypetrushin/file-dependency-example

Instructions how to run in readme

```
$ ts-node -v
v8.3.0
$ node -v
v11.2.0
```

**Comment by blakeembrey** [comment]
I haven't been able to replicate this in 8.x:

```
❯ ts-node alib.ts
hello from b
```

However, I noticed on the latest builds (going to be v9) this will be broken and you'll be expected to use `references` going forward.

**Comment by cspotcode** [comment]
npm uses symlinks for `file:` dependencies.  Maybe this was a symlink issue?  If so, #970 should hopefully have solved any symlink issues.

I can't seem to reproduce this bug locally so I'm going to close it.
