### ISSUE TITLE
How to use with nvm?

### ISSUE THREAD

**Issue by krzkaczor** [TypeStrong/ts-node#861]
I feel like I can't be the only one looking for an answer, I figured it out and decided to leave the answer here for future generations ;) 

To use it with NVM you need to inject ts-node with `-r ts-node/register` to exact node binary. 

So for example to set it up in VS code you do:

```
	{
      "type": "node",
      "request": "launch",
      "name": "Launch",
      "runtimeExecutable": "${env:HOME}/.nvm/versions/node/v10.16.0/bin/node",
      "protocol": "inspector",
      "outputCapture": "std",
      "args": [
        "-r",
        "ts-node/register",
        "${workspaceFolder}/index.js"
      ],
    }
```

**Comment by vjba** [comment]
Thank you for this @krzkaczor.

Do you know of any way to make the ` "runtimeExecutable"` path dynamically update to newer versions of node after being installed by nvm?

**Comment by krzkaczor** [comment]
@vjba not sure but it seems like there are some aliases available:
```
Any time your local copy of nvm connects to nodejs.org, it will re-create the appropriate local aliases for all available LTS lines. These aliases (stored under $NVM_DIR/alias/lts), are managed by nvm, and you should not modify, remove, or create these files - expect your changes to be undone, and expect meddling with these files to cause bugs that will likely not be supported.```

maybe its the way to go.

**Comment by vjba** [comment]
@krzkaczor thanks again for the help. I've got your first solution working.

I'll do some digging on the suggestion you provided and hopefully I'll be able to post back with a clean solution.

**Comment by conceptstom** [comment]
> I feel like I can't be the only one looking for an answer, I figured it out and decided to leave the answer here for future generations ;)
> 
> To use it with NVM you need to inject ts-node with `-r ts-node/register` to exact node binary.
> 
> So for example to set it up in VS code you do:
> 
> ```
> 	{
>       "type": "node",
>       "request": "launch",
>       "name": "Launch",
>       "runtimeExecutable": "${env:HOME}/.nvm/versions/node/v10.16.0/bin/node",
>       "protocol": "inspector",
>       "outputCapture": "std",
>       "args": [
>         "-r",
>         "ts-node/register",
>         "${workspaceFolder}/index.js"
>       ],
>     }
> ```

Hello: Long time ago this post was intiated but i got the same issue with NVM and ts-node not working together.

Where to put above lines of code exactly  ?
And what does this acutally mean: '-r ts-node/register` to exact node binary' ? 
How to put it exactly with an inject - but is it like this: npm install -r ts-node ?
I used this for a local instal of ts-node: npm install -D ts-node
 Cheers !
