### ISSUE TITLE
Use globally installed @types/node if not found locally (to match node)

### ISSUE THREAD

**Issue by G-Rath** [TypeStrong/ts-node#862]
I've looked around, and seen a number of issues about not being able to find types, and the solutions are all local-based ones, which are fine in their context, except...

if I'm wanting to do loose scripting à la mode de vanilla `node`, it's a bit of a pain, since I have to install `@types/node` locally - meaning any folder I'm in needs at least a `node_modules` & `package-lock.json` file.

I think that `ts-node` should check the `node_modules` folder it's installed in for `@types/node`.

That way we could jump right into using the native modules in the same manner as when running `node`.

I'm happy to try and come up w/ a PR for this, if you're interested in this feature.

Looking at the `node` api, `process.execArgv` can be used to get the location of `ts-node`:

```
root@host-004:/home/ubuntu# ts-node
> // @ts-ignore
undefined
> process.execArgv
[ '/usr/lib/node_modules/ts-node/dist/bin.js' ]
```

So I think (/hope) it's just a matter of looking for `@types/node` in the first `node_modules` along that path.

This could be extended maybe to load any globally installed types, but you're previously mentioned loading in extra files can be very slow, and I think it's a fair call to say you'll only load in `@types/node` to improve matching the vanilla `node` REPL.

**Comment by blakeembrey** [comment]
I don't think this would be a particularly simple feature to add, and it probably shouldn't be default either. But I would consider a PR behind a flag if you get it working!

**Comment by G-Rath** [comment]
Exactly what I wanted to hear, and yeah I thought after I opened the issue it's probably best to have it as a flag.

I'm thinking it might be best to try and leverage an in-memory `tsconfig.json` of some sort, so effectively the flag would translate to something like:

```
ts-node -O '{"types":["@types/node"],"typeRoots":["/usr/lib/node_modules"]}' <args>
```

The tests for that might be a bit tricky 😬

**Comment by G-Rath** [comment]
@blakeembrey works like a treat:

![ss+(2019-07-30+at+06 15 41)](https://user-images.githubusercontent.com/3151613/62105287-17a68a00-b2f6-11e9-9ae2-391f27c8237d.png)

That's using:

```
if(config.options.types === undefined) {
      config.options.types = [];
    }

    config.options.types.push('@types/node');

    if(config.options.typeRoots === undefined) {
      config.options.typeRoots = [];
    }

    config.options.typeRoots.push('/usr/lib/node_modules');
```

Just before the return in `fixConfigs`.

If it's alright w/ you, I'll make use of [`global-modules-path`](https://www.npmjs.com/package/global-modules-path) (once my typings have been released on `@types`) to get if the package is installed globally.

I'll clean it up and make a PR sometime next week.

After that, I might see if theres a nice way to define the native modules as already being imported so that we can use them directly... (since you can do `// @ts-ignore` and then use them directly, so they're imported like in vanilla node).

**Comment by cspotcode** [comment]
This has been implemented and released in v10.

For example, the following will work in an empty directory without any node_modules or other boilerplate:

```shell
# The latest npm v7 installs peer dependencies by default, so this is all you need
$ npm install -g ts-node
```

Create the following file and give it execute permission:

```typescript
#!/usr/bin/env ts-node
import fs from 'fs';

// hey this is line 4

const source = fs.readFileSync(__filename, 'utf8');
console.log(source.split('\n')[3]);
// Uncomment this to prove that typechecking works
// const num: number = source;

// Requires a modern `target` and `lib`, but `ts-node` will set these automatically on modern node versions
const bigint = 100n;
console.dir(bigint);
```

Run it:

```shell
$ ./foo.ts
// hey this is line 4
100n
```

**Comment by rayfoss** [comment]
PSA: ts-node-dev and ts-node are not related... ts-node-dev does not even use ts-node. Code that runs on ts-node may not run on ts-node-dev. Your mileage may vary. Please consult your doctor.

**Comment by cspotcode** [comment]
ts-node-dev internally uses ts-node's compiler service, right?
