### ISSUE TITLE
ts-node compilation slows down after loading a certain number of modules

### ISSUE THREAD

**Issue by ajfranzoia** [TypeStrong/ts-node#863]
_Environment:_
* `tsc`: v3.5.3 
*  `ts-node`: v8.0.2
* `node`: v10.15.3

I'm experiencing some issues using `ts-node`, by using `NODE_DEBUG=module` I realized that the compilation seems to slow down after loading a certain number of loaded modules. The files where it usually "slows down" don't have any particular difference to the rest. See the video below.
The `src` folder has around 250 files. I'm running `ts-node` with the `--files` option to be able to load declaration files. This is my `tsconfig.json` configuration:
```json
{
  "compilerOptions": {
    "rootDir": "./src",
    "outDir": "./build",
    "lib": [ "es2017" ],
    "sourceMap": true,
    "noImplicitAny": true,
    "strictNullChecks": true
  },
  "exclude": [
    "bin",
    "node_modules",
    "other"
  ]
}

```

![AwesomeScreenshot-2019-7-29-1564394314042](https://user-images.githubusercontent.com/964115/62039987-075cb500-b1f9-11e9-95ae-019f5991c897.gif)

**Comment by jamonholmgren** [comment]
I'm also noticing major slowdowns with ts-node 8.0.x on [Ignite CLI](https://github.com/infinitered/ignite).

Steps to reproduce:

```
git clone https://github.com/infinitered/ignite.git
cd ignite
yarn
yarn link
time ignite help
# note how fast it goes -- should be about 0.5s
yarn add -D ts-node@8.0.2
time ignite help
# note it goes much slower -- about 7s or more
```

**Comment by ianbytchek** [comment]
@ajfranzoia @jamonholmgren You might want to take a look at #754.

@blakeembrey Probably would be a good idea to pin that issue.

**Comment by cspotcode** [comment]
Closing for mostly the same reasons as https://github.com/TypeStrong/ts-node/issues/754#issuecomment-860345150
