### ISSUE TITLE
How to add --project flag to ts-node/register?

### ISSUE THREAD

**Issue by DylanJu** [TypeStrong/ts-node#869]
My issue is not working `--project` flag with nodemon.
For watching(detecting file changes) nodemon is needed.

But nodemon config and cli can not read `ts-node` flags including --project.

modemon.json
````
{
  "restartable": "rs",
  "ignore": [".git", "node_modules/**/node_modules"],
  "verbose": true,
  "execMap": {
    "ts": "node --require ts-node/register src/server.ts --project tsconfig.server.json"
  },
  "watch": ["src/"],
  "env": {
    "NODE_ENV": "development"
  },
  "ext": "js,json,ts"
}
````

I want to compile `ts-node` with` tsconfig.server.json` instead of `tsconfig.json`.
`tsconfig.json` is a default config for ts-node but `server.ts` needs another typescript config because es5, commonjs syntax.
(in my project, `tsconfig.json` is for client compile)

How can I add --project flag to ts-node?

P.S.
if I change the order of cli,
`node --require ts-node/register--project tsconfig.server.json  src/server.ts `

it crashed with node error
`node: bad option: --project`

**Comment by yi-fan-song** [comment]
try `TS_NODE_PROJECT` environment variable

**Comment by blakeembrey** [comment]
@DylanJu Like @yi-fan-song mentions, `--project` is not an option for `node` - it's an option for `ts-node`. You can also change the executable with `nodemon` to be `ts-node` to get around this.

**Comment by matiishyn** [comment]
`node --require ts-node/register` is required when I want to use `--inspect`
So my question is,
how can I use both `--inspect` for debugging with Chrome and `--project` for setting my custom tsconfig.json
@blakeembrey can you plz take a look

**Comment by cspotcode** [comment]
You should be able to use our environment variables for this.

https://github.com/TypeStrong/ts-node#visual-studio-code
https://github.com/TypeStrong/ts-node#cli-and-programmatic-options

**Comment by DTX-92** [comment]
Same problem.
How do I setup enviroment variables when I use script from package.json?
`"tsc3": "node -r ts-node/register  ./src/index2.ts"`

**Comment by cspotcode** [comment]
https://www.npmjs.com/package/cross-env

**Comment by 0x1af2aec8f957** [comment]
> 就像@ yi-fan-song提到的那样，@ DylanJu`--project`不是一个选项`node`-它是一个选项`ts-node`。您还可以更改与可执行`nodemon`要`ts-node`来解决这个问题。

```bash
ts-node --script-mode main.ts
```
or

```bash
cross-env TS_NODE_PROJECT=<tsconfig.json> main.ts # npm install cross-env -D
```
or

```jsvascript
require('ts-node').register({dir: <tsconfig.json>}); // required
require('./main.ts'); // import typescript
```
