### ISSUE TITLE
print imported images as [object Object] 

### ISSUE THREAD

**Issue by alireza-mh** [TypeStrong/ts-node#871]
In case we import images like below typescript and ts-node have different outputs.
`import Logo from 'src/image.logo.svg'`
in SSR application that uses ts-node we gonna see `[object Object]`  as img `src` value.
the command that we used: `ts-node --files -r tsconfig-paths/register server/server.ts`

In case we use `tsc` with node image path will be shown.
`tsc -p tsconfig.json --skipLibCheck && node ./server/bootstrap.ts`

**Comment by alireza-mh** [comment]
I guess since `transform-assets` apply to the `js` files it works.
couldn't find a corresponding plugin for typescript to check it.

**Comment by blakeembrey** [comment]
This is outside of the scope of `ts-node`. Importing an image isn't supported by node.js natively in any case, so I suspect all this behavior is somewhere within Webpack or other bundler configuration, or another loader you're using. Happy to help if you need it, but it's unclear what I can change with this issue description.

**Comment by codler** [comment]
Is it possible to override import in ts-node? for example when importing a svg we should ignore the content instead of getting `SyntaxError: Unexpected token <`?

**Comment by codler** [comment]
Nvm, found answer here https://github.com/TypeStrong/ts-node/issues/576#issuecomment-384359471

**Comment by juliengbt** [comment]
@codler I got the same error as you with `import logo from 'src/assets/logo.svg`, how did you fix that ?
