### ISSUE TITLE
"Short form" flags like "-D6133" no longer work

### ISSUE THREAD

**Issue by kbd** [TypeStrong/ts-node#872]
It used to be possible to give arguments to `ts-node` in standard "short form" like:

```
$ ts-node -D6133
```

Now (while "-D 6133" works) the short form fails with: 

```
$ ts-node -D6133
/usr/local/lib/node_modules/ts-node/node_modules/arg/index.js:97
					throw new TypeError(`Option requires argument (but was followed by another short argument): ${originalArgName}`);
					^

TypeError: Option requires argument (but was followed by another short argument): -D
    at arg (/usr/local/lib/node_modules/ts-node/node_modules/arg/index.js:97:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/dist/bin.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)
    at internal/main/run_main_module.js:17:11
```

Using:

```
$ ts-node --version
v8.3.0
```

**Comment by blakeembrey** [comment]
@kbd In which version did this used to be possible? You are probably correct, but a major version does imply backward incompatible changes. In any case, this does sound like something we should correct in https://github.com/zeit/arg. Happy to accept a PR with tests to ensure we don't regress if `arg` supports it already.

**Comment by kbd** [comment]
> In which version did this used to be possible?

Not sure exactly, but [my "scratch" script](https://github.com/kbd/setup/blob/master/snip/scratch.ts) using `ts-node` in its shebang was last updated on Oct 30, 2018, so it worked then (I stopped working in JavaScript since then but am on another project now).

**Comment by blakeembrey** [comment]
Makes sense. You'll need to submit a feature request to https://github.com/zeit/arg/issues, for now this will unfortunately be incompatible. This was released as a breaking change in https://github.com/TypeStrong/ts-node/releases/tag/v8.0.0, I'd definitely recommend pinning to a major version in the future - it's expected that some breaking changes can happen over the course of a year.
