### ISSUE TITLE
project with `bin` file using ts-node works only when `npm link`ed, fails otherwise

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/ts-node#875]
But when I install the project and don't `npm link` it, then on the first TypeScript file that is `require`d I get the error

```
SyntaxError: Unexpected token *
    at Module._compile (internal/modules/cjs/loader.js:760:23)
```

When I step through the code in devtools, the firs thing to be called is `require('ts-node')` in the entry point which is a `.js` file, which then imports the first `.ts` file.

This all works great when the ts-node-using project is `npm link`ed into my other project.

The linked package provides a `bin` file, which is the file that is using `ts-node`.

Then when I'm all ready to test it out without linking, `ts-node` doesn't seem to do anything.

Any ideas?

**Comment by trusktr** [comment]
Here's a reproduction.

To see the non-working state:

```sh
git clone git@github.com:infamous/infamous.git
cd infamous
git checkout issues/ts-node-875
npm install
./node_modules/.bin/leafdoc # ERROR, unexpected token *
```

It appears ts-node is not coming into play.

But you can clone my fork of leafdoc and `npm link` it into the project, and it will work great:

```sh
git clone git@github.com:trusktr/Leafdoc.git
cd Leafdoc
git checkout typescript
npm link
cd ../infamous
npm link leafdoc
./node_modules/.bin/leafdoc # NO ERROR!
```

Any idea why it works great only when `npm link`ed?

**Comment by lu4** [comment]
I think I've bumped into similar issue https://github.com/TypeStrong/ts-node/issues/874

**Comment by blakeembrey** [comment]
Closing in favor of https://github.com/TypeStrong/ts-node/issues/874.
