### ISSUE TITLE
Environment variable doesn't strip

### ISSUE THREAD

**Issue by yi-fan-song** [TypeStrong/ts-node#881]
In my package.json I have a script 
`set TS_NODE_PROJECT=./tsconfig.server.json && node --inspect=5858 -r ts-node/register ./server/server.ts`.
When ran, it gives me
```
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS5058: The specified path does not exist: 'C:/dev/st/PrioritySortingTool/tsconfig.server.json '.
```
Notice the extra space after `tsconfig.server.json`

**Comment by blakeembrey** [comment]
@yi-fan-song Is this a Windows related thing? It seems odd to have to change the string you set manually, but it could be done.

**Comment by yi-fan-song** [comment]
Yea, windows keeps that space there. Unintuitively, `set TS_NODE_PROJECT=./tsconfig.server.json&& node --inspect=5858 -r ts-node/register ./server/server.ts` works.
