### ISSUE TITLE
Please consider using `prepublishOnly` rather than `prepare` to transpile code to `dist`

### ISSUE THREAD

**Issue by ohjames** [TypeStrong/ts-node#886]
Having the transpilation in `prepare` means that everyone time someone `npm install`s this package into their own project, it is transpiled (despite the transpiled source code already existing in `dist`).

If you moved the build into `prepublishOnly` or `prepack` then the code would be transpiled once before being uploaded to the npm repository. Then you'd save everyone who installs `ts-node` from having to compile it a second (and third, fourth, fifth etc.) time.

**Comment by blakeembrey** [comment]
That’s not true at all.
