### ISSUE TITLE
Runtime reference error with --transpile-only

### ISSUE THREAD

**Issue by kaienbcjdoapwkfldue** [TypeStrong/ts-node#887]
When using the `--transpileOnly` flag, I get a runtime reference error that `ReturnType` is undefined on the following code

```typescript
function wrapper<T extends (...args: any[]) => any>(
  func: T
): (...funcArgs: Parameter<T>) => ReturnType<T> {
    return async (...args: Parameters<T>): ReturnType<T> => {
        // do stuff
        return await func
    }
}
```
I know that there is a type error in that it should read `Promise<ReturnType<T>>`. However, I would like to ignore it for now as I won't get the correct return type if `func` returns itself a promise (I would get `Promise<Promise<...>>`).

Anyway, It seems that `ReturnType` still remains in the resulting Javascript code after transpilation, which shouldn't happen regardless of the type error, I suppose (?). Without `--transpileOnly`, it works.

Note: I am actually using `ts-node-dev`, but I suppose this belongs to `ts-node`.

**Comment by blakeembrey** [comment]
I’ll test this in the next few days, if it does turn out to be a reproducible issue we’ll need to report it to the TypeScript repository.

**Comment by blakeembrey** [comment]
Wasn't able to replicate this on TypeScript 3.6, it's possible this was a bug in an earlier version.
