### ISSUE TITLE
extend Window occur error

### ISSUE THREAD

**Issue by tqma113** [TypeStrong/ts-node#889]
Typescript: 3.6.2
ts-node: 8.4.1

```
interface MyWindow extends Window {
  __CONFIG__: Config
}

(window as MyWindow & typeof globalThis).__CONFIG__ = config
```
when i write it in ide, it doesn't warn, but when run it with ts-node it will throw an error.

> UnhandledPromiseRejectionWarning: ReferenceError: window is not defined

How can i avoid it?

**Comment by blakeembrey** [comment]
There’s no such thing as window on node.js.
