### ISSUE TITLE
Support fileGlobs

### ISSUE THREAD

**Issue by unional** [TypeStrong/ts-node#89]
`ts-node **/*.ts` :smile:

**Comment by blakeembrey** [comment]
Node core doesn't, why would this?

**Comment by unional** [comment]
Um.....true.

How do I run all tests from the test folder in the typings?
I was thinking `"test": "ts-node --project test **/*.ts"` or `"test": "cd test && ts-node **/*.ts" (as `--project` doesn't work).

**Comment by blakeembrey** [comment]
What are you trying to run like that? Usually test runners provide a CLI tool you should be using to accept globs.

**Comment by unional** [comment]
I see. This would work. :+1: 
`"test": "cd test && ts-node ../node_modules/blue-tape/bin/blue-tape **/*.ts | tap-spec && echo run source tests"`

Thanks!
