### ISSUE TITLE
Got syntax error when running npm start SyntaxError: missing ) after argument list 

### ISSUE THREAD

**Issue by ViniAugusto** [TypeStrong/ts-node#891]
Hi, I would like some help to understand what's happening here.

When I run `npm start` I got this error:
 `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)`

also got this path:  `\node_modules\.bin\ts-node:2`

When doing some research I found that other packages also have this issue when running an application on Windows.

Do you guys have any tips on how to deal with it?

Thanks

**Comment by blakeembrey** [comment]
It looks like your trying to run a shell script with this package? I’d need more information to help though.

**Comment by ViniAugusto** [comment]
I'm trying to run a server when I type npm start on terminal I got this error.


my package.json script is:
 ```
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "cross-env NODE_ENV=development nodemon ./node_modules/.bin/ts-node ./server/server.ts"
  }
```

I was doing a tutorial and there's said that when running this command I should be able to open localhost:5000 but I got this error and since my research found that maybe it's a Windows thing with the package I thought that maybe someone already saw this and have a solution.

This is my first issue ever so if you need some specific info you can tell me.

[This Link to the tutorial](https://medium.com/nerdzao/crie-uma-api-restful-em-nodejs-para-gerenciar-seus-crushs-c4c74c3db96e) it's in portuguese tho. But basically I stopped at the first npm start command.

Thanks

**Comment by blakeembrey** [comment]
It could be because you're doing `nodemon ./node_modules/.bin/ts-node`, which I believe doesn't usually work. Can you try pointing to the `bin` file within the package directly instead of the bash proxy? E.g. `nodemon node_modules/ts-node/dist/bin.js`? Usually that's how you work around this with other packages too.

**Comment by doaazouiter95** [comment]
basedir=$( node dirname "$(echo "$0" | sed -e 's,\\,/,g')")
