### ISSUE TITLE
Installing on raspberry pi (arm32) yields empty package in node_modules

### ISSUE THREAD

**Issue by mmc41** [TypeStrong/ts-node#892]
The most recent ts-node npm 12.7.11 does not install correctly with "npm install" for raspberry pi (arm 32). The resulting folder in node_modules is empty except from a "package.json" file when running node 12.0 and npm 6.10.3

**Comment by blakeembrey** [comment]
This sounds out of my control. Have you tried installing other packages? This is deployed as a single build to the NPM registry, not as different builds for different machines, so there shouldn’t be any difference unless there’s an issue with your machine or NPM on this machine.

**Comment by mmc41** [comment]
Not sure what is wrong - some packages install correctly (f.x. typescript npm) and some does not (like this one).

**Comment by mmc41** [comment]
just tested using yarn instead of npm and here it works. So it must be a npm problem. Closing this.
