### ISSUE TITLE
How to prevent moment automatically converted to number in the Template Literals

### ISSUE THREAD

**Issue by RazgrizHsu** [TypeStrong/ts-node#900]
on node:
```
const moment = require( 'moment' );
console.info( `show: [${ moment.utc() }]` )

//output: 'show: [Wed Oct 30 2019 11:30:00 GMT+0000]'
```

on ts-node:
```
const moment = require( 'moment' );
console.info( `show: [${ moment.utc() }]` )

//output: 'show: [1572435290801]'
```

i need it keep string output (ts-node)

but even override moment.prototype.toString still same result...

**Comment by blakeembrey** [comment]
If you use `"target": "es2015"` then you will have native template literals, which appear to have a different behavior than string concatenation which is what TypeScript would be outputting.
