### ISSUE TITLE
Augmentation of type "Global" sometimes unavailable

### ISSUE THREAD

**Issue by newlukai** [TypeStrong/ts-node#904]
I'm working on a project based on a legacy template where `global` is augmented:
```typescript
// index.ts
declare global {
  namespace NodeJS {
    interface Global {
      __service: string;
    }
  }
}
```

Of course, I want to test my code, so I've written unit tests which are run using "mocha". Since one might have the idea to run a single unit test, I added above `global` extension to every unit test file:
```typescript
declare global {
  namespace NodeJS {
    interface Global {
      __service: string;
    }
  }
}

// imports

describe('UnitToTest', function unitToTest() {
 // …
}
```

This works quite well. But sometimes I get an error
`
TSError: ⨯ Unable to compile TypeScript:
source/index.ts(16,23): error TS2339: Property '__service' does not exist on type 'Global'.
`

It often was due to an import addition since WebStorm puts a new import in line 1. But recently I also faced this issue without any code change. I figured out how to wipe the "ts-node" cache which results in proper compilation. Until the next issue occurrence…

So I'm currently figuring out how to solve this issue and came up with

- trying to use the "--no-cache" option when using "ts-node" with "mocha". Unfortunately it seems this isn't possible.
- the hint in "ts-node"s README to define and include a type declaration. So I put the following module declaration into a "typings" directory, added it to `typeRoots` in "tsconfig.json" and removed all declarations in my .ts files. Now the TS compiler complains again regarding my code accessing `global.__service`.

```typescript
declare module global { // only ambient module declaration allowed here
  namespace NodeJS {
    interface Global {
      __service: string;
    }
  }
}
```

Does anyone reading this have an idea how to solve this? One way might be to add just a new file in "ts-node/register" to disable the cache. But I've the feeling, there might be a more elegant solution regarding the augmentation of the `global` object.

The `tsconfig.json` looks like
```json
{
  "compilerOptions": {
    "target": "ES2017",
    "module": "commonjs",
    "lib": [
      "es2017",
      "esnext.bigint"
    ],
    "allowJs": true,
    "sourceMap": true,
    "strict": true,
    "noImplicitAny": false,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "typeRoots": [
      "./node_modules/@types"
    ],
    "outDir": "./dist"
  },
  "exclude": [
    ".idea", "dist", "gulpfile.js", "logs", "node_modules"
  ],
  "include": [
    "source", "test"
  ]
}
```

Thanks in advance

**Comment by blakeembrey** [comment]
@newlukai You _could_ create a type and use it via `typeRoots` as mentioned in the README, but you can also just put this in any `.ts` file. The only time you should be getting an error is when the file with that augmentation is not loaded at all.

**Comment by newlukai** [comment]
I found a [further example on how to augment `global`](https://stackoverflow.com/questions/56223520/augmenting-global-in-typescript).
So I added this file:
```typescript
// ./typings/NodeJS/index.d.ts
declare namespace NodeJS {
  export interface Global {
    __service: string
  }
}
```

and changed the "tsconfig.json" accordingly. Works. Nice!
