### ISSUE TITLE
Add a flag to increase verbosity

### ISSUE THREAD

**Issue by mgummelt** [TypeStrong/ts-node#905]
This is the current output format when an error is encountered:

```
$ npx ts-node --project tsconfig.json scripts/test.js 
Cannot read property 'getState' of undefined
```

As is, I can't debug this.  It would help a lot if the stack trace were included.

**Comment by blakeembrey** [comment]
Pretty sure this is an NPX bug. If you can create and share a repro without NPX feel free to comment.
