### ISSUE TITLE
Syntax error: Unexpected Token ... with default property value in class and heritage

### ISSUE THREAD

**Issue by pierrecle** [TypeStrong/ts-node#91]
Same symptoms as #60 with the following code, `tsc` is fine, but `ts-node` don't like it, ES5 & ES6:
```typescript
'use strict';
class Foo {}
class Bar extends Foo {
  anyInitedPropertyHere:string = 'O_o';
}
new Bar();
```
But if I add a constructor to `Bar` which calls `super()` then everything is fine.

**Comment by blakeembrey** [comment]
@pierrecle This is a JavaScript error, not `ts-node`. You are compiling as ES6 but node does not support all ES6 features yet.

**Comment by blakeembrey** [comment]
Reference: https://github.com/TypeStrong/ts-node/issues/43. Can not support ES6 features that don't exist and TypeScript does not support granular typings. The generated ES6 from TypeScript is below, which hopefully explains things:

```js
'use strict';
class Foo {
}
class Bar extends Foo {
    constructor(...args) {
        super(...args);
        this.anyInitedPropertyHere = 'O_o';
    }
}
new Bar();
```

**Comment by pierrecle** [comment]
Thanks for the explaination, clear indeed :+1:
