### ISSUE TITLE
Not possible anymore to preload a file

### ISSUE THREAD

**Issue by oktapodia** [TypeStrong/ts-node#910]
hello,

since the new version of this library (8.5.0), it's not possible anymore to preload a ts file like I used to do to load the configuration.

e.g.: `ts-node -r ./config src/index.ts` is preloading the config and initializing the env variables before loading the app (avoiding `process.env.WHATEVER is undefined`)

looks like the [module preloading](https://github.com/TypeStrong/ts-node/commit/2e99c5065f07293bb40649029990498515ba9616#diff-ee45801c137c3b9f9d8ec7ece340a514L190) has been updated but I don't find a way to resolve it.

**Working version**: <= 8.4.1

Regards

**Comment by blakeembrey** [comment]
Reverted in https://github.com/TypeStrong/ts-node/releases/tag/v8.5.2.
