### ISSUE TITLE
Perfomance Issues with current tsconfig

### ISSUE THREAD

**Issue by sajadghawami** [TypeStrong/ts-node#911]
Hey there,

i seem to have a bad performance issues with my current `.tsconfig.json`.
When i run the application, it takes a lot of time to start up and later very long to restart on changes.

Additionally, the battery of my laptop gets drained incredibly fast. Even while i am connected to power, i can see the battery down - which is really odd.

The  important packages from`package.json`:

```
    "ts-node": "8.3.0",
    "typescript": "^3.5.3",
    "nodemon": "^1.19.1",
```

This is the current `.tsconfig.json`:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "allowJs": true,
    "esModuleInterop": true,
    "target": "esnext",
    "noImplicitAny": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "outDir": "build",
    "baseUrl": ".",
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "noUnusedLocals": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": false,
    "isolatedModules": true,
    "paths": {
      "*": ["node_modules/*"]
    }
  },
  "include": ["src/**/*", "src/index.d.ts"],
  "exclude": ["node_modules", "build"],
  "inspect": true
}
```

I use the `dev:start` for developing in these are the scripts:

```
  "scripts": {
    "preinstall": "node ../shared/disallow-npm-preinstall.js",
    "staging:start": "node ./build/backend/src/app.js",
    "lint": "tslint -c tslint.json -p tsconfig.json",
    "dev:start": "npm-run-all debug entry",
    "start": "nodemon --watch src -e ts,ejs,js -L --exec npm run dev:start",
    "entry": "ts-node --transpile-only --noEmit --files ./src/app.ts",
    "debug": "node --inspect=0.0.0.0:9111 -r ts-node/register ./src/app.ts"
  },
```

This is the current folder structure:

![Screenshot 2019-11-14 14 55 23](https://user-images.githubusercontent.com/11796944/68863036-d5f7ee80-06ee-11ea-9e97-d3a9a53b3d56.png)

Any clue what i can do to stop this from happening is very mich appreciated.

**Comment by blakeembrey** [comment]
Unfortunately it won't be easy to help you debug this so I'm going to close the issue. From reading your `package.json`, you're creating two instances of `node` and `ts-node` running the same code with different modes - that probably makes things slower than necessary. Aside from that, are you sure you're using 8.x - you would be getting an error using the `--noEmit` flag:

```
Error: Unknown or unexpected option: --noEmit
```
