### ISSUE TITLE
Path ignore regex are being matched against parent directories

### ISSUE THREAD

**Issue by ks07** [TypeStrong/ts-node#913]
Ignored path regexes are matched against absolute paths, rathern than being taken relative to the current working directory, meaning that file ignoring behaviour can change if the parent directory is moved or renamed.

The simplest way to reproduce this problem is to trigger the default ignore pattern for node_modules (which is what originally triggered this issue for me). Steps provided below.

Create a dummy typescript file to demonstrate, e.g. **example.ts**
```typescript
function print(msg: string) {
  console.log(msg);
}

print("hello world");
```

Run this typescript file under ts-node, it should work as expected:
```
$ npx ts-node example.ts
hello world
```

Now create (or rename) a _parent_ directory into something covered by the ts-node ignore list, e.g.
```
example$ mkdir -p ./foo/node_modules/bar/
example$ cp example.ts ./foo/node_modules/bar/
example$ cd ./foo/node_modules/bar/
bar$ pwd
/home/ks07/example/foo/node_modules/bar
bar$ npx ts-node example.ts
npx: installed 8 in 2.428s
Unexpected token ':'
```

I think it's unexpected that the ignore option would apply to parent directories of the package, and ts-node should run the same regardless of the naming of the parent directory.

This looks to me to be a regression introduced in 9830c84b13c4172f736f6c93307c7e07ba9816fe, where before this commit the file path was converted to a relative path before matching:

https://github.com/TypeStrong/ts-node/commit/9830c84b13c4172f736f6c93307c7e07ba9816fe#diff-f41e9d04a45c83f3b6f6e630f10117feL310

I am running td-node v8.5.2 on node v12.13.0

**Comment by blakeembrey** [comment]
The behavior is/was intentional, since a `require()` could require a parent `node_modules/<name>` automatically. It could be reverted in the next major version, how did this come up for you? Are you actually trying to run TypeScript from `node_modules`?

**Comment by blakeembrey** [comment]
However, a relative path might actually cover my concerns above anyway, since it'd generate `../../node_modules/blah` so feel free to ignore that comment 😄 Sounds like a reasonable change, would love to hear a little more about how it come up since the change is 3 years old.

**Comment by blakeembrey** [comment]
Let me know if https://github.com/TypeStrong/ts-node/releases/tag/v8.5.3 fixes it for you.
