### ISSUE TITLE
[8.5.3] TSLib compiler errors during husky script

### ISSUE THREAD

**Issue by Favna** [TypeStrong/ts-node#919]
After upgrading to version 8.5.3 our scripts are failing due to TypeScript compiler issues in relation to tslib. Going back to 8.5.2 resolves the issue. 

Entire error log: https://hasteb.in/tarozeki.php

Repo for reproduction: https://github.com/RWS-NL/air-node-packages

Reproduction steps:
1. Clone repo
2. Upgrade ts-node to 8.5.3: `yarn add -DW ts-node@8.5.3`
3. Try running the `validateNoOnly` script: `yarn scripts:validateNoOnly`
4. You'll see the above errors being logged.

**Comment by blakeembrey** [comment]
Fixed with https://github.com/TypeStrong/ts-node/releases/tag/v8.5.4.
