### ISSUE TITLE
Cache compilation

### ISSUE THREAD

**Issue by Timmmm** [TypeStrong/ts-node#920]
Apparently this used to support caching, but it was removed. Unfortunately caching is pretty much a necessity if you're using this for interactive scripts because compilation is so slow (around 2 seconds for my 100-line script!)

It would be nice to have caching back!

**Comment by blakeembrey** [comment]
Duplicate of https://github.com/TypeStrong/ts-node/issues/908 and https://github.com/TypeStrong/ts-node/issues/754. Feel free to test `master` (different compilation mode) or submit a PR.
