### ISSUE TITLE
Hi, I have such a directory structure how to run scripts

### ISSUE THREAD

**Issue by bosens-China** [TypeStrong/ts-node#926]
### structure
``` sh
.
├─ src
│    ├─ config.ts
│    ├─ index.ts
│    ├─ type.ts
│    └─ utils.ts
├─ tsconfig.json
└─ types
       └─ global.d.ts
```
 ## tsconfig.json
``` json
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "noImplicitAny": true,
    "outDir": "./dist",
    "sourceMap": true,
    "esModuleInterop": true,
    "lib": ["ES2020", "DOM"],
    "baseUrl": ".",
    "downlevelIteration": true,
  },
  "exclude": ["node_modules"]
}
```
### package.json
``` json
...
  "scripts": {
    "climb": "ts-node --project tsconfig.json src/index.ts",
  },
...
```

## problem
I rely on a third-party module in the index file. I wrote its declaration file in the global.d.ts file, but through the npm.script running file, I would like to know how to make the tsconfig.json path, ✿✿ヽ (° del °) ノ✿

**Comment by blakeembrey** [comment]
@bosens-China Can you explain the issue your having? Or share an error? Based on https://github.com/TypeStrong/ts-node#help-my-types-are-missing you aren't following the correct directory structure for custom typings, and haven't specified it in your `tsconfig.json`.

**Comment by bosens-China** [comment]
> @bosens-China Can you explain the issue your having? Or share an error? Based on https://github.com/TypeStrong/ts-node#help-my-types-are-missing you aren't following the correct directory structure for custom typings, and haven't specified it in your `tsconfig.json`.

Run error, execute the prompt that there is no corresponding d.ts file in the installed library. I defined the d.ts file in types / global. D.ts, and I speculated that tsconfig was not written correctly, so I want to ask you what is the correct way based on the above file path

**Comment by blakeembrey** [comment]
Please follow the directions in https://github.com/TypeStrong/ts-node#help-my-types-are-missing. You need to add `typeRoots` and use `types/globals/index.d.ts` as documented. Or you can just use `--files` for `tsc`-like behavior.
