### ISSUE TITLE
Invalid optional chaining causes strange autocomplete behavior

### ISSUE THREAD

**Issue by jeiea** [TypeStrong/ts-node#927]
### Environment
- windows 10.1909
- typescript 3.7.4
- ts-node 8.5.4
- tsconfig.json: `{ "target": "es2018" }`

### What I did
Typing `(null as null | string)?.slice.call` in ts-node

### What I expected
Normal text input

### What I got
```
PS> ts-node   
> (null as null | string)?.slice.[eval].ts:1:7 - error TS2304: Cannot find name 'slice'.
1 try { slice } catch {}
        ~~~~~
c[eval].ts:1:7 - error TS2304: Cannot find name 'slice'.
1 try { slice } catch {}
        ~~~~~
a[eval].ts:1:7 - error TS2304: Cannot find name 'slice'.
1 try { slice } catch {}
        ~~~~~
l[eval].ts:1:7 - error TS2304: Cannot find name 'slice'.
1 try { slice } catch {}
        ~~~~~
l[eval].ts:1:7 - error TS2304: Cannot find name 'slice'.
1 try { slice } catch {}
        ~~~~~
```

**Comment by blakeembrey** [comment]
This looks like a node.js autocompletion issue. I was able to replicate it by hitting tab. I don't think the REPL has been completely expanded to support autocompletion. I'm going to close this issue by link it to https://github.com/TypeStrong/ts-node/issues/8 for reference. It would be great to support and might be an interesting issue for someone to tackle.
