### ISSUE TITLE
Unknown compiler option 'inlineSourceMap'. 

### ISSUE THREAD

**Issue by gutenye** [TypeStrong/ts-node#93]
Can not run `ts-node` command.

```
$ npm -g install ts-node typescript
$ ts-node
⨯ Unable to compile TypeScript
Unknown compiler option 'inlineSourceMap'. (5023)
Unknown compiler option 'inlineSources'. (5023)
```

**Comment by gutenye** [comment]
Resolved by myself.

**Comment by blakeembrey** [comment]
@gutenye Mind sharing how you resolved it?

**Comment by gutenye** [comment]
I re-installed both ts-node and typescript again, and the problem just gone. 
Sent from Outlook Mobile




On Thu, Apr 7, 2016 at 4:08 PM -0700, "Blake Embrey" <notifications@github.com> wrote:












@gutenye Mind sharing how you resolved it?
