### ISSUE TITLE
getting TS Error

### ISSUE THREAD

**Issue by ravi005e** [TypeStrong/ts-node#932]
getting TS Error, using the latest version, see the screenshot

![Annotation 2019-12-27 085935](https://user-images.githubusercontent.com/29851236/71525749-01423180-2888-11ea-8bdc-08d9f4abab36.png)

**Comment by blakeembrey** [comment]
Maybe resolved with https://github.com/TypeStrong/ts-node/commit/3334305b2912df82da7e8fb493932cce446cfceb, don't use Windows to be able to tell but reading the TypeScript source code implies this is done internally anyway (at least on the latest release).
