### ISSUE TITLE
setInterval does not fire after long interval on raspberry pi

### ISSUE THREAD

**Issue by dylanAOA** [TypeStrong/ts-node#933]
I am having the same issue noted in this node issue (https://github.com/nodejs/node/issues/4262)
However I am using ts-node. 

ts-node version: 8.5.4

running on Raspian GNU/Linux 10 (buster)

When setting short timeouts under 10 minutes they will fire but anything over that is not firing

**Comment by blakeembrey** [comment]
@dylanAOA Can you replicate it without `ts-node`? It seems unlikely to relate to `ts-node` since this module doesn't implement any node.js APIs - it's just a transpiler.
