### ISSUE TITLE
Use of `>>>` operator gives different results for same expression

### ISSUE THREAD

**Issue by goepi** [TypeStrong/ts-node#936]
I am working with bitwise operators. However, when I use the `>>>` operator I do not always get the same result:

Here is my bash session:
```
$ ts-node -v
v8.5.4
$ ts-node
> -5 >>> 0
4294967291
> -5 >>> 0
31
> -5 >>> 0
undefined
>
```

What is going on here?

**Comment by cspotcode** [comment]
Every time you hit the "Enter" key, ts-node needs to pass *all* inputs from the entire REPL session to the typescript compiler as a single file.  For example, if you refer to an interface that was declared earlier in the REPL session, the compiler needs to be given the declaration and the usage in a single source file.  This means prior REPL inputs are compiled repeatedly, but only the emitted JavaScript corresponding with the most recent REPL input should be evaled.  ts-node uses a diffing library to figure out which lines of code are new and should be evaled.

In this case, the diff looks like this:

```
[
  {
    count: 2,
    added: undefined,
    removed: true,
    value: '-5 >>> 0;\n' +
      '//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiL2MvVXNlcnMvYWJyYWRsZXkvRG9jdW1lbnRzL1tldmFsXS50cyIsInNvdXJjZXMiOlsiL2MvVXNlcnMvYWJyYWRsZXkvRG9jdW1lbnRzL1tldmFsXS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSxDQUFDLENBQUMsS0FBSyxDQUFDLENBQUEiLCJzb3VyY2VzQ29udGVudCI6WyItNSA+Pj4gMFxuIl19'
  },
  {
    count: 3,
    added: true,
    removed: undefined,
    value: '-5 >>> 0\n' +
      '    - 5 >>> 0;\n' +
      '//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiL2MvVXNlcnMvYWJyYWRsZXkvRG9jdW1lbnRzL1tldmFsXS50cyIsInNvdXJjZXMiOlsiL2MvVXNlcnMvYWJyYWRsZXkvRG9jdW1lbnRzL1tldmFsXS50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSxDQUFDLENBQUMsS0FBSyxDQUFDO01BQ1AsQ0FBQyxLQUFLLENBQUMsQ0FBQSIsInNvdXJjZXNDb250ZW50IjpbIi01ID4+PiAwXG4tNSA+Pj4gMFxuIl19'
  }
]
```

Looks like the code being compiled is `-5 >>> 0 -5 >>> 0;`  The diff says this entire expression is new code, so it's evaled, and the result is `31`.

**Comment by cspotcode** [comment]
You can see what the compiler's emitting via the Playground:
http://www.typescriptlang.org/play/index.html?ssl=2&ssc=5&pln=2&pc=1#code/LQVgBAfFYAwLAChSWvJ4oVkA

**Comment by blakeembrey** [comment]
As @cspotcode says, we have some tricks around this to handle ASI, but in this case it’s broken - should be fairly easy to fix though.
