### ISSUE TITLE
VSCode erratic debug stepping behavior when empty lines are added before the function declarations

### ISSUE THREAD

**Issue by tiborgg** [TypeStrong/ts-node#937]
Noticed that the stepping behavior in VSCode while debugging is influenced by the empty lines that appear throughout the code, to the point that *Step over* actually skips statements and steps into inner functions (the more empty lines there are before the code, the more statements are skipped).

### Project structure
Here is the simplest configuration in which I could reproduce the issue:

**main.ts** (empty lines on purpose)
```typescript







function func() {
    return 3;
}

function main() {
    debugger;

    let x = 1;
    let y = 2;
    let z = func();

    return x + y + z;
}

main();
```

**package.json**
```json
{
    "name": "vscode-tsnode-debugger-issue",
    "devDependencies": {
        "ts-node": "^8.5.4",
        "typescript": "^3.7.4"
    }
}
```

**.vscode/launch.json**
```json
{
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "main",
                "runtimeArgs": [
                    "-r",
                "ts-node/register"
            ],
            "args": [
                "./main.ts"
            ]
        }
    ]
}
```

I could reproduce this without `tsconfig.json` or any other files.

### Steps to reproduce
1. Run the "main" configuration from the VSCode debugger (F5). It should stop correctly at the `debugger` statement.
2. Invoke *Step over* (F10)

The code jumps directly inside `func` at the `return 3` statement, completely skipping all the statements before the `func` invocation. Also, the debugger steps into `func` rather than stopping at the invocation statement within `main`.

The correct behavior would be to jump to the next statement after `debugger`, which is `let x = 1`.

If you play around with the number of empty lines before the first declaration, you'll get different behaviors: 
1. No empty lines cause the debugger to behave correctly
2. Less empty lines cause the debugger to behave correctly just for a few statements 
3. More empty lines cause the debugger to jump directly into node internals after the code execution is complete

### My observations
1. Running the same configuration using `tsc` and the `tsc: build - tsconfig.json` preLaunchTask behaves correctly
2. The issue doesn't happen with plain JS
3. Tried all sorts of configurations of tsconfig.json, launch.json, with all combinations of sourceMap flags possible, smartStep on or off, etc, and the behavior is the same
4. The location of the empty lines doesn't matter, as long as it is before the code you are running (behavior is the same if you place `func` on the first line but leave some empty lines between it and `main`.
5. The same happens with methods inside classes
6. Same behavior is caused by Step out / Step into
7. Putting breakpoints and hitting Continue until the next breakpoint behaves correctly, regardless of the empty lines
8. In my original setup when I first started investigating this I was playing around with removing / adding unused imports, constructors, which changed the behavior as well

### What I'm using
Windows 10 version 1903, OS build 18362.535
VSCode version 1.41.1
ts-node version 8.5.4
typescript version 3.7.4

My guess is that it's something wrong with the sourceMaps, but I don't know where to start in investigating this into more details.

Also, I'm not sure if this is actually a problem with ts-node, but given that tsc and plain js behaved correctly, I figured that this is not a problem with VSCode or typescript.

**Comment by cspotcode** [comment]
@tiborgg What happens when your disable "smartStep"?  `"smartStep": false` in your vscode launch config.

I was able to reproduce the issue you were seeing in VSCode but *not* in Chrome DevTools, which led me to believe this is a VSCode issue.  When I disable "smartStep", the problem goes away.

**Comment by tiborgg** [comment]
Indeed, disabling "smartStep" fixes the issue. 

I was absolutely sure that it didn't fix it, because it was one of the first things I tried, but probably I messed up somewhere, maybe changed it in the wrong place or something :)

I also think that VSCode might play a part in this, given that there was also a similar issue with the `vscode-chrome-debug` tool a while ago: https://github.com/Microsoft/vscode-chrome-debug/issues/296

But as I've mentioned, I could not reproduce it using the native TypeScript compiler with source maps, so my gut feeling is that there's something that VSCode doesn't like about the source maps generated by ts-node. 

Source maps are still an alien topic to me, so I might be wrong about that.

**Comment by cspotcode** [comment]
@tiborgg 
I confirmed with someone on the VSCode team that this behavior is a limitation in their old debugger.  They're working on a new one which supports in-memory transpilers like ts-node.

You can try out their new debugger following the instructions here:
https://github.com/microsoft/vscode-js-debug

This issue roughly describes the issue.
https://github.com/microsoft/vscode-js-debug/pull/174

I'm going to close this issue as answered and not a ts-node issue, but please reply if you think there's more to discuss.

**Comment by tiborgg** [comment]
@cspotcode 
Thanks a lot for the effort. I"ll follow the progress on the new VSCode debugger.

**Comment by PatternFinder** [comment]
> @cspotcode Thanks a lot for the effort. I"ll follow the progress on the new VSCode debugger.

vscode debug will sometime skip a line of code when stepping

**Comment by Vitalii-Kh95** [comment]
Strange. It's 2025 and I still have this. Only "smartStep": false option doesn't fix it for me.
I just didn't get. Is this VS Code or ts-node problem?
