### ISSUE TITLE
Node engine V8 compatibility is broken

### ISSUE THREAD

**Issue by Borewit** [TypeStrong/ts-node#940]
ts-node is no longer work on Node V8, because [yn](https://github.com/sindresorhus/yn) is enforcing Node V10 compatibility.
Caused by: [yn#26](https://github.com/sindresorhus/yn/pull/26)

The motivation for changing the V8 requirement to V10 is because Node.js V8 is no longer supported. I believe node engine requirement should indicate the engine(s) the module **works** with.

**Comment by cspotcode** [comment]
I'm going to try wrapping the *old* version of yn in a wrapper that converts null return values to undefined.  That should achieve the desired behavior without upgrading yn, which avoids the problematic engine requirement.

**Comment by cspotcode** [comment]
We can also add a `yarn` invocation to the test suite to catch the incompatibilities.

**Comment by cspotcode** [comment]
@Borewit @Darep `yarn --ignore-engines` should let you install in the meantime.

Our tests run on node 6 so everything should work once you get past the package manager.
