### ISSUE TITLE
[Meta]: Conventions for triaging, closing, and tagging issues?

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#946]
@blakeembrey 
Are there guidelines you'd like me to follow when tagging and closing issues?

I'd like to have a shorter list of issues to focus on.  Right now there are 68 open issues, so it's tough to figure out what's relevant.  Is it ok if I more aggressively close issues?  Would you prefer to do that with tagging?  Are there any conventions I should be following in particular?

For example, can I go ahead and close #899?  I can add a message that the reporter should re-open it if they think my answer's insufficient.  This lets us knock down the list of issues more quickly without appearing rude or unhelpful.

**Comment by blakeembrey** [comment]
@cspotcode No particular guidelines, I trust your judgement here 👍 

Feel free to close/consolidate issues. I usually leave feature requests that seem valid open, but we can close to centralize it if that helps at all. If new tags are needed, feel free to add them - I typically stick to `docs`, `bug`, `enhancement`, `needs more info` and `help wanted`.

**Comment by cspotcode** [comment]
Thanks, sounds good to me.
