### ISSUE TITLE
nodemon + ts-node

### ISSUE THREAD

**Issue by herbertpimentel** [TypeStrong/ts-node#950]
how can we use nodemon + ts-node to enable debug !?

I have tryed several combinations not with success:

```sh
> nodemon --inspect --exec ts-node/register --files src/index.ts
```

**Comment by blakeembrey** [comment]
It seems people have it working, you can find examples via search: https://github.com/TypeStrong/ts-node/issues?q=is%3Aissue+nodemon+is%3Aclosed. One example is using `--exec ts-node`. If you wish to combine that with flags for `ts-node`, you'll need to use environment variables such as `TS_NODE_FILES=true` or `tsconfig.json` with `"ts-node": { files: true }`.
