### ISSUE TITLE
Questions about release process

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#957]
What is the release process for ts-node?  I think this is a question for @blakeembrey 

As far as I can tell:

A maintainer runs `npm publish <patch|minor|major>` locally
`git push --tags` to push the new tag to github
Edit the release associated with the new tag to add a description of the changes, following existing formatting like https://github.com/TypeStrong/ts-node/releases

**Comment by blakeembrey** [comment]
I personally use https://www.npmjs.com/package/np which generates most of these steps for you. I can add you as collaborator on NPM now.

**Comment by cspotcode** [comment]
Thanks!  I'll learn `np` and post if I have any questions.

**Comment by cspotcode** [comment]
@blakeembrey I published 8.7.0 to the npm `next` tag.  I wanted to be sure I had done everything correctly before moving the `latest` tag.

If you have a moment, can you review the release notes and git to be sure everything looks correct?  After that, I will update the `latest` dist-tag on npm.

https://github.com/TypeStrong/ts-node/releases/tag/v8.7.0
https://www.npmjs.com/package/ts-node/v/8.7.0

**Comment by blakeembrey** [comment]
@cspotcode Awesome, thanks!
