### ISSUE TITLE
our caching for `readDirectory` drops all but the first argument

### ISSUE THREAD

**Issue by cspotcode** [TypeStrong/ts-node#962]
`ts.sys.readDirectory` accepts a half-dozen arguments, but our caching wrapper drops all but the first.  It seems like this isn't causing bugs because typescript normally doesn't call this function.  Perhaps it's only used to populate the files array based on tsconfig "include" and "exclude" arrays, so our implementation is never called.

It looks like a bug waiting to happen, unless I'm missing something.  We can either drop the caching or write a different wrapper that puts all arguments into the cache key.

https://github.com/TypeStrong/ts-node/commit/1e838f76a3b3590b3ee37acfcb9d846a4e0bd08d

**Comment by blakeembrey** [comment]
Sounds reasonable to drop the caching here 👍
