### ISSUE TITLE
Safe navigation operator not working

### ISSUE THREAD

**Issue by zilvinasu** [TypeStrong/ts-node#964]
### Expected Behavior

Safe navigation operator `person?.lastName` should be working.

### Actual Behavior

Result: `SyntaxError: Unexpected token '.'`
<img width="663" alt="Screenshot 2020-02-17 at 11 40 57" src="https://user-images.githubusercontent.com/1578440/74641704-66285280-517a-11ea-8a46-6697748960ab.png">

### Steps to reproduce the problem

```shell
ts-node -e "const person = { firstName: 'Mr', lastName: 'Bing'}; console.log(person?.lastName);"
```

### Specifications

* ts-node version: v8.6.2
* node version: v13.5.0
* Operating system and version: macOS 10.15.3

**Comment by cspotcode** [comment]
@zilvinasu This works for me.  I'm guessing your compilerOptions -> target value is set to something like ESNext, so Typescript is passing `?.` syntax verbatim to node.

**Comment by zilvinasu** [comment]
Ah damn, good catch, works now, closing the issue, thanks!
