### ISSUE TITLE
ts-node/register fails if I include (and use) a SQLite library

### ISSUE THREAD

**Issue by jonmountjoy** [TypeStrong/ts-node#966]
### Expected Behavior

A detox/mocha configuration with ts-node/register should compile all the files.

### Actual Behavior

It fails, under a single circumstance - when I include an additional library (SQLIte).

When it fails, it fails with the error:

```
detox[51056] INFO:  [test.js] node_modules/.bin/mocha --opts e2e/mocha.opts --configuration ios.sim.debug --grep :android: --invert e2e/firstTest.spec.ts
/private/tmp/AwesomeProject/AwesomeProject2/node_modules/react-native/Libraries/Utilities/warnOnce.js:15
const warnedKeys: {[string]: boolean} = {};
      ^^^^^^^^^^

SyntaxError: Missing initializer in const declaration
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .js] (/private/tmp/AwesomeProject/AwesomeProject2/node_modules/ts-node/src/index.ts:807:44)
```

### Steps to reproduce the problem

The minimal app shows a simple detox/mocha setup that uses ts-node, and a simple test.
The test will succeed if the Engine.ts file doesn't use SQLite. It fails if it does.
I do the same for axios - but for axios, it works - which makes me think there's something odd 
about [react-native-sqlite-storage](https://www.npmjs.com/package/react-native-sqlite-storage) or its [typing](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native-sqlite-storage) and their interaction with ts-node.

### Minimal reproduction

I've created a minimal app that reproduces the problem:

https://github.com/jonmountjoy/ts-node-bug

See the README for instructions on how to make ts-node succeed or fail.

### Specifications

* ts-node version: ^8.6.2
* node version: 10.17.0
* Operating system and version: MacOS
* If Windows, are you using WSL or WSL2?:

**Comment by blakeembrey** [comment]
Just a note, but the failure here looks like it's because your trying to compile something in `node_modules/react-native`. TS node won't compile your `node_modules` by default.

**Comment by jonmountjoy** [comment]
Yes - I find it very strange that the inclusion of the SQLite seems to trigger it to do that.

My hunch is that there's something strange in the interplay between ts-node/register and the [top level types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native-sqlite-storage/index.d.ts) like the function declaration of `DEBUG`.

**Comment by cspotcode** [comment]
Looks like not a ts-node issue.
react-native appears to be incompatible with node.

https://runkit.com/cspotcode/require-react-native-fails

---

The error message is caused by node trying to execute invalid JS syntax via the `.js` extension loader, not `.ts`:
```
/private/tmp/AwesomeProject/AwesomeProject2/node_modules/react-native/Libraries/Utilities/warnOnce.js:15
const warnedKeys: {[string]: boolean} = {};
      ^^^^^^^^^^
```

Looking at that file, it has invalid .js in it:
https://unpkg.com/browse/react-native@0.61.5/Libraries/Utilities/warnOnce.js

Are you sure this bug only happens when ts-node is being used?  What happens when you load `'react-native-sqlite-storage';` *without* using ts-node?

I believe you can simplify your reproduction to a single file with a single line of code:

```
import 'react-native-sqlite-storage';
```

**Comment by jonmountjoy** [comment]
@cspotcode - you got me thinking, and I managed to reproduce this problem in [a new react native app](https://github.com/jonmountjoy/detox-problem) that does not use Typescript at all, so I agree that this is probably nothing to do with `ts-node`.  Thank you!
