### ISSUE TITLE
Strange source map error during TypeScript compilation

### ISSUE THREAD

**Issue by underflow00** [TypeStrong/ts-node#967]
This issue may or may not be related to https://github.com/TypeStrong/ts-node/issues/956.
I get a TypeScript compilation error with the following workflow:
1. Publish repo with raw TypeScript files to Git.
  - This repo has a npm script `"postinstall": "ts-node --transpile-only --skip-ignore npm-postinstall"`.
  - This `npm-postinstall` script compiles the TypeScript files by running the shell command `tsc --project <configfile>`.
2. `npm install` the published repo from Git.

The `tsc` command exits with a non-zero exit code.

The console output contains:
```
src/source-map-helper.ts:17:59 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'RawSourceMap'.

17     const sourceMapConsumer = await new SourceMapConsumer(sourceMapStr);

Found 1 error.

...

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mypackage2@0.0.0 postinstall: `ts-node --transpile-only --skip-ignore npm-postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mypackage2@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-02-29T16_50_22_825Z-debug.log
```

The debug log contains:
```
4670 verbose stack Error: mypackage2@0.0.0 postinstall: `ts-node --transpile-only --skip-ignore npm-postinstall`
4670 verbose stack Exit status 1
4670 verbose stack     at EventEmitter.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
4670 verbose stack     at EventEmitter.emit (events.js:210:5)
4670 verbose stack     at ChildProcess.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
4670 verbose stack     at ChildProcess.emit (events.js:210:5)
4670 verbose stack     at maybeClose (internal/child_process.js:1021:16)
4670 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
4671 verbose pkgid mypackage2@0.0.0
4672 verbose cwd C:\mypackage1
4673 verbose Windows_NT 10.0.18362
4674 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
4675 verbose node v12.13.1
4676 verbose npm  v6.13.7
4677 error code ELIFECYCLE
4678 error errno 1
4679 error mypackage2@0.0.0 postinstall: `ts-node --transpile-only --skip-ignore npm-postinstall`
4679 error Exit status 1
4680 error Failed at the mypackage2@0.0.0 postinstall script.
4680 error This is probably not a problem with npm. There is likely additional logging output above.
4681 verbose exit [ 1, true ]
```

After some investigation I found that the type error is likely related to ts-node using an older version of the source-map package, thus conflicting with my usage in my source-map-helper.ts file. I don't see how this can cause an issue though. Could it be a caching issue? Or maybe because the `tsc` process inherits the environment variables?

### Expected Behavior
No TypeScript compile error.

### Actual Behavior
TypeScript compile error.

### Minimal reproduction
Can't seem to reproduce minimally.

### Specifications

* ts-node version: v12.13.1
* node version: v8.6.2
* Operating system and version: Windows 10 Pro
* If Windows, are you using WSL or WSL2?: ?

**Comment by cspotcode** [comment]
You refer to a script named (I assume) `npm-postinstall.ts` but omitted the source code of that script.  We'll need to see it to know exactly what's happening here.

**Comment by underflow00** [comment]
The `npm-postinstall.ts` script creates a ts-config file
```
{
  "compilerOptions": {
    "lib": [
      "es6",
      "dom"
    ],
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "strict": true,
    "sourceMap": true,
    "declaration": true,
    "rootDir": "C:\\<path>\\src"
  },
  "include": [
    "C:\\<path>\\src\\**\\*"
  ]
}
```

then runs
`require('child_process').spawn(['tsc'], ['--project', 'C:\<path>\tsconfig'], {shell: true})`

**Comment by cspotcode** [comment]
@underflow00 What happens when you precompile the `npm-postinstall.ts` script and modify your package.json to look like this?

```
"postinstall": "node npm-postinstall"
```

I'm not convinced this is a ts-node issue.  We don't have proof that the issue is caused by ts-node.

**Comment by underflow00** [comment]
I switched from npm to yarn and so far I haven't had this issue. So I'm assuming it's an npm problem, though I can't confirm yet because the issue only happens sometimes. I'll close this for now.
