### ISSUE TITLE
Version?

### ISSUE THREAD

**Issue by nikkwong** [TypeStrong/ts-node#98]
How can we tell ```ts-node``` what version of TS to run—or simply see which version it is running? I am trying some new syntax that's only available in 1.8+ and ```ts-node``` seems to be responding as if it doesn't understand the syntax. Many thanks.

**Comment by blakeembrey** [comment]
It does understand the syntax. It would be node that doesn't. It runs on all TypeScript versions >= 1.5, as mentioned in the README and in CI.

**Comment by nikkwong** [comment]
Thanks for the response. I updated node, but I am getting: 

````
interface MyInterface {
	easing: 'one' | 'two';
}
````

````      
line 2  col 10  expected an assignment or function call 
````

Though this should be supported as stated: http://www.typescriptlang.org/docs/release-notes/typescript-1.8.html

**Comment by blakeembrey** [comment]
That is neither an error from TypeScript or node, where is that coming from?

**Comment by nikkwong** [comment]
Issue was from ```tslint```. Apologize for wasting your time.

**Comment by blakeembrey** [comment]
That's odd, glad you found it!
