### ISSUE TITLE
--files argument doesn't work in latest 8.8.0 version

### ISSUE THREAD

**Issue by tjx666** [TypeStrong/ts-node#986]
ts-node doesn't load declaration files and throw compile error

### reproduce

https://github.com/tjx666/coo/tree/e8861b8d5c3fb9eddea386d6854fb798757b52cd

### Specifications

* ts-node version: 8.8.0
* TypeScript version: 3.8.3
* tsconfig.json, if you're using one:
```
{
    "compilerOptions": {
        /* Basic Options */
        "target": "ES2019",
        "module": "commonjs",

        /* Strict Type-Checking Options */
        "strict": true,

        /* Additional Checks */
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,

        /* Module Resolution Options */
        "moduleResolution": "node",
        "esModuleInterop": true,
        "resolveJsonModule": true,

        /* Experimental Options */
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,

        /* Advanced Options */
        "forceConsistentCasingInFileNames": true,
        "skipLibCheck": true
    }
}
```
* node version: v12.16.1
* Operating system and version: win10pro 1909, not wsl

**Comment by blakeembrey** [comment]
Thanks for the report! Fixed with https://github.com/TypeStrong/ts-node/releases/tag/v8.8.1. I'll look into getting a test case covering it tonight.

**Comment by pawlufelice** [comment]
Seems to broken again on 9.1.0

**Comment by cspotcode** [comment]
[Our tests](https://github.com/TypeStrong/ts-node/actions) are still passing, so I'm going to assume this is all working correctly in 9.1.1 unless there's some specific use-case that's being missed.
